### ISSUE TITLE
拖入库 运行 报错

### ISSUE THREAD

**Issue by cjckkk** [CoderMJLee/MJExtension#103]
一旦引进 mjextion的库 就报错
萧少  19:39:06

duplicate symbol _main in:
    /Users/Luci/Library/Developer/Xcode/DerivedData/0618video-engcbvgddntxbddhttiikvlzicfc/Build/Intermediates/0618video.build/Debug-iphonesimulator/0618video.build/Objects-normal/i386/main-9DC53E1DF0BE428A.o
    /Users/Luci/Library/Developer/Xcode/DerivedData/0618video-engcbvgddntxbddhttiikvlzicfc/Build/Intermediates/0618video.build/Debug-iphonesimulator/0618video.build/Objects-normal/i386/main-7D7D2DBDDEDDA579.o
ld: 1 duplicate symbol for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by CoderMJLee** [comment]
目测，应该是加错东西了哈。你应该加入里面的MJExtension文件夹就OK了，你可能是将外面的整个文件夹拖进项目的
