### ISSUE TITLE
图片可以部署吗？

### ISSUE THREAD

**Issue by elliotxin** [CoderMJLee/MJExtension#107]
杰哥，我是个新手，我想问问你这个框架支持上传照片后的返回值转换成模型吗？
我把照片传到服务器，服务器返回的不是JSON，是一个“__NSCFDictionary”类型，然后我打印出来，它是这个样子的：
{
    url = "/images/2015/06/24/70/__/7052c5de1f5b5d0c0e96219c2e29a0be20150624.png";
}
但是公司的API文档上显示的是这个样子的：
{
    "photo": "/images/2013/04/11/fc/__/fc01d65fdc5eca9b47dd26ba02147b1c20130411.jpg"
}
所以我现在迷茫了，请教这个问题应该怎么解决，我真的是个小白！

**Comment by CoderMJLee** [comment]
NSCFDictionary就是JSON对象吖，那就按照真实返回的url处理，不用photo
