### ISSUE TITLE
部署出错了，请教一下！

### ISSUE THREAD

**Issue by elliotxin** [CoderMJLee/MJExtension#108]
杰哥，我这个程序有一个接口，返回的JSON看的我蛋疼（毕竟我是个小白），然后我把这个返回数据制作成了plist文件
![screen shot 2015-06-25 at 6 12 28 pm](https://cloud.githubusercontent.com/assets/3390411/8352249/3973e0fa-1b66-11e5-9ed4-5eecafcf422a.png)
首先我创建了一个PCMenu模型，然后里面有三个参数， 一个是categoryList,一个是menu，一个是ts。categoryList又单独建立一个模型，然后里面有categoryId，name，mt，imageList（这个我很纠结，不知道要怎么处理，它是一个Array，但是里面竟然是string）,subCategoryList.
然后subCategoryList模型里面我创建了subCategoryId，name，description，imageList（这个我很纠结，不知道要怎么处理，它是一个Array，但是里面竟然是string）。
menu模型，dishId，name，description，imageList（这个我很纠结，不知道要怎么处理，它是一个Array，但是里面竟然是string），priceList，extraPriceList，merchantId，categoryId，subCategoryId，isPromotion，isSpicymt，mt
priceList模型， small，Normal，large
extraPriceList模型，Less Spicy，Very Spicy
这几个模型创建好后，我用AFN向服务器发送请求，然后请求成功，用responseObject返回的JSON进行映射，最后失败了。。。。。
杰哥，能指点一下我吗？我真的是个小白！

**Comment by wangKeen** [comment]
MJ哥，model值为空的属性，model.keyValues转换成Dictionary的时候就直接丢掉了吗？能否保留

**Comment by CoderMJLee** [comment]
Dictionary里面是不能放nil值的，所以扔掉了

**Comment by wangKeen** [comment]
如果要把模型中包含@""值的属性转成json，不是有点麻烦了

**Comment by CoderMJLee** [comment]
@elliotxin imageList直接搞个@property(nonatomic, strong) NSArray * imageList;属性就可以了，不用增加额外的代码
