### ISSUE TITLE
给MJ提几个建议哈，

### ISSUE THREAD

**Issue by nsdictionary** [CoderMJLee/MJExtension#11]
1.MJIvar里面的遍历，可以增加一个idx索引。
2.我的同事写的接口有id，class字段，或者select等字段，为了不冲突就用了大写（有的有大小写，有的纯小写），希望增加大小写支持。
我手动改过你的代码，先直接匹配，如果没有就转为纯小写匹配。

谢谢，留个名吧，成都 charlin 华西都市网

这个是我写的，呵呵https://github.com/nsdictionary/CoreRefresh

**Comment by CoderMJLee** [comment]
谢谢意见哈，我个人是这么看的哈，你看看OK不？

**Comment by CoderMJLee** [comment]
谢谢你的宝贵意见，我个人是这么看的哈，你看看OK不？
1.成员变量在对象中的顺序感觉没有用处，所以没有考虑idx
2.究竟大写还是小写，我觉得由使用框架的开发者自己去解决或者调整会好一点。因为有可能一个对象同时有这样的2个属性：name、Name，这种情况下，它们代表不同的含义

**Comment by f33chobits** [comment]
变量名是的规范就是纯小写，就算不是也建议前后端保持一致。凭个人经验，如果写Json返回Name或者Name和name两个字段，我觉得这样的帅哥不会知道这个MJExtension的存在的。。。

**Comment by zhw511006** [comment]
一直用JSONModel, 无意当中发现MJExtension, 很给力，加油！

**Comment by CoderMJLee** [comment]
谢谢支持
