### ISSUE TITLE
出现了几个莫名其妙的字段（id） ，怎么弄掉 

### ISSUE THREAD

**Issue by hongdong** [CoderMJLee/MJExtension#110]
![5bb2773e-9b45-422e-ba61-acede33878af](https://cloud.githubusercontent.com/assets/5499518/8372247/0112fcce-1c14-11e5-8780-51c597b155a1.png)
出现了几个莫名其妙的字段，怎么弄掉

**Comment by hongdong** [comment]
sorry  好像是数据库那边加到

**Comment by CoderMJLee** [comment]
是的，应该是数据库加的
