### ISSUE TITLE
这样的数据无法解析。。。。。这个是什么问题

### ISSUE THREAD

**Issue by liujianying** [CoderMJLee/MJExtension#111]
data =     (
                {
            boxId = 1;
            boxItemId = 11;
            idx = 1;
            memo = 1;
            moreImg = "http://www.trylist.com/uploads/allimg/150401/16245-150401100153930.jpg";
            moreUrl = "http://117.27.139.187:7080/GroupWeb/intf?act=viewArticle&request={'data':'7','session':''}";
            status = 1;
            subTitle = "\U6eda\U52a8\U5e7f\U544a";
            title = "\U82cf\U5b81\U6613\U8d2d \U65b0\U4eba\U798f\U5229\U6ce8\U518c\U900110\U5143\U65e0\U95e8\U69db\U5238(100%)";
            urlType = web;
            ver = 1;
        }
    );

**Comment by CoderMJLee** [comment]
解决了？

**Comment by liujianying** [comment]
可以解析。是我这的代码问题。原先以为是特殊字符导致的。谢谢
