### ISSUE TITLE
MJ哥，麻烦有时间帮我看看这个问题

### ISSUE THREAD

**Issue by lexiaoyao20** [CoderMJLee/MJExtension#113]
我有一个Model，里面有一个NSArray，NSArray里面包含的是NSString类型，我调用 keyValues 方法返回的数据有问题，如下所示：
RequestData =     {
        HasPhoto = true;
        MicroBlogBody = ff;
        NickName = "";
        PhotoList =         (
                        {
            },
                        {
            }
        );
    };

数组的内容变为空的了。。。
我试了各种办法都没有用：
+ (NSDictionary *)objectClassInArray {
    return @{@"PhotoList": NSStringFromClass([NSString class])};
}

+ (NSDictionary *)objectClassInArray {
    return @{@"PhotoList": @“NSString”)};
}
不实现这个方法也没效果。。。

**Comment by CoderMJLee** [comment]
你PhotoList里面装的是NSString？你下载最新的代码试试

**Comment by lexiaoyao20** [comment]
是啊，里面是放的NSString类型， 我是pod 的最新代码，但是我用pod 'MJExtension',  '~> 2.0.2' ，且不去实现 objectClassInArray 方法是可以的

**Comment by lexiaoyao20** [comment]
应该是你最新版本改出来的BUG，你自己可以试试看。。。

**Comment by CoderMJLee** [comment]
最新版本是2.3.6吖。。。你需要pod repo update
