### ISSUE TITLE
使用同一个model解JSON的cache问题

### ISSUE THREAD

**Issue by rainer-liao** [CoderMJLee/MJExtension#114]
在使用MJExtension的时候,出现一个这样的问题:
定义一个model,比如叫NYGReturnInfoModel, 其中data属性是需要再解析的,即其中会包含其他model
@interface NYGReturnInfoModel : NSObject
@property (nonatomic, strong) NSNumber *code;
@property (nonatomic, strong) NSArray *data;// Contatins 各种Model
@property (nonatomic, copy) NSString *message;
@property (nonatomic, strong) NSNumber *subcode;
@end

然后使用setupObjectClassInArray去解,此时data对应的model是NYGGameModel,没有问题.
[NYGReturnInfoModel setupObjectClassInArray:^NSDictionary *{
        return @{
                 @"data" : @"NYGGameModel"
                 };
    }];
    NYGReturnInfoModel *gameReturnInfoModel = [NYGReturnInfoModel objectWithKeyValues:responseObject];

然后再使用setupObjectClassInArray去解另外一个model, 此时data对应NYGObtainedCommentModel,如
[NYGReturnInfoModel setupObjectClassInArray:^NSDictionary *{
        return @{
                 @"data" : @"NYGObtainedCommentModel"
                 };
    }];
    NYGReturnInfoModel *returnInfoModel = [NYGReturnInfoModel objectWithKeyValues:responseObject];//MJExtension

此时, 会发现returnInfoModel类型并不是预想的NYGReturnInfoModel, 而是NYGGameModel.

查看源码发现, 使用了cache. 但是对于这种情况, 使用cache貌似不是一个好的选择?

期待你的回答.

**Comment by CoderMJLee** [comment]
当时设计setup方法的初衷就是希望一次性设置哈，在初始化的时候设置一次

**Comment by CoderMJLee** [comment]
我刚才更新了下框架，2.3.7版本，每次调用setup方法，我会刷新一下缓存，你看看好不好使哈？

**Comment by rainer-liao** [comment]
Hi, 使用2.3.7版本, 问题解决了. 不过又发现了一个新的问题.  
还是之前的代码, data是个数组, 数组中还有模型, 有时候能解析正确, 有时候某个模型解析全是nil值.
不知是哪里姿势不正确

**Comment by CoderMJLee** [comment]
是模型里面的属性值为nil？有时候才能解析正确？会不会是因为JSON里面本来就没有值？

**Comment by rainer-liao** [comment]
确定JSON里面有值, 我再看看

**Comment by CoderMJLee** [comment]
是偶尔出现这个问题？可以发Demo看看么？谢谢哈

**Comment by rainer-liao** [comment]
是NYGReturnInfoModel中data包含A model, A model又包含B model.然后解析出的B model全是nil.
确定JSON里面有值.
我先暂时用另外一种方法解决这个问题, 过两天再仔细看看.

**Comment by rainer-liao** [comment]
对了, 多谢. 找到问题issue你

**Comment by rainer-liao** [comment]
问题解决了, 是我这边类型写错, MJExtension没错, 多谢

**Comment by CoderMJLee** [comment]
解决了就好哈
