### ISSUE TITLE
2.3.3版本后报错

### ISSUE THREAD

**Issue by kiwh** [CoderMJLee/MJExtension#115]
_type = [MJType cachedTypeWithCode:[attrs substringWithRange:NSMakeRange(loc, len)]];

之前使用的是2.3.3版本，今天更新pod,把MJExtension也更新了，但是一运行就出现这个错误，一路追踪，发现是这一行出现错误 。
在MJProperty类中的此方法中:
- (void)setProperty:(objc_property_t)property

Bug出现时间是在MJExtensionConfig文件中Model调用 setupObjectClassInArray方法时

错误信息:
2015-06-30 17:33:20.681 Y9Mobile[77717:1927315] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString substringWithRange:]: Range {1, 9223372036854775806} out of bounds; string length 3'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106b24c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000106341bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x0000000106b24b9d +[NSException raise:format:] + 205
	3   CoreFoundation                      0x0000000106a4bb98 -[__NSCFString substringWithRange:] + 136
	4   Y9Mobile                            0x0000000102ac1213 -[MJProperty setProperty:] + 419
	5   Y9Mobile                            0x0000000102ac1024 +[MJProperty cachedPropertyWithProperty:] + 132
	6   Y9Mobile                            0x0000000102ac8dd3 __32+[NSObject(Property) properties]_block_invoke + 115
	7   Y9Mobile                            0x0000000102ac8acf +[NSObject(Property) enumerateClasses:] + 143
	8   Y9Mobile                            0x0000000102ac8cf0 +[NSObject(Property) properties] + 224
	9   Y9Mobile                            0x0000000102ac95fb +[NSObject(Property) setupObjectClassInArray:] + 123
	10  Y9Mobile                            0x00000001028b9778 +[MJExtensionConfig load] + 56
	11  libobjc.A.dylib                     0x0000000106343648 call_load_methods + 716
	12  libobjc.A.dylib                     0x0000000106346147 load_images + 231
	13  ???                                 0x0000000103636a81 0x0 + 4351814273
	14  ???                                 0x00000001036415a2 0x0 + 4351858082
	15  ???                                 0x000000010364143c 0x0 + 4351857724
	16  ???                                 0x00000001036416ad 0x0 + 4351858349
	17  ???                                 0x0000000103636d40 0x0 + 4351814976
	18  ???                                 0x000000010363a074 0x0 + 4351828084
	19  ???                                 0x000000010363627c 0x0 + 4351812220
	20  ???                                 0x00007fff65e38163 0x0 + 140734902796643
	21  ???                                 0x00007fff65e37277 0x0 + 140734902792823
	22  ???                                 0x00007fff65e33276 0x0 + 140734902776438
	23  ???                                 0x00007fff65e33036 0x0 + 140734902775862
	24  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by CoderMJLee** [comment]
可以把你的模型代码粘给我看看么？或者发个Demo哈，谢谢

**Comment by money150604** [comment]
请问这个错误解决了吗？。

**Comment by CoderMJLee** [comment]
@money150604 你也遇到这个错误了么？
其实我暂时没有遇到这个错误哈，需要等@kiwh 发个Demo过来。

**Comment by BaiCanLin** [comment]
MJ哥，更新后我也奔溃了

**Comment by CoderMJLee** [comment]
啊？不是吧，我好像没改那个呀，哈哈。我看看哈

**Comment by CoderMJLee** [comment]
@BaiCanLin 发个Demo看看？

**Comment by kiwh** [comment]
已发Demo到richermj123go@vip.qq.com

**Comment by CoderMJLee** [comment]
非常感谢Demo，已经解决了哈，谢谢。pod repo update，然后更新MJExtension就OK了
