### ISSUE TITLE
Questions about MJExtension depth ？

### ISSUE THREAD

**Issue by ccguo** [CoderMJLee/MJExtension#116]
Questions about MJExtension depth ？
Has three class, the class A of array storage object B, class B have array storage C object, class C is A basic model, the attribute is are basic string,
MJExtension if starting from the B parsing can be normal analytical,
Come from A parse time to start parsing failure, excuse me MJ :  MJExtension related analytical depth problem

**Comment by CoderMJLee** [comment]
Can you send me a simple demo?Thank you.

**Comment by ccguo** [comment]
I 'm very very sorry, I got a mismatch of json from pretest environment, very very Thanks for the MJExtension. At the same time,  I want tell you a message, first of all, very honored to reference from your contribution share in our team,  in our team，each one of us all like MJExtension.

**Comment by CoderMJLee** [comment]
Thank you.
