### ISSUE TITLE
模型归档

### ISSUE THREAD

**Issue by suochenhe** [CoderMJLee/MJExtension#117]
我最近在使用本框架的时候，发现了一个归档的bug，就是我本身要归档的模型，遵守一个另一个框架的协议，结果导致归档失败。
在本地数据存储方面有问题想要问mj老师：
1.由于以上所说直接归档失败，我将模型转字典，然后存本地，解析时再转成对象，这种方法和直接归档相比，性能如何？
2.将字典存储本地的时候，直接writetofile 和 将字典转NSData或json再存储本地相比，综合性能和安全性应该如何选择？

**Comment by CoderMJLee** [comment]
另一框架是？什么协议呢？
1.我个人觉得其实性能相差不大
2.两者的安全性都差不多、不高。真是那种需要保密的数据，那就加密后存储

**Comment by suochenhe** [comment]
另一个框架是restkit，协议是基于restkit自定义的。
测试本地存储的时候发现问题，
model类，和modelFrame类。modelFrame中包含model，其他字段都是CGRect
1.将modelFrame的模型数组，转字典数组，然后writeTofile本地存储失败，本地不会生成文件（model的模型数组如此操作会成功）
2.将modelFrame模型数组NSKeyedArchiver归档，归档成功，但是读档成功后modelFrame中的model为nil（model的模型数组如此操作会成功，读档也正常）
