### ISSUE TITLE
关于多级数组的映射

### ISSUE THREAD

**Issue by funior** [CoderMJLee/MJExtension#119]
{
    data = ( 
                  {foo:far},  
                  {foo1:bar1, foo2:bar2} , 
                  {foo3:bar3}  
                )
}
请问对于这种类型的json数据要如何解析出foo的值（数组里的字典元素格式不同）?

对于字典的话，我们可以使用多级映射 ：
+ (NSDictionary *)replacedKeyFromPropertyName
{
    return @{@"categories":@"data.content"};
}

如果需要映射多级数组里的某个元素的话，是否有类似于：
+ (NSDictionary *)replacedKeyFromPropertyName
{
    return @{@"categories":@"data.content[0]};
}
的方法？

谢谢MJ老师。

**Comment by CoderMJLee** [comment]
已经支持了哈，你试试最新版，2.4.0版本

**Comment by funior** [comment]
谢谢，神效率。
