### ISSUE TITLE
关于replacedKeyFromPropertyName使用后的bug

### ISSUE THREAD

**Issue by xmxiao6** [CoderMJLee/MJExtension#12]
不知道是不是我的需求比较特别，使用过程中有以下两点问题：
1、子类中要实现replacedKeyFromPropertyName要先获取父类中的replacedKeyDict再拼接上自己要替换的属性，否则父类中的replacedKeyFromPropertyName会被覆盖掉？
2、当子类中实现replacedKeyFromPropertyName要替换掉父类属性对应的key时，缓存机制cachedIvarWithIvar   和  MJCachedIvarsKey  工作就会出现问题。

最后，忍不住要夸一下，这套框架很棒~ 用着非常爽~

**Comment by CoderMJLee** [comment]
谢谢你的夸奖和宝贵的意见。
第1个问题：我觉得最好还是保持现状，继续按照继承的原则：子类重写完全覆盖父类，如果子类还想拥有父类功能，那就用super解决问题。
第2个问题：是框架的BUG，不是你需求特别哈，我这几天抽空看看，再次感谢！

**Comment by CoderMJLee** [comment]
我已经修复了第2个问题的bug，你有空测试一下哈。希望你能测试结果反馈一下，如果bug已经解决，我就更新一下cocoapods

**Comment by dong09000** [comment]
杰哥威武,未来两年我一定要努力达到杰哥的高度

**Comment by xmxiao6** [comment]
第2个问题的bug 已经解决
