### ISSUE TITLE
字符串数组返回空字典

### ISSUE THREAD

**Issue by liamogierussell** [CoderMJLee/MJExtension#120]
这是通过谷歌翻译，以便excues任何语言问题。我有一个具有以下特性的模型。

@property (nonatomic, copy) NSString *name;
@property (nonatomic, strong) NSArray *emails;
@property (nonatomic, strong) NSArray *numbers;

电子邮件是一个字符串数组但是当我使用 obj.keyValues 电子邮件返回一个空的字典。

有没有一种方法来返回一个字符串，而不是空的字典中被返回的数组？

感谢和伟大的图书馆，
利亚姆。

**Comment by CoderMJLee** [comment]
啥意思？

**Comment by liamogierussell** [comment]
这是我的目标

![screen shot 2015-07-07 at 09 28 21](https://cloud.githubusercontent.com/assets/12812886/8542048/889b91a0-248a-11e5-87ad-89acbbabeedb.png)

这是JSON之前我的对象
![screen shot 2015-07-07 at 09 22 38](https://cloud.githubusercontent.com/assets/12812886/8542061/a50c9f46-248a-11e5-854b-23d1d52e697a.png)

这是JSON后我的对象
![screen shot 2015-07-07 at 09 32 12](https://cloud.githubusercontent.com/assets/12812886/8542115/1511bb00-248b-11e5-87e1-7d56797de090.png)

相反，含有NSArray的字符串，我得到的字典空数组

**Comment by CoderMJLee** [comment]
你更新一下最新的2.4.1版本，已经修复这个问题了，sorry哈

**Comment by liamogierussell** [comment]
Fixed now thanks.
