### ISSUE TITLE
instance is null

### ISSUE THREAD

**Issue by caofei10119** [CoderMJLee/MJExtension#121]
Here is my code.

+ (IPPrayer *)prayerWithDictionary:(NSDictionary *)dic {
    IPPrayer *prayer = [IPPrayer objectWithKeyValues:dic];
    
    return prayer;
}

+ (NSDictionary *)replacedKeyFromPropertyName {
    return @{@"prayerId" : @"id",
             @"blamesCount" : @"blames_count",
             @"commentsCount" : @"comments_count",
             @"groupId" : @"group_id",
             @"userId" : @"user_id",
             @"lastCommentId" : @"last_comment_id",
             @"supportsCount" : @"supports_count",
             @"commentsCount" : @"comments_count",
             @"repraysCount" : @"reprays_count",
             @"createdAtTimestamp" : @"created_at",
             @"answeredAtTimestamp" : @"answered_at",
             @"contentImageUrlString" : @"photo_url"};
}

in prayerWithDictionary, prayer object gets null after run this line.
IPPrayer *prayer = [IPPrayer objectWithKeyValues:dic];

any idea?

**Comment by CoderMJLee** [comment]
check your dic, is your dic null?

**Comment by caofei10119** [comment]
no, all properties have been filled with values from dictionary. but prayer object is NULL

**Comment by CoderMJLee** [comment]
ARC?MRC?
Can you send me a demo? richermj123go@vip.qq.com

**Comment by caofei10119** [comment]
never mind, it has been fixed suddenly. maybe xCode bug. thanks for your help

**Comment by CoderMJLee** [comment]
Ok
