### ISSUE TITLE
how to handle inheritance

### ISSUE THREAD

**Issue by caofei10119** [CoderMJLee/MJExtension#122]
class A has one, two properties
class B extends A and has own properties

how to define replacedKeyFromPropertyName static method?

**Comment by CoderMJLee** [comment]
[A setup....]; // a properties
[B setup....]; // b properties, will extend A steup

**Comment by caofei10119** [comment]
ok, thanks let me check

**Comment by caofei10119** [comment]
would you post sample implement here?

**Comment by CoderMJLee** [comment]
Can you supply your model interface code?

**Comment by caofei10119** [comment]
@implementation IPBaseObject

+ (NSDictionary *)replacedKeyFromPropertyName {
    return @{@"objectId":@"id",
             @"createdAtTimestamp":@"created_at",
             @"updatedAtTimestamp":@"updated_at"};
}
-(id)initWithCoder:(NSCoder *)decoder {
    if (self = [super init]) {
        [self decode:decoder];
    }
    return self;
}

- (void)encodeWithCoder:(NSCoder *)encoder {
    [self encode:encoder];
}


@implementation IPComment

+ (IPComment *)commentWithDictionary:(NSDictionary *)dic {
    IPComment *comment = [IPComment objectWithKeyValues:dic];
    
    return comment;
}

+ (NSDictionary *)replacedKeyFromPropertyName {
    return @{@"commentId":@"comment_id",
             @"createdAtTimestamp":@"comment_created_at",
             @"userPhotoUrlString":@"user_photo_url",
             @"contentImageUrlString":@"photo_url" };
}
}

this is what I tried but not worked

**Comment by CoderMJLee** [comment]
I got it.If you implement static method in your .m file, you shuold call [super replacedKeyFromPropertyName]
```objc
+ (NSDictionary *)replacedKeyFromPropertyName {
NSMutableDictionary *dict = [NSMutableDictionary dictionary];
[dict addEntriesFromDictionary:[super replacedKeyFromPropertyName]];
[dict addEntriesFromDictionary:@{@"objectId":@"id",
@"createdAtTimestamp":@"created_at",
@"updatedAtTimestamp":@"updated_at"}];
return dict;
}
```

**Comment by caofei10119** [comment]
gotcha, thanks a lot
