### ISSUE TITLE
Converting an NSArray of NSStrings

### ISSUE THREAD

**Issue by bboyle18** [CoderMJLee/MJExtension#123]
Hi
I love using your library, but I'm having trouble with one part of it. I'm using version 2.4.

I'm trying to convert an NSArray of NSString objects but it just returns an empty dictionary. 
```
@interface Person : NSObject

@property (nonatomic, strong) NSArray *names;
@property (nonatomic, copy) NSString *age;

@end

Person *person = Person.new;
person.names = @[@"John", @"Peter", @"James"];
person.age = @"22";
NSDictionary *jsonDict = person.keyValues;
}
```
In the code above, the jsonDict is populated with the "age" property but the "names" property has an empty dictionary as its value. MJExtension doesn't seem to convert the string values. 

Can you please tell me if this is a bug and if not, how can this be fixed?

Thanks, 
Brian

**Comment by CoderMJLee** [comment]
I had it fixed just now in version 2.4.1, thank you for your issue.
