### ISSUE TITLE
mj老师你好，为什么用了框架之后只能在第一次调用的时候字典模型可以转换！

### ISSUE THREAD

**Issue by yxfCode** [CoderMJLee/MJExtension#124]
第一次以后调用就转换不了了 ，然后重启xcode的第一次调用也是可以的，这是为什么呢？
 调用： ProductListModel *productlist= [ProductListModel objectWithKeyValues:dic];
＝＝＝＝
@interface ProductListModel : NSObject
@property (nonatomic,copy) NSString *responseCode;
@property (nonatomic,copy) NSArray *responseText;
@property (nonatomic,assign) NSInteger countPage;
@property (nonatomic,assign) NSInteger page;
@property (nonatomic,assign) NSInteger count;

+(NSDictionary *)objectClassInArray
{
    return @{
             @"responseText":[ProductModel class]
             };
}
＝＝＝＝＝＝

/**
 商品模型
 */
@interface ProductModel : NSObject

@property (nonatomic,copy) NSString *detailed;
@property (nonatomic,copy) NSString * id;
@property (nonatomic,copy) NSString *money;
@property (nonatomic,copy) NSString *pName;
@property (nonatomic,copy) NSString *path;
@property (nonatomic,copy) NSString *titile;
@property (nonatomic,copy) NSString *total;

还请mj老师给解答一下啊 TT

**Comment by yxfCode** [comment]
就是 ProductModel 这个模型没有值

**Comment by CoderMJLee** [comment]
@property (nonatomic,copy) NSArray *responseText;
改为strong试试？

我从没遇到这个问题哈，还是不行的话，发个Demo看看？3Q

**Comment by yxfCode** [comment]
mj老师，在重新写demo的是时候 发现问题了， 前边数据模型转换没有问题，转换完成后使用的时候有个方法传值的类型写错了（ProductModel 写成了NSDictionary）！！改正确了就好了。但是不知道问什么这会影响前面的。感谢mj老师。

**Comment by CoderMJLee** [comment]
不客气哈
