### ISSUE TITLE
Embedded object with nil properties stops keyValues in parent object

### ISSUE THREAD

**Issue by liamogierussell** [CoderMJLee/MJExtension#125]
Hi,

I have a parent object

@interface ParentModel : NSObject

@property (nonatomic, strong) MusicLibrary *musicLibrary;
@property (nonatomic, strong) NSArray *contacts;

@end

The music library has the following properties

@interface MusicLibrary : NSObject

@property (nonatomic, strong) NSArray *songs;
@property (nonatomic, strong) NSArray *plays;

@end

If both songs and plays are nil, then contacts in the parent model never gets converted to a dictionary when i call key values. So if all properties in an embedded object are nil it stops iterating through the properties on the parent object at that point.

What should happen is if songs and plays are nil then contacts should still be converted to the dictionary. Can you have a look at this?

**Comment by liamogierussell** [comment]
So what I expect if songs = nil and plays = nil is.

{
 "contacts": {
        name: "my name";
}
}

what I get is

{

}

This is just example dictionaries. Probably not correct syntax but just used to illustrate the point.

**Comment by CoderMJLee** [comment]
Is contacts an array?Contacts is not a dictionary.

**Comment by liamogierussell** [comment]
Contacts is an array of contact objects.

**Comment by liamogierussell** [comment]
It just never reaches this array if all the properties of the parent object are nil.

**Comment by CoderMJLee** [comment]
If your property is nil, you will find nothing in dictionary.That is it.

**Comment by liamogierussell** [comment]
I expect to find nothing in the dictionary for musicLibrary because songs and plays is nil. That is perfect. The problem is that no record exists in the dictionary for contacts which is not nil. Your iteration through the properties in ParentModel stops at MusicLibrary if MusicLibrary's embedded objects are nil. It should put nothing in the dictionary for MusicLibrary but still go on to contacts and put that in the dictionary. If this is not clear I can make a demo project to replicate?

**Comment by CoderMJLee** [comment]
Ok.Please send me a demo.Thank you. My email is richermj123go@vip.qq.com

**Comment by CoderMJLee** [comment]
Sorry, it's really a bug.I had it fixed just now.The latest version is 2.4.2.

**Comment by liamogierussell** [comment]
Works perfect now, thanks for the speedy updates.
