### ISSUE TITLE
mjexentsion 转换对象失败

### ISSUE THREAD

**Issue by huangping35** [CoderMJLee/MJExtension#127]
# pragma mark 首页获取广告

+(void)advertisementAryWithCallback:(ShareCallback)shareCallback
{
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{

```
    [NetworkHandle requestWithURL:kHttpURL withParameters:@{@"cmd":kCmd_adver} withDataAry:nil withCallback:^(id obj) {

        NSDictionary *root=obj;

        for(NSString *key in root.allKeys)
        {
            NSLog(@"广告 %@ %@",key,root[key]);

        }
        if([NetworkHandle handleState:root[kResponse_state]]==YES)
        {


            NSArray *items=[AdvertisementInfo objectArrayWithKeyValuesArray:root[@"items"] context:[NSManagedObjectContext MR_defaultContext]];

            for(int i=0;i<items.count;i++)
            {
                AdvertisementInfo *info=items[i];
                NSLog(@"info %@",info);
                AdvertisementInfo *info2=[AdvertisementInfo MR_findAllWithPredicate:[NSPredicate predicateWithFormat:@"ad_id=%@",info.ad_id] inContext:[NSManagedObjectContext MR_defaultContext]].lastObject;
                if(info2==nil)
                {
                    [[NSManagedObjectContext MR_defaultContext]MR_saveToPersistentStoreWithCompletion:^(BOOL contextDidSave, NSError *error) {

                    }];
                }

            }

            shareCallback(items);
        }
        else if(root[kResponse_state]==kResponse_noLogin)
        {
            shareCallback(@"未登录");
        }
        else
        {
            shareCallback(root[@"msg"]);
        }
    }];
});
```

}

2015-07-14 16:04:50.505 DIANDIANSHANGDU[1286:86203] 广告 state 1
2015-07-14 16:04:50.506 DIANDIANSHANGDU[1286:86203] 广告 items (
        {
        "ad_id" = 2;
        descripe = "\U8d5a\U94b1\U4e5f\U8981\U201c\U73a9\U82b1\U6837\U201d";
        "t_img" = "1434506858.png";
        url = "http://www.baidu.com";
    },
        {
        "ad_id" = 1;
        descripe = "\U6b63\U8a89\U80a1\U4efd\U6709\U9650\U516c\U53f8";
        "t_img" = "1434506945.png";
        url = "http://www.zhengyugf.com";
    },
        {
        "ad_id" = 3;
        descripe = "\U641c\U7d22\U5e7f\U544a";
        "t_img" = "1434534865.png";
        url = "http://www.zhengyugf.com";
    },
        {
        "ad_id" = 4;
        descripe = 111;
        "t_img" = "1434534874.png";
        url = "";
    }
)
2015-07-14 16:04:50.506 DIANDIANSHANGDU[1286:86203] 广告 msg 广告列表返回成功!
2015-07-14 16:04:50.506 DIANDIANSHANGDU[1286:86203] info {
    "ad_id" = 2;
    descripe = "\U8d5a\U94b1\U4e5f\U8981\U201c\U73a9\U82b1\U6837\U201d";
    "t_img" = "1434506858.png";
    url = "http://www.baidu.com";
}
2015-07-14 16:04:50.507 DIANDIANSHANGDU[1286:86203] -[__NSCFDictionary ad_id]: unrecognized selector sent to instance 0x174463600
2015-07-14 16:04:50.614 DIANDIANSHANGDU[1286:86203] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFDictionary ad_id]: unrecognized selector sent to instance 0x174463600'
**\* First throw call stack:
(0x18520c2d8 0x196e880e4 0x1852133a4 0x185210154 0x185112ccc 0x10022dd8c 0x100209af8 0x100417bb8 0x100b3cfd4 0x100b3cf94 0x100b41c28 0x1851c37f8 0x1851c18a0 0x1850ed2d4 0x18eb4b6fc 0x189ceaf40 0x100230b90 0x197532a08)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by CoderMJLee** [comment]
你的EntityName是AdvertisementInfo么？

**Comment by huangping35** [comment]
是的，entityName是AdvertisementInfo，我用回2.4.0的版本就不会报错。

**Comment by CoderMJLee** [comment]
试试最新版？
