### ISSUE TITLE
字典转换对象失败 

### ISSUE THREAD

**Issue by huangping35** [CoderMJLee/MJExtension#129]
我把版本升级到2.5.1还是不行，在2.4.0版本就可以，错误请看截图
![1](https://cloud.githubusercontent.com/assets/3032136/8714017/f1594c2c-2ba2-11e5-8922-d152b85d8858.png)
![2](https://cloud.githubusercontent.com/assets/3032136/8714018/f15e0780-2ba2-11e5-8ff7-5de1ea636940.png)
![3](https://cloud.githubusercontent.com/assets/3032136/8714019/f181c7e2-2ba2-11e5-9675-8f641a5c5716.png)

**Comment by sunkehappy** [comment]
在2.4.1中，增加了判断model类是不是foundation子类的判断，你这个类是继承了NSManagedObject，MJFoundation会认为它是foundation的类或者子类，然后后面的类没有解析就直接返回了（也就是一个NSDictionary）。
我对之前的做法不了解，@CoderMJLee，你看这个需要怎么改？

**Comment by CoderMJLee** [comment]
你再试试哈，已经更新版本了
