### ISSUE TITLE
丢失精度

### ISSUE THREAD

**Issue by wanzhu159** [CoderMJLee/MJExtension#13]
杰哥，字典里value的值是double类型时。转成模型会丢失精度，变成整形。

**Comment by CoderMJLee** [comment]
你的模型属性是int类型么？那肯定会丢失的。你试试把模型属性定义为double类型或者NSNumber类型

**Comment by wanzhu159** [comment]
杰哥，后台给的数据用NSJSONSerialization转成字典后，字典里面的key = latitude、 value值类型是double(比如@"latitude":(double)39.828282),我的模型里面latitude属性是nsstring.转完之后就变成一个@"39"了，是我没看清楚后台来的数据类型。%>_<%

**Comment by CoderMJLee** [comment]
改为double或者NSNumber就好了吧？

**Comment by CoderMJLee** [comment]
你下载最新框架代码试试，你用NSString应该也没问题了，我增加了个小功能

**Comment by wanzhu159** [comment]
我没改，让后台改了。我下午一点多下的最新的。😊

**Comment by CoderMJLee** [comment]
不是的，我刚才改了代码，不管服务器是什么类型，你写NSString都OK了，哈哈

**Comment by wanzhu159** [comment]
恩，我去。拉下来研究下。顶起来！！！！

**Comment by youngcao2015** [comment]
杰哥，精度丢失问题（NSJSONSerialization）依然存在哦，服务端返回的是99.99，我用NSString 接收，结果是99.98999999999999

**Comment by SuperDannyDeveloper** [comment]
我也出现了
服务器返回："deposit": 78.400, 
结果转成模型就变成 deposit = "78.40000000000001";

**Comment by Bob-WPF** [comment]
杰哥，精度丢失问题（NSJSONSerialization）依然存在哦，服务端返回的是99.99，我用NSString 接收，结果是99.98999999999999  在value = [value description] 转的时候就丢失了

**Comment by shijinliang** [comment]
服务端返回小数，用NSString接收，结果出现一堆99999，value = [value description] 转的时候就丢失精度，这个问题现在有解决方案吗？

**Comment by kinarob** [comment]
@shijinliang 用NSString 接收，不应该就是原始的的值吗？怎么会丢失呢，贴段你的代码看看呢？

**Comment by shijinliang** [comment]
@kinarob 
定义的时候是字符串@property (nonatomic,copy) NSString *price;
但是服务端返回的是数值类型，比如9.2，不是"9.2"，这个时候模型转换就会给price赋值为9.1999999999，跟踪了代码发现是mj转换的时候丢失了精度，value是NSNumber，但是用NSString接收，value = [value description]; 这句代码转换引起了精度丢失，

```
if (propertyClass == [NSString class]) {
                    if ([value isKindOfClass:[NSNumber class]]) {
                        // NSNumber -> NSString
                        value = [value description];
                    } else if ([value isKindOfClass:[NSURL class]]) {
                        // NSURL -> NSString
                        value = [value absoluteString];
                    }
                }
```

**Comment by kinarob** [comment]
@wanzhu159 你用NSNumber 或者 NSDecimal 转试试呢？

**Comment by shijian123** [comment]
> @kinarob
> 定义的时候是字符串@Property (nonatomic,copy) NSString *price;
> 但是服务端返回的是数值类型，比如9.2，不是"9.2"，这个时候模型转换就会给price赋值为9.1999999999，跟踪了代码发现是mj转换的时候丢失了精度，value是NSNumber，但是用NSString接收，value = [value description]; 这句代码转换引起了精度丢失，
> 
> ```
> if (propertyClass == [NSString class]) {
>                     if ([value isKindOfClass:[NSNumber class]]) {
>                         // NSNumber -> NSString
>                         value = [value description];
>                     } else if ([value isKindOfClass:[NSURL class]]) {
>                         // NSURL -> NSString
>                         value = [value absoluteString];
>                     }
>                 }
> ```

最后怎么解决的？让后台把数值类型变成字符串吗？

**Comment by wolfcon** [comment]
Duplicate of #572
