### ISSUE TITLE
继承自定义类，无法从dict返回嵌套的Model

### ISSUE THREAD

**Issue by jaysonjh** [CoderMJLee/MJExtension#132]
Model contains model-array【模型中有个数组属性，数组里面又要装着其他模型】
当StatusResult是继承了自定义的Class就失效了。只解析到不是NSArray的数据。而Array对应的model在debug看到的还是Dictionary。例如：

@interface BaseObject:NSObject
@propery (strong,nonatomic) NSString *name;
@end

@interface Ad : NSObject
@property (copy, nonatomic) NSString *image;
@property (copy, nonatomic) NSString *url;
@end

@interface StatusResult : BaseObject
/** Contatins status model */
@property (strong, nonatomic) NSMutableArray *statuses;
/** Contatins ad model */
@property (strong, nonatomic) NSArray *ads;
@property (strong, nonatomic) NSNumber *totalNumber;
@end

/***********************************************/

// Tell MJExtension what type model will be contained in statuses and ads.
[StatusResult setupObjectClassInArray:^NSDictionary *{
    return @{
               @"statuses" : @"Status",
               // @"statuses" : [Status class],
               @"ads" : @"Ad"
               // @"ads" : [Ad class]
           };
}];

**Comment by CoderMJLee** [comment]
我测试过了哈，没有问题哦。可以发一个有问题的Demo过来看看么？

**Comment by jaysonjh** [comment]
我检查了是自己代码上出现一些问题。抱歉，浪费你时间了

**Comment by CoderMJLee** [comment]
没事哈，解决了就好
