### ISSUE TITLE
【模型中有个数组属性，数组里面又要装着其他模型】

### ISSUE THREAD

**Issue by cassyr** [CoderMJLee/MJExtension#133]
【模型中有个数组属性，数组里面又要装着其他模型】这种情况如果有多级嵌套该如何去设置?
比如【模型A中有个数组属性B,数组B装着模型ModelB，ModelB里面又要装着数组属性C,数组属性C装着模型ModelC】,同时多级嵌套下属性映射是什么配置的啊?

**Comment by CoderMJLee** [comment]
数组B在模型A中配置，数组C在模型B中配置。是谁的属性，就在谁那里配置

**Comment by cassyr** [comment]
原来是这样,明白了
