### ISSUE TITLE
突然遇到莫名其妙的问题

### ISSUE THREAD

**Issue by mrkey0310** [CoderMJLee/MJExtension#136]
我在重构工程的时候加入了MJExtension做为模型的处理，刚开始添加的一些属性还有一些Key的映射都没问题，但后来添加了一个或者多个属性跟Key的映射之后，新的属性一直为空，如果在转换之前断点的话，偶尔会转换成功，但直接运行的时候一直是空值...

前面的属性转换经过多次的测试是没问题的，是后面修改过或新添加的属性会出现以上所属的问题。

**Comment by CoderMJLee** [comment]
有Demo看看么？是不是字典的值偶尔为nil呢？或者试试最新版？

**Comment by mrkey0310** [comment]
暂时没有demo，昨天手动更新到最新版之后就没问题了。字典的值不为nil，这个经过多次测试了，在相同的数据，在断点的情况下有时候是转换成功的，但是在直接运行的时候就大部分时候都是转换成空值的。PS:这个现象是在model 进行过更新之后才会出现的问题。
