### ISSUE TITLE
2.5.1 replacedKeyFromPropertyName 模型转字典失效

### ISSUE THREAD

**Issue by zhfish** [CoderMJLee/MJExtension#137]
+ (NSDictionary *)replacedKeyFromPropertyName {
    return @{@"idx":@"id"};
}

字典转模型时, 会把字典的id转成model里的idx
模型转字典时, 不会把idx转成id
我用的上一个版本2.3.3 ,是没问题的

**Comment by CoderMJLee** [comment]
新版本改版了，需要设置下面的属性位YES，目的是提供2种转字典的方式：
```objc
[模型类 referenceReplacedKeyWhenCreatingKeyValues:YES];
```

**Comment by zhfish** [comment]
能不能加个全局的默认设置?

**Comment by CoderMJLee** [comment]
Sorry哈，目前默认是不按照replaceKeyFromPropertyName来完成模型转字典。
[模型类 referenceReplacedKeyWhenCreatingKeyValues:YES];这句代码只需要设置一次的，比如你可以考虑在AppDelegate的启动方法中设置一次

**Comment by zhfish** [comment]
MJ兄..关键是我用了大量model... 总不要每个modeld都来一遍吧...

**Comment by zhfish** [comment]
@CoderMJLee 
MJ兄,我相信用到replaceKeyFromPropertyName的人还是占多数,希望解决方案如下,望参考
1. 希望可以给一个全局设定的地方
2. 默认是使用....
3. 像replaceKeyFromPropertyName这些方法一样给一个静态方法,我们去return YES or NO,也好过在一个不相干的地方初始化model

**Comment by CoderMJLee** [comment]
下载2.5.3版本哈，可以通过下面代码搞定
```objc
[NSObject referenceReplacedKeyWhenCreatingKeyValues:YES];
```
子类会继承父类的这个设置
