### ISSUE TITLE
json 里面的value包含html

### ISSUE THREAD

**Issue by blackchena** [CoderMJLee/MJExtension#138]
解析json 的时候 如果value中包含html代码 如何解析成功呢？mj哥

**Comment by CoderMJLee** [comment]
将HTML解析成NSString *么？可以发一段JSON来看看么？

**Comment by blackchena** [comment]
对不起，上次遇到这个问题的时候实在没法把那个字段取消了，所以忘记回复了。
其实就是html里面含有特殊字符串导致这段NSString不是正规的json，没办法转成NSDictionnary，对于这种不知道怎么解决
