### ISSUE TITLE
How to handle a typedef enum property?

### ISSUE THREAD

**Issue by Jasonbroker** [CoderMJLee/MJExtension#14]
Hi, MJ

I came across a problem:
if there is a property named:

@property (nonatomic, assign)ZC_SchemeCategory category;

which is a enum:

typedef enum{
    
    ZC_SchemeCategoryMusic,
    
}ZC_SchemeCategory;

how could I tell the extension to handle it ?

thanks!

**Comment by CoderMJLee** [comment]
MJExtension will treat enum as int. ZC_SchemeCategoryMusic is equal to 0.
