### ISSUE TITLE
MJExtension解析字典崩溃

### ISSUE THREAD

**Issue by K-Kevin** [CoderMJLee/MJExtension#140]
data =     {
        linkedList =         (
                        {
                adName = "11111";
                adUrl = "http://demo.lanrenzhijia.com/2014/pic0929/images/youku.png";
                directContext = 1;
                directType = 1;
                id = 10;
            },
        );
    };
    errorCode = 0;
    msg = "<null>";
    success = 1;

这个用以下model解析，会有大几率崩溃:
@interface ADAnalyzeToDictionaryDto : NSObject
@property (nonatomic, strong) NSString *success;
@property (nonatomic, strong) NSMutableDictionary *data;
@property (nonatomic, strong) NSString *msg;
@property (nonatomic, strong) NSString *message;
@property (nonatomic, strong) NSString *errorCode;
@end

**Comment by CoderMJLee** [comment]
能否贴出错误信息看看哈？谢谢。因为从这些数据看不出是MJExtension的哪个问题哈

**Comment by K-Kevin** [comment]
malloc: *** error for object 0x170071040: Invalid pointer dequeued from free list
*** set a breakpoint in malloc_error_break to debug

**Comment by K-Kevin** [comment]
+ (instancetype)cachedPropertyWithProperty:(objc_property_t)property
{
    MJProperty *propertyObj = objc_getAssociatedObject(self, property);
    if (propertyObj == nil) {
        propertyObj = [[self alloc] init];
        propertyObj.property = property;
        objc_setAssociatedObject(self, property, propertyObj, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    }
    return propertyObj;
}

**Comment by AdorkableDean** [comment]
我也遇到这种情况的~
时不时会崩溃

**Comment by CoderMJLee** [comment]
@K-Kevin 是这个方法里面出错了？希望能发个Demo哈

**Comment by K-Kevin** [comment]
@interface AnalyzeToDictionaryDto : NSObject
@property (nonatomic, strong) NSString *success;
@property (nonatomic, strong) NSMutableDictionary *data;
@property (nonatomic, strong) NSString *msg;
@property (nonatomic, strong) NSString *message;
@property (nonatomic, strong) NSString *errorCode;
@end

经常在success和msg这里崩掉~

**Comment by K-Kevin** [comment]
你好，崩溃在下面方法的_cachedTypes[code] = type;这一行，但是实际上控制台打印type不是空的，为何却会进入方法内呢？
+ (instancetype)cachedTypeWithCode:(NSString *)code
{
    MJAssertParamNotNil2(code, nil);
    MJType *type = _cachedTypes[code];
    if (type == nil) {
        type = [[self alloc] init];
        type.code = code;
        _cachedTypes[code] = type;
    }
    return type;
}

**Comment by sugarLW** [comment]
我也遇到了这个问题，很烦恼啊~但是但是好像找到方法~在MJProperty

**Comment by wolfcon** [comment]
#660
