### ISSUE TITLE
MJ哥 这种模型怎么转化  

### ISSUE THREAD

**Issue by cherishloveyou** [CoderMJLee/MJExtension#141]
{
    "list":[
        {
            "address":"xxxxx",
            "contactName":"汪天顺",
            "userId":1,
            "open":1,
            "sections":[
                {
                    "siteId":1,
                    "timeInfo":"08:00-09:00"
                },
                {
                    "siteId":1,
                    "timeInfo":"09:00-10:00"
                },
                {
                    "siteId":1,
                    "timeInfo":"10:00-11:00"
                },
                {
                    "siteId":1,
                    "timeInfo":"11:00-12:00"
                }
            ]
        },
        {
            "address":"xxxxx",
            "contactName":"汪天顺",
            "userId":2,
            "open":1,
            "sections":[
                {
                    "siteId":2,
                    "timeInfo":"08:00-09:00"
                },
                {
                    "siteId":1,
                    "timeInfo":"09:00-10:00"
                },
                {
                    "siteId":1,
                    "timeInfo":"10:00-11:00"
                },
                {
                    "siteId":1,
                    "timeInfo":"11:00-12:00"
                }
            ]
        }
    ]
}

**Comment by CoderMJLee** [comment]
可以考虑设计2个模型：
1.拥有address、contactName、userId、open、sections属性
2.拥有siteId、timeInfo模型
其他的你自己斟酌一下了哈，加油

**Comment by cherishloveyou** [comment]
模型我知道    但是转换不了的样子    JSON array -> model array 这种方式转换，但是（2.拥有siteId、timeInfo模型）这个好像不自动转换  我又遍历了一次做转换

**Comment by xlePE** [comment]
我也遇到了这种情况，怎样才能直接把复杂的字典数组直接转换成期望的模型数组呢？

**Comment by LengBinBin** [comment]
[这个？](https://github.com/EnjoySR/ESJsonFormat-Xcode)  而且 楼上cher 那个  这话说的 怎么看都不是在请教问题

**Comment by CoderMJLee** [comment]
@cherishloveyou @xlePE 希望你们好好看看github的README哈，里面说得很详细[模型数组属性](https://github.com/CoderMJLee/MJExtension#Model_contains_model_array)

**Comment by xlePE** [comment]
很抱歉这么蠢的问题，十分感谢。
