### ISSUE TITLE
MJ哥，字典转模型奔溃，有加-Objc，手动解析就没问题

### ISSUE THREAD

**Issue by zjz2330** [CoderMJLee/MJExtension#144]
<img width="466" alt="003ebcaa-525d-4e52-91fc-c72d5f93e2df" src="https://cloud.githubusercontent.com/assets/9798391/8898789/97884a68-345d-11e5-917d-e06da188dce9.png">
<img width="633" alt="87b9923a-e85d-40f5-bab7-47178e82a628" src="https://cloud.githubusercontent.com/assets/9798391/8898790/978a97e6-345d-11e5-8dac-1524fed61e0c.png">
<img width="313" alt="910e3964-784d-4050-bd18-369c0d7c3034" src="https://cloud.githubusercontent.com/assets/9798391/8898792/97ba2d9e-345d-11e5-9d80-cd548fd08965.png">

**Comment by CoderMJLee** [comment]
使用的是CocoaPods？

**Comment by zjz2330** [comment]
是的。

**Comment by CoderMJLee** [comment]
Xcode版本，CocoaPods版本分别是多少？

**Comment by zjz2330** [comment]
Xcode6.4，CocoaPods是0.36.1

**Comment by CoderMJLee** [comment]
升级试试？我的pod是0.37.2

**Comment by zjz2330** [comment]
<img width="607" alt="2015-07-28 11 17 16" src="https://cloud.githubusercontent.com/assets/9798391/8922818/bff2ce98-351a-11e5-99cc-deebee88ab4a.png">
升级了，0.38.2，但是编译通不过。

**Comment by LengBinBin** [comment]
额 楼上看看是不是没有创建 PPTripStateData 的 @implementation 。。。我上午有个错误就是这么出的 报错信息差不多一样

**Comment by zjz2330** [comment]
对了，谢谢，不小心把这个一起注释了，忘了打开，补上后编译通过，但是之前崩溃的问题依然存在。

**Comment by Shenjiakai** [comment]
@CoderMJLee # @zjz2330 
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_NSEntityDescription", referenced from:
      objc-class-ref in NSObject+MJKeyValue.o
  "_OBJC_CLASS_$_NSManagedObject", referenced from:
      objc-class-ref in NSObject+MJKeyValue.o
      objc-class-ref in MJFoundation.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


MRC环境的代码 mjextension配置了-objc ，是手动拖入的 ， 编译后直接报这个错 。。 请教这个是怎么修改
