### ISSUE TITLE
请问下JSON里有个key是"id"怎么直接转模型？并且多加一个字典里没有的属性？

### ISSUE THREAD

**Issue by magic3584** [CoderMJLee/MJExtension#148]
例如下面的id是字典里有的，type是方法的参数

     +(NSMutableArray *)getEnergyOrderArrayWithDictionary:(NSDictionary *)dictionary andType:(int)type
     {
        NSMutableArray * arr = [NSMutableArray array];
        for (NSDictionary * dic in dictionary[@"result"]) {
            EnergyOrderModel * model = [EnergyOrderModel new];
            model.orderId = dic[@"id"];
            model.type = type;
        }
        return arr;
      }

**Comment by LengBinBin** [comment]
这[映射说明](https://github.com/CoderMJLee/MJExtension#-model-name---json-key-mapping模型中的属性名和字典中的key不相同或者需要多级映射)

**Comment by magic3584** [comment]
第一次使用，README没理解透，多谢楼上提醒！
贴下我的代码吧，方便后来人使用。

首先是模型初始化方法：

    -(instancetype)init
    {
        if (self = [super init]) {
            [EnergyOrderModel setupReplacedKeyFromPropertyName:^NSDictionary *{
                return @{
                         @"orderId": @"id"};
            }];
        }
        return self;
    }

然后是主要的方法：

    +(NSMutableArray *)getEnergyOrderArrayWithDictionary:(NSDictionary *)dictionary andType:(int)type
    {
        NSMutableArray * arr = [NSMutableArray array];

        for (NSDictionary * dic in dictionary[@"result"]) {
        
            NSMutableDictionary * mutableDic = [NSMutableDictionary dictionaryWithDictionary:dic];

            [mutableDic setValue:[NSNumber numberWithInt:type] forKey:@"orderType"];
            EnergyOrderModel * model = [EnergyOrderModel objectWithKeyValues:mutableDic];

            [arr addObject:model];
        
        }
        return arr;
    }
