### ISSUE TITLE
多线程调用导致崩溃

### ISSUE THREAD

**Issue by CodingPub** [CoderMJLee/MJExtension#152]
![snip20150731_2](https://cloud.githubusercontent.com/assets/7928804/9030452/710efbfc-39d5-11e5-85b9-b478abdfcacf.jpg)

**Comment by Orion777** [comment]
使用项目附带的测试代码，加上多线程调用，测试几次就会出现崩溃问题，测试代码如下：
        NSOperationQueue *queue = [[NSOperationQueue alloc] init];
        queue.maxConcurrentOperationCount = 5;
        for(NSInteger i=0; i<2000; i++) {
            NSBlockOperation *operation = [NSBlockOperation blockOperationWithBlock:^{
                NSLog(@" >>>>>>>>>>>> %zd", i);
                NSLog(@" >>>>>>>>>>>> %zd", i);
                NSLog(@" >>>>>>>>>>>> %zd", i);
                execute(keyValues2object3, @"复杂的字典 -> 模型 (模型的数组属性里面又装着模型)");
                NSLog(@" >>>>>>>>>>>> %zd", i);
                NSLog(@" >>>>>>>>>>>> %zd", i);
                NSLog(@" >>>>>>>>>>>> %zd", i);
            }];
            [queue addOperation:operation];
        }
        [queue waitUntilAllOperationsAreFinished];

**Comment by Orion777** [comment]
建议方案：
+ (instancetype)objectWithKeyValues:(id)keyValues context:(NSManagedObjectContext *)context error:(NSError *__autoreleasing *)error
{
    @synchronized([self class])
    {
        if (keyValues == nil) return nil;
        if ([self isSubclassOfClass:[NSManagedObject class]] && context) {
            return [[NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass(self) inManagedObjectContext:context] setKeyValues:keyValues context:context error:error];
        }
        return [[[self alloc] init] setKeyValues:keyValues error:error];
    }
}

**Comment by CoderMJLee** [comment]
在3.0.12中已经解决哈
