### ISSUE TITLE
CoreDate relationship

### ISSUE THREAD

**Issue by zhudengdengdeng** [CoderMJLee/MJExtension#153]
一般NSManagedObject一对多关联或者多对多关联的时候会生成NSSet或者NSOrderedSet类型的property，但是我看 + (void)setupObjectClassInArray:(MJObjectClassInArray)objectClassInArray; 方法好像只支持NSArray，我主要是觉得Mantle在CoreData上的转换上有不少问题然后发现了这个库，确实非常轻量，但是现在用CoreData越来越多了，是不是也把这块搞一下比较好？

**Comment by CoderMJLee** [comment]
等不这么忙了，我抽时间搞一下哈

**Comment by zhudengdengdeng** [comment]
期待干掉Mantle！
