### ISSUE TITLE
关于在多个api接口中，不同的key对应相同的值

### ISSUE THREAD

**Issue by Mfk759853063** [CoderMJLee/MJExtension#154]
杰哥你好，我想问下这个框架有没有实现多个key对应相同的值呢？比如A接口：
persion =                 {
                    name = "xxx";
                   age = "xxx"'
                };

B接口:
people =                 {
                    name = "xxx";
                    age = "xxx"'
                };

这两个接口都是一个model，只是key不一样

**Comment by CoderMJLee** [comment]
看看README，里面有个《key mapping，key的映射》一节。你看看是不是你想要的？

**Comment by Mfk759853063** [comment]
应该不是，我想要的是比如这样A接口中的description字段对应model中的desc ，在B接口中的description1字段也是对应model的desc属性。好像这个框架没有实现吧？setupReplacedKeyFromPropertyName这个方法返回一个字典，key是model的属性，value是返回的数据，只有一个，而我想要的是字典的key可以对应多个value 。杰哥，我这样说你能明白吗？
/***********************************************/

// How to map
[Student setupReplacedKeyFromPropertyName:^NSDictionary *{
    return @{
               @"ID" : @"id",
               @"desc" : @"?",
               @"oldName" : @"name.oldName",
               @"nowName" : @"name.newName",
               @"nameChangedTime" : @"name.info[1].nameChangedTime",
               @"bag" : @"other.bag"
           };
}];
// Equals: Student.m implements +replacedKeyFromPropertyName method.
A接口返回的数据如下：

NSDictionary *dict = @{
    @"id" : @"20",
    @"desciption" : @"kids",
    @"name" : @{
        @"newName" : @"lufy",
        @"oldName" : @"kitty",
        @"info" : @[
                 @"test-data",
                 @{
                             @"nameChangedTime" : @"2013-08"
                         }
                  ]
    }
};

B接口返回的数据如下：

NSDictionary *dict = @{
    @"id" : @"20",
    @"desciption1" : @"kids",
    @"name" : @{
        @"newName" : @"lufy",
        @"oldName" : @"kitty",
        @"info" : @[
                 @"test-data",
                 @{
                             @"nameChangedTime" : @"2013-08"
                         }
                  ]
    }
};

**Comment by CoderMJLee** [comment]
最新版的MJExtension已经增加这个功能
```objc
[Student setupReplacedKeyFromPropertyName:^NSDictionary *{
return @{
     @"desc" : [@"description", @"description1"]
};
}];
```
如果description有值，就是用description，否则是用description1

**Comment by Mfk759853063** [comment]
感谢杰哥~！
