### ISSUE TITLE
isReferenceReplacedKeyWhenCreatingKeyValues 有问题

### ISSUE THREAD

**Issue by oklink** [CoderMJLee/MJExtension#156]
造成  NSObject+MJKeyValue.m 行350
   if ([aClass isReferenceReplacedKeyWhenCreatingKeyValues]) 

条件永不成立

**Comment by CoderMJLee** [comment]
如果希望成立，设置[ModelClass referenceReplacedKeyWhenCreatingKeyValues:YES]就OK了哈，默认是NO
