### ISSUE TITLE
'MJExtensionConst.h' file not found

### ISSUE THREAD

**Issue by Lilacxyz** [CoderMJLee/MJExtension#158]
刚才pod update更新了一下已有项目的pods，结果在MJExtension/MJFoundation.m中`#import "MJExtensionConst.h"`一行报错`'MJExtensionConst.h' file not found`. 是因为最近MJExtension更新了么？

**Comment by CoderMJLee** [comment]
是更新了哈。最新的MJExtension是2.5.5版本哈。你尝试pod repo update哈

**Comment by wenzhaot** [comment]
pod 确实没有设置好
