### ISSUE TITLE
coredata的model 转换不了。

### ISSUE THREAD

**Issue by recx** [CoderMJLee/MJExtension#16]
继承 NSManagedObject 的model不能转换。

**Comment by CoderMJLee** [comment]
已经增加了对CoreData的支持，可以测试一下哈！

**Comment by wang9262** [comment]
试了下，CoreData貌似还是不太好使。。会不会是我姿势不对？希望MJ能在ExampleDemo里面加入coredata的Demo

**Comment by CoderMJLee** [comment]
你的Demo发我邮箱看看哈

**Comment by yupliang** [comment]
杰哥放个CoreData Demo 上来呀。

**Comment by wang9262** [comment]
@CoderMJLee 已发

**Comment by CoderMJLee** [comment]
```objc
NSDictionary *dict = @{
                       @"name" : @"Jack",
                       @"icon" : @"lufy.png",
                       @"age" : @20,
                       @"height" : @"1.55"
                       };

User *user = [NSEntityDescription insertNewObjectForEntityForName:@"User"
                                             inManagedObjectContext:self.managedObjectContext];
// 应该要调用这个方法，直接使用NSEntityDescription创建出来的user对象
[user setKeyValues:dict]; 
// 不要使用[User objectWithKeyValues:dict]，不然又创建出一个新对象，NSEntityDescription就白用了
```

**Comment by yupliang** [comment]
杰哥，那这种直接把字典数组转换成core data 对象数组的方法是不能调用么
[Article objectArrayWithKeyValuesArray:json[@"datas"] error:&error]？
是不是需要这样逐一转换呀
User *user = [NSEntityDescription insertNewObjectForEntityForName:@"User"
                                             inManagedObjectContext:self.managedObjectContext];
[user setKeyValues:dict];

**Comment by CoderMJLee** [comment]
嗯， 暂时是的哦。因为CoreData的特殊性，必须通过NSEntityDescription去创建对象。
[Article objectArrayWithKeyValuesArray:json[@"datas"] error:&error]这个类方法会自动产生对象，并不是通过CoreData去创建对象。或者我可以试试封装一下

**Comment by yupliang** [comment]
这种 对象的属性如果是coredata 对象的呢？比如Status 是coredata 对象类。感觉即使是上边声成单个对象的方式也有问题，还是因为CoreData的特殊性，必须通过NSEntityDescription去创建对象。不知道俺说的对不，杰哥
@interface Status : NSManagedObject
@property (copy, nonatomic) NSString *text;
@property (strong, nonatomic) User *user;
@property (strong, nonatomic) Status *retweetedStatus;
@end

**Comment by CoderMJLee** [comment]
只要是继承NSManagedObject的对象，都得通过CoreData的方式创建。我今晚尝试封装一下

**Comment by CoderMJLee** [comment]
最新版的CoreData用法，对比以前，就多传递一个context参数哈
```objc
User *user = [User objectWithKeyValues:dict context:context];
```

**Comment by wang9262** [comment]
``` Objective-C
@interface Status : NSManagedObject
@property (copy, nonatomic) NSString *text;
@property (strong, nonatomic) User *user;
@property (strong, nonatomic) Status *retweetedStatus;
@end
```
@CoderMJLee 像这种结构直接使用[Status objectWithKeyValues:dict context:context]好像还是处理不了？

**Comment by CoderMJLee** [comment]
再发个Demo哈，3Q

**Comment by CoderMJLee** [comment]
完全没问题的哈，你发的代码应该要这么写哈
```objc
@class Book;
@interface User : NSManagedObject
@property (nonatomic, retain) NSNumber * age;
@property (nonatomic, retain) NSNumber * height;
@property (nonatomic, retain) NSString * icon;
@property (nonatomic, retain) NSString * name;
// book不应该写成NSManagedObject类型
@property (nonatomic, retain) Book *book;
@end
```

**Comment by wang9262** [comment]
@CoderMJLee 我都没注意，直接用Xcode生成的Model，都忘记去更改一下了。多谢
