### ISSUE TITLE
json 解析都是新对象 能通过判断已经存在的对象就不需要创建了？

### ISSUE THREAD

**Issue by huangping35** [CoderMJLee/MJExtension#160]
NSArray *items=[BillsInfo objectArrayWithKeyValuesArray:root[@"items"] context:[NSManagedObjectContext MR_defaultContext]];

这里都是新对象，如果保存到本地，就会重复，请问框架有判断对象已经存在就不需要创建，只是修改吗？

**Comment by wolfcon** [comment]
自行判断
