### ISSUE TITLE
复杂字典->模型（模型中既有模型又有模型数组）

### ISSUE THREAD

**Issue by Lilacxyz** [CoderMJLee/MJExtension#162]
请教MJ大师一个问题：
![qq20150812-1](https://cloud.githubusercontent.com/assets/5526378/9221129/78d97afa-411a-11e5-9c5a-e27c9344a0c6.png)

如上图所示的字典，转化成下图的模型：
![qq20150812-2](https://cloud.githubusercontent.com/assets/5526378/9221164/b57affba-411a-11e5-8018-f0cbe9947f4b.png)

在.m文件中有写` + (NSDictionary *)objectClassInArray` 方法，指定array里面的model。
但每次运行的时候都会在内嵌的model（如CourseInfoTVCellModel）处报错，错误信息为：
`-[CourseInfoTVCellModel copyWithZone:]: unrecognized selector sent to instance 0x7f9c43f69e20`

请问我还需要在什么地方配置什么信息么？该怎么修正这个问题？谢谢！

**Comment by Lilacxyz** [comment]
自行解决了。。貌似内嵌的model不能用copy？

**Comment by CoderMJLee** [comment]
苹果的copy只适用于遵守了NSCopying协议的对象
