### ISSUE TITLE
MJ,如果一个模型里面有很多个数组，这些数组里面我想装着对应的模型，该怎么做呢？？

### ISSUE THREAD

**Issue by zjz2330** [CoderMJLee/MJExtension#163]
+ (NSDictionary *)objectClassInArray 这个方法只能确保一个数组里装着对应的模型啊。。。

**Comment by CoderMJLee** [comment]
可以多个的：
```objc
+ (NSDictionary *)objectClassInArray
{
    return {
@"books" : @"MJBook",
@"cars" : @"MJCar" 
};
}
```

**Comment by zjz2330** [comment]
@interface PPPassportInfo : PPResponseData
@property (nonatomic, strong) NSNumber          *ID;
@end

@interface PPUserInfoData : PPResponseData
@property (nonatomic, strong) NSNumber          *ID;
@property (nonatomic, strong) PPPassportInfo    *passport;
@end

[PPUserInfoData setupReplacedKeyFromPropertyName:^NSDictionary *{
                  return @{@"ID" : @"id"};
              }];
 PPUserInfoData *userInfoData = [PPUserInfoData objectWithKeyValues:dict];
MJ老师，我想把PPPassportInfo里面后台返回的id也改成ID，应该在上面的方法中怎么做呢？？

**Comment by CoderMJLee** [comment]
交给父类就好了：
```objc
[PPResponseData setupReplacedKeyFromPropertyName:^NSDictionary *{
return @{@"ID" : @"id"};
}];
```
