### ISSUE TITLE
昨天更新完最新版本后发现之前存入本地的模型里的属性值全部为nil了

### ISSUE THREAD

**Issue by FredQU** [CoderMJLee/MJExtension#164]
之前本地存入了好多模型数据到plist文件里，昨天更新了一下最新MJExtention后，发现存入本地的模型里的属性全部为nil ,这可如何是好，以后如何兼容之前的版本呢？求救MJ大神。

**Comment by CoderMJLee** [comment]
这个问题应该是因为：
1.很久以前的版本里面用的_开头的成员变量名作为key来存取数据
2.新版本里面用的是没有_开头的属性名作为key来存取数据
