### ISSUE TITLE
是否有必要增加readonly的判断？

### ISSUE THREAD

**Issue by WenchaoIOS** [CoderMJLee/MJExtension#165]
现在是这样，在MJType解析时传入的code中已经抛弃了后面的内容。有时候碰到一个类中会出现很多readonly的属性，这些属性现在在setKeyValues还是会一条一条的解析。
但是考虑如果加上这个属性也不见得一定节约时间，因为被code抛弃的内容需要拿回来。但是起码在模型对象数量很多的时候还起点作用。请问当时是考虑过这个因素故意忽略了只读属性的判断么？

**Comment by CoderMJLee** [comment]
以前采取的是或者Ivar（成员变量），就算是Readonly属性，也能赋值，所以没有去做判断
现在换成了objc_property（成员属性），应该可以像你所说的，考虑忽略只读属性了。
谢谢提醒哈，我再思考一下
