### ISSUE TITLE
字典转换模型是同步的吗？

### ISSUE THREAD

**Issue by jiaowochunge** [CoderMJLee/MJExtension#169]
发现一个奇怪的问题。self.foo = [Entity objectWithKeyValues:dic];下面调用方法填充UI，我方法体第一句是if (!_foo) return;居然直接返回了。然后我就断点调试，发现确实是在if (!_foo) return这里返回了。如果我在self.foo = [Entity objectWithKeyValues:dic];也打个断点，是可以得到模型数据的。

**Comment by jiaowochunge** [comment]
纯失误。我把属性设成了weak

**Comment by CoderMJLee** [comment]
👌，解决了就好哈
