### ISSUE TITLE
当json数据中的值为：accord = "<null>";这种情况的时候崩溃

### ISSUE THREAD

**Issue by pfirsiche** [CoderMJLee/MJExtension#170]
小码哥，您好，我在使用您的这个库的时候，当返回的json数据当中有 accord = "<null>"; 这样的字段的时候，就会崩溃，报的这样的错误：**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to insert non-property list object (
麻烦您更新一下这里，对这种情况加以判断，谢谢了。
<img width="1230" alt="2015-08-19 12 40 06" src="https://cloud.githubusercontent.com/assets/9293179/9336199/ebaa69a0-460a-11e5-9eca-27c903679e09.png">

**Comment by studyBully** [comment]
你这个是用userDefault 保存的时候不对吧。保存的时候出现了空数据。
