### ISSUE TITLE
最近在使用你的MJExtension遇到了一个转换MJKeyValue对象错误问题

### ISSUE THREAD

**Issue by Tate-zwt** [CoderMJLee/MJExtension#172]
设置成员变量的值
 (void)setValue:(id)value forObject:(id)object

在使用数组字典转换成模型数组的时候，我写的模型名称为Imp  转换一直返回空字典，MJKeyValue 对象错误（上面方法里属性object类型错误），后来我把模型名称换成Sort就转换成功了，我也想知道这个是哪里出了问题，希望你能回复说明下，谢谢

**Comment by CoderMJLee** [comment]
能否将报错代码贴出来看看？谢谢哈

**Comment by Tate-zwt** [comment]
改回去后我发现居然不会转错误了= =

**Comment by CoderMJLee** [comment]
没问题就OK了哈
