### ISSUE TITLE
J哥  我又来请教问题了 模型转换出现 0 key/value 问题 谢谢

### ISSUE THREAD

**Issue by chihaodong** [CoderMJLee/MJExtension#174]
MJ老师，迫不得已，给你QQ留言，但是发现你不在，只能到这里请教了

服务器返回来的数据是 模型  模型嵌套，但是转换的时候 出现 0 key/value 问题，包括自写手写模型转换方法，也同样出现  0 key/value  ，莫名其妙，想请你帮忙  看看问题出现哪里了

我把服务器返回来的，模型数组，单独取出一个模型在本地，

文件位置：General-Mine-CollectionSellerController.m 文件中的 test 方法   模型转化不过去 导致  UItableView 索引条 不能使用，之前第一次运行模型有数据的时候  点击所以条 就崩溃，然后在运行模型就没有数据了   

界面操作：我- 收藏商家 页面

代码我发到 QQ邮箱了  J哥  谢谢啊

**Comment by CoderMJLee** [comment]
我刚才抽空看了下你的代码哈，因为你的是本地服务器地址，所以我这边请求不来数据，看不到最终的错误效果

**Comment by CoderMJLee** [comment]
你具体是什么问题？你说的0 key/value我不太理解哈。有没有报错信息？

**Comment by chihaodong** [comment]
J哥  非常抱歉啊 ，才来回复，问题搞定了  是Xcode的问题 显示是模型里面是 0key/value，但是实际打印，是有内容的  因为外网服务还没有部署上 所以暂时看不到效果，谢谢你啊  哈

**Comment by CoderMJLee** [comment]
哈哈哈，那其实是没问题哈

**Comment by chihaodong** [comment]
感谢 J哥  ~~~！
