### ISSUE TITLE
objectArrayWithKeyValuesArray不可用

### ISSUE THREAD

**Issue by tospery** [CoderMJLee/MJExtension#178]
NSArray *addresses = [LHAddress objectArrayWithKeyValuesArray:response context:kMRContext];
在执行类似如上代码的时候，因为LHAddress是NSManagedObject的子类，而
+ (NSSet *)foundatonClasses
{
    if (_foundationClasses == nil) {
        _foundationClasses = [NSSet setWithObjects:
                              [NSURL class],
                              [NSDate class],
                              [NSValue class],
                              [NSData class],
                              [NSArray class],
                              [NSDictionary class],
                              [NSManagedObject class], // 会造成直接返回
                              [NSString class], nil];
    }
    return _foundationClasses;
}

**Comment by CoderMJLee** [comment]
更新一下MJExtension就可以了，好早以前改过了哈

**Comment by tospery** [comment]
朕，知道了，感谢！
