### ISSUE TITLE
老师好，以前服务器遗留的接口回返回那种实体类属性的拼音简写，能不能转换下

### ISSUE THREAD

**Issue by sunjie798893816** [CoderMJLee/MJExtension#179]
那种属性真心头疼啊，我如果在model里面定义的和服务器json返回数据名字一样，可读性太差了，能不能转换下下  比如把 车辆名字  clmz  这个属相装换成carName

**Comment by CoderMJLee** [comment]
有的，参考README和Demo中的replacedKey...用法
