### ISSUE TITLE
进行多级映射的时候，上一级必须有对应的值，否则奔溃

### ISSUE THREAD

**Issue by FutureChen** [CoderMJLee/MJExtension#18]
你好，MJ 老师
    在项目中使用这个框架的时候，发现一个小问题： 进行多级映射的时候，json数据中必须有对应的值，否则会奔溃。
我将您的示例demo 做了修改，用来复现BUG，您可以看看。
void keyValues2object4()
{
    // 1.定义一个字典
    NSDictionary *dict = @{
                           @"id" : @"20",
                           @"desciption" : @"好孩子",
                           @"name" : [NSNull null],
                           @"other" : @{
                                @"bag" : @{
                                    @"name" : @"小书包",
                                    @"price" : @100.7
                                }
                           }
                        };

    // 2.将字典转为Student模型
    Student *stu = [Student objectWithKeyValues:dict];
——————————此处crash
}

"oldName" : @"name.oldName",
在Student 类中对 oldName进行了name.oldName的多级映射，  但是如果上一级name ==null 则就直接奔溃。

在我的项目中的实际场景是   @"赠送人" : @{@”赠送人ID“，@”赠送人姓名“} 
如果赠送人都不存在， 那么“赠送人”=nul，进行赠送人ID 和赠送人姓名，映射解析的时候就奔溃了。

**Comment by FutureChen** [comment]
NSObject+MJKeyValue.m中

        id value = keyValues ;
        if (!value || value == [NSNull null]) return MJLog(@"映射上一级为空");
        NSArray *keys = [ivar keysFromClass:[self class]];
        for (NSString *key in keys) {
                value = value[key];
        }
        if (!value || value == [NSNull null]) return;
貌似这样就解决了

**Comment by CoderMJLee** [comment]
谢谢提醒，此问题已经解决
id value = keyValues ;
```
NSArray *keys = [ivar keysFromClass:[self class]];
for (NSString *key in keys) {
    if (![value isKindOfClass:[NSDictionary class]]) continue;
    value = value[key];
}
 if (!value || value == [NSNull null]) return;
```
