### ISSUE TITLE
和关键字冲突

### ISSUE THREAD

**Issue by stevenlfg** [CoderMJLee/MJExtension#180]
后台返回过来的字段里面有关键字description,然后程序停在了这里
- (void)setValue:(id)value forObject:(id)object
{
    if (self.type.KVCDisabled || value == nil) return;
    [object setValue:value forKey:self.name];
}
有什么方法可以替换关键字吗？
初步使用MJExtension,请指教，谢谢！

**Comment by jasoncooperJ** [comment]
+ (NSDictionary *)replacedKeyFromPropertyName
{
    return @{
             @"stevenIfg" : @"description",
             };
}

**Comment by stevenlfg** [comment]
谢谢！
