### ISSUE TITLE
解析对象时，出现crash

### ISSUE THREAD

**Issue by tospery** [CoderMJLee/MJExtension#182]
- (id)valueForObject:(id)object
{
    if (self.type.KVCDisabled) return [NSNull null];
    return [object valueForKey:self.name];
}
调试发现object类型为NSURLError、从而引起crash，建议修改为：
- (id)valueForObject:(id)object
{
    if (self.type.KVCDisabled) return [NSNull null];

    if ([object isKindOfClass:[NSError class]]) {
        return [(NSError *)object localizedDescription];
    }

    return [object valueForKey:self.name];
}

**Comment by CoderMJLee** [comment]
你应该是模型转字典时出错了吧？试试最新的2.5.9版本，我加了个NSError相关的处理

**Comment by tospery** [comment]
谢谢
