### ISSUE TITLE
将多个字典数组转模型数组

### ISSUE THREAD

**Issue by HugSea** [CoderMJLee/MJExtension#184]
MJ老师,将一个字典数组转模型数组直接用+ (NSDictionary *)objectClassInArray; 但是如果一个模型里面有多个数组,我想将模型里面的多个字典数组同时转换为模型数组该怎么处理,感谢MJ老师.

**Comment by CoderMJLee** [comment]
```objc
@{
@"users" : @"MJUser",
@"cars" : @"MJCar"
}
```

**Comment by HugSea** [comment]
不行呢,编译Faild
我是这么写的:
+ (NSDictionary *)objectClassInArray {
    return @{@"idealist" : [XLStrategy class],
             @"catlist" : [XLStrategyCat class]};
}
报错:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_XLStrategyCat", referenced from:
      objc-class-ref in XLStrategyResult.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by CoderMJLee** [comment]
这是其他问题了哈，跟框架没有关系，错误信息表示：XLStrategyCat类找不到，意思是XLStrategyCat是没有参与编译。你可以在Compile Source界面把这个类加进去，或者重新创建这个类

**Comment by HugSea** [comment]
已解决,之前我把模型XLStrategy和XLStrategyCat分别都写到XLStrategy.h里面了,现在重新创建了XLStrategyCat.h,问题就解决了,感谢MJ老师

**Comment by CoderMJLee** [comment]
不客气哈
