### ISSUE TITLE
李老师,这个框架不太稳定

### ISSUE THREAD

**Issue by WilsonSheldon** [CoderMJLee/MJExtension#185]
李老师你好! 我在使用你的框架的过程中,有时会崩掉,但不做任何修改,过一会又可以运行了;
报错信息:
2015-08-27 10:01:40.372 YJWeibo[25453:10060540] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFConstantString substringWithRange:]: Range {9223372036854775808, 18446744073709551615} out of bounds; string length 0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e373c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010dc50bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010e373b9d +[NSException raise:format:] + 205
	3   CoreFoundation                      0x000000010e29ab98 -[__NSCFString substringWithRange:] + 136
	4   YJWeibo                             0x000000010d6172ba -[YJStatus setSource:] + 234
	5   Foundation                          0x000000010d7e6b53 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 259
	6   YJWeibo                             0x000000010d5e5a5d -[MJIvar setValue:] + 157
	7   YJWeibo                             0x000000010d5e7de1 __37-[NSObject(MJKeyValue) setKeyValues:]_block_invoke + 897
	8   YJWeibo                             0x000000010d6099fa __46-[NSObject(MJMember) enumerateIvarsWithBlock:]_block_invoke + 202
	9   YJWeibo                             0x000000010d609e4e -[NSObject(MJMember) enumerateClassesWithBlock:] + 158
	10  YJWeibo                             0x000000010d6098e5 -[NSObject(MJMember) enumerateIvarsWithBlock:] + 181
	11  YJWeibo                             0x000000010d5e7a15 -[NSObject(MJKeyValue) setKeyValues:] + 277
	12  YJWeibo                             0x000000010d5e7727 +[NSObject(MJKeyValue) objectWithKeyValues:] + 199
	13  YJWeibo                             0x000000010d5e8b26 +[NSObject(MJKeyValue) objectArrayWithKeyValuesArray:] + 566
	14  YJWeibo                             0x000000010d5ed041 __32-[YJHomeController loadMoreData]_block_invoke + 209
	15  YJWeibo                             0x000000010d604701 __55-[AFHTTPSessionManager GET:parameters:success:failure:]_block_invoke + 241
	16  YJWeibo                             0x000000010d642abb __72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_276 + 203
	17  libdispatch.dylib                   0x0000000111360186 _dispatch_call_block_and_release + 12
	18  libdispatch.dylib                   0x000000011137f614 _dispatch_client_callout + 8
	19  libdispatch.dylib                   0x0000000111367a1c _dispatch_main_queue_callback_4CF + 1664
	20  CoreFoundation                      0x000000010e2db1f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	21  CoreFoundation                      0x000000010e29cdcb __CFRunLoopRun + 2043
	22  CoreFoundation                      0x000000010e29c366 CFRunLoopRunSpecific + 470
	23  GraphicsServices                    0x0000000113d37a3e GSEventRunModal + 161
	24  UIKit                               0x000000010f48a900 UIApplicationMain + 1282
	25  YJWeibo                             0x000000010d66fa1f main + 111
	26  libdyld.dylib                       0x00000001113b3145 start + 1
	27  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by xingheng** [comment]
MJExension借助KVC给model class赋值，从堆栈上看，你修改了YJStatus这个类的source这个setter属性，setSource既然是你自己写的实现，中间出现了字符串操作错误，这不属于MJExtension的问题，也是你在使用这个拓展框架不当导致。


3 CoreFoundation 0x000000010e29ab98 -[__NSCFString substringWithRange:] + 136
4 YJWeibo 0x000000010d6172ba -[YJStatus setSource:] + 234
5 Foundation 0x000000010d7e6b53 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 259

**Comment by xingheng** [comment]
至于为什么会“有时会崩掉”，部分原因应该取决于你的数据。

**Comment by WilsonSheldon** [comment]
我已经找到问题的原因了, 谢谢!

**Comment by CoderMJLee** [comment]
错误在这：
```objc
4 YJWeibo 0x000000010d6172ba -[YJStatus setSource:] + 234
```
服务器传的source值不稳定
