### ISSUE TITLE
两份不同的JSON->同一个Model

### ISSUE THREAD

**Issue by wzf** [CoderMJLee/MJExtension#187]
Hi, Lee:
描述一下场景，User类包括两个@property，分别是uID、name。
服务器端接口返回的JSON数据中可能存在如下两种格式
1. {"userID":"",  "userName":""}
2. {"userid":"", "username":""}
(解释一下这样的情况，APP中可能多个界面都需要用到【人员】这样的角色，比如登录可能就是会员，再比如通讯录可能就是联系人信息，等等。最终都可以归结到User这个Model中。或者，后台接口是好多个人写的，然后针对这一个User类，会返回不同的key，唉，就是这么扯淡。。。)

>> 已有的解决方案：基类User，子类Account、Contacter

MJExtension提供了类方法+setupReplacedKeyFromPropertyName：
不足点，因为是类方法，无法做到实例化操作。尤其是多线程处理过程中，如果设置多次的话，可能就会失败了吧。

问题：能不能扩展一个实例方法，可能的用法如下
"================================================================"
NSDictionary *jsonDict0 = @{"username":"wzf", "userid":"107"};
User *user0 = [User objectWithKeyValues:jsonDict  keyMapping:^NSDictionary *{
    return @{
               @"uID" : @"userid",
               @"name" : @"username",
           };
}
"================================================================"
NSDictionary *jsonDict1 = @{"userName":"wzf", "userID":"107"};
User *user1 = [User objectWithKeyValues:jsonDict  keyMapping:^NSDictionary *{
    return @{
               @"uID" : @"userID",
               @"name" : @"userName",
           };
}

猜测可能会出现的问题：效率有所下降。

**Comment by CoderMJLee** [comment]
最新的MJExtension支持这种功能
```objc
return @{
@"uID" : @[@"userid", @"userID"],
@"name" : @[@"username", @"userName"]
};
```
