### ISSUE TITLE
模型 字段设置为float类型时，小数点后的数据都被设置为0了

### ISSUE THREAD

**Issue by bluesky0109** [CoderMJLee/MJExtension#188]
![Uploading image.png…]()

**Comment by CoderMJLee** [comment]
Sorry，看不到图片哈。我这边测试了一下，小数还是有保留的。会不会服务器返回的数据本来就没有小数？

**Comment by chengleyi** [comment]
MJ哥，请问NSSet什么时候支持。。。还有由于NSManagedObject 多线程传递会有些问题。我这边总coredata方法出了挺多的麻烦以及内存泄露，请问有没有什么好的方法可以解决。 发自网易邮箱大师 在2015年08月28日 18:16 ，bluesky0109写道： [Uploading image.png…]() — Reply to this email directly or view it on GitHub.

**Comment by klaus01** [comment]
我也遇到小数被四舍五入的问题。使用目前最新的代码重现了该问题，代码如下：
``` Objective-c
NSString *jsonString = @"{\"name\":\"Jack\", \"icon\":\"lufy.png\", \"age\":20, \"height\":33333333.7}";
User *user = [User objectWithKeyValues:jsonString];
NSLog(@"name=%@, icon=%@, age=%d, height=%f", user.name, user.icon, user.age, user.height);
```
按理height应等于33333333.7，而转换后height=33333334.000000

**Comment by CoderMJLee** [comment]
这是打印的问题，你用的时候建议这么用:包装成NSNumber就准确了
```objc
NSLog(@"name=%@, icon=%@, age=%d, height=%@", user.name, user.icon, user.age, @(user.height))
```

**Comment by CoderMJLee** [comment]
比较建议使用NSNumber，能保证数据的完整性
