### ISSUE TITLE
能默认添加Copy支持吗？

### ISSUE THREAD

**Issue by xx-li** [CoderMJLee/MJExtension#19]
您好，有时候有Copy 或者 coder/encoder的需求,  后续会提供此功能吗？

**Comment by CoderMJLee** [comment]
你的意思是让模型支持copy功能？比如[dog copy]

**Comment by xx-li** [comment]
是的， 还有支持NSCoding协议， 有时候需用用到archiver 方法进行数据存储。

**Comment by CoderMJLee** [comment]
NSCoding已经支持：参考NSObject+MJCoding.h文件哈。只要在你的.m文件中添加MJCodingImplementation宏，就可以实现所有属性支持归档和解档。如果有个别属性不想进行归解档，那就实现+ (NSArray *)ignoredCodingPropertyNames;方法，在数组中说明哪些属性不需要归解档。
