### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by stevenlfg** [CoderMJLee/MJExtension#190]
建议作者把开发者在使用MJExtension过程中经常出现的问题和解决方案列出来，这样对于刚开始使用该框架的人就不会一直提出类似的问题了。

**Comment by CoderMJLee** [comment]
好的，谢谢提醒。后期会打算搞个专门的网站来介绍MJRefresh和MJExtension哈

**Comment by stevenlfg** [comment]
Good!
