### ISSUE TITLE
Swift2.0中objectWithKeyValues不能使用

### ISSUE THREAD

**Issue by yanshinian** [CoderMJLee/MJExtension#195]
objectWithKeyValues is unavailable：use object construction nsobject(keyValues:)

然而我把use object construction nsobject(keyValues:)随便改成叫做wwww 然后就可以用了

莫非是命名上的冲突还是啥子问题

**Comment by yanshinian** [comment]
改成 + (instancetype)dictToModel:(id)keyValues;  就这样可以调用了
        let dict = ["name": "zhoujielun", "age": "22"]
//        let p1 = Person.objectWithKeyValues(dict)
        let p = Person.dictToModel(dict)
        print(p.name)

结果 Optional("zhoujielun")

**Comment by CoderMJLee** [comment]
是Swift语法问题，应该这样调用 let model = ModelClass(keyValues: dict)

**Comment by yanshinian** [comment]
ok, ModelClass(keyValues: dict)可以的
可以问个延伸问题么？
我模型中的属性是 var li: [Article]?
用MJExtension处理完似乎 是NSArray
            let newDictStr = "{ \"li\" : \(request.responseString)}"
            let articles = Articles(keyValues: newDictStr)
//            let articles = Articles.dictToModel(newDictStr)
            print(articles.li);
于是有个错误发生“fatal error: NSArray element failed to match the Swift Array Element type”

**Comment by yanshinian** [comment]
override static func objectClassInArray() -> [NSObject : AnyObject]! {
        return ["li": "Article"]
    }
这个函数貌似没起倒作用，以至于打印出来不是模型的数组，奇怪了

**Comment by lyluoyuan** [comment]
同问
