### ISSUE TITLE
初始化MJExstension出现了问题

### ISSUE THREAD

**Issue by wuyangchinanju** [CoderMJLee/MJExtension#196]
同样的代码，在同事电脑上运行正确，在我电脑报这个错误。
代码：[NSObject referenceReplacedKeyWhenCreatingKeyValues:YES];
错误：arc semantic issue
           no known class method for selector ‘referenceReplacedKeyWhenCreatingKeyValues’

**Comment by yangfeiyu** [comment]
我也遇到了这个问题

**Comment by CoderMJLee** [comment]
@wuyangchinanju 是同一份代码么？会不会是你和你同事的MJExtension版本不一致？
