### ISSUE TITLE
[swift+alamofire+MJ]无法转换成Model

### ISSUE THREAD

**Issue by dyguests** [CoderMJLee/MJExtension#198]
MJ大大早上好:
    我昨天试用时,有一个转换过不去,如下:

1.服务器端返回内容为:  {"status":"0","content":{"infect":1,"normal":0,"total":1}}
2.客户端用 Alamofire.request(...).responseJSON取得JSON
3.用json["content"]取得content中的内容.
4.将其转换成Model
   var dict = content as! NSDictionary
   var count = InfectCount(keyValues: content)
注:
class InfectCount:NSObject {
    var normal:Int?
    var infect:Int?
    var total:Int?
}

5.但转换成count中的元素均为nil.

请问您知道是怎么回事吗?

**Comment by CoderMJLee** [comment]
目前MJExtension只能很好地支持OC哈，并不能完美支持Swift中的数据模型。你可以使用.h和.m编写模型代码，然后在bridge文件中#import "模型.h"用到Swift中去

**Comment by yanshinian** [comment]
@CoderMJLee  嗯，晓得了

**Comment by yanshinian** [comment]
嗯，直接用kvc吧，也写不了太多代码了，我直接用kvc了
