### ISSUE TITLE
5s 及其之上的模拟器正常，5s之下的模拟器异常

### ISSUE THREAD

**Issue by YueLiXing** [CoderMJLee/MJExtension#199]
-[__NSCFString longValue]: unrecognized selector sent to instance 0x79a2cd20

<img width="447" alt="2015-09-11 14 08 17" src="https://cloud.githubusercontent.com/assets/9456800/9808122/b71a4bf6-588e-11e5-9d8d-aeb1acc0636f.png">

 Error Domain=-[__NSCFString longValue]: unrecognized selector sent to instance 0x78e526b0 Code=250 "The operation couldn’t be completed. (-[__NSCFString longValue]: unrecognized selector sent to instance 0x78e526b0 error 250.)"

**Comment by CoderMJLee** [comment]
试试最新的MJExtension，2.5.10。原因在于32bit、64bit环境下的long类型符不一致哈。
```objc
pod repo update
pod update
```
