### ISSUE TITLE
pod search MJExtension

### ISSUE THREAD

**Issue by MrQQQQQQQQQQ** [CoderMJLee/MJExtension#20]
添加依赖的时候一直卡在Analyzing dependencies，pod search MJExtension，发现找不到， Unable to find a pod with name matching `MJExtension'。另一个MJRefresh也同样找不到。

**Comment by CoderMJLee** [comment]
首先要更新你本地的pod库哈，比如
pod repo update 
或者
pod setup

**Comment by MrQQQQQQQQQQ** [comment]
OK,非常感谢！
