### ISSUE TITLE
@implementation UITableView (MJRefresh)分类导致我程序崩溃。。。

### ISSUE THREAD

**Issue by liuchaoqian** [CoderMJLee/MJExtension#202]
- (void)mj_reloadRowsAtIndexPaths:(NSArray *)indexPaths withRowAnimation:(UITableViewRowAnimation)animation
{

   [self mj_reloadRowsAtIndexPaths:indexPaths withRowAnimation:animation];
    
    [self executeReloadDataBlock];
}

**Comment by CoderMJLee** [comment]
试试2.4.10版本
```objc
pod repo update
pod update
```

**Comment by liuchaoqian** [comment]
还是有问题哦，MJ大神，程序还是会崩溃。

**Comment by liuchaoqian** [comment]
我把这句代码注释，会不会影响刷新？
[self mj_reloadRowsAtIndexPaths:indexPaths withRowAnimation:animation];

**Comment by CoderMJLee** [comment]
我都已经删掉那段代码了哦？还会崩溃？这个不会影响你的刷新，只会影响footer的自动显示和隐藏，不过这些都可以人为解决的

**Comment by liuchaoqian** [comment]
恩，好的，谢谢MJ大神啊，之前学基础都是看的你的视频，祝小马哥越办越好啊。

**Comment by CoderMJLee** [comment]
谢谢哈
