### ISSUE TITLE
一个奇葩的映射问题

### ISSUE THREAD

**Issue by CodeCMLee** [CoderMJLee/MJExtension#203]
Dog.h
![qq20150915-2](https://cloud.githubusercontent.com/assets/11853095/9872248/96e27586-5bca-11e5-825e-dfc2827c1673.png)

Dog.m
![qq20150920-1](https://cloud.githubusercontent.com/assets/11853095/9979322/c324a484-5f99-11e5-8cda-8a2adddc4a32.png)

以属性“nickName”为例，如果要转换对Dog对象的字典中的key是“nick_name”时，转换是正常的，如果是“nickName”，转换后，nickName对应的字段就得不到正确的值。截图如下：
字典中为"nick_name"
![qq20150915-1](https://cloud.githubusercontent.com/assets/11853095/9872529/758fda84-5bcc-11e5-9d7d-b2ca35f31857.png)

字典中为"nickName"
![qq20150915-4](https://cloud.githubusercontent.com/assets/11853095/9872536/812d51c8-5bcc-11e5-91ab-f782cee64f0d.png)

问题：是否可以兼容一下呢？让字典中无论是"nickName"还是"nick_name"都可以映射到"nickName"属性。有时候因为后台新旧接口兼容的原因，有的接口返回的是"nickName"，有的是"nick_name",碰到这种情况就纠结了……

**Comment by CoderMJLee** [comment]
Dog.m的内容贴出来看看

**Comment by CodeCMLee** [comment]
非常感谢J哥在百忙之中看了我的问题，非常抱歉，上次把图给贴错了，现在已经换掉了。不知道上面的表述能不能表达清楚，我的想法是对于"nickName"这个字段，不管后台接口返回的是"nickName"还是"nick_name"，通过 + (NSDictionary *)replacedKeyFromPropertyName; 方法提供的字典 
@{
            @"nickName":@"nick_name",
            @"salePrice":@"sale_price",
            @"runSpeed":@"run_speed"
        };
都能正确的转换。

**Comment by CoderMJLee** [comment]
@"nickName" : @[@"nickName", @"nick_name"]
