### ISSUE TITLE
老师好。关于 class_copyIvarList

### ISSUE THREAD

**Issue by wy19901227** [CoderMJLee/MJExtension#204]
我记得以前是用的 class_copyIvarList，其他两个流行的用的是class_copyPropertyList。现在怎么也改成class_copyPropertyList了，速度会变慢吗？

**Comment by wy19901227** [comment]
是从哪个版本改的了？

**Comment by CoderMJLee** [comment]
是的，以前用是ivar，应该是从2.0版本开始用的property。ivar只能获得成员变量，property可以兼顾到那些没有生成成员变量的@dynamic属性。速度是不会变慢的。

**Comment by wy19901227** [comment]
也就说是为了支持core data 必须使用class_copyPropertyList？
