### ISSUE TITLE
字典数组转模型数组，当数据元素为foundation类型时，返回数组类型不可变

### ISSUE THREAD

**Issue by ZaggerWang** [CoderMJLee/MJExtension#207]
是不是可以这样改一下，MJ大神
![1](https://cloud.githubusercontent.com/assets/11342795/9951638/869004f4-5dfb-11e5-84b4-021bfd585f41.png)

**Comment by yafengxn** [comment]
@ZaggerWang 请问下，你这样改是出于什么样的考虑？更方便？

**Comment by ZaggerWang** [comment]
@yafengxn 安全，有时传入的字典中包含的数据是immutalbe的，但是模型里字义的对应字段却是NSMutableArray导致出现crash,而且既然这个方法的返回值类型写的是NSMutableArray*，我觉得就应该保证这一点。

**Comment by yafengxn** [comment]
@ZaggerWang ，的确是这样，你这样写更为严谨

**Comment by CoderMJLee** [comment]
@ZaggerWang 3Q。已经Merge了你的代码哈

**Comment by ZaggerWang** [comment]
@CoderMJLee ok！
