### ISSUE TITLE
数组中的字典不能转换成模型

### ISSUE THREAD

**Issue by liuxinyugithub** [CoderMJLee/MJExtension#208]
最新版本的MJExtension在使用的时候遇到的问题。以前的版本正常。
问题如下：模型中有个数组，数组中又有模型时。使用以下方法指定数组中存放的模型类型后
-(NSDictionary *)objectClassInArray
{
    return @{@"attribute1":[XXXX class]};
}
转换时，这个数组中的字典数据不能转换成对应的XXXX模型。在日志中打印出来的类型仍为字典。
但是以前的版本是能正常转换的？
请MJ老师测试以下。或者给予指正

**Comment by CoderMJLee** [comment]
```objc
// -  > + 在很久以前，就废弃了-号的用法哈
+ (NSDictionary *)objectClassInArray
{
return @{@"attribute1":[XXXX class]};
}
```

**Comment by liuxinyugithub** [comment]
原来如此啊

**Comment by CoderMJLee** [comment]
Sorry哈，给你带来不便了
