### ISSUE TITLE
没有Model->JSON

### ISSUE THREAD

**Issue by yanglezyq** [CoderMJLee/MJExtension#210]
老师，Model转JSON加一个吧，哈哈。

 NSDictionary * modelDictionary = model.keyValues;
            NSString * modelJSONStr = [[NSString alloc] initWithData:[NSJSONSerialization dataWithJSONObject:modelDictionary  options:0 error:nil] encoding:NSUTF8StringEncoding];

**Comment by CoderMJLee** [comment]
```objc
NSString *string = model.JSONString;
```
