### ISSUE TITLE
老师，加一个 字典字符串 －> Model的功能吧

### ISSUE THREAD

**Issue by yanglezyq** [CoderMJLee/MJExtension#211]
老师，我这边把所有的Model都以text类型存入数据库了，text中所存放的都是 字典类型的字符串，而非JSON类型的字符串。
然后，在读取数据库的时候，就无法解析这么个字典字符串了。

**Comment by CoderMJLee** [comment]
本身字典字符串就不好解析哈。。。应该需要大量的字符串解析工作，因为它并不是标准的JSON格式
