### ISSUE TITLE
multple methods name 'count' found with mismatched result,parameter type or attributes

### ISSUE THREAD

**Issue by landaship** [CoderMJLee/MJExtension#212]
multple methods name 'count' found with mismatched result,parameter type or attributes,在MJPropertyKey.h文件里，请问这个怎么解决？
![2015-09-22 9 58 49](https://cloud.githubusercontent.com/assets/8022528/9993705/a91c3954-60ab-11e5-891a-bdf46ddc9833.png)

**Comment by CoderMJLee** [comment]
有些项目就会出现这个问题哈，大部分项目不会。我加了个宏MJDot，解决了一下，任何项目都没问题了，你试试2.5.11版本。
```objc
pod repo update
pod update
```
