### ISSUE TITLE
如果一个Model里面包含一个NSDictionary属性,能不能指定Key和Value的类型,或者只是Value类型就行了

### ISSUE THREAD

**Issue by core-lib** [CoderMJLee/MJExtension#213]
如果一个Model里面包含一个NSDictionary属性,能不能指定Key和Value的类型,或者只是Value类型就行了

因为我做了一个跨平台RPC框架,接口规范由服务端定义  Android和iOS端客户端代码 是通过后台生成的  包括接口和对应的Model类型  因为Java有泛型所以这个问题很简单    但是Objective-C没有泛型  所以这个问题比较难解决...

**Comment by CoderMJLee** [comment]
Xcode7开始支持泛型了

**Comment by wolfcon** [comment]
#385
