### ISSUE TITLE
MJExample中的问题

### ISSUE THREAD

**Issue by muchtalk** [CoderMJLee/MJExtension#215]
在MJExampleDemo中发现在main函数中执行 keyValues2object4() 函数时， student类中注释掉
//+ (NSDictionary *)replacedKeyFromPropertyName 方法仍然能建立正确的映射，但是copy相关代码到新建的Viewcontroller中执行却不能正确建立model 难道是exmaple中有什么黑魔法？请MJ哥解答

**Comment by CoderMJLee** [comment]
参考MJExtensionConfig.m
