### ISSUE TITLE
字典转模型中出现id

### ISSUE THREAD

**Issue by cjnwan** [CoderMJLee/MJExtension#217]
JSON数据中会有id字段

**Comment by CoderMJLee** [comment]
参考
```objc
[模型类 setupNewValueFromOldValue:^id(id object, id oldValue, MJProperty *property) {
      // 将服务器返回的oldValue进行处理后，返回一个newValue
    return newValue;
}];
```

**Comment by lehom** [comment]
不是应该在modelClass 中覆写+ (NSString *)replacedKeyFromPropertyName121:(NSString *)propertyName方法吗？

因为
+ (NSString *)propertyKey:(NSString *)propertyName
{
    MJExtensionAssertParamNotNil2(propertyName, nil);
    
    __block NSString *key = nil;
    // 查看有没有需要替换的key
    if ([self respondsToSelector:@selector(replacedKeyFromPropertyName121:)]) {
        key = [self replacedKeyFromPropertyName121:propertyName];
    }
...........
}

**Comment by CoderMJLee** [comment]
有了id字段，就意味着这个模型的类型可能是动态确定的。所以需要根据服务器返回的数据是什么来决定将他转成什么模型。我的理解是这样哈
