### ISSUE TITLE
Crash with value type 'int32_t'

### ISSUE THREAD

**Issue by sunkehappy** [CoderMJLee/MJExtension#219]
I'm using [mogenerator](https://github.com/rentzsch/mogenerator) and `MJExtension`. Then `MJExtension` will encounter error at line 62 in file `MJProperty.m`. Version is 2.5.12

Its `attrs` seems to be `Ti`? Very strange.

**Comment by CoderMJLee** [comment]
I just made a test with int32_t.I didn't find any crash.Can you give me more information?

**Comment by CoderMJLee** [comment]
Please try to use the latest version of MJExtension.

**Comment by sunkehappy** [comment]
OK, I'll test later. Currently I'm working on other things.
