### ISSUE TITLE
问下NSDate类型怎么处理的

### ISSUE THREAD

**Issue by wxfstwxf** [CoderMJLee/MJExtension#22]
后台返回的是java里1970年的毫秒数，如何才能自动转换为model中的NSDate属性

**Comment by CoderMJLee** [comment]
我个人觉得自动转换不太灵活，最好交给开发者去转换。
做法是：重写NSDate属性的set方法，将传递进来的毫秒数转成自己想要的NSDate对象

**Comment by CoderMJLee** [comment]
现在提供了+ (void)setupNewValueFormOldValue:(MJNewValueFormOldValue)newValueFormOldValue方法或者在.m中实现- (id)newValueFromOldValue:property:来统一处理时间类型哈。具体可以看看Demo，谢谢。
