### ISSUE TITLE
‼️去除系统自动增加的元素description，会导致请求接口中如果含有description字段的值无法提交

### ISSUE THREAD

**Issue by hawskpy** [CoderMJLee/MJExtension#220]
// 去除系统自动增加的元素
        if ([keyValues isKindOfClass:[NSMutableDictionary class]]) {
            [keyValues removeObjectsForKeys:@[@"superclass", @"debugDescription", @"description", @"hash"]];
        }

**Comment by CoderMJLee** [comment]
description属于系统自带的一个属性，不建议自动生成。如果真的需要此属性，建议手动添加
