### ISSUE TITLE
新需求，字典转模型

### ISSUE THREAD

**Issue by YueLiXing** [CoderMJLee/MJExtension#221]
![temp](https://cloud.githubusercontent.com/assets/9456800/10409155/69236558-6f46-11e5-958e-64df0442ad0b.jpg)
我希望可以这样
![temp1](https://cloud.githubusercontent.com/assets/9456800/10409156/696867f2-6f46-11e5-9e2c-bb1bc68df44b.jpg)

**Comment by CoderMJLee** [comment]
应该是这么写法吧，属性名写在左边，key写在右边。MJExtension是支持这个功能的
```objc
@{
@"Comment" : @"commentinfo.replylist"
}
```

**Comment by YueLiXing** [comment]
介绍里面是这么写的，名字写在签名，数组所包含的类名在后面
<pre><code>// Tell MJExtension what type model will be contained in statuses and ads.
[StatusResult setupObjectClassInArray:^NSDictionary *{
    return @{
               @"statuses" : @"Status",
               // @"statuses" : [Status class],
               @"ads" : @"Ad"
               // @"ads" : [Ad class]
           };
}];</code></pre>
而不是上边的写法，是与不是验证一下就知道了

**Comment by CoderMJLee** [comment]
我明白你意思了哈，不好意思，一开始误解了。这种需求，MJExtension暂时不支持哦。
建议暂时可以在CommentListModel类中搞一个CommentInfo模型属性
```objc
@property (nonatomic, strong)  CommentInfo *commentinfo;

[CommentInfo setupObjectClassInArray:^NSDictionary *{
    return @{
                @"replylist" : @"Comment"
           };
}];
```

**Comment by YueLiXing** [comment]
嗯，所以我现在是稍微麻烦了一下。
先对 CommentListModel  赋值，然后再对里面的commentinfo赋值
希望以后支持这种点语法
3Q

**Comment by CoderMJLee** [comment]
好的，等有时间我尝试添加一下哈
