### ISSUE TITLE
setupReplacedKeyFromPropertyName和setupObjectClassInArray不能连续组合使用

### ISSUE THREAD

**Issue by BigBlackApple** [CoderMJLee/MJExtension#223]
setupReplacedKeyFromPropertyName和setupObjectClassInArray不能连续组合使用，
[HomeModel setupReplacedKeyFromPropertyName:^NSDictionary *{
        return @{
                 @"home_statuses" : @"statuses",
                 @"home_total_number" : @"total_numbe"
                 };
    }];
[HomeModel setupObjectClassInArray:^NSDictionary *{
        return @{
                 @"statuses":@"HomeStatusesModel"
                 };
    }];

HomeModel *home = [HomeModel objectWithKeyValues:returnValue];

HomeStatusesModel里面的东西就解析不到了，不知道能不能补充

**Comment by CoderMJLee** [comment]
这2个方法是可以联合使用的哈，一直都用得OK。是不是returnValue的数据有点问题？或者其他地方写错了？

**Comment by wanyakun** [comment]
+1 也遇到这种问题了

**Comment by CoderMJLee** [comment]
@BigBlackApple @wanyakun 可以写个简单的有这个问题的Demo看看么？因为我没发现这个问题哈

**Comment by wanyakun** [comment]
//分类， 想获取分类的数组
@interface CategoryModel : NSObject


@property (nonatomic, copy) NSString *imageUrl;

@property (nonatomic, copy) NSString *categoryName;

@property (nonatomic, assign) NSInteger categoryLevel;

@property (nonatomic, assign) NSInteger parentCategoryId;

//分类下面包括几个产品
@property (nonatomic, strong) NSArray *products;

@end

//分类中
@implementation HomeCategoryModel

+ (NSDictionary *)replacedKeyFromPropertyName
{
    return @{
             @"imgUrl":@"image_url",
             @"categoryName":@"category_name",
             };
}

+ (NSDictionary *)objectClassInArray
{
    return @{
             @"products": [ProductModel class],
             };
}


@interface ProductModel : NSObject

@property (nonatomic, assign) NSInteger isOnSale;

@property (nonatomic, copy) NSString *productCode;

@property (nonatomic, copy) NSString *mainImageUrl;

@property (nonatomic, copy) NSString *amountUom;

@property (nonatomic, assign) NSInteger salesQty;

@property (nonatomic, assign) NSInteger stock;

@property (nonatomic, assign) NSInteger depthUmo;

@property (nonatomic, copy) NSString *keywords;

@property (nonatomic, assign) NSInteger productId;

@property (nonatomic, assign) NSInteger currentSalesPrice;

@end

在使用      NSArray  *categoryArray = [CategoryModel objectArrayWithKeyValuesArray:array];之后，结果categoryArray中的每个CategoryModel都是空的，好像是把CategoryModel解析成数组了。
不知是我使用的方法是否不当.

**Comment by CoderMJLee** [comment]
CategoryModel和HomeCategoryModel名字怎么对不上的？

**Comment by wanyakun** [comment]
@CoderMJLee 不好意思，应该是下面这样
//分类中
@implementation CategoryModel

+ (NSDictionary *)replacedKeyFromPropertyName
{
    return @{
             @"imageUrl":@"image_url",
             @"categoryName":@"category_name",
             };
}

+ (NSDictionary *)objectClassInArray
{
    return @{
             @"products": [ProductModel class],
             };
}

**Comment by CoderMJLee** [comment]
@wanyakun 会不会是传入的JSON数据问题？拿出JSON数据看看哈

**Comment by wanyakun** [comment]
部分json 如下：
{
   "code": 0,
   "msg": "操作成功",
   "data": [
      {
         "id": 1,
         "category_id": "20",
         "category_name": "海鲜水产",
         "productIds": "1046568,1000243,1000245,1000273",
         "tag": 1,
         "rank": 6,
         "desription": "desription",
         "image_url": "http://i1.ucaiyuan.com/ugoods/110100000001/110100000001_750.jpg",
         "status": 1,
         "products": [
            {
               "productId": 1000243,
               "productCode": "60001907",
               "keywords": "福瑞斯,鱼,生蚝,海鲜",
               "barcode": "6949125102111",
               "productName": "福瑞斯冰冻半壳生蚝500g",
               "brandName": "福瑞斯",
               "taxRate": 17,
               "depthUmo": null,
               "isOnSale": 1,
               "amountUom": "盒",
               "stock": 100000,
               "currentSalesPrice": 15,
               "finalPrice": 15,
               "listSalesPrice": 35,
               "salesQty": null,
               "salePriceValid": false
            }
         ]
      }
   ]
}

在json转化过程中
// 如果是JSON字符串
    keyValuesArray = [keyValuesArray JSONObject];
这句转化的结果还是没问题的。

**Comment by wanyakun** [comment]
@CoderMJLee 部分json如下
{
   "code": 0,
   "msg": "操作成功",
   "data": [
      {
         "id": 1,
         "category_id": "20",
         "category_name": "海鲜水产",
         "productIds": "1046568,1000243,1000245,1000273",
         "tag": 1,
         "rank": 6,
         "desription": "desription",
         "image_url": "http://baidu.com",
         "status": 1,
         "products": [
            {
               "productId": 1000243,
               "productCode": "60001907",
               "keywords": "福瑞斯,鱼,生蚝,海鲜",
               "barcode": "6949125102111",
               "productName": "福瑞斯冰冻半壳生蚝500g",
               "brandName": "福瑞斯",
               "taxRate": 17,
               "depthUmo": null,
               "isOnSale": 1,
               "amountUom": "盒",
               "stock": 100000,
               "currentSalesPrice": 15,
               "finalPrice": 15,
               "listSalesPrice": 35,
               "salesQty": null,
               "salePriceValid": false
            }
         ]
      }
   ]
}

在json 转化的过程还没问题：
// 如果是JSON字符串
    keyValuesArray = [keyValuesArray JSONObject];
这句的出来的array是正常的

**Comment by CoderMJLee** [comment]
你是取出了data对应的数组么

**Comment by wanyakun** [comment]
是的
