### ISSUE TITLE
建议添加一个  NSDictionary<Key,Model>  和 NSDictionary<Key, NSDictionary> 的相互转换

### ISSUE THREAD

**Issue by core-lib** [CoderMJLee/MJExtension#224]
实际上 Dictionary 里面 用NSString作为Key 模型作为Value 是很常见的!! 
MJKeyValue<NSObject> 只有 模型 <--> 字典  和  模型数组 <--> 字典数组 的相互转换
没有包含 NSDictionary&lt;Key,Model&gt;    <-------->    NSDictionary&lt;Key, NSDictionary&gt;的转换
实际上只要拷贝MJKeyValue 里面 模型数组 <--> 字典数组 的相关代码  把 NSArray 换成 NSDictionary
key类型不考虑转换原封不动放进去就行了    但是我不想改MJ哥的代码怕以后升级麻烦  希望MJ哥考虑添加这个功能

**Comment by CoderMJLee** [comment]
可以换一种方式解决么？比如将NSDictionary<Key,Model>变成一个大Model，key变成这个的属性，key对应的Model就是属性值

**Comment by core-lib** [comment]
可以这样解决, 但是NSDictionary&lt;Key,Model&gt; 变成了 NSArray&lt;BigModel&gt;  如果想使用NSDictionary 的objectForKey  就需要自己遍历这个NSArray 了
