### ISSUE TITLE
枚举类型属性反序列化问题

### ISSUE THREAD

**Issue by core-lib** [CoderMJLee/MJExtension#225]
枚举类型的JSON序列化有两种格式  一种是下标数字  一种是名称字符串
第一种数据量少  第二种是可读性好  但是好像MJExtension只支持第一种  就是假如数据是从另外一种语言来的 很有可能是用第二种的哦
现在我是强制Jackson 用下标表示枚举值的 可以跟MJExtension 无缝结合  不过还是建议MJExtension能支持两种方式

**Comment by wolfcon** [comment]
请详细描述下. 下标数字?  Objective-C 暂时还不支持字符串类型的枚举吧?
