### ISSUE TITLE
字典数组-->模型数组

### ISSUE THREAD

**Issue by WCrazyStone** [CoderMJLee/MJExtension#226]
模型中有个数组，数组中得元素都对应一个模型。之前都是用objectClassInArray这个方法转换的，但是在最新版的MJExtension中，这样转换不管用。看了一下源码，其中：
 Class objectClass = [property objectClassInArrayForClass:[self class]];
应该是根据这个方法来转换的。但是在模型中，怎么做映射，将数组和模型给映射起来。

**Comment by wy19901227** [comment]
![2c70628c-b892-41da-8fbc-ee390d9b06cd](https://cloud.githubusercontent.com/assets/8086633/10503036/bb4566ec-7324-11e5-81bb-f902fda0abdd.png)

**Comment by wy19901227** [comment]
什么跟新 变这样 我不知道，看了下介绍，变这样用了

**Comment by WCrazyStone** [comment]
我知道问题在哪了，我用的是- (NSDictionary *)objectClassInArray；现在都改成+ (NSDictionary *)objectClassInArray，类方法了。
