### ISSUE TITLE
希望增加一个 模型转化为字典的时候，改变key值的方法。

### ISSUE THREAD

**Issue by FengDeng** [CoderMJLee/MJExtension#228]
字典转模型：
- (NSDictionary *)replacedKeyFromPropertyName
  {
  return @{@"bank_id":@"id"};
  }

模型转字典：
- (NSDictionary *)replacedKeyFromPropertyName
  {
  return @{@"id":@"bank_id"};
  }

**Comment by CoderMJLee** [comment]
[Model reference....:YES]
