### ISSUE TITLE
什么时候支持对swift

### ISSUE THREAD

**Issue by sgxiang** [CoderMJLee/MJExtension#23]
用这个无法将字典转为swift编写的模型类

**Comment by CoderMJLee** [comment]
由于苹果的Swift语法还在更新，所以暂时不打算编写Swift版本，等Swift再成熟点，定会编写Swift版本哈，sorry

**Comment by CoderMJLee** [comment]
最近修改了下框架，要不你试试Swift里面能调用不？谢啦

**Comment by ChengLuffy** [comment]
可以添加对 swift 3.0 的支持吗？
