### ISSUE TITLE
实现协议无法归档

### ISSUE THREAD

**Issue by zkuku** [CoderMJLee/MJExtension#231]
使用MJCodingImplementation时发现：
一个继承自NSObject的模型并且实现某个协议（接口设计需要）  ，进行归档时出现崩溃

**Comment by CoderMJLee** [comment]
可以贴出崩溃信息么

**Comment by zkuku** [comment]
根据老师给的demo，构造了一下
//  Bag.h
@protocol PriceProtocol <NSObject>
- (float)howMuch;
@end

@interface Bag : NSObject <PriceProtocol>
@property (copy, nonatomic) NSString *name;
@property (assign, nonatomic) double price;
@end

//  Bag.m
@implementation Bag
MJExtensionCodingImplementation
- (float)howMuch {
    return 30.0f;
}
@end
在demo中调用coding()执行归档时
异常
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSObject encodeWithCoder:]: unrecognized selector sent to class 0x7fff774470f0'

**Comment by zkuku** [comment]
根据老师给的demo，构造了一下
```javascript
// Bag.h
@protocol PriceProtocol<NSObject>
- (float)howMuch; 
@end

@interface Bag : NSObject<PriceProtocol>
@property (copy, nonatomic) NSString *name;
@property (assign, nonatomic) double price;
@end
```
```javascript
// Bag.m
@implementation Bag
MJExtensionCodingImplementation
- (float)howMuch {
    return 30.0f;
}
@end
```
在demo中调用coding()执行归档时 
异常 
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSObject encodeWithCoder:]: unrecognized selector sent to class 0x7fff774470f0'

**Comment by CoderMJLee** [comment]
看看你的coding()实现

**Comment by zkuku** [comment]
调用的就是老师给出的example，归档时就会崩溃
```javascript
void coding()
{
    // 创建模型
    Bag *bag = [[Bag alloc] init];
    bag.name = @"Red-------bag";
    bag.price = 200.8;

    NSString *file = [NSHomeDirectory() stringByAppendingPathComponent:@"Desktop/bag.data"];
    // 归档
    [NSKeyedArchiver archiveRootObject:bag toFile:file];
    // 解档
    Bag *decodedBag = [NSKeyedUnarchiver unarchiveObjectWithFile:file];
    NSLog(@"name=%@, price=%f", decodedBag.name, decodedBag.price);
}
```

**Comment by CoderMJLee** [comment]
暂时没看出问题哦，有代码发来看看么？

**Comment by zkuku** [comment]
好的，代码已经发送到了老师主页留的邮箱地址 richermj123go@vip.qq.com上

**Comment by CoderMJLee** [comment]
已经修复，试试最新版本哈

**Comment by kinarob** [comment]
Fix via #665  #666
