### ISSUE TITLE
新需求,或者是我没找到对应的方法

### ISSUE THREAD

**Issue by wangbiye** [CoderMJLee/MJExtension#236]
服务器返回给我的数组中有n个对象,但是我要先过滤一遍再赋值给model,要把其中的某些过滤掉或者改变它,我在demo中没有找到合适的例子,还请李老师赐教,或者告诉我应该重写哪个方法

**Comment by CoderMJLee** [comment]
数组中有N个不同的对象？将N个不同的对象转换为模型对象？

**Comment by wangbiye** [comment]
可是是我表达不准确, 假如对model的某个字段赋值之前,我想对服务器的数据做一下修改再赋值,需要重写哪个方法, 这个字段可能是个数组,本身服务器发下来这个数组里有10个对象,我要把这10个对象筛选一下,有些可能不需要了,有些可能需要合并

**Comment by CoderMJLee** [comment]
参考
```objc
- (id)newValueFromOldValue:property:;
```

**Comment by wangbiye** [comment]
好的,谢谢李老师
