### ISSUE TITLE
关于多层嵌套list<model>时，2层后面的 list 不能转成 model的问题

### ISSUE THREAD

**Issue by yuzhongxingke** [CoderMJLee/MJExtension#237]
![d414d8f8-96b0-4bb5-9218-c41a6313462b](https://cloud.githubusercontent.com/assets/4360943/10842162/76248716-7f2a-11e5-9a2d-b1ef059aa74f.png)
![e48f16dd-da62-431b-8474-d4fe8f1d855d](https://cloud.githubusercontent.com/assets/4360943/10842169/80585802-7f2a-11e5-9fec-24765d4affd6.png)
如图，多层嵌套数组，List 对应的 model 也指定啦，但是转换后的结果还是字典，请问这个要如何设置呢？多谢啦

**Comment by CoderMJLee** [comment]
类名写错了，应该是
```objc
[GoodsDetail setupClass.....];
```
因为props是属于GoodsDetail模型里面的

**Comment by yuzhongxingke** [comment]
谢谢啦，确实如此，再次感谢

**Comment by CoderMJLee** [comment]
不客气
