### ISSUE TITLE
json 字符串数组如何解析

### ISSUE THREAD

**Issue by shuleihen** [CoderMJLee/MJExtension#24]
imageURLs =         (
            "http://0ac3aaf8-4ef2-4e8b-aede-254992c2e98e",
            "http://35ee2218-2939-45d6-825c-a9fb203e2a56",
            "http://f6010d44-deb2-44b2-85ea-37852a32f4e0",
            "http://048ae4e1-1a6d-4cf2-9187-112a133e116b",
            "http:/bbd77a06-2cac-44f5-ad10-ff5c77568df7"
        );
类似这样的Jason数组如何解析，
我尝试了下面的设置，不能解析
+ (NSDictionary *)objectClassInArray
{
    return @{
             @"imageURLs" : [NSString class]
             };
}

**Comment by CoderMJLee** [comment]
至于这种情况，不用重写objectClassInArray方法哈，因为NSString不是自己编写的模型。你只要这么写可以了：
@property (nonatomic, strong) NSArray * imageURLs;

**Comment by shuleihen** [comment]
是的，是我没仔细看。对基本类型解析，像long long int ，double等类型，只有属性定义，都应该转换相应类型的吧


发自网易邮箱大师
在2015年03月25日 01:11，M了个J 写道:

至于这种情况，不用重写objectClassInArray方法哈，因为NSString不是自己编写的模型。你只要这么写可以了：
@property (nonatomic, strong) NSArray * imageURLs;
