### ISSUE TITLE
[NSObject encodeWithCoder:]: unrecognized selector sent to class

### ISSUE THREAD

**Issue by WCrazyStone** [CoderMJLee/MJExtension#245]
是不是和定义的类有关系
@interface TGCategory : NSObject《TGDropDownMenuItem》
@end

归档失败。
[NSKeyedArchiver archiveRootObject:xxx toFile:aaaFile];

**Comment by WCrazyStone** [comment]
是不是和定义的类有关系
@interface TGCategory :NSObject<TGDropDownMenuItem>
@end

下面这个就可以归档成功
@interface TGSort : NSObject
@end

**Comment by CoderMJLee** [comment]
试试最新的MJExtension？

**Comment by WCrazyStone** [comment]
像这种定义的可以归档成功。
@interface TGSort : NSObject
@property(nonatomic, copy) NSString *label;
@property(nonatomic, assign) int value;
@end
但是像如下这种的,归档不成功。
@interface TGCategory :NSObject\<TGDropDownMenuItem\>
/** 大图标(高亮) */
@property(nonatomic, copy) NSString *highlighted_icon;
/** 大图标 */
@property(nonatomic, copy) NSString *icon;
/** 类别名称 */
@property(nonatomic, copy) NSString *name;
/** 小图标(高亮) */
@property(nonatomic, copy) NSString *small_highlighted_icon;
/** 小图标 */
@property(nonatomic, copy) NSString *small_icon;
/** 子类别 */
@property(nonatomic, strong) NSArray *subcategories;
@end

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
打断点进入如下函数：
- (void)encode:(NSCoder *)encoder
{
    Class aClass = [self class];
    
    NSArray *allowedCodingPropertyNames = [aClass totalAllowedCodingPropertyNames];
    NSArray *ignoredCodingPropertyNames = [aClass totalIgnoredCodingPropertyNames];
    
    [aClass enumerateProperties:^(MJProperty *property, BOOL *stop) {
        // 检测是否被忽略
        if (allowedCodingPropertyNames.count && ![allowedCodingPropertyNames containsObject:property.name]) return;
        if ([ignoredCodingPropertyNames containsObject:property.name]) return;
        
        id value = [property valueForObject:self];
        if (value == nil) return;
        [encoder encodeObject:value forKey:property.name];
    }];
}

这个函数是对不是TGCategory里面的属性进行遍历吗？但是在遍历属性的时候，我发现多遍历了两个属性，
这两个属性的_name =@"hash", _name = @"superclass";
异常就是出现在_name = @"superclass"，调用  [encoder encodeObject:value forKey:property.name];
然后就挂掉了。
顺便说一下，我这个MJExtension 是最新的。

**Comment by WCrazyStone** [comment]
但是用下面这个旧的MJExtension框架就可以归档成功：
#import "NSObject+MJCoding.h"
#import "NSObject+MJMember.h"

@implementation NSObject (MJCoding)
/**
 *  编码（将对象写入文件中）
 */
- (void)encode:(NSCoder *)encoder
{
    [self enumerateIvarsWithBlock:^(MJIvar *ivar, BOOL *stop) {
        if (ivar.isSrcClassFromFoundation) return;
        [encoder encodeObject:ivar.value forKey:ivar.name];
    }];
}

/**
 *  解码（从文件中解析对象）
 */
- (void)decode:(NSCoder *)decoder
{
    [self enumerateIvarsWithBlock:^(MJIvar *ivar, BOOL *stop) {
        if (ivar.isSrcClassFromFoundation) return;
        ivar.value = [decoder decodeObjectForKey:ivar.name];
    }];
}

**Comment by CoderMJLee** [comment]
这个问题在前几天已经解决过了哈，你重新下载一次MJExtension吧，你有可能是上个月下载的
