### ISSUE TITLE
偶尔出现EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by xl9211** [CoderMJLee/MJExtension#246]
MJDictionaryCache中的

``` objective-c
+ (id)objectForKey:(id<NSCopying>)key forDictId:(const void *)dictId
{
    return [self dictWithDictId:dictId][key];
}
```

偶尔出现EXC_BAD_ACCESS，我怀疑是[self dictWithDictId:dictId]返回了nil。
希望MJ老师关注一下这个问题。

**Comment by CoderMJLee** [comment]
错误就指向这一行么？有具体的错误信息么？

**Comment by xulin97** [comment]
@CoderMJLee 就指向这一行

**Comment by studyBully** [comment]
我这边也是经常出现 野指针的问题。只是偶尔出现一次，但是又找不到原因。其他情况都正常。野指针出现在 MJProperty  这个类里面。

**Comment by wolfcon** [comment]
#660
