### ISSUE TITLE
建议新增一个方法来构造Users中的names数组

### ISSUE THREAD

**Issue by Pikdays** [CoderMJLee/MJExtension#247]
User *user = [[User alloc] init];
user.name = @"Jack";
user.icon = @"lufy.png";

NSArray *dictArray = @[
                         @{
                             @"name" : @"Jack",
                             @"icon" : @"lufy.png"
                         },
                         @{
                             @"name" : @"Rose",
                             @"icon" : @"nami.png"
                         }
                     ];

// JSON array -> User array
NSArray *userArray = [User objectArrayWithKeyValuesArray:dictArray];

// Printing
for (User *user in userArray) {
    NSLog(@"name=%@, icon=%@", user.name, user.icon);
}

---

问题：提取model数组中的某个key所对应的value，构造一个新的values数组。
方法一（原）：
NSMutableArray *names = [@[]mutableCopy];
for (User *user in userArray) {
    [names addObject:user.name];
}

方法二（新）：
NSArray *names = [User objectArrayWithKey:user.name];

---

**Comment by Pikdays** [comment]
类似NSArray里的 valueForKeyPath

**Comment by Pikdays** [comment]
https://github.com/ColinEberhardt/LinqToObjectiveC   这个库实现了偶刚说的，MJ老师可以参考一下

**Comment by wolfcon** [comment]
这个请自行实现.

因为内容不固定. 这个不属于JSON 与模型库该干的功能
