### ISSUE TITLE
请问下  和系统自带的 setkeyandValuesWithDictionary 是一个原理吗？

### ISSUE THREAD

**Issue by wy19901227** [CoderMJLee/MJExtension#25]

**Comment by wy19901227** [comment]
setValuesForKeysWithDictionary:

**Comment by CoderMJLee** [comment]
内部原理是一样的，都是使用KVC技术。只不过MJExtension做了更多的细节处理，setValuesForKeysWithDictionary:有太多的局限性了，功能不够用哈
