### ISSUE TITLE
多个子类继承自一个基类时，基类的一个属性是否可以完成

### ISSUE THREAD

**Issue by azxfire** [CoderMJLee/MJExtension#250]

**Comment by azxfire** [comment]
多个类都继承这个基类，基类的属性，可否改为直接进行setupReplacedKeyFromPropertyName。这样就不用对所有的子类都setupReplacedKeyFromPropertyName来操作了

**Comment by CoderMJLee** [comment]
可以的

**Comment by azxfire** [comment]
哦，那天我断点看了下，确实是实现了，但是好像是赋值给了父类的对象的把？

**Comment by CoderMJLee** [comment]
这个配置是保存在基类中，但是可以作用在子类对象身上
