### ISSUE TITLE
纠结该不该问这个问题，到底还是问了

### ISSUE THREAD

**Issue by QQ920924960** [CoderMJLee/MJExtension#253]
看到您最近更新把__weak换成了__unsafe_unretained，这样做是基于什么考虑的呢？

**Comment by CoderMJLee** [comment]
基于性能考虑，__unsafe_unretained会明显比__weak性能高哈。这个是可以测试出来的

**Comment by QQ920924960** [comment]
哈哈，好吧，真是追求极致啊

**Comment by CoderMJLee** [comment]
越快越好，哈哈
