### ISSUE TITLE
mj_objectWithKeyValues 与 objectWithKeyValues 哪个是最新的？

### ISSUE THREAD

**Issue by Rsers** [CoderMJLee/MJExtension#254]
下载下来的Demo用的方法是加mj前缀的，GitHub的教程也是加mj前缀的。我同事导入的一个版本都是不加mj前缀的，百度出来的教程也是不加mj前缀的。请问mj_objectWithKeyValues 与 objectWithKeyValues 哪个是最新的？谢谢码哥。
Demo里的方法：
+ (instancetype)mj_objectWithKeyValues:(id)keyValues
{
    return [self mj_objectWithKeyValues:keyValues context:nil];
}
我同事找到的版本：
+ (instancetype)objectWithKeyValues:(id)keyValues
{
    return [self objectWithKeyValues:keyValues error:nil];
}

**Comment by CoderAO** [comment]
加MJ前缀的是最新的

**Comment by Rsers** [comment]
谢谢^_^
