### ISSUE TITLE
能否对NSDate扩展下，另外NSObject能否扩展copy呢

### ISSUE THREAD

**Issue by jimmymi** [CoderMJLee/MJExtension#259]
我发现oc的NSDate提供的日期操作，格式化方面的弱爆了，是否考虑对这方面扩展一下，像java或C#那样扩展一下，有AddDays,AddYears，getDay，getYear,format，datediff等之类的。

**Comment by CoderMJLee** [comment]
日期操作可以参考NSCalendar类，至于copy，我有空会再看看哈

**Comment by jimmymi** [comment]
好的

**Comment by bingxue314159** [comment]
MJ帅哥，来个mj_copy支付一下copy吧，我也在是通过这样copy的，
Model --> JSON
JSON --> Model

**Comment by wolfcon** [comment]
#678
