### ISSUE TITLE
字段中有BOOL值时解析失败

### ISSUE THREAD

**Issue by lockezhang** [CoderMJLee/MJExtension#26]
MJ老师，我开始把你这个框架用到了我现在开发的一个项目中，发现在解析服务器返回的布尔字段时出错，我的实体类中字段类型是BOOL

**Comment by CoderMJLee** [comment]
你服务器返回的BOOL值是什么，true？false？YES？NO？还是其他？

**Comment by lockezhang** [comment]
哦，是我们这边服务器定义的问题,他服务器返回的性别是："1"或者"2"

**Comment by CoderMJLee** [comment]
那肯定不能用BOOL哈，BOOL只认0和1，我建议你定义为enum或者int，比如SexMan=1，SexWoman=2

**Comment by lockezhang** [comment]
嗯，不好意思，是我们这边的问题，谢谢老师。这个库用起来很方便，解析时不用去一个一个字段地写代码了。感谢

**Comment by CoderMJLee** [comment]
不客气
