### ISSUE TITLE
请问模型转字典时如何自定义转换？

### ISSUE THREAD

**Issue by gamedragon** [CoderMJLee/MJExtension#260]
mj_newValueFromOldValue是用来在字典转模型的时候做自定义转换使用的，那当模型转字典的时候可以做自定义转换吗？
比如我有一个property NSDate，但转换到字典时我想转成数字格式（Unix时间戳）。之前的例子都是字典转模型的时候，从NSNumber转到NSDate。那么在模型转字典时，我想把这个NSDate转成NSNumber可以吗？
或者更极端的情况：

``` objectivec
@interface AA : NSObject
@property NSArray *data;
@end
```

但是要转成的JSON格式是：
{"data":"1,2,3"}
请问这种情况如何来做？

**Comment by harryyuanfeng** [comment]
？

**Comment by wolfcon** [comment]
暂时没有这个方法, 得手动转
