### ISSUE TITLE
model转字典的时候、number转过来的value还是个对象

### ISSUE THREAD

**Issue by hongdong** [CoderMJLee/MJExtension#261]
model转字典的时候、number转过来的value还是个对象

**Comment by CoderMJLee** [comment]
肯定是对象哈，字典里面只能放对象。数字转过来应该是NSNumber对象。

**Comment by hongdong** [comment]
那这个字典可以可以转成json字符串吗？  转的时候一直报错、说是number的原因

**Comment by hongdong** [comment]
原来是运算的时候分母为0了、才会产生这样的问题、thx、耐心的回答

**Comment by CoderMJLee** [comment]
不客气
