### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by HJiang88** [CoderMJLee/MJExtension#262]
MJ你好,使用MJExtension时出现EXC_BAD_ACCESS错误,自己找不到原因
MJDictionaryCache:
- (id)setObject:(id)object forKey:(id<NSCopying>)key forDictId:(const void *)dictId
  {
  // 获得字典
  NSMutableDictionary *dict = [self dictWithDictId:dictId];
  if (dict == nil) {
      dict = [NSMutableDictionary dictionary];
      objc_setAssociatedObject(self, dictId, dict, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
  }
  
  // 存储数据
  dict[key] = object;
  
  return dict;
  }
  在存储数据这报exc_bad_access
  ![Uploading Snip20151118_2.png…]()

**Comment by CoderMJLee** [comment]
报错图片看不到，可以发到邮箱么

**Comment by wangbiye** [comment]
这个报错一般是因为引用了已经释放的内存地址, 我碰到过几次都是因为在model生成之后, 因为类型错误导致没有使用copy或者strong而使用了assgin, 然后自己又手动改了类型, 等到用到这个字段去取值的时候已经释放掉了

**Comment by sunjincai** [comment]
现在仍然有这个问题，一定几率出现，报错堆栈：
1 	+[MJDictionaryCache objectForKey:forDictId:] (MJDictionaryCache.m:30)
2 	+[NSObject(Property) properties] (NSObject+MJProperty.m:0)
3 	+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:0)
4 	-[NSObject(MJKeyValue) mj_setKeyValues:context:] (NSObject+MJKeyValue.m:190)
5 	+[NSObject(MJKeyValue) mj_objectWithKeyValues:context:] (NSObject+MJKeyValue.m:210)
6 	+[NSObject(MJKeyValue) mj_objectArrayWithKeyValuesArray:context:] (NSObject+MJKeyValue.m:0)
7 	__48-[NSObject(MJKeyValue) mj_setKeyValues:context:]_block_invoke (NSObject+MJKeyValue.m:0)
8 	+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:120)
9 	-[NSObject(MJKeyValue) mj_setKeyValues:context:] (NSObject+MJKeyValue.m:190)
10 	+[NSObject(MJKeyValue) mj_objectWithKeyValues:context:] (NSObject+MJKeyValue.m:210)

**Comment by wolfcon** [comment]
#660
