### ISSUE TITLE
嵌套类strong，已经定稿的类XPGWifiDevice。该如何使用MJExtension

### ISSUE THREAD

**Issue by jieson** [CoderMJLee/MJExtension#263]
问个问题 关于 MJExtension 归档的问题  
风来风去  15:52:32
自己写了一个类 
风来风去  15:52:35
@interface Device : NSObject<MJCoding>
@property (strong, nonatomic)XPGWifiDevice *xpgDevice;
@property (copy, nonatomic) NSString *iconName; @end 
风来风去  15:53:48
@interface XPGWifiDevice : NSObject

@property (nonatomic, strong, readonly) NSString *did;

@property (nonatomic, strong, readonly) NSDictionary *ui;  @end   这是一个第三方的类
风来风去  15:54:28
这种情况下  要归档 读取 该怎么写。用MJExtension。

**Comment by jieson** [comment]
我在Device的实现里 加了 MJCodingImplementation。 然后写了XPGWifiDevice的分类，在分类里也加了MJCodingImplementation。
风来风去  15:55:39
这种做法 对不？                                                                                             

在从文件反 归档的时候 报错。*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<XPGWifiDevice 0x17024ec40> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key did.'

**Comment by CoderMJLee** [comment]
因为你的是readonly，所以报错

**Comment by jieson** [comment]
哦 那对于readonly 的属性 是不是没办法 反归档了。有什么好的建议吗？

**Comment by CoderMJLee** [comment]
我刚才想错了哈，readonly应该也是可以的。你可以发个Demo看看么
