### ISSUE TITLE
大坑！误以为是MJExtension找不到！

### ISSUE THREAD

**Issue by WangJH2333** [CoderMJLee/MJExtension#265]
mj_objectWithKeyValues: 在示例代码中，函数写的这个样子，但是在你的源码里面根本就没有这个函数！在源码中它是objectWithKeyValues:。同理其他示例函数也是坑。遇到这个问题的同学们请抱紧我！

**Comment by CoderMJLee** [comment]
哈哈，不会吧。你更新下MJExtension版本。
```objc
pod repo update
```

**Comment by WangJH2333** [comment]
我的pod版本是0.39.0 ，你说的这个命令被墙，用了翻墙代理也用不了。我用的是pod install --verbose --no-repo-update,这个命令可以更新到最新版本吗。我这个版本的MJExtension中的方法的确和项目首页示例代码不一样。

**Comment by CoderMJLee** [comment]
那就试试pod update

**Comment by WangJH2333** [comment]
解决了。我之前的cocoapods版本是0.39，但是specs没有更新到最新，所以安装的MJExtension是2.5版本。我对比了新旧MJExtension的源码，新旧版本源码的确不一致，新代码和项目首页示例代码一致，新代码有更好的代码风格。嘿嘿，谢谢哈。

**Comment by CoderMJLee** [comment]
不客气
