### ISSUE TITLE
数组里面放的是NSString等数据时返回的数组是NSArray而不是NSMutableArray

### ISSUE THREAD

**Issue by maplelover** [CoderMJLee/MJExtension#266]
+ (NSMutableArray *)mj_objectArrayWithKeyValuesArray:(id)keyValuesArray context:(NSManagedObjectContext *)context

// 如果数组里面放的是NSString、NSNumber等数据
if ([MJFoundation isClassFromFoundation:self]) return [NSMutableArray arrayWithArray:keyValuesArray];

测试数据：
@interface StatusResult : BaseObject
@property (strong, nonatomic) NSMutableArray *stringArray;
@end

NSDictionary *dict = @{
                           @"stringArray" : @[
                                   @"text", @"Nice weather!", @"Rose", @"nami.png"
                                   ]
                           };
StatusResult *result = [StatusResult mj_objectWithKeyValues:dict];

lldb: p (BOOL)[result.stringArray isKindOfClass:NSMutableArray.class]

另外发现个小问题，
stringArray 使用NSMutableArray好像解析不出来，NSArray就ok

PS：
在mj_objectClassInArray中显式指定数组元素类型为NSString后，result.stringArray的确是NSMutableArray类型，以上测试是没指定的
+ (NSDictionary *)mj_objectClassInArray
{
    return @{
              @"stringArray": [NSString class]
             };
}

**Comment by CoderMJLee** [comment]
你试试最新版的MJExtension

**Comment by maplelover** [comment]
fixed.
