### ISSUE TITLE
模型归档，解档。数据不统一，有丢失

### ISSUE THREAD

**Issue by SYLing** [CoderMJLee/MJExtension#267]
代码如下：
        HSUserModel *user = [HSUserModel mj_objectWithKeyValues:dic];
        NSLog(@"useruser--%@\n",user.mj_keyValues);
        [NSKeyedArchiver archiveRootObject:user toFile:path];

        HSUserModel *decodeUser = [NSKeyedUnarchiver unarchiveObjectWithFile:[HSSaveTool getUserModelFilePath]];
        NSLog(@"%@",decodeUser.mj_keyValues);
        
     打印结果：
2015-11-20 10:33:57.086 HooSoon[11272:5741653] __39-[HSLoginViewController saveUserDetail]_block_invoke 109 
 useruser--{
	birthday : 2016-09-24 00:00:00,
	province : 北京 丰台区,
	status : 0,
	code : 55849976549,
	sex : 男,
	city : ,
	signature : 如同改革经济界健健康康 i,
	realname : SYLing,
	username_list : ,10017,,
	reg_ip : ,
	salt : 66D66D,
	point : 0,
	id : 14,
	levelid : 1,
	parent_username : ,
	mobile : 000000,
	user_type : General,
	adddate : 2015-09-24 23:28:22,
	avatar : /upload/201511/18/201511181527439469.jpg,
	username_layer : 1,
	password : 0BC0C90B56B1AFD4,
	username : 10017
}

2015-11-20 10:33:57.096 HooSoon[11272:5741653] __39-[HSLoginViewController saveUserDetail]_block_invoke 112 
 {
	avatar : /upload/201511/18/201511181527439469.jpg,
	mobile : 000000,
	city : ,
	birthday : 2016-09-24 00:00:00,
	username : 10017,
	realname : SYLing,
	sex : 男,
	province : 北京 丰台区
}

**Comment by CoderMJLee** [comment]
你模型的.m文件里面的encode和decode代码如何写的？

**Comment by SYLing** [comment]
额，是.m文件中没有写入全部字段。
