### ISSUE TITLE
3.0.6 报错

### ISSUE THREAD

**Issue by huangping35** [CoderMJLee/MJExtension#268]
怎么搞的，又是报错，在解析coredata对象。

**Comment by CoderMJLee** [comment]
是以前就报错？还是新版本才报错？

**Comment by NullpoIntD** [comment]
mj_objectWithKeyValues 字典转模型方法创建出来的对象指针nil

**Comment by CoderMJLee** [comment]
Sorry，非常抱歉。一时手残，写错了。。。已经修复，不好意思，3.0.7
