### ISSUE TITLE
有崩溃问题，杰哥能否处理下？或者解析下原因呢

### ISSUE THREAD

**Issue by nsdictionary** [CoderMJLee/MJExtension#27]
杰哥，请看截图哈，好像说什么no summary

我有一个方法需要判断表是否自动创建，如果没有创建成功，那么就使用MJExtension不停的重复工作，直到表创建成功，所以在短时间内（我设的是0.1f调用一次MJExtension的成员变量遍历）大量重复调用MJExtension。

卡死行：_cachedTypes[code] = type;//卡死在这里，系统自行打了一个断点，且无法跳过此断点
原因： 未知，，大概原因是多次高速调用MJIvar（业务需求，我必须这么做），读取成员属性造成的。

我暂时的解决土办法：高速调用时间周期为0.1秒，我试过周期越大，崩溃的概率越小，设为2秒调用一次，崩溃很少，但是还是偶尔有，且业务受到影响。

MJType *type = _cachedTypes[code]; //卡死在此行，不能过掉
断点查看code = @\"@"NSString\""，有时候崩溃这个code又是正常的,但是会出现no summary（如图）。

报错信息：
CoreFMDBModel(2901,0x1198e9000) malloc: *** error for object 0x7fd099703c70: double free
*** set a breakpoint in malloc_error_break to debug

![3](https://cloud.githubusercontent.com/assets/8357630/6889061/91de2ea2-d6c0-11e4-95a6-0670e81de5f1.png)

![28cfea65-5c42-4f5e-b0ac-75e44583fbc4](https://cloud.githubusercontent.com/assets/8357630/6883692/426071e0-d5f4-11e4-80a5-ebc6c09fe163.png)

还有这里也会崩溃,这些崩溃查看里面的变量，好像都是正常的，
![1](https://cloud.githubusercontent.com/assets/8357630/6883722/980db638-d5f5-11e4-95f0-1555b8e2a99a.png)
下面这个是左侧的线程信息：
![2](https://cloud.githubusercontent.com/assets/8357630/6883726/cd9b751a-d5f5-11e4-80ed-3709ec73dbdd.png)

上面两个都不是正常的崩溃，是卡死在这个地方，不能过掉。

**Comment by nsdictionary** [comment]
杰哥，请看截图哈，好像说什么no sumaary

![28cfea65-5c42-4f5e-b0ac-75e44583fbc4](https://cloud.githubusercontent.com/assets/8357630/6883692/426071e0-d5f4-11e4-80a5-ebc6c09fe163.png)

**Comment by CoderMJLee** [comment]
现在解决了么

**Comment by coppercash** [comment]
是`_cachedTypes ` 和 `MJProperty` 的实例被多线程同时访问（且不止有读操作，还有写操作）造成的。
解决方案:
1. 给这些资源加锁
2. 在 `+load()` 中把所有相关资源在一个线程中建好。之后所有线程就都是读操作了。

**Comment by coppercash** [comment]
建议 MJ 把多线程需要在框架外同步的问题写在 README 中，以便大家躲坑。

**Comment by CoderMJLee** [comment]
好的
