### ISSUE TITLE
<null>问题

### ISSUE THREAD

**Issue by xiaomianbao** [CoderMJLee/MJExtension#270]
MJ老师，我们后台比较蛋疼 	buyDate :  \<null\> ,  content : \<null\> , 返回字段经常是java里面的空指针对象，然后转模型的时候 是NSNull对象  然后一用到就崩了    能不能判断下后台返回NSNull的时候，字段封为nil

**Comment by CoderMJLee** [comment]
你用的是什么版本的MJExtension？

**Comment by xiaomianbao** [comment]
六期黑马的

**Comment by xiaomianbao** [comment]
六期黑马的了   最新版的改了么？

**Comment by xiaomianbao** [comment]
MJ哥  不好意思  刚刚实验了一下   是会转换的。。不好意思打扰你宝贵的时间了。。这种数据 直接取字典会崩而已           content : <null> ,     NSDictionary *dict =   resultDic[@"object"];
                                      
                                                          NSLog(@"----->%@",dict[@"content"]); 这样会崩  需要判断。
