### ISSUE TITLE
无法对key前面带点的进行名称匹配赋值

### ISSUE THREAD

**Issue by yizzuide** [CoderMJLee/MJExtension#272]
如：
[CBLoginInfoModel mj_setupReplacedKeyFromPropertyName:^NSDictionary *{
        return @{
                 @"expires" : @".expires"
                 };
    }];
使用最新的版本，无法对expires属性赋值，debug查看.expires是有值的，只能通过[@".expires"]字典取出来直接赋值了

**Comment by wolfcon** [comment]
`.` 不要使用. MJ 里有特殊用法
