### ISSUE TITLE
MJ老师，replacedKeyFrom....方法冲突与小建议

### ISSUE THREAD

**Issue by memorywarning** [CoderMJLee/MJExtension#276]
MJ老师，刚刚开始接触你的MJExtension，写的简直太棒了，良心之作啊。
但发现有个不完美的地方。
一. 下面这两个方法会冲突
  + (NSDictionary *)mj_replacedKeyFromPropertyName  //处理自定义属性命名不配
  + (NSString *)mj_replacedKeyFromPropertyName121:(NSString *)propertyName  //处理驼峰命名
  如果我实现了replacedKeyFromPropertyName121:这个方法，然后这个方法replacedKeyFromPropertyName就不会调用了。

二.  MJ老师，希望能添加一个Manger之类的全局处理的一些方法接口。例如：服务器总是很调皮，返回的字段名总是有下划线连接，作为OC开发者很难去直视，您的mj_replacedKeyFromPropertyName121:这个非常好，但是我们需要在每一个Model的实现文件中去重复mj_replacedKeyFromPropertyName121:方法实现相同的代码，一个项目几十个Model，这样地话就不太完美了（当然，我们也可以使用继承来解决这个问题），如果有个Manger类的可以全局设置的话就非常的完美了。

-----非常感谢MJ老师对iOS界的贡献-----

**Comment by CoderMJLee** [comment]
谢谢建议哈：
1.本来就是这么设计的哈，既然mj_replacedKeyFromPropertyName121有返回值了，就不会再调用了mj_replacedKeyFromPropertyName了，除非在mj_replacedKeyFromPropertyName121针对某些属性返回nil，就会尝试调用mj_replacedKeyFromPropertyName
2.一样的，在mj_replacedKeyFromPropertyName121中对需要全局设置的属性名返回nil，然后这样设置
```objc
[NSObject mj_setupReplacedKeyFromPropertyName121:^{

}];
```

**Comment by memorywarning** [comment]
明白了，谢谢MJ老师

**Comment by CoderMJLee** [comment]
不客气
