### ISSUE TITLE
nsarray -> jsonString will crash

### ISSUE THREAD

**Issue by tospery** [CoderMJLee/MJExtension#277]
NSArray *notes = [MyNetworking01Note objectArrayWithKeyValuesArray:content];
_textView.text = [notes JSONString];

**Comment by CoderMJLee** [comment]
可以发个Demo看看么

**Comment by tospery** [comment]
杰哥，示例：链接: http://pan.baidu.com/s/1qW8E9qc 密码: 836e

**Comment by tospery** [comment]
另外，用+ (instancetype)mj_objectWithKeyValues:(id)keyValues context:(NSManagedObjectContext *)context来创建core data模型的时候，模型里有NSSet类型的关系，这个会解析失败。是不是因为缺少与+ (NSDictionary *)mj_objectClassInArray;相应的+ (NSDictionary *)mj_objectClassInSet;方法？

**Comment by tospery** [comment]
Demo下载地址更新：http://pan.baidu.com/s/1mgF85AC

**Comment by wolfcon** [comment]
暂时不支持, 数组转字符串请自行使用 NSArray 自带的方法
