### ISSUE TITLE
KVC vs runtime

### ISSUE THREAD

**Issue by WenchaoIOS** [CoderMJLee/MJExtension#279]
Hi 小码哥:
    我最近使用KVC赋值的方式(setValue:forKey)，与runtime中的objc_msgSend赋值方式做了比较，结果发现后者比前者快了将近10倍，这应该会对本框架有一定帮助的吧：）

**Comment by CoderMJLee** [comment]
谢谢，明白的哈，当初用KVC是为了方便做自动类型转换

**Comment by WenchaoIOS** [comment]
嗯嗯明白，方便和高效也只能二者选其一，谢谢。
