### ISSUE TITLE
混编c++的时候，导入框架编译报错

### ISSUE THREAD

**Issue by WuKongCoo1** [CoderMJLee/MJExtension#28]
在NSObject+MJvar.m文件中   公共类方法+ (instancetype)tempObject 报错   static const char MJTempObjectKey;  提示信息：Default initalization of an object of const type 'const char'
编译器为：Default compiler （Apple LLVM 6.0）

**Comment by CoderMJLee** [comment]
试试最新的，还有这个问题么？
