### ISSUE TITLE
MJ老师，碰见一个，字典是null的时候，它崩溃的问题，贴代码给你看 

### ISSUE THREAD

**Issue by hunter858** [CoderMJLee/MJExtension#286]
1.正常数据
    "extra": {
        "bid": "55cb2a54b69178a052f735fb",
        "book": {
            "author": "[苏] 瓦·格罗斯曼",
            "id": "55cb2a54b69178a052f735fb",
            "img": "http://7qn8pq.com2.z0.glb.qiniucdn.com/55cb2a5451e3521eb6009bd6",
            "name": "生存与命运",
            "rating": 8,
            "recommend": "● 一本被判定“在二三百年后才能出版的作品”\n● 欧美公认“当代的《战争与和平》”“20世纪最伟大的"
        }
    }
2.值为null的数据
  "extra": {}

3.我写的模型
#import <Foundation/Foundation.h>
#import "CCbook.h"
@interface CCextra : NSObject
@property (nonatomic,copy) NSString *bid;
@property (nonatomic,strong) CCbook *book;
@property (nonatomic,strong) NSString *html;

4.报错提示
*** Terminating app due to uncaught exception 'keyValues is not a NSDictionary', reason: ''

**Comment by hunter858** [comment]
服务器给的数据是一个字典，字典内包的是数组，我用的是你的，数组数据转数组模型的方法
 NSMutableArray *channelCellArray =[CCchannelCellModel objectArrayWithKeyValuesArray:responseObject[@"data"]];

**Comment by hunter858** [comment]
后来我更新了，您的最新的类库，好像问题解决了，抱歉

**Comment by CoderMJLee** [comment]
不客气
