### ISSUE TITLE
字典转model，然后再将model转字典，key不是属性名。

### ISSUE THREAD

**Issue by mg459046365** [CoderMJLee/MJExtension#288]
mj老师，我将字典中的xxx_url 映射成了model中的xxxURL这个属性,再将这个model转成字典时xxxURL在字典中又变成了xxx_url,而不是xxxURL,为什么啊，求解答

**Comment by mg459046365** [comment]
MJ老师，[User mj_setupReplacedKeyFromPropertyName:^NSDictionary *{
        return @{@"userID":@"id"};
    }];
model后，然后再调用下面的方法，并返回空字典
[User  mj_setupReplacedKeyFromPropertyName:^NSDictionary *{
        return @{};
    }];
这个问题就解决了。这算不算一个bug,还是本应该这样使用。

**Comment by CoderMJLee** [comment]
可以使用这个解决
```objc
[User mj_referenceReplacedKeyWhenCreatingKeyValues:YES];
```

**Comment by mg459046365** [comment]
MJ老师:
[YGUser mj_setupReplacedKeyFromPropertyName:^NSDictionary *{
        return @{
                 @"nickname" : @"nickName",
                 @"birthday" : @"birthDay",
                 @"avaterProps" : @"logo",
                 @"isAuth" : @"auth",
                 @"isArtist" : @"artist",
                 @"isInstructor" : @"instructor",
                 @"instructorUrl" : @"instructor_url",
                 @"enterpriseUrl" : @"enterprise_url",
                 };
    }];
    YGUser *user1 = [YGUser mj_objectWithKeyValues:data];
    [YGUser mj_referenceReplacedKeyWhenCreatingKeyValues:NO];
    NSDictionary *dic = [user mj_keyValues];
    YGUser *user2 = [YGUser mj_objectWithKeyValues:dic];

data 为原始字典数据，在转换的过程中，user1,dic数据都没有问题，但是user2数据出错，有些数据丢失比如enterpriseUrl会变为nil值。
但是如果改成下面的话就OK了。
 .......
 [YGUser mj_setupReplacedKeyFromPropertyName:^NSDictionary *{
        return @{};
    }];
    YGUser *user2 = [YGUser mj_objectWithKeyValues:dic];
