### ISSUE TITLE
mj_replacedKeyFromPropertyName这个方法没有起作用啊,得到的nearByCity_id还是nil

### ISSUE THREAD

**Issue by GLei1122** [CoderMJLee/MJExtension#291]
- (NSDictionary *)mj_replacedKeyFromPropertyName
  {
  return @{@"nearByCity_id":@"id"};
  }

**Comment by CoderMJLee** [comment]
具体是怎么用的？可能用错位置了

**Comment by GLei1122** [comment]
我是在modelResult 里   直接使用的
+ (NSDictionary *)mj_replacedKeyFromPropertyName { return @{@"nearByCity_id":@"id"}; }
我还用了mj_objectClassInArray这个方法, 这个方法可以使用,但是规避 id那个不行.

**Comment by CoderMJLee** [comment]
会不会服务器返回的id本来就是nil

**Comment by passionchenjianye** [comment]
貌似swift中也不起作用,我的model如下
class APResponseModel: NSObject {
    var status: String!
    var info: String!
    var data: Dictionary<String,String>?
    func mj_replacedKeyFromPropertyName() -> Dictionary<String, String>! {
        return ["data":"response_data", "info":"response_info", "status":"response_status"]
    }   
}
这里是字典转Model的截图，请杰哥帮忙看看，谢谢！
![image](https://cloud.githubusercontent.com/assets/4251642/11932554/47a80af4-a831-11e5-91be-a3a959f04430.png)
