### ISSUE TITLE
杰哥，这个工具不支持泛型吗？什么时候能适配下泛型

### ISSUE THREAD

**Issue by reaper12** [CoderMJLee/MJExtension#295]
杰哥，这个工具不支持泛型吗？什么时候能适配下泛型

**Comment by AbooJan** [comment]
泛型好像只能在xcode7有效，在xcode6好像会报错。
还有那些关键字 __kindof  _Nullable 那些

**Comment by reaper12** [comment]
要结合一下新技术嘛，而且用泛型封装model操作起来也非常方便

**Comment by wolfcon** [comment]
#385
