### ISSUE TITLE
对id类型的支持

### ISSUE THREAD

**Issue by xx-li** [CoderMJLee/MJExtension#30]
非常感谢开源这么好的库。在改用此库的过程中，有一些类是有id类型的成员变量（可能是某个自定义的model）， 这个id类型是根据业务需求来变化的。 可否提供一个类似的方法：

@property (strong, nonatomic) id user;

- (NSDictionary *) classNameForId {
    
    if (_type == AdminUserType) {
        return @{@"user" : [AdminUser class]};
    }
    return @{@"user" : [GeneralUser class]};
}

这样以便提供id类型在model与dictionary之间互转的时候是根据正确的类型来转换的。

**Comment by CoderMJLee** [comment]
其实我不建议这么做哈，原因有：
1.面向id类型开发较为麻烦，使用时需要判断真实类型
2.由于字典转模型是无序的，所以当调用classNameForId时，不能确保模型的_type已经有值了哦
我建议这么做哈，有2种做法：
1.把AdminUser和GeneralUser合并为一个大类，比如User，通过User的内部属性来判断是什么用户
2.叫后台返回两个用户字典，比如adminUser ： { }、generalUser ： {  }
你觉得呢？

**Comment by xx-li** [comment]
感觉id类型是一个很重要的特性，如果有合适的方法来支持的话最好了。  实际开发中，多态是一个很重要的特性， 例如不是id 类型，而是一个adminUser，generalUser的基类 User 类型。 这样的情况也是比较常见的。

但是就如您所说的第二点， 确实不好去保证type是否有值。貌似也没什么好的思路去实现。 另外非常感谢您提供解决方案。

在 2015年4月2日，上午10:23，M了个J <notifications@github.com> 写道：
