### ISSUE TITLE
大神 ，请问这样的json怎么解析呢？

### ISSUE THREAD

**Issue by xian3513** [CoderMJLee/MJExtension#300]
{"HeWeather data service 3.0":[
                      {
                       "basic":{},
                       "daily_forecast":[],
                        "hourly_forecast":[
                             {
                                 "date":"2015-12-18 13:00",
                                  "wind":{
                                             "deg":"52",
                                             "dir":"NE",
                                            }
                            },
                            {
                               "date":"2015-12-18 16:00",
                               "wind":{
                                        "deg":"55",
                                        "dir":"NE",
                            }
  ]},

大神 ：请问这样的json 用MJExtension 如何做到 hourly_forecast 集合中的模型类直接得到deg，和dir两个属性值，而不是在创建一个wind模型类呢？

**Comment by maplelover** [comment]
不考虑基类的序列化？

- (void)encodeWithCoder:(NSCoder *)coder
{
    if ([super respondsToSelector:@selector(encodeWithCoder:)])
    {
        [super performSelector:@selector(encodeWithCoder:) withObject:coder];
    }

    [self mj_encode:coder];
}

**Comment by CoderMJLee** [comment]
```objc
+ (NSDictionary *)mj_replacedKeyFromPropertyName
{
    return @{@"deg" : @"wind.deg", @"dir" : @"wind.dir"};
}
```
