### ISSUE TITLE
Camel -> underline【统一转换属性名（比如驼峰转下划线）】如何禁止

### ISSUE THREAD

**Issue by nanmingzhidian** [CoderMJLee/MJExtension#307]
如题，不管我实现不实现驼峰方法，它都自动转换，我想禁止掉它，应该怎么做？
对于我来说失去了一些值
![qq20151227-0 2x](https://cloud.githubusercontent.com/assets/7157746/12008929/94b6635e-ac9b-11e5-9e19-4aac8636d3e4.png)

**Comment by CoderMJLee** [comment]
Demo是在MJExtensionConfig.m中设置了MJDog

**Comment by Spaino** [comment]
NSString+MJExtension.m文件中第76行代码已经过期,老是会给出警告,有必要修改为:
[self stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet characterSetWithCharactersInString:@"!$&'()*+,-./:;=?@_~%#[]"]];
谢谢!

**Comment by Spaino** [comment]
NSString+MJExtension.m文件中第76行代码已经过期,老是会给出警告,有必要修改为: 
 return [NSURL URLWithString:[self stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet characterSetWithCharactersInString:@"!$&'()*+,-./:;=?@_~%#[]"]]];
谢谢!

**Comment by Spaino** [comment]
另外好像AppIcon做小了点..
