### ISSUE TITLE
数组里面有字典，字典里面有数组，数组里面还有一个字典，最后一级转换失败。

### ISSUE THREAD

**Issue by liuzhecodekiller** [CoderMJLee/MJExtension#308]
明杰老师，你好。 在这边  json数据里面数据比较复杂     数组里面有字典，字典里面有数组，数组里面还有一个字典，最后一级转换失败。就是最后一个字典没有转化成模型。之前的版本是可以的。

**Comment by icodeface** [comment]
同样遇到此问题，之前的版本正常。

**Comment by wolfcon** [comment]
做好对应关系. `mj_objectClassInArray`
