### ISSUE TITLE
您好，这种数据结构怎么映射？

### ISSUE THREAD

**Issue by yaonuo** [CoderMJLee/MJExtension#309]
现在一个项目中，服务器返回的json字符串中，有个Message字段，它是一个字典集合，但是key（如下图的"20151231"）值是动态变化的。
问：这样的Model怎么写？
{
  "Success": true,
  "Message": {
    "20151231": [
      {
        "MatchDate": "2015/12/31 4:00:00",
        "MatchId": "6a3198ba17c44a54b5b1664cf68bc9d9",
        "MatchOrder": "016",
      },
      {
        "MatchDate": "2015/12/31 4:00:00",
        "MatchId": "6a3198ba17c44a54b5b1664cf68bc9d9",
        "MatchOrder": "016",
      }
    ]
  },
  "Other": "null"
}

**Comment by bigParis** [comment]
@interface MessageModel : NSObject
@property (strong, nonatomic) NSArray* date;
@end

@interface DateModel : NSObject
@property (strong, nonatomic) NSString* MatchDate;
@property (strong, nonatomic) NSString* MatchId;
@property (strong, nonatomic) NSString* MatchOrder;
@end

@interface Model : NSObject
@property(assign, nonatomic) BOOL Success;
@property(strong, nonatomic) MessageModel* Message;
@property(strong, nonatomic) NSString* Other;
@end

**Comment by yaonuo** [comment]
非常感谢！
已解决 :-)

2016-01-19 9:58 GMT+08:00 bigParis <notifications@github.com>:

**Comment by yangshengchaoios** [comment]
请问你是怎么解决的？
