### ISSUE TITLE
使用MJCodingImplementation在NSKeyedArchiver之后，如果模型新增属性，在NSKeyedUnarchiver时会崩溃

### ISSUE THREAD

**Issue by cxmapp** [CoderMJLee/MJExtension#31]
/**
 *  设置成员变量的值
 */
- (void)setValue:(id)value
{
    if (_type.KVCDisabled) return;
    
   // 在这边添加判断返回
    if (value == nil) {
        return;
    }

    // 这边value为nil时，会导致crash
    [_srcObject setValue:value forKey:_propertyName];
}

**Comment by CoderMJLee** [comment]
最新版的代码里面已经解决这个问题了哈
