### ISSUE TITLE
模型内部多层嵌套该模型本身

### ISSUE THREAD

**Issue by zhaozhenbo** [CoderMJLee/MJExtension#310]
明杰大神，如果一个模型里面又多层嵌套了这个模型，如何用您的框架解决这问题，内容如图
<img width="415" alt="2015-12-30 4 28 14" src="https://cloud.githubusercontent.com/assets/15224840/12048169/753b5c68-af12-11e5-9ef9-0d2e08283536.png">

**Comment by wolfcon** [comment]
参看例子
