### ISSUE TITLE
数组调用mj_JSONObject会crash

### ISSUE THREAD

**Issue by tospery** [CoderMJLee/MJExtension#312]
```
MyTest *a1 = [MyTest new];
a1.it = 1;
a1.str = @"a";
MyTest *a2 = [MyTest new];
a2.it = 2;
a2.str = @"b";

NSArray *arr = @[a1, a2];
id obj = [arr mj_JSONObject]; // Crash
```

**Comment by MrReN** [comment]
什么错误

**Comment by MrReN** [comment]
@tospery 就是简单的crash？

**Comment by tospery** [comment]
MyTest *a1 = [MyTest new];
    a1.it = 1;
    a1.str = @"a";
    MyTest *a2 = [MyTest new];
    a2.it = 2;
    a2.str = @"b";
    
    NSArray *arr = @[a1, a2];
    id obj = [arr mj_JSONData]; // Crash，用mj_JSONObject不报错

**Comment by tospery** [comment]
就是简单的crash，
- (NSData *)mj_JSONData
{
    if ([self isKindOfClass:[NSString class]]) {
        return [((NSString *)self) dataUsingEncoding:NSUTF8StringEncoding];
    } else if ([self isKindOfClass:[NSData class]]) {
        return (NSData *)self;
    }
    
    return [NSJSONSerialization dataWithJSONObject:[self mj_JSONObject] options:kNilOptions error:nil]; // Crash在这里
}

**Comment by wolfcon** [comment]
```objective-c
[[MyTest mj_keyValuesArrayWithObjectArray:arr] mj_JSONString];
```
or
```objective-c
[[MyTest mj_keyValuesArrayWithObjectArray:arr] mj_JSONData];
```
