### ISSUE TITLE
字典或者数组转字符串会失败

### ISSUE THREAD

**Issue by CodeCMLee** [CoderMJLee/MJExtension#313]
杰哥，刚遇到了把字典或数组映射成字符串，结果解析为nil，新版本出现了这个现象，旧版本是正常的，
模型类：
![2016-01-03 9 24 46](https://cloud.githubusercontent.com/assets/11853095/12078933/9da7f0ac-b260-11e5-8a20-2bf111f03a71.png)
测试代码：
![2016-01-03 9 25 26](https://cloud.githubusercontent.com/assets/11853095/12078935/b5d81c1a-b260-11e5-9c52-8e7b8f006256.png)
结果：
![2016-01-03 9 25 35](https://cloud.githubusercontent.com/assets/11853095/12078937/c15dd002-b260-11e5-9a6b-eb576390a4dc.png)

**Comment by bigParis** [comment]
list是数组，试试用@property(nonatomic, strong) NSArray *list; 并mj_setupObjectClassInArray指定数组的类型

dict本身是个model，应该在定义一个model进行嵌套，
@interface dictModel
@property(nonatomic, strong) NSString *key1;
@property(nonatomic, strong) NSString *key2;
@end

@interface TestModel
@property (nonatomic, strong) NSString *name;
@property (nonatomic, assign) NSInteger userId;
@property (nonatomic, strong) dictModel dict;
@property (nonatomic, strong) NSArray *list; 
@end

调用
[TestModel mj_setupObjectClassInArray:^NSDictionary *{
    return @{
               @"list" : @"NSInteger"
           };
}];

TestModel *model = [TestModel mj_objectWithKeyValues:metaDict];
NSLog...
