### ISSUE TITLE
为什么要用NSDecimalNumber去接收nsnumber的数据呢

### ISSUE THREAD

**Issue by zhkufish** [CoderMJLee/MJExtension#315]
我在使用的时候,发现我原来的nsnumber对象都被转成了NSDecimalNumber,, 这个会导致我在使用fmdb的时候查不到正常数据.set = [db executeQuery:sql withArgumentsInArray:@[ employee.empolyeeId ]];

**Comment by CoderMJLee** [comment]
现在分开处理了NSNumber和NSDecimalNumber，你试试最新的3.0.9版本
