### ISSUE TITLE
MJDictionaryCache执行到 dict[key] = object时crash

### ISSUE THREAD

**Issue by Vidtion** [CoderMJLee/MJExtension#316]
@implementation MJDictionaryCache
- (id)setObject:(id)object forKey:(id<NSCopying>)key forDictId:(const void *)dictId
  {
  // 获得字典
  NSMutableDictionary *dict = [self dictWithDictId:dictId];
  if (dict == nil) {
      dict = [NSMutableDictionary dictionary];
      objc_setAssociatedObject(self, dictId, dict, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
  }
  
  // 存储数据
  dict[key] = object;   //经常挂在这里，不必现。
  
  return dict;
  }

**Comment by todaylover** [comment]
thread safe 问题

**Comment by wolfcon** [comment]
#660
