### ISSUE TITLE
杰哥，模型的属性里有CoreData类型的属性该怎么办？

### ISSUE THREAD

**Issue by yangjunfeng22** [CoderMJLee/MJExtension#317]
现在有一个继承自NSObject的模型。然后这个模型里面有个CoreData类型的属性。转换之后，貌似这个CoreData的属性出问题了。<User: 0x13b0f3d50> (entity: <null>; id: (null) ; data: <fault>)
# import "HSAPIResponse.h"
# import "User.h"

@interface UserAPIResponse : HSAPIResponse

@property (nonatomic, strong) User *user;
@property (nonatomic, copy) NSString *token;

@end
其中这个User是一个CoreData类型的模型。
谢谢您！

**Comment by Chan4iOS** [comment]
这个功能还没有

**Comment by wolfcon** [comment]
```objc
[UserAPIResponse mj_objectWithKeyValues:dict context:context];
```
使用这个应该可以解决
