### ISSUE TITLE
新版本解析NSDate为空   --   Demo中归档解档路径不好使

### ISSUE THREAD

**Issue by biyu6** [CoderMJLee/MJExtension#318]
杰哥:我在使用上发现两个问题,不知道是不是操作失误导致的,您有空可以看一下:
1.Model contains model-array【模型中有个数组属性，数组里面又要装着其他模型】:
      数组里有NSDate属性,解析为空(3月份的MJExtension可以转换)

 2.Coding
NSString *file = [NSHomeDirectory() stringByAppendingPathComponent:@"Desktop/bag.data"];
Demo中的这个无法使用;换成固定路径后或者tmp文件的路径后就解决了
NSString *tmpPath = NSTemporaryDirectory();
     NSString *file = [tmpPath stringByAppendingPathComponent:@"bag.data"];

演示的链接: https://git.oschina.net/biyu6/MJExtension---demo.git

**Comment by yinanfang** [comment]
我也有同样问题！

**Comment by iTofu** [comment]
+1

**Comment by wolfcon** [comment]
链接404了
