### ISSUE TITLE
关于-模型中有个数组属性，数组里面又要装着其他模型的一点建议

### ISSUE THREAD

**Issue by CellerX** [CoderMJLee/MJExtension#319]
_杰哥,您好:_
　我是小码哥第11期的学生,今晚预习您的视频,学习了关于使用MJExtension框架,字典转模型,模型中有个数组属性，数组里面又要装着其他模型.
    `能否通过泛型告诉框架这个数组里面存放的是什么模型?`
    `例如:车组模型里面有个carsArr数组存放了cars模型`

``` objc
    @property (nonatomic, copy) NSString *title;
    @property (nonatomic, strong) NSArray<CXCars *> *carsArr; 
```

   如果可以的话就不需要返回模型名称，一句话就搞定了.
   在下初学iOS,不知道如何实现，杰哥不要在意~:P

**Comment by bigParis** [comment]
想法不错,但好像不是OC语法吧

**Comment by wanganjun** [comment]
@bigParis 是 OC 语法, 不过新出没多节, 可以参见 http://blog.sunnyxx.com/2015/06/12/objc-new-features-in-2015/

**Comment by bigParis** [comment]
长知识了，要是能把泛型加进去必是极好的，mj_setupReplacedKeyFromPropertyName可以尝试自己改下这个接口的实现。

**Comment by bigParis** [comment]
https://github.com/EnjoySR/ESJsonFormat-Xcode  这里有个插件,可以直接生成代码的,也别说泛型不泛型了,总之,不用自己写代码了.亲测了下,对于简单的jason是可以用的.

**Comment by CellerX** [comment]
@bigParis 那个框架看了下,确实不错 谢谢分享!

**Comment by wolfcon** [comment]
#385
