### ISSUE TITLE
有个问题，麻烦老师有空看下

### ISSUE THREAD

**Issue by Jason8812** [CoderMJLee/MJExtension#32]
MJ Teacher:
您好，对于你的这个新方法
// 新方法更加没有侵入性和污染
+ (NSDictionary *)objectClassInArray
{
    return @{
         @"statuses" : @"Status",
         @"ads" : @"Ad"
    };
}
我想问，这个模型能作为参数传进来吗？
因为我服务器返回的是这样的json数据，{"code" : 1, "msg" : null, "obj" : [{"id" : 1, "name" : "张三"}，{"id" : 2, "name" : "李四"}] }   这里的obj 对象是动态的，可能是集合List，也可能是个对象, 字段不一，如何将这个JSON 转成对象模型呢？

**Comment by CoderMJLee** [comment]
好的，我思考下怎么实现会比较好
