### ISSUE TITLE
手机语言切换到德国,法国之类的时候

### ISSUE THREAD

**Issue by chengsifang** [CoderMJLee/MJExtension#321]
NSObject+MJKeyValue 类的 162行 value = [numberFormatter_ numberFromString:oldValue]; 当oldValue为带小数点的字符串的时候 转出0 , 其他语言不会有问题, 好奇怪啊

**Comment by wolfcon** [comment]
兄弟, 我这边测试是正常的. 用的德语, 如果你测试还有问题, 请继续联系
