### ISSUE TITLE
【高清图：大量崩溃汇总】-----MJExtension

### ISSUE THREAD

**Issue by CharlinFeng** [CoderMJLee/MJExtension#324]
您好，在正常使用MJExtension基本是没有问题的，
但是在CoreModel里面MJExtension会大量密集崩溃。
CoreModel主要是在子线程中高速调用MJExtension，并导致在一定概率上（20%左右）大量崩溃，这些崩溃不是必然的，但是概率很高20%左右。而且崩溃点有很多个，个人感觉可能是某一些异常没有做处理，贴图如下，希望有时间可以看看。感谢。

地址：https://github.com/CharlinFeng/CoreModel

![2](https://cloud.githubusercontent.com/assets/8357630/12324157/bf13ab5c-bafb-11e5-9c25-11b4b82c1264.jpg)
![3](https://cloud.githubusercontent.com/assets/8357630/12324159/bfa114d8-bafb-11e5-89f7-d2f84f42eebe.jpg)
![4](https://cloud.githubusercontent.com/assets/8357630/12324158/bf9f45cc-bafb-11e5-8f6f-750ef8bd3591.jpg)

![5](https://cloud.githubusercontent.com/assets/8357630/12324787/2c323718-bb00-11e5-9bb9-d5429821b1da.jpg)
![6](https://cloud.githubusercontent.com/assets/8357630/12324786/2c30581c-bb00-11e5-8a25-6b29758734e9.jpg)

**Comment by SamHongqiang** [comment]
..一样遇到了呢~有解决方法吗

**Comment by CoderPJChao** [comment]
杰哥，我在执行  pod spec lint xxx.podspec命令的时候，提示
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.beta.1`
[!] The spec did not pass validation, due to 1 error. 应该怎么解决。跪求！！！[泪流满面]

**Comment by CoderMJLee** [comment]
在3.0.12中已经解决哈
