### ISSUE TITLE
How to start using MJExtension?App crashed when I use MJExtension.unrecognized selector 

### ISSUE THREAD

**Issue by bigParis** [CoderMJLee/MJExtension#325]
NAME : NSInvalidArgumentException
REASON : +[MJUser mj_objectWithKeyValues:]: unrecognized selector sent to class 0x103c0f5e8

I add pod 'MJExtension' in my podfile
in my ViewControl.m file I define MJUser as the demo did,
and ,I import "MFExtension.h" as well,
in viewDidLoad, I write [MJUser mj_objectWithKeyValues:dic];
dic is defined as the demo did.

where I was wrong?
Is there something I lost?

**Comment by bqlin** [comment]
试试手动导入 MJExtension 目录到项目中

**Comment by bigParis** [comment]
可以了，难道pod下来的代码是不可用的？

**Comment by bigParis** [comment]
@bqlin OK 了 已经用了3.0.8版本

**Comment by cpg1234** [comment]
我使用pod MJExtenstion 项目中使用mj_objectWithKeyValues 直接说找不到方法，手动导入到工程中就ok ，求解
