### ISSUE TITLE
您好MJ老师，要把模型转成字典，如果模型中属性名是ID，怎么实现转成字典中的Key为小写id

### ISSUE THREAD

**Issue by mzmJACK** [CoderMJLee/MJExtension#327]
// More complex situation
Student *stu = [[Student alloc] init];
stu.ID = @"123";
stu.oldName = @"rose";
stu.nowName = @"jack";
stu.desc = @"handsome";
stu.nameChangedTime = @"2018-09-08";

Bag *bag = [[Bag alloc] init];
bag.name = @"a red bag";
bag.price = 205;
stu.bag = bag;

NSDictionary _stuDict = stu.mj_keyValues;
NSLog(@"%@", stuDict);
/_
{
 *这里把大写ID转成小写的id ? 
   id = 123;
    bag =     {
        name = "\U5c0f\U4e66\U5305";
        price = 205;
    };
    desc = handsome;
    nameChangedTime = "2018-09-08";
    nowName = jack;
    oldName = rose;
}
 */

**Comment by PandaLuck** [comment]
可以用用这个方法:
    + (void)mj_setupReplacedKeyFromPropertyName:(MJReplacedKeyFromPropertyName)replacedKeyFromPropertyName

   BLOCK中返回一个字典:字典中的键就是要得到的 ,而对应的值就是你要修改的

**Comment by AngryLi** [comment]
楼上看错了吧

**Comment by wolfcon** [comment]
@AngryLi 的确是用你楼上的方法

**Comment by AngryLi** [comment]
@wolfcon 惊了，16年的评论有人回复了
