### ISSUE TITLE
方法命名问题

### ISSUE THREAD

**Issue by coco227** [CoderMJLee/MJExtension#328]
突然发现新的mjextension中的方法名都加了"mj_"前缀，感觉打字起来有点不方便，每次都要mj然后来个下划线，这个能在以后的版本中去掉么

**Comment by AngryLi** [comment]
已经去掉了，我用CocoaPods安装的就去掉了。下载的源码没有去掉，你看看是怎么回事

**Comment by bigParis** [comment]
pod下来的版本和git上的版本不太一样.

**Comment by AngryLi** [comment]
哪个版本高？

**Comment by bigParis** [comment]
应该是git上的高，我用pod现在pod下来的直接不能用了

**Comment by coco227** [comment]
我pod直接指定的2.x版本的最后一版，可以正常使用。

**Comment by bigParis** [comment]
pod 'MJExtension', '~> 2.x' ?? x = ?

**Comment by AngryLi** [comment]
是的，我查到了，git上下的更早，pod的版本是2.5.12，git上面的至少2.5.16

在 2016-01-19 10:05:46，"bigParis" <notifications@github.com> 写道：


应该是git上的高，我用pod现在pod下来的直接不能用了

**Comment by coco227** [comment]
pod 'MJExtension’, ‘~> 2.5.16’

**Comment by bigParis** [comment]
@coco227 请问你是怎么知道版本号的？

**Comment by bigParis** [comment]
@coco227 已经试过2.5.16和3.0.8  Installing MJExtension 2.5.16 (was 3.0.8)  都不能用

**Comment by coco227** [comment]
可以用的，pod的时候显示的就是2.5.16，使用正常
