### ISSUE TITLE
json数据转换为model时候出现错误

### ISSUE THREAD

**Issue by jimmyken** [CoderMJLee/MJExtension#33]
[__NSCFConstantString objectArrayWithKeyValuesArray:]: unrecognized selector sent to instance 0x10012d848

NSObject+MJKeyValue 第125行
                Class objectClass = [ivar objectClassInArrayFromClass:[self class]];
                if (objectClass) {
                    // 3.字典数组-->模型数组
                    value = [objectClass objectArrayWithKeyValuesArray:value];
                }

调用直接报错。

@property (strong,nonatomic) NSMutableArray * topic;

数据:
{"data":{"topic":[{"tid":2154829,"author":"\u5443\u5443\u5443\u989d\u989d\u989d","authorid":15498192,"subject":"\u82e6\u903c\u7684\u6708\u5b50\u7ec8\u4e8e\u8981\u7ed3\u675f\u4e86\uff01\u5410\u69fd\u90a3\u4e9b\u70e6\u5fc3\u4e8b\uff01"},{"tid":2141234,author":"xin206","authorid":11252235,"subject":"\u90fd\u6765\u8bf4\u8bf4\u5b9d\u5b9d\u662f\u8ddf\u81ea\u5df1\u7761\u8fd8\u662f\u5a46\u5a46\u7761"},{"tid":2126980,"author":"Babyface212","authorid":14429965,"subject":"\u6709\u6ca1\u6709\u52c7\u6c14\u6652\u6652\u4f60\u7684\u6708\u5b50\u7167\uff01"}]},"errmsg":{"errno":0,"msg":""},"status":1}

**Comment by CoderMJLee** [comment]
你有没有在模型.m文件中实现+ (NSDictionary *)objectClassInArray方法，告诉框架{"tid":2154829,"author":"\u5443\u5443\u5443\u989d\u989d\u989d","authorid":15498192,"subject":"\u82e6\u903c\u7684\u6708\u5b50\u7ec8\u4e8e\u8981\u7ed3\u675f\u4e86\uff01\u5410\u69fd\u90a3\u4e9b\u70e6\u5fc3\u4e8b\uff01"}这货究竟是什么模型？

**Comment by wonderffee** [comment]
我加了objectClassInArray，但是这个方法没有调用到，不知道是怎么回事

**Comment by CoderMJLee** [comment]
发个Demo到邮箱看看可以么？我没有遇到这个情况哦

**Comment by wonderffee** [comment]
原来的版本有点低，更新到最新的版本就解决了。还是用你的方法把pod repo源换了一下，换了之后就好了。链接：http://blog.sina.com.cn/s/blog_800cdf9c0102ve7e.html，感谢你的分享啊

**Comment by CoderMJLee** [comment]
不客气哈
