### ISSUE TITLE
在iPhone5上NSNumber的转换出了问题

### ISSUE THREAD

**Issue by FlyKite** [CoderMJLee/MJExtension#330]
从服务器获得的json是这样的一个结构
```
{
    @"list" : [
              @"model" : {
                         @"time" : @"1450013271000"
                         }
              ]
}
```
得到的time是1450013271000，转成model后NSNumber的值是-1685675048。
然后转换到NSDate之后得到了1969年的日期(╯‵□′)╯︵┻━┻
已更新到目前最新版本的MJExtension，依旧这个Bug
目前这个Bug只出现在了iPhone5上（目前没有4s用户，5s以及更新版本的iPhone未出现Bug）
猜测可能与5s使用了64位CPU而5是32位的CPU有关。

**Comment by XuCe** [comment]
你定义的 time 类型是？

**Comment by FlyKite** [comment]
设置断点调试，有新发现。
在NSObject+MJKeyValue.m第189行
```
    [property setValue:value forObject:self];
```
value的值为1450013271000，这行执行完后value值不变，model中值为-1685675048
```
    // 此处value为NSNumber类型，而model中的属性为NSInteger类型
    [object setValue:value forKey:self.name];
```
不知道为什么在iPhone5s以及更新版iPhone上都没有出现问题而iPhone5上出现了。

**Comment by FlyKite** [comment]
已找到原因，这不怪MJExtension(╯‵□′)╯︵┻━┻
```
#if __LP64__ || (TARGET_OS_EMBEDDED && !TARGET_OS_IPHONE) || TARGET_OS_WIN32 || NS_BUILD_32_LIKE_64
typedef long NSInteger;
typedef unsigned long NSUInteger;
#else
typedef int NSInteger;
typedef unsigned int NSUInteger;
#endif
```

**Comment by FlyKite** [comment]
类型是NSInteger，现在已找到问题~32位处理器的NSInteger是int类型的导致溢出了。

2016-01-20 10:07 GMT+08:00 XuCe <notifications@github.com>:
