### ISSUE TITLE
mj_setupReplacedKeyFromPropertyName 方法的一个BUG，复现代码如下

### ISSUE THREAD

**Issue by mg459046365** [CoderMJLee/MJExtension#331]
首先设置
[YGCourse mj_setupReplacedKeyFromPropertyName:^NSDictionary *{
        return @{
                 @"logoCover" : @"logo_cover"
                 };
    }];
然后:
for(NSDictionary *tmpDic in result)
{
       YGCourse *course = [YGCourse mj_objectWithKeyValues:tmpDic];
}
如上方法去转换，只有数组中的第一个字典元素转对象，logoCover会转换正确。后面所有的字典全部转换失败，logoCover = nil;

**Comment by bigParis** [comment]
是不是你字典数组中的其它元素不满足YGCourse类型呢?

**Comment by mg459046365** [comment]
那为什么数组中的第一个元素映射成对象正确啊，而且如果将[YGCourse mj_setupReplacedKeyFromPropertyName:^NSDictionary *{
return @{
@"logoCover" : @"logo_cover"
};
}];
写在for循环中，那么所有的字典都能够映射成功。

**Comment by bigParis** [comment]
@mg459046365 一个字典对应一个模型,所有字典都一样才可以解

**Comment by mg459046365** [comment]
@bigParis  是否意味着的所有字典中的key,都保证一值？这里有一个具体细节，YGCourse中有A,B两个属性。数组中有dic1,dic2两个字典，dic1中有key1,key2,key3,dic2有key1,key2;其中key1,key2分别对应A,B这个两个属性。这个时候就会出现dic1映射成功，而dic2中的key2会映射失败的问题但是其他属性都会映射成功。这种问题，什么原因。

**Comment by bigParis** [comment]
@mg459046365 我个人感觉dic1会解析出key1,key2,但key3是nil；dic2会正常解析，不过这种解析本身没什么意义吧？你用不匹配的模型去解析字典不会得到你想要的结果，你可以把dic或者jason贴出来看看怎么处理。

**Comment by CoderMJLee** [comment]
@mg459046365 我还没遇到过这样的问题哦，是不是后面那些字典本来就没有logo_cover
