### ISSUE TITLE
一种思考

### ISSUE THREAD

**Issue by BelongsH** [CoderMJLee/MJExtension#335]
{
"topic_id": "1625",
"content": "真是棒棒的",
.......
----上面是帖子相关信息----

----下面是用户相关信息----
"head_ico": "upload/head/df84bf8cf4c44caeede3e10fcbe023",
"nick_name": "Hardy",
"sex": "1",
"signature": "个性签名",
"position": "设计师",
.....
}
- 服务端返回的数据有点奇葩(帖子模型和用户模型)在同一级.
- 可以新建一个Model去解析这个json但是觉得有点违背面向对象编程（不知道这个模型改叫什么名字）。

自己的想法是:
用TopicModel去解析帖子的相关信息.用UserModel去解析用户的相关信息。但是在解析用户相关信息的时候，要先创建UserModel的实例。（不知道用MJExtension怎么处理）。

先谢谢百忙之中回答问题的你。谢谢。谢谢。收下我的膝盖。

**Comment by misaka14** [comment]
用一个类，包含这两个模型类，就可以了吧。

**Comment by BelongsH** [comment]
@misaka14   可以用这种方式来解决。但是这样的话 项目中会出现很多这样为了解析所出现的Model

**Comment by BelongsH** [comment]
@CoderMJLee   MJ老师有什么比较好的解决办法哈 ？
