### ISSUE TITLE
-[MJProperty propertyKeysForClass:] crash

### ISSUE THREAD

**Issue by lengmolehongyan** [CoderMJLee/MJExtension#336]
![qq20160216-1 2x](https://cloud.githubusercontent.com/assets/11879527/13071577/64192f9a-d4cf-11e5-9f30-95e758d28110.png)
![qq20160216-2 2x](https://cloud.githubusercontent.com/assets/11879527/13071578/64d85d98-d4cf-11e5-9ff0-5d524582f222.png)

**Comment by kobe1941** [comment]
遇到了一样的多线程问题，作者来看一下？

**Comment by kinarob** [comment]
Related #667
