### ISSUE TITLE
复杂数据结构里有 "MJHelpMe":{"110”：[{},{},{}] ,“120”：[{},{},{}]} 这种格式该如何转模型

### ISSUE THREAD

**Issue by Echoecho126** [CoderMJLee/MJExtension#338]
最近遇到这种情况，不知如何解决。返回的复杂数据里边层层字典转模型，中间有一个模型里的属性值是字段字符串是MJHelpMe，数据结构如下 
{ "id"= 10086,
  "age" =100，
  "MJHelpMe":{"110”：[{},{},{}] ,“120”：[{},{},{}]}
}
这只是个简单例子，我在写MJHelpMe 时，该怎么根据110 ，120 来解析里边的模型数组？

**Comment by wolfcon** [comment]
110 和 120 里面的模型不确定吗? 确定的话, 他肯定是一个模型, 按照例子走就可以
