### ISSUE TITLE
使用mj_replacedKeyFromPropertyName转换key，但是原有的key却不能转换了

### ISSUE THREAD

**Issue by zingos** [CoderMJLee/MJExtension#340]
有这样一个json
`{
    "data": [{
        "name": "配置项1",
        "code": 1001
    }, {
        "name": "配置项2",
        "value": 3001
    }, {
        "name": "配置项2",
        "value": 3002
    }]
}`

我想将key值 ：code转换成value
实现了下面的方法
- (NSDictionary *)mj_replacedKeyFromPropertyName
  {
  return @{@"value" : @"code"};
  }

这个时候如果遇到原来key=value的值，就无法转换了，这个怎么破？

**Comment by wolfcon** [comment]
```objective-c
(NSDictionary *)mj_replacedKeyFromPropertyName
{
return @{@"value" : @[@"code", @"value"]"};
}
```
