### ISSUE TITLE
对swift的基础数据类型支持还不够完善

### ISSUE THREAD

**Issue by linhan6177** [CoderMJLee/MJExtension#343]
//JSON
{"provinces":[...]}
//Model
class SWCity:NSObject{
    var ID:String? = ""
    var name:String? = ""
}
class SWProvince:NSObject{
    var ID:String? = ""
    var name:String? = ""
    var cities:[SWCity] = []
}
class SWCountry:NSObject{
    var provinces:[SWProvince] = []
}
//报错
fatal error: NSArray element failed to match the Swift Array Element type
if let country:SWCountry = SWCountry.SWCountry.mj_objectWithKeyValues(JSONString)
{
                for province in country.provinces
                {
                    print(province)
                }  
 }

**Comment by wolfcon** [comment]
```swift
var cities: [SWCity]?
```

或者
```swift
var cities = [SWCity]()
```
