### ISSUE TITLE
老师，Analyze的时候出现了N个内存泄露，求帮忙，在线等，着急中

### ISSUE THREAD

**Issue by saeipi** [CoderMJLee/MJExtension#344]
老师，Analyze
![snip20160229_1](https://cloud.githubusercontent.com/assets/16273098/13391389/2d604c82-df0f-11e5-822f-007213d5225c.png)
的时候出现了N个内存泄露，求帮忙，在线等，着急中

**Comment by CoderMJLee** [comment]
那些都是旧方法，可以不用管哈
