### ISSUE TITLE
不能解析emoji表情 比如 //  NSString *jsonString = @"{\"emoji\":\"\\ud83d\\ude04\"}";  // 2.JSONString -> User User *user = [User mj_objectWithKeyValues:jsonString];

### ISSUE THREAD

**Issue by liu521227** [CoderMJLee/MJExtension#346]
不能解析emoji表情 比如\ud83d\ude04

**Comment by MISSAJJ** [comment]
.NET的实体类转JSON unicode 一般都会多一个斜杠
你的json数据是{\"emoji\":\"\\ud83d\\ude04\"}, 里面多了斜杠了

标准的该是{"emoji":"\ud83d\ude04\"}

方案:
在解析之前先找规律批量去掉{\"emoji\"里的前后斜杠, 再去掉"\\ud83d\\ 里的前后斜杠,

让数据变成标准状态, 再用杰哥的MJExtension工具解析.

**Comment by wolfcon** [comment]
> .NET的实体类转JSON unicode 一般都会多一个斜杠
> 你的json数据是{"emoji":"\ud83d\ude04"}, 里面多了斜杠了
> 
> 标准的该是{"emoji":"\ud83d\ude04"}
> 
> 方案:
> 在解析之前先找规律批量去掉{"emoji"里的前后斜杠, 再去掉"\ud83d\ 里的前后斜杠,
> 
> 让数据变成标准状态, 再用杰哥的MJExtension工具解析.

他的例子本身解析就不会出错. String 中有 `"` 必须加 `\` 转义. 有 `\` 必须加 `\` 转义
