### ISSUE TITLE
MJ男神，MJExtension是否可以支持Realm的自定义RLMArray<Class> 类型（类似泛型）

### ISSUE THREAD

**Issue by HeroOnline** [CoderMJLee/MJExtension#354]
Realm框架： https://github.com/realm/realm-cocoa
# import
# import

// 注意这里 ！！！
RLM_ARRAY_TYPE(Dog)

@interface Person : RLMObject
@property(nonatomic, copy) NSString *name;
// 类似泛型 // MJExtension 解析报错
@property(nonatomic, strong) RLMArray *dogs;

// NSMutableArray
//@property (nonatomic, strong) NSMutableArray *dogs;

//@property (nonatomic, strong) NSArray *dogs;

// All properties must be primitives, NSString, NSDate, NSData, RLMArray, or subclasses of RLMObject. See https://realm.io/docs/objc/latest/api/Classes/RLMObject.html for more information.'

// 不支持 NSArray，只能支持 RLMArray

@end

**Comment by wolfcon** [comment]
不支持哈

**Comment by wolfcon** [comment]
你对 Realm 比较熟悉的话可以做一个中间中转的子库, 便于. 挂载在 MJExtension 下. 这个一般是要做一层处理的. 欢迎你提 PR
