### ISSUE TITLE
关于-模型中有个字典属性,字典里面装着字典(value又要装着其他模型,比如新浪微博一条微博返回的数据)

### ISSUE THREAD

**Issue by BossKing** [CoderMJLee/MJExtension#355]
{
    "pic_infos" : {
        "eb8fce65jw1ew468zkxcgj237k1t01l0" : {
            "thumbnail" : {
                "cut_type" : 1,
                "type" : "WEBP",
                "url" : "http://ww2.sinaimg.cn/or180/eb8fce65jw1ew468zkxcgj237k1t01l0.jpg",
                "width" : 266,
                "height" : 150
            },
            "bmiddle" : {
                "cut_type" : 1,
                "type" : "WEBP",
                "url" : "http://ww2.sinaimg.cn/or360/eb8fce65jw1ew468zkxcgj237k1t01l0.jpg",
                "width" : 480,
                "height" : 270
            },
            "large" : {
                "cut_type" : 1,
                "type" : "JPEG",
                "url" : "http://ww2.sinaimg.cn/wap720/eb8fce65jw1ew468zkxcgj237k1t01l0.jpg",
                "width" : 720,
                "height" : 405
            },
            "largest" : {
                "cut_type" : 1,
                "type" : "JPEG",
                "url" : "http://ww2.sinaimg.cn/large/eb8fce65jw1ew468zkxcgj237k1t01l0.jpg",
                "width" : 2048,
                "height" : 1152
            },
            "pic_id" : "eb8fce65jw1ew468zkxcgj237k1t01l0",
            "photo_tag" : 0,
            "original" : {
                "cut_type" : 1,
                "type" : "JPEG",
                "url" : "http://ww2.sinaimg.cn/woriginal/eb8fce65jw1ew468zkxcgj237k1t01l0.jpg",
                "width" : 2048,
                "height" : 1152
            },
            "filter_id" : "1",
            "object_id" : "1042018:c9c58ca914425bc1370ca0d9f56cae83",
            "middleplus" : {
                "cut_type" : 1,
                "type" : "WEBP",
                "url" : "http://ww2.sinaimg.cn/or480/eb8fce65jw1ew468zkxcgj237k1t01l0.jpg",
                "width" : 640,
                "height" : 360
            }
        }
    }
}

**Comment by wolfcon** [comment]
仔细看例子
