### ISSUE TITLE
setupReplacedKeyFromPropertyName 有BUG

### ISSUE THREAD

**Issue by ghost** [CoderMJLee/MJExtension#356]
[SomeClass setupReplacedKeyFromPropertyName:^NSDictionary *{
                return @{@"oneKey" : @"oldKey"};
            }];
[SomeClass setupReplacedKeyFromPropertyName:^NSDictionary *{
                return @{@"twoKey" : @"oldKey"};
            }];

这个方法替换只有第一次调用时才能替换成功，之后调用无法替换了。
则oldKey只能是oneKey了

场景：比如我在a VC里替换了Key值 然后我在b VC里也替换了Key值 但是替换失败

**Comment by wolfcon** [comment]
建议你不要这样干, 因为这个 Key 替换严重依赖于你的业务逻辑, 如果在不同的 VC 中模型参数不定. **如果出现 2 个 VC 都有用或者都需要解析这个模型时, 有可能会出现严重的 bug**. 

**不要将模型内聚属性(原发的)与 Controller 之间耦合**

建议你使用 `2 个模型`.
其余部分使用 `Protocol` 进行公共声明
不同的部分特异化.

> 当然你也可以使用继承
