### ISSUE TITLE
关于64位机和32位机转换中的BOOL类型问题

### ISSUE THREAD

**Issue by TheyCallMeTank** [CoderMJLee/MJExtension#359]
杰哥你好，经过我的测试，在model->json时，64位的手机会将bool型转换成true和false，32位的手机会将bool转换成0和1，我现在服务端这边只能接受true和false，所以必须进行过滤，但是现在库只有json->model的过滤方法，没有model->json的过滤方法，我只能修改你的源码临时用了，不知道杰哥有没有空解决一下这个问题呢？

**Comment by BirdsAndFish** [comment]
杰哥你好，我也遇到了这个问题，在iphone5以下的设备上传数据始终不能够成功，提示：json: cannot unmarshal number into Go value of type bool

**Comment by tigerZhang86** [comment]
@TheyCallMeTank 可以分享下临时解决方案吗，或者给作者提个PR？

**Comment by wolfcon** [comment]
JSON 转 String 的时候是由系统的 `NSJSONSerialization` 在处理的, 没有其他的人为干预
