### ISSUE TITLE
NSString -> BOOL, 结果不都对

### ISSUE THREAD

**Issue by zhw511006** [CoderMJLee/MJExtension#36]
我的JSON文件像这样
{
"online" : "yes" or "online" : "true"
}

低于iPhone5s 机器上面, 结果是 online = NO;
iPhone5s之后，包含iPhone5s， 结果是 online = YES;

这样看来是arm64的结果是正常的，armv7, armv7s都不正常，请查看，谢谢!

**Comment by CoderMJLee** [comment]
这个主要看你使用了什么技术去解析服务器返回的JSONData哈，不过没有关系，我可以做一个判断，你用啥技术都行哈
