### ISSUE TITLE
执行pod spec lint xxx.podspec命令，出现的问题，跪求。

### ISSUE THREAD

**Issue by FMengz** [CoderMJLee/MJExtension#360]
杰哥，我在执行 pod spec lint xxx.podspec命令的时候，提示
[!] Unable to load a specification for the plugin /Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.beta.1
[!] The spec did not pass validation, due to 1 error. 应该怎么解决。跪求！！！[泪流满面]

**Comment by DeveloperPans** [comment]
请看官方文档：http://cocoapods.org
