### ISSUE TITLE
xcode7.3报错

### ISSUE THREAD

**Issue by fanxiao168** [CoderMJLee/MJExtension#362]
MJ,更新xcode7.3后，下面的方法报错
- (id)getNewValueFromObject:(__weak id)object oldValue:(__weak id)oldValue property:(__weak MJProperty *)property;
  报错内容如下：
  /Pods/Headers/Public/MJExtension/NSObject+MJProperty.h:46:30: Cannot create __weak reference in file using manual reference counting

**Comment by LeoiOS** [comment]
+1

**Comment by LeoiOS** [comment]
删除 __weak 关键字即可。
参考：http://stackoverflow.com/questions/36147625/xcode-7-3-cannot-create-weak-reference-in-file-using-manual-reference-counting

**Comment by slq0378** [comment]
我也遇到这种问题了

**Comment by halechan** [comment]
https://github.com/CoderMJLee/MJExtension/pull/365

**Comment by zuolingfeng** [comment]
赞赞
