### ISSUE TITLE
对象的属性为NSDictionary时无法转化

### ISSUE THREAD

**Issue by robin2013** [CoderMJLee/MJExtension#363]
@property(strong,nonatomic)NSMutableDictionary \* time_info;
该属性无法转化成功,
- (instancetype)mj_setKeyValues:(id)keyValues context:(NSManagedObjectContext *)context
  函数转换时,跳转到了(objectClass 是 NSMutableDictionary):
  // 字典数组-->模型数组
                  value = [objectClass mj_objectArrayWithKeyValuesArray:value context:context];

导致赋值错误

**Comment by fengmiting** [comment]
我也遇到同样的问题了

**Comment by wolfcon** [comment]
demo?
