### ISSUE TITLE
复杂字典->模型（模型中既有模型又有模型数组）

### ISSUE THREAD

**Issue by wanghaiqian** [CoderMJLee/MJExtension#369]
请问MJ这是因为什么呢?
<img width="553" alt="2016-03-26 4 01 54" src="https://cloud.githubusercontent.com/assets/10462783/14058975/851f7c10-f36c-11e5-8a3e-271edfd88d3d.png">
<img width="509" alt="2016-03-26 4 04 17" src="https://cloud.githubusercontent.com/assets/10462783/14058976/99d1f174-f36c-11e5-8c89-402de5691a7e.png">
<img width="404" alt="2016-03-26 4 02 22" src="https://cloud.githubusercontent.com/assets/10462783/14058977/a27d91fc-f36c-11e5-9596-532fe661981e.png">
<img width="638" alt="2016-03-26 4 03 03" src="https://cloud.githubusercontent.com/assets/10462783/14058978/acc9ac4a-f36c-11e5-87df-46ebcf22c2e9.png">

**Comment by tangkunyin** [comment]
貌似这是个坑，我晚上过一遍源码看看

**Comment by wolfcon** [comment]
Demo
