### ISSUE TITLE
字段存的时时间转出来是空

### ISSUE THREAD

**Issue by hlm1990** [CoderMJLee/MJExtension#37]
比如有一个字段是出生日期  保存的是字符串类型的  "2014-01-01"  转成model的时候是空

**Comment by CoderMJLee** [comment]
1.模型里面是NSString *类型么？
2.保存？是指用过NSCoding技术么？

**Comment by CoderMJLee** [comment]
现在提供了+ (void)setupNewValueFormOldValue:(MJNewValueFormOldValue)newValueFormOldValue方法或者在.m中实现- (id)newValueFromOldValue:property:来统一处理时间类型哈。具体可以看看Demo，谢谢。
