### ISSUE TITLE
Optional protocol

### ISSUE THREAD

**Issue by hpsoar** [CoderMJLee/MJExtension#371]
MJ老师，请问能否实现类似JSONModel的Optional protocol，在定义属性时，就决定这个属性是否参与模型转换，要不然还要写一个ignore列表，这里面的属性都是字符串，没法利用编译器检查合法性。

另外，能否忽略readonly属性。

我这边经常会在model上定义一些只读属性，用于显示，这些属性在模型转换时也转换了，不是很好。

**Comment by xx-li** [comment]
这确实是个问题，定义了一个数据结构的协议， 同时存在`require`及`optional`属性。 如果一个数据结构没有实现`optional`的属性，进行keyValue转model操作时就会crash， 这个是不合理的。

**Comment by wolfcon** [comment]
对模型进行包装一下
