### ISSUE TITLE
后台返回double和long类型的, 是应该用什么数据类型来接呢 ?

### ISSUE THREAD

**Issue by lifution** [CoderMJLee/MJExtension#373]
之前我一直用NSNumber来接收int和long的, 但是今天需要接收double类型的, 我看杰哥你demo你的示例是用NSString来接收的, 但是示例里的json是字符串, 不知道后台返回dobule的, 我用NSString会不会有什么隐藏的bug. (目前是用NSString来接, 暂时没发现bug, 所以来问一下确定一下)

**Comment by CoderMJLee** [comment]
NSString、NSNumber都可以

**Comment by lifution** [comment]
谢谢
