### ISSUE TITLE
mj_replacedKey两个方法冲突

### ISSUE THREAD

**Issue by MalongGuo** [CoderMJLee/MJExtension#377]
mj_replacedKeyFromPropertyName121与mj_replacedKeyFromPropertyName，将这两种方法放在同一个类中时，只有前者生效，后者不生效。
例如：

#####################
@interface Dog : NSObject
/*
@"nick_name" : @"旺财",
@"sale_price" : @"10.5",
@"run_speed" : @"100.9"
 */
@property (strong, nonatomic) NSString *nickName;
@property (strong, nonatomic) NSString *ID;
@property (assign, nonatomic) double salePrice;
@property (assign, nonatomic) double runSpeed;
@property (assign, nonatomic) double speed;

@end
######################
+ (NSString *)mj_replacedKeyFromPropertyName121:(NSString *)propertyName
{
    // nickName -> nick_name
    return [propertyName mj_underlineFromCamel];
}

+ (NSDictionary *)mj_replacedKeyFromPropertyName
{
    return @{
             @"ID" : @"id"
             };
}
#################################
    NSDictionary *dict = @{
                           @"nick_name" : @"旺财",
                           @"sale_price" : @"10.5",
                           @"run_speed" : @"100.9",
                           @"id" : @"10"
                           };

    Dog *dog = [Dog mj_objectWithKeyValues:dict];
    // 打印

    NSLog(@"nickName=%@, scalePrice=%f runSpeed=%f ID=%@", dog.nickName, dog.salePrice, dog.runSpeed, dog.ID);

运行结果为
nickName=旺财, scalePrice=10.500000 runSpeed=100.900000 ID=(null)，没有将id转化为ID。

**Comment by CoderMJLee** [comment]
没错，设计的初衷就是mj_replacedKeyFromPropertyName121优先级高于> mj_replacedKeyFromPropertyName，只能使用其中一个

**Comment by MalongGuo** [comment]
优先级高低，应该是针对同一个Key，我这个是两个不同的Key，似乎不存在优先级的问题吧，或者这个功能能不能完善一下：     针对同一个Key，mj_replacedKeyFromPropertyName121优先级高于mj_replacedKeyFromPropertyName；针对不同的Key，两个方法都可以使用。

**Comment by CoderMJLee** [comment]
即时有优先级，也是不太可行的哈。因为1个key在执行mj_replacedKeyFromPropertyName121方法的时候已经经过mj_underlineFromCamel方法返回具体值，既然有值了，自然就轮不到执行mj_replacedKeyFromPropertyName方法。
你可以将mj_replacedKeyFromPropertyName的内容写到mj_replacedKeyFromPropertyName121的，合二为一。
```objc
- (NSString *)mj_replacedKeyFromPropertyName121:(NSString *)propertyName
{
    if ([propertyName isEqualToString:@"ID"]) return @"id";
    return [propertyName mj_underlineFromCamel];
}
```

**Comment by MalongGuo** [comment]
好的，已经解决我的问题了。多谢。

**Comment by dongdong3344** [comment]
OMG  终于在这个地方遇到解决方案了。
