### ISSUE TITLE
Coredata 联合使用问题

### ISSUE THREAD

**Issue by LeeCQ** [CoderMJLee/MJExtension#378]
coredata 建立了两个entity  entity1 包含entity2    由于core data里边包含关系 是用NSSet 集合 所以用您这个解析的时候失败了  
            // 不可变 -> 可变处理
            if (propertyClass == [NSMutableArray class] && [value isKindOfClass:[NSArray class]]) {
                value = [NSMutableArray arrayWithArray:value];
            } else if (propertyClass == [NSMutableDictionary class] && [value isKindOfClass:[NSDictionary class]]) {
                value = [NSMutableDictionary dictionaryWithDictionary:value];
            } else if (propertyClass == [NSMutableString class] && [value isKindOfClass:[NSString class]]) {
                value = [NSMutableString stringWithString:value];
            } else if (propertyClass == [NSMutableData class] && [value isKindOfClass:[NSData class]]) {
                value = [NSMutableData dataWithData:value];
            }
            是不是你这里需要加一个NSSet的呢

**Comment by wolfcon** [comment]
Duplicate of #43
