### ISSUE TITLE
数组中有字典，字典中还有数组，数组中还有字典，但是要改最里面字典里的属性名称，怎么修改

### ISSUE THREAD

**Issue by vickmiller** [CoderMJLee/MJExtension#380]
比如拿你的例子
@interface Ad : NSObject
/*\* 这两个属性名要修改，注意看下面的dictonnary */
@property (copy, nonatomic) NSString *image;
@property (copy, nonatomic) NSString *url;
@end

@interface StatusResult : NSObject
/*\* Contatins status model _/
@property (strong, nonatomic) NSMutableArray *statuses;
/_\* Contatins ad model */
@property (strong, nonatomic) NSArray *ads;
@property (strong, nonatomic) NSNumber *totalNumber;
@end

/***********************************************/

// Tell MJExtension what type model will be contained in statuses and ads.
[StatusResult mj_setupObjectClassInArray:^NSDictionary *{
    return @{
               @"statuses" : @"Status",
               // @"statuses" : [Status class],
               @"ads" : @"Ad"
               // @"ads" : [Ad class]
           };
}];
// Equals: StatusResult.m implements +mj_objectClassInArray method.

NSDictionary *dict = @{
    @"statuses" : @[
                      @{
                          @"text" : @"Nice weather!",
                          @"user" : @{
                              @"name" : @"Rose",
                              @"icon" : @"nami.png"
                          }
                      },
                      @{
                          @"text" : @"Go camping tomorrow!",
                          @"user" : @{
                              @"name" : @"Jack",
                              @"icon" : @"lufy.png"
                          }
                      }
                  ],
    @"ads" : @[
                 @{
                     @"_image" : @"ad01.png",
                     @"_url" : @"http://www.ad01.com"
                 },
                 @{
                     @"_image" : @"ad02.png",
                     @"_url" : @"http://www.ad02.com"
                 }
             ],
    @"totalNumber" : @"2014"
};

// JSON -> StatusResult
StatusResult *result = [StatusResult mj_objectWithKeyValues:dict];

**Comment by MalongGuo** [comment]
在.m文件里，使用
+ (NSDictionary *)mj_replacedKeyFromPropertyName
{
    return @{
             @"ID" : @"id",
             @"desc" : @"description",
             };
}
这个方法。
说明文档中有提到的。
