### ISSUE TITLE
json字符串通过mj_JSONObject方法转成NSDictionary时，如果json字符串中某个值为负数，转换出来的字典中该值会自动转换成long类型一大串的数字（与json字符串的原始值不一致）

### ISSUE THREAD

**Issue by zhipingli** [CoderMJLee/MJExtension#382]
json字符串通过mj_JSONObject方法转成NSDictionary时，如果json字符串中某个值为负数，转换出来的字典中该值会自动转换成long类型一大串的数字（与json字符串的原始值不一致）

**Comment by sopig** [comment]
有的，自己好好看看代码，不要做伸手党

发自我的 iPhone
