### ISSUE TITLE
使用mj_setupReplacedKeyFromPropertyName时出现一个问题

### ISSUE THREAD

**Issue by zingos** [CoderMJLee/MJExtension#383]
因为服务器端的命名不规范，导致同样一个对象，在2个接口中的key的命名是不一样的，比如一个Customer对象，在A接口中ID命名为customerId，而在B接口中ID命名为uid，本来想用mj_setupReplacedKeyFromPropertyName方法将customerId替换成uid，结果A接口没问题，到了B接口，uid不能被正常解析了，因为默认uid就是等于customerId,其他的设置就不管了，这个如何解决？

**Comment by maplelover** [comment]
@[k1, k2]

**Comment by CoderMJLee** [comment]
@maplelover 是的。
```objc
[MJStudent mj_setupReplacedKeyFromPropertyName:^NSDictionary *{
        return @{@"ID" : @[@"customerId", @"uid"]};
    }];
```

**Comment by songhailiang** [comment]
这个用法是从哪个版本里增加的？我现在都是用2个属性，然后在mj_keyValuesDidFinishConvertingToObject方法里把第二个属性值赋值给第一个属性....

**Comment by CoderMJLee** [comment]
忘记了，比较早了哈，去年就有了
