### ISSUE TITLE
[__NSCFConstantString objectForKeyedSubscript:]李老师，我这经常出现这个报错，服务器有时候反的字段是空的

### ISSUE THREAD

**Issue by XHJiang** [CoderMJLee/MJExtension#384]
请问下如何解决

**Comment by CoderMJLee** [comment]
这是错误地将字符串当做字典来用了，也就是说你服务器返回的可能是字符串，你却当做字典来使用。服务器返回的数据是空的，这是服务器的问题。以上的问题都跟MJExtension没有关系哈

**Comment by imagons** [comment]
杰哥说的对. 明显是服务器那边的关系 你可以去找服务器那边的麻烦了

**Comment by XHJiang** [comment]
@imagons 钢不过啊。你能理解一个通讯录乱七八糟返回给我所有数据，我自己前段排序分组的痛苦么。。。而且我们这安卓啥也不懂，就知道叫。。。

**Comment by XHJiang** [comment]
@CoderMJLee 谢谢杰哥，等错误再出现的时候我再排查一下。。。

**Comment by CoderMJLee** [comment]
@XHJiang 加油
