### ISSUE TITLE
什么时候可以支持泛型？

### ISSUE THREAD

**Issue by JxbSir** [CoderMJLee/MJExtension#385]
NSArray<__covariant ObjectType> 

用mj_objectClassInArray实在太麻烦，JsonModel支持泛型

**Comment by CoderMJLee** [comment]
谢谢建议，我尽快看看如何处理。据我所知，JSONModel不算是真正的泛型哈，它是利用协议来间接实现的

**Comment by yuhuixia** [comment]
这个字典转模型框架 支持大小写互相转化吗

**Comment by wolfcon** [comment]
泛型是编译器阶段实现的. MJ 是通过 Runtime 来工作的

**Comment by wolfcon** [comment]
由于 Objective-C 是轻量级的泛型支持. 仅编译器阶段以及之前作用. 编译后, 没有泛型这个概念了. 与 Java 不同.
