### ISSUE TITLE
Model A里面有NSString m 和NSarray n类型，NSArray n里面是另外一个Model B，Model B里面有NSArray<NSString* C>,怎么解析这种Model A？

### ISSUE THREAD

**Issue by mianli** [CoderMJLee/MJExtension#389]
比如：
@interface ResponseObject : NSObject
@property (strong, nonatomic) NSString\* ErrorMsg;
@property (strong, nonatomic) NSString\* Result;
@property (strong, nonatomic) NGData\* Data;
@end

@interface NGData : NSObject
@property (strong, nonatomic) NGAddress\* address;
@end

@interface NGAddress : NSObject
@property (strong, nonatomic) NSArray<NGSubs>\* subs;//NGSubs list
@end

@interface NGSubs : NSObject
@property (strong, nonatomic) NSArray<NGsub>\* sub;//NGsub list
@end

@interface NGsub : NSObject
@property (assign, nonatomic) NSInteger region_id;
@property (strong, nonatomic) NSString\* local_name;
@end

**Comment by wolfcon** [comment]
看例子
