### ISSUE TITLE
服务端返回的json里有null，框架崩溃

### ISSUE THREAD

**Issue by woshixmy** [CoderMJLee/MJExtension#39]
服务端返回的json里有null，框架崩溃，用的去年你课程里附带的代码，不知道新版本有改吗？

**Comment by CoderMJLee** [comment]
1.没问题的，很久以前就更新了。
2.建议以后遇到问题了，可以优先试试最新框架哈。因为大部分情况，你遇到的问题可能别人也遇到了，然后被我修复了哈
