### ISSUE TITLE
看到别人也出现这个问题了 ，就是使用replacedKeyFromPropertyName方法

### ISSUE THREAD

**Issue by jql772386689** [CoderMJLee/MJExtension#392]
在服务器返回的数据名和Model名不一致的时候，使用replacedKeyFromPropertyName替换
+ (NSDictionary *)replacedKeyFromPropertyName {
    return @{@"number" : @"num"};
}

但是添加这个方法之后，如果服务器有地方返回的是number的话就无法赋值给number这个属性了，导致number属性为空

**Comment by CoderMJLee** [comment]
```objc
- (NSDictionary *)replacedKeyFromPropertyName { return @{@"number" : @[@"number", @"num"]}; }
```

**Comment by jql772386689** [comment]
谢谢大神 ，完美解决啦
