### ISSUE TITLE
杰哥，如果我有两套数据源，结构都类似，公用一个modal，怎么用啊

### ISSUE THREAD

**Issue by momo25** [CoderMJLee/MJExtension#393]
replacedKeyFromPropertyName 只能修改一套映射，另外一个数据源 怎么处理啊，求指导啊

**Comment by tl454251115** [comment]
把两套数组的所有属性都写到一个model类上去，解析的时候就会对应属性名解析，不同的属性就是nil，取的时候对应取就行了

**Comment by momo25** [comment]
谢谢，我当时懵逼了，后来想通了
