### ISSUE TITLE
swift 模型嵌套

### ISSUE THREAD

**Issue by gushenmeiying** [CoderMJLee/MJExtension#395]
杰哥swift里面模型嵌套的时候报错fatal error: NSArray element failed to match the Swift Array Element type   有什么方法可以解决么

```
    var banner: [Banner] = []
    var category: [Category] = []
    var icon: [Icon] = []
```

**Comment by tl454251115** [comment]
这个框架貌似不支持swift数组，建议还是用NSArray

**Comment by CoderMJLee** [comment]
是的，本框架还是OC层面的

**Comment by gushenmeiying** [comment]
swift模型嵌套需重写mj_keyValuesDidFinishConvertingToObject
`var model: [Model] = []
override func mj_keyValuesDidFinishConvertingToObject()
    {
        self.model = Model.mj_objectArray(withKeyValuesArray: self.model).copy() as! [Model]
        
    }`

**Comment by BabyWong** [comment]
import UIKit

class HeadResources: NSObject {

    @objc var msg: String?
    @objc var reqid: String?
    @objc var data: HeadData?
    
    class func loadHomeHeadData(_ completion:(_ data: HeadResources?, _ error: NSError?) -> Void) {
        let path = Bundle.main.path(forResource: "首页焦点按钮", ofType: nil)
        let data = try? Data(contentsOf: URL(fileURLWithPath: path!))
        if data != nil {
            let dict: NSDictionary = (try! JSONSerialization.jsonObject(with: data!, options: .allowFragments)) as! NSDictionary
            let headResourcesDataModel = HeadResources.mj_object(withKeyValues: dict)
            completion(headResourcesDataModel, nil)
        }
    }
    
//  quesion: NSArray element failed to match the Swift Array Element type
//  MARK:  -----  解决问题的核心代码  ------
    override func mj_keyValuesDidFinishConvertingToObject() {
        data?.focus = Activities.mj_objectArray(withKeyValuesArray: data?.focus).copy() as? [Activities]
        data?.icons = Activities.mj_objectArray(withKeyValuesArray: data?.icons).copy() as? [Activities]
        data?.activities = Activities.mj_objectArray(withKeyValuesArray: data?.activities).copy() as? [Activities]
    }
}

class HeadData: NSObject {
    @objc var focus: [Activities]? = [Activities]()
    @objc var icons: [Activities]? = [Activities]()
    @objc var activities: [Activities]? = [Activities]()
}

class Activities: NSObject {
    @objc var id: String?
    @objc var name: String?
    @objc var img: String?
    @objc var topimg: String?
    @objc var jptype: String?
    @objc var trackid: String?
    @objc var mimg: String?
    @objc var customURL: String?
}
