### ISSUE TITLE
使用mj_JSONString时有null对象时报错

### ISSUE THREAD

**Issue by zhongqc** [CoderMJLee/MJExtension#398]
在使用mj_JSONString方法将字典转换为json字符串时如果字典中有null对象时会报错程序崩溃

**Comment by CoderMJLee** [comment]
1.如果字典中放的是nil，那这个崩溃跟mj_JSONString方法没有关系哈，字典中本身不可以放nil，
2.如果字典中放的是NSNull对象，用了mj_JSONString方法会转成null，不会崩溃报错
