### ISSUE TITLE
数组中不同的字典模型转换问题

### ISSUE THREAD

**Issue by PelloUp** [CoderMJLee/MJExtension#401]
一个数组中存在多个模型，解析时需要根据其中的一个字段来具体决定采用哪个模型，这个时候应该怎么解决？

**Comment by tl454251115** [comment]
写三个数组

**Comment by tl454251115** [comment]
为毛要搞数组，直接写多个模型不就行了

**Comment by CoderMJLee** [comment]
方法1：遍历数组的所有字典，将不同字典转成不同模型
方法2：用同一种模型（这个模型包含了所有字典的所有属性）
