### ISSUE TITLE
如果一个字典的key是不固定的，应该怎么转呢

### ISSUE THREAD

**Issue by frankpcl** [CoderMJLee/MJExtension#404]
"reasonMap": {
    "104": [
      {
        "id": 115,
        "text": "Purchase Protection is running out, but package is still in transit",
        "class": ".api.mobile.dataobject.Reason"
      },
      {
        "id": 116,
        "text": "Package was returned to seller by shipping company",
        "class": "ue.api.mobile.dataobject.Reason"
      } ],
  "105": [
      {
        "id": 115,
        "text": "Purchase Protection is running out, but package is still in transit",
        "class": ".api.mobile.dataobject.Reason"
      }]
}
请问对于这种数据结构，reasonMap是一个dictionary, 但其中key是不固定的，那么就不能转成一个model,但是dic中value中的值又想转成一个model 类似

@property NSDictionary<NSString*,NSArray<ItemDTO*>*> *reasonMap; 

现有的框架能处理么

**Comment by CoderMJLee** [comment]
可以遍历reasonMap的所有value（也就是装着字典的数组），然后将字典数组转成模型数组
