### ISSUE TITLE
关于内建类型的问题

### ISSUE THREAD

**Issue by enqingchen** [CoderMJLee/MJExtension#408]
如果新建一个类型，什么也不做，序列化出来的字典会带上内建类型的值.
比如MJUser里的age字段出现age=0,然后我并没有设置。
那么问题来了，对于内建类型，可不可以做到设置了才序列化，没有设置不序列化

**Comment by CoderMJLee** [comment]
这个不方便直接通过值是否为0来判断是否设置过，因为也有可能开发者自己手动设置age为0

**Comment by enqingchen** [comment]
那可不可以实现成这样，我设置了age的值，才把age这个字段序列化进去，否则不序列化

**Comment by CoderMJLee** [comment]
可以的，只是比较麻烦，需要去记录开发者有无调用set方法或者直接修改成员变量，成员变量值的直接修改是不好去监听的
