### ISSUE TITLE
MJ老师，如何把不同接口返回的不同字段名，赋值给同一个Model的某个属性呢

### ISSUE THREAD

**Issue by chengyifly** [CoderMJLee/MJExtension#41]
MJ老师，如何把不同接口返回的不同字段名，赋值给同一个Model的某个属性呢？

比如有个模型User，有个属性userId，有多个地方需要用到这个模型，
服务器2个不同接口，其中一个返回 {“userId” : "132"}，另一个返回的是{"commentUserId" : "132"}

用这个也没法解决呀
+ (NSDictionary *)objectClassInArray {
    return @{@"userId": @“commentUserId”};
}

我该怎么处理这种问题？

不吝赐教~

**Comment by sylarhcn** [comment]
两个都做，然后在getter方法里面判断，哪个有值返回哪个。

**Comment by chengyifly** [comment]
@sylarhcn 你是说在userId这个属性的getter里判断吗？请问你是不是理解错我的问题了，不是model有2个属性从同一个key取值，是一个属性在不同地方用到，需要从不同的key取值

**Comment by CoderMJLee** [comment]
我建议是：声明2个属性
```objc
@property (nonatomic, copy) NSString * userId;
@property (nonatomic, copy) NSString * commentUserId;
```

**Comment by chengyifly** [comment]
@CoderMJLee 好吧，谢谢MJ！~   我建议以后可以增加一下这个case

**Comment by chengyifly** [comment]
@CoderMJLee 总的来说，已经很不错了~ 用的很爽，再次感谢啦

**Comment by lp380490944** [comment]
现在应该是可以了吧？上面的朋友可以看一下这个https://www.jianshu.com/p/99aaf2e85432

**Comment by chengyifly** [comment]
> 现在应该是可以了吧？上面的朋友可以看一下这个https://www.jianshu.com/p/99aaf2e85432

赞👍
