### ISSUE TITLE
字典数组中又包含字典数组该怎么转？最后在顶层数组上用for循环实现了转换

### ISSUE THREAD

**Issue by xiaolongarm** [CoderMJLee/MJExtension#411]
@[
                           @{
                               @"name" : @"Jack",
                               @"icon" :      @[
                                                          @{
                                                      @"file" : @"ere",
                                                      @"number" : @"l214234",
                                                           },

```
                                                        @{
                                                            @"file" : @"fdgdf",
                                                            @"number" : @"68678",
                                                      }
                       ];
                           },

                       @{
                           @"name" : @"Rose",
                           @"icon" : @"nami.png",
                           }
                       ];
```

**Comment by wolfcon** [comment]
看例子
