### ISSUE TITLE
model -> dictionary ，  数据解析不能逆向？ 

### ISSUE THREAD

**Issue by dingfude2008** [CoderMJLee/MJExtension#412]
// 映射
- (id)mj_newValueFromOldValue:(id)oldValue property:(MJProperty *)property
  {
  if ([property.name isEqualToString:@"datetime"])
  {
      if (!oldValue) return @"";
      else{
          oldValue = [NSDate dateWithTimeIntervalSince1970:[oldValue longLongValue] / 1000];
      }
  }
  return oldValue;
  }

//return @{@“非关键字的属性名” : @“数组的key”};
- (NSDictionary *)replacedKeyFromPropertyName
  {
  return @{ @"datetime":@"datetimeValue"};
  }

拉去的json 中 datetimeValue 字段是个 时间戳，我本地存放的字段是  datetime， NSDate 类型，在 json -> model 时， 按照上面的方法可以解析成功，但是 model - > json 的时候，变成了 datetimeValue = "2016-06-23 05:19:09 +0000";,，   怎么解析成  时间戳呢 ？

**Comment by wolfcon** [comment]
建议你使用时间戳存储, 然后重新写一个方法转换为 Date, 另做他用
