### ISSUE TITLE
怎么实现多级映射

### ISSUE THREAD

**Issue by wwwying9** [CoderMJLee/MJExtension#414]
mj 老师!
在框架说明中有这么一句:
"Model name - JSON key mapping【模型中的属性名和字典中的key不相同(或者需要多级映射)】"
它的意识是说可以实现多级映射么?但是在使用的时候发现它能处理属性名和字典中的key不相同, 但是我想实现用同一个模型对应JOSN数据中的两个不同名字的字典. 例如: JOSN数据中有一个字典
 @{
                 @"date"   : @"星期一",
                 @"high"   : @"35",
} 
 还有另一个字典 
@{
                 @"date_1"   : @"星期一",
                 @"high_1"   : @"35",
} 
我想用同一个模型来保存这两个字典,于是定义了一个模型,里面有两个属性:
@property(nonatomic, strong) NSString *date;
@property(nonatomic, strong) NSString *high;
使用老师的框架后可以将第一个字典转换成模型.第二个字典无法转换.

再使用了下面的方法后: 
    [XXXX  mj_setupReplacedKeyFromPropertyName:^NSDictionary *{
        return @{
                 @"date"   : @"date_1",
                 @"high"   : @"high_1",
                 };
    }]; 
第一个字典将无法转换,第二个字典就可以转换了. 但这不是我想要的,我想将这两个不同的字典转换成同一个模型.不知道该框架可以实现多级映射么?

**Comment by CoderMJLee** [comment]
```objc
@"date" : @[@"date", @"date_1"]
```

**Comment by wwwying9** [comment]
thanks!

**Comment by yyhinbeijing** [comment]
Wonderful

**Comment by ripperhe** [comment]
Amazing!

**Comment by feihuang89** [comment]
It's too cool
