### ISSUE TITLE
解析key 为 HeWeather data service 3.0 这种类型的字典有问题

### ISSUE THREAD

**Issue by HOWIE-CH** [CoderMJLee/MJExtension#417]
解析key 为 HeWeather data service 3.0 这种类型的字典有问题，测试过了，把json字典里的HeWeather data service 3.0  ，字符串 去掉 3.0，改为HeWeather data service 就能转模型，望指教！
测试代码：https://github.com/CH-HOWIE/textExtension.git

**Comment by wolfcon** [comment]
因为 `.` 已经用在多级映射上了. 所以尽量避免使用 `.`
