### ISSUE TITLE
debug版本正常 release版本出现问题

### ISSUE THREAD

**Issue by keath90** [CoderMJLee/MJExtension#420]
我有一个模型A ，里面有一个属性名为"result",在接口返回数据中，result可能存在两种值（字典或者数组），所以我用了id类型来接数据（@property (nonatomic,assign) id result;），并且在.m文件中使用mj_objectClassInArray转换了。当result中是数组数据时，在debug版本下，转换正常，result被转换为数组，但是在release版本下，出现了问题，不能转换为数组，还是id类型

**Comment by wustzhy** [comment]
对的 , 我debug正常 ,release run 崩溃 返回model为nil , model中有字典数组. 求解!
