### ISSUE TITLE
方法找不到

### ISSUE THREAD

**Issue by LarionLee** [CoderMJLee/MJExtension#421]
使用pod将MJExtension导入到一个workspace下的子project里之后在该project里使用mj系列方法运行Carsh，错误信息是 [NSObject mj_objectWithKeyValues:]: unrecognized selector sent to class 0x10d1a2170

**Comment by cpg1234** [comment]
请问怎么解决了  我的也是，手动导入时没问题的

**Comment by woaiyouxi0803** [comment]
同手动导入没问题
