### ISSUE TITLE
[NSKeyedArchiver archivedDataWithRootObject] crash

### ISSUE THREAD

**Issue by bigParis** [CoderMJLee/MJExtension#423]
Thread 0 (crashed)
 0  CoreFoundation!__exceptionPreprocess + 0x7c
    Found by: given as instruction pointer in context
 1  libobjc.A.dylib!objc_exception_throw + 0x34
    Found by: previous frame's frame pointer
 2  CoreFoundation!-[NSException raise] + 0x8
    Found by: previous frame's frame pointer
 3  Foundation!-[NSObject(NSKeyValueCoding) valueForUndefinedKey:] + 0xf8
    Found by: previous frame's frame pointer
 4  Foundation!-[NSObject(NSKeyValueCoding) valueForKey:] + 0x100
    Found by: previous frame's frame pointer
 5  MakeFriends!-[MJProperty valueForObject:] [MJProperty.m : 79 + 0x10]
    Found by: previous frame's frame pointer
 6  MakeFriends!__32-[NSObject(MJCoding) mj_encode:]_block_invoke [NSObject+MJCoding.m : 28 + 0xc]
    Found by: previous frame's frame pointer
 7  MakeFriends!+[NSObject(Property) mj_enumerateProperties:] [NSObject+MJProperty.m : 143 + 0xc]
    Found by: previous frame's frame pointer
 8  MakeFriends!-[NSObject(MJCoding) mj_encode:] [NSObject+MJCoding.m : 23 + 0x20]
    Found by: previous frame's frame pointer
 9  Foundation!_encodeObject + 0x498
    Found by: previous frame's frame pointer
10  Foundation!-[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 0x1bc
    Found by: previous frame's frame pointer
11  Foundation!_encodeObject + 0x498
    Found by: previous frame's frame pointer
12  MakeFriends!__32-[NSObject(MJCoding) mj_encode:]_block_invoke [NSObject+MJCoding.m : 30 + 0x14]
    Found by: previous frame's frame pointer
13  MakeFriends!+[NSObject(Property) mj_enumerateProperties:] [NSObject+MJProperty.m : 143 + 0xc]
    Found by: previous frame's frame pointer
14  MakeFriends!-[NSObject(MJCoding) mj_encode:] [NSObject+MJCoding.m : 23 + 0x20]
    Found by: previous frame's frame pointer
15  Foundation!_encodeObject + 0x498
    Found by: previous frame's frame pointer
16  Foundation!+[NSKeyedArchiver archivedDataWithRootObject:] + 0xa8
    Found by: previous frame's frame pointer

this is callstack
when I use NSData *descData = [NSKeyedArchiver archivedDataWithRootObject:item.desc];
to save my data.
I got this exception:
Exception Name: NSUnknownKeyException
    Exception Reason: [ valueForUndefinedKey:]: this class is not key value coding-compliant for the key roomId.

but there is no roomId in my model.

**Comment by PandexLee** [comment]
我估计也是差不多的问题，下面是bugly统计的crash堆栈

0 libobjc.A.dylib	objc_retain + 9
1 OK记	-[MJProperty valueForObject:] (MJProperty.m:79)
2 OK记	__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:318)
3 OK记	+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
4 OK记	-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
5 OK记	-[KWSync getAllMedias:] (KWSync.m:342)
6 OK记	__13-[KWSync run]_block_invoke (KWSync.m:498)
7 libdispatch.dylib	__dispatch_call_block_and_release + 11
8 libdispatch.dylib	__dispatch_root_queue_drain + 1573
9 libdispatch.dylib	__dispatch_worker_thread3 + 95
10 libsystem_pthread.dylib	_pthread_wqthread + 1024

**Comment by hpsoar** [comment]
same problem, how did you solve this? @bigParis @PandexLee

**Comment by PandexLee** [comment]
@hpsoar I'm useing YYModel,it's good and tiny

**Comment by wolfcon** [comment]
#231
