### ISSUE TITLE
当一个模型中的属性为数组，后台接口返回json数据对应值为<null>，既然可以正常设置值

### ISSUE THREAD

**Issue by tuyuan2012** [CoderMJLee/MJExtension#429]
当一个模型中的属性为数组，后台接口返回数据json数据对应值为<null>，既然可以正常设置值，这种非有效数据最好做过滤处理。否则取出来后，调用相应方法会crash，谢谢！

**Comment by lishengbing** [comment]
这个一般会跟后台协商好，或者你可以做一次安全判断
