### ISSUE TITLE
子线程进行json解析时发生crash比较多

### ISSUE THREAD

**Issue by xiongzenghuidegithub** [CoderMJLee/MJExtension#432]
![snip20160721_3](https://cloud.githubusercontent.com/assets/15605196/17020047/263b43fc-4f72-11e6-9352-a017d0b9b7a1.png)

之前很少发生crash，但是最新将解析json的一些方法放到了子线程上，发生crash几率很大了。
问下，MJExtensions解析只能放在主线程吗？

如果与线程关系不大，那么导致频繁crash大致原因是哪一些方面，求解JM大神。。。

项目比较急，谢谢~~

**Comment by CoderMJLee** [comment]
在最新的3.0.12中已经解决，你更新试试哈

**Comment by xiongzenghuidegithub** [comment]
@implementation MJProperty

#pragma mark - 懒加载
- (NSMutableDictionary *)propertyKeysDict
{
    if (!_propertyKeysDict) {
        _propertyKeysDict = [NSMutableDictionary dictionary];
    }
    return _propertyKeysDict;
}

- (NSMutableDictionary *)objectClassInArrayDict
{
    if (!_objectClassInArrayDict) {
        _objectClassInArrayDict = [NSMutableDictionary dictionary];
    }
    return _objectClassInArrayDict;
}

#pragma mark - 缓存
+ (instancetype)cachedPropertyWithProperty:(objc_property_t)property
{
    MJProperty *propertyObj = objc_getAssociatedObject(self, property);
    if (propertyObj == nil) {
        propertyObj = [[self alloc] init];
        propertyObj.property = property;
        objc_setAssociatedObject(self, property, propertyObj, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    }
    return propertyObj;
}


这三段代码是否也需要多线程同步？

**Comment by xiongzenghuidegithub** [comment]
主要是问下，如果不加多线程同步，会导致MJProperty崩溃吗？

**Comment by xiongzenghuidegithub** [comment]
我用demo代码证实，多线程并发访问懒加载的缓存对象，是会产生崩溃的：

#import "MultithreadViewController.h"
#import <pthread.h>

//static pthread_mutex_t mutex;
//static dispatch_semaphore_t semaphore;

@interface MultithreadViewController ()
@property (nonatomic, strong) NSMutableDictionary *cache;
@property (nonatomic, strong) dispatch_queue_t serialQueue;
@end

@implementation MultithreadViewController

//- (void)setObject:(NSString *)obj forKey:(nonnull id<NSCopying>)aKey {
//    pthread_mutex_lock(&mutex);
//    if (!_cache) _cache = [NSMutableDictionary new];
//    [_cache setObject:obj forKey:aKey];
//    pthread_mutex_unlock(&mutex);
//}
//
//- (id)objectForkey:(NSString *)key {
//    pthread_mutex_lock(&mutex);
//    if (!_cache) _cache = [NSMutableDictionary new];
//    NSString *obj = [_cache objectForKey:key];
//    pthread_mutex_unlock(&mutex);
//    return obj;
//}

//- (void)setObject:(NSString *)obj forKey:(nonnull id<NSCopying>)aKey {
//    dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER);
//    if (!_cache) _cache = [NSMutableDictionary new];
//    [_cache setObject:obj forKey:aKey];
//    dispatch_semaphore_signal(semaphore);
//}
//
//- (id)objectForkey:(NSString *)key {
//    dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER);
//    if (!_cache) _cache = [NSMutableDictionary new];
//    NSString *obj = [_cache objectForKey:key];
//    dispatch_semaphore_signal(semaphore);
//    return obj;
//}

//- (void)setObject:(NSString *)obj forKey:(nonnull id<NSCopying>)aKey {
//    dispatch_async(_serialQueue, ^{
//        if (!_cache) _cache = [NSMutableDictionary new];
//        [_cache setObject:obj forKey:aKey];
//    });
//}
//
//- (id)objectForkey:(NSString *)key {
//    __block NSString *obj;
//    dispatch_sync(_serialQueue, ^{
//        if (!_cache) _cache = [NSMutableDictionary new];
//        obj = [_cache objectForKey:key];
//    });
//    return obj;
//}

- (NSMutableDictionary *)cache {
    if (!_cache) {
        _cache = [NSMutableDictionary new];
    }
    return _cache;
}

- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    dispatch_async(dispatch_get_global_queue(0, 0), ^{
        for (int i = 0; i < 1000; i++) {
//            [self setObject:@"1111" forKey:@"11111"];
//            NSLog(@"1111 = %@", [self objectForkey:@"1111"]);
            [self.cache setObject:@"111" forKey:@"111"];
        }
    });
    
    dispatch_async(dispatch_get_global_queue(0, 0), ^{
        for (int i = 0; i < 1000; i++) {
//            [self setObject:@"2222" forKey:@"2222"];
//            NSLog(@"1111 = %@", [self objectForkey:@"2222"]);
            [self.cache setObject:@"222" forKey:@"2222"];
        }
    });
    
    dispatch_async(dispatch_get_global_queue(0, 0), ^{
        for (int i = 0; i < 1000; i++) {
//            [self setObject:@"3333" forKey:@"3333"];
//            NSLog(@"1111 = %@", [self objectForkey:@"3333"]);
            [self.cache setObject:@"333" forKey:@"333"];
        }
    });
    
    dispatch_async(dispatch_get_global_queue(0, 0), ^{
        for (int i = 0; i < 1000; i++) {
//            [self setObject:@"4444" forKey:@"4444"];
//            NSLog(@"1111 = %@", [self objectForkey:@"4444"]);
            [self.cache setObject:@"4444" forKey:@"5555"];
        }
    });
    
    dispatch_async(dispatch_get_global_queue(0, 0), ^{
        for (int i = 0; i < 1000; i++) {
//            [self setObject:@"55555" forKey:@"55555"];
//            NSLog(@"1111 = %@", [self objectForkey:@"5555"]);
            [self.cache setObject:@"6666" forKey:@"6666"];
        }
    });
}

@end

也不是必蹦，只是崩溃的几率就比较大了，上一个线程使用的指针指向的对象已经废弃了，成为了一个野指针，最后objc_msgSend(指针，sel, 参数)就崩溃了，strong指针不会被自动赋值nil。

MJ大大，可以考虑把里面所有的缓存代码块，都加上同步，要不然在子线程崩溃的几率很大的。

**Comment by CoderYLZhang** [comment]
我在子线程转换缓存的对象也会几率蹦

**Comment by xiongzenghuidegithub** [comment]
恩是的，就是因为里面用的缓存字典对象，有一些地方没有多线程同步引起的
