### ISSUE TITLE
请问下老师如果我的字典数组里唯独有一个特殊的不是字典的元素（List是个数组）需要剔除再转模型，应该怎么做呢？

### ISSUE THREAD

**Issue by CoderYQ** [CoderMJLee/MJExtension#438]
```
    "details":[
        {
            "cate":{
                "detail_cate_id":0,
                "name":"衣物",
                "picture":""
            },
            "cate":{
                "detail_cate_id":0,
                "name":"食品",
                "picture":""
            },
            "cate":{
                "detail_cate_id":0,
                "name":"其他",
                "picture":""
            },
            "list":[
                    "reg_detail_id":"12",
                    "detail_id":"9",
                    "price":"20.0",
            ]
        }
    ],
```

**Comment by FrostBest** [comment]
这儿有点儿问题呢 字典里面为什么有一样的key
{
            "cate":{
                "detail_cate_id":0,
                "name":"衣物",
                "picture":""
            },
            "cate":{
                "detail_cate_id":0,
                "name":"食品",
                "picture":""
            },
            "cate":{
                "detail_cate_id":0,
                "name":"其他",
                "picture":""
            },
            "list":[
                    "reg_detail_id":"12",
                    "detail_id":"9",
                    "price":"20.0",
            ]
        }
