### ISSUE TITLE
NSObject+MJProperty 166行 过滤掉Foundation框架类里面的属性 最新版本有问题

### ISSUE THREAD

**Issue by Pijulin** [CoderMJLee/MJExtension#440]
hash
superclass
description
debugDescription

未过滤掉，在使用MJCoding与MJExtensionCodingImplementation的Model中，归档造成崩溃

**Comment by huipengo** [comment]
对的，我也遇到了，新版本有问题，还是用3.0.12版本好

**Comment by kinarob** [comment]
Fix via #665  #666
