### ISSUE TITLE
老师，能不能兼容一下swift的解析

### ISSUE THREAD

**Issue by lyx501135** [CoderMJLee/MJExtension#443]
李老师您好，您能不能做一下Swift版本的兼容，OC时代一直用MJExtension，目前MJExtension无法解析Swift中的Int Bool等类型的属性，我的模型中的整型 布尔属性必须是NSNumber才能解析，字符串不存在问题，NSString和String都可以解出来，谢谢

**Comment by BadReese** [comment]
same to you

**Comment by wolfcon** [comment]
`Int` 可以解析.
`Bool` 请使用 `NSNumber`

因为 `Objective-C` 跟 `Swift` 的 `Bool` 不通用. 没法 `@objc`
