### ISSUE TITLE
模型中的属性名和字典中的key映射问题

### ISSUE THREAD

**Issue by wonderffee** [CoderMJLee/MJExtension#45]
对于这个问题，readme里说的是单独调用setupReplacedKeyFromPropertyName:方法来实现，看了一下Example是放在MJExtensionConfig类里的load方法里调用，只会调用一次，实现很巧妙，但是还是有不足：映射与Model类分离。觉得把这个映射放在Model类里不是更好吗，比如放在Model类的+load方法中？或者用其它的函数？
如果方法可取建议更新readme

**Comment by wonderffee** [comment]
另外这个setupReplacedKeyFromPropertyName:方法好像是2.0.1版本里有的，1.2.1版本里没有？

**Comment by CoderMJLee** [comment]
提供了2种手段：
1.使用setupReplacedKeyFromPropertyName:，映射和Model分离了

**Comment by wonderffee** [comment]
觉得+replacedKeyFromPropertyName还好啊，又不需要引用MJExtension的头文件，哪里污染了模型？
觉得一分离的话，后人看以前的代码估计都有点摸不着头脑，不知道在哪里进行了映射

**Comment by CoderMJLee** [comment]
所以我提供了2种做法啊，哈哈。任你选择。
