### ISSUE TITLE
V3.0.13当一个对象实现了NSCoding协议之后，再用MJ字典模型转换会报错

### ISSUE THREAD

**Issue by huipengo** [CoderMJLee/MJExtension#450]
setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key description

**Comment by zhangfurun** [comment]
我也出现了这个问题  不知道明杰还有没有时间解决问题

**Comment by zhangfurun** [comment]
我现在是可以存档archivedDataWithRootObject,当时unarchiveObjectWithData的时候  会报错,错误提示和上面写的是一样的.提示的我的key都是写的relondy的属性,采用了一个这种的方案.
 @try {
            [property setValue:value forObject:self];
        } @catch (NSException *exception) {
        } @finally {
        }
目前为止,可以解决崩溃的问题

**Comment by wolfcon** [comment]
protocol 声明的属性记得 `@synthesize <#你在 Protocol 中声明的属性#>`
