### ISSUE TITLE
Swift中调用问题

### ISSUE THREAD

**Issue by hezongjiang** [CoderMJLee/MJExtension#451]
Swift中调用字典转模型（`public class func mj_objectArray(withKeyValuesArray keyValuesArray: AnyObject!) -> NSMutableArray!`）后，返回值是`NSMutableArray`，怎么转成自己需要的类型，例如`[ModelClass]`，求教！

**Comment by bybyhuang** [comment]
可以这样写 let array = RecommendArtisanModel.mj_objectArray(withKeyValuesArray: array).mutableCopy() as![RecommendArtisanModel]
