### ISSUE TITLE
这一种 字典类型无法正确解析.

### ISSUE THREAD

**Issue by tangzzz-fan** [CoderMJLee/MJExtension#454]
{
      "DistrictId": 2165,
      "NewPropCount": 8,
      "District": {
        "GScopeId": 2165,
        "GScopeCnName": "闵行区",
        "FullPY": "minxingqu",
        "FirstPY": "MXQ",
        "GScopeLevel": 2,
        "ParentId": 21,
        "lng": 121.400181,
        "lat": 31.116533
      },
      "GscopeEsts": [
        {
          "DistrictId": 216505,
          "NewPropCount": 1,
          "District": {
            "GScopeId": 216505,
            "GScopeCnName": "七宝",
            "FullPY": "qibao",
            "FirstPY": "QB",
            "GScopeLevel": 3,
            "ParentId": 2165,
            "lng": 121.361722,
            "lat": 31.152578
          },
          "GscopeEsts": []
        }
}

我已经调用                 mj_objectClassInArray 方法告诉框架:return @{@ 
          "GscopeEsts"":@"GscopeModel"}
GscopeModel 中对应的数据类型就是:
          {
            "GScopeId": 216505,
            "GScopeCnName": "七宝",
            "FullPY": "qibao",
            "FirstPY": "QB",
            "GScopeLevel": 3,
            "ParentId": 2165,
            "lng": 121.361722,
            "lat": 31.152578
          }

使用mj_objectClassInArray 解析出来的结果都是空值或者是0

**Comment by Coder-younghao** [comment]
"GscopeModel“对应的应该是”District“吧
