### ISSUE TITLE
实现 `debugDescription` 方法

### ISSUE THREAD

**Issue by iShawnWang** [CoderMJLee/MJExtension#455]
其它同类的第三方库都实现了 `description`方法, 方便调试, MJExtension 没有实现,是有什么特殊的考虑么... 比如性能 ? 
我再看看代码... 争取提 Pull Request

**Comment by iShawnWang** [comment]
刚刚看到 [issue 在控制台直接po model不能打印出内容,还要转换一次](https://github.com/CoderMJLee/MJExtension/issues/222),
但我用官方的 Demo 试了一下... 打印出下面的东西... 

````Objective-c

(lldb) po dog
< MJDog : 0x7f986ad06e70> : (
    "<MJProperty: 0x7f986ad082e0>",
    "<MJProperty: 0x7f986ad083a0>",
    "<MJProperty: 0x7f986ad01960>",
    "<MJProperty: 0x7f986ad08b40>",
    "<MJProperty: 0x7f986ad08d40>",
    "<MJPr

... ... 
```

**Comment by wolfcon** [comment]
`MJLogAllIvars` or `MJExtensionLogAllProperties` 都可以支持

新版本使用 `MJImplementDebugDescription` 这个更好一点 #675

**Comment by iShawnWang** [comment]
3 年了老铁 !!! 我都转前端两年了 !

**Comment by wolfcon** [comment]
我才经手. 我并不是 MJ 本人啊
