### ISSUE TITLE
二维数组转字典问题

### ISSUE THREAD

**Issue by kankaLiu** [CoderMJLee/MJExtension#456]
<h1>二维数组转换问题:
<p>
模型:A 字段NSString *b 字段 NSArray *c;
字段c为"二维数组"，c放置模型D，
模型A .m文件：
- (NSDictionary *)mj_objectClassInArray{<br>
    return @{<br>
                    @"c":[D class]<br>
                   }<br>
  }<br>
  字典转模型一切正常<br>
  但将该模型转字典时：<br>
  转换出来的字典为(控制台打印信息):<br>
  {<br>
   "b"="xxx",//该字段正常转换<br>
   "c"=(<br>
                (<br>
                     "<D: 0x7f9b32c9e340>",//即仍为模型对象没能转为字典<br>
                     "<D: 0x7f9b32c9e340>",//即仍为模型对象没能转为字典<br>
                     "<D: 0x7f9b32c9e340>",//即仍为模型对象没能转为字典<br>
                 ),<br>
                (<br>
                     "<D: 0x7f9b32c9e340>",//即仍为模型对象没能转为字典<br>
                     "<D: 0x7f9b32c9e340>",//即仍为模型对象没能转为字典<br>
                     "<D: 0x7f9b32c9e340>",//即仍为模型对象没能转为字典<br>
                 )<br>
           )<br>
  }<br>

ps(@"我花了十几分分钟来写清我遇到的问题，有空就回复我一下把，哪怕没能解决我的问题，啦啦啦啦。。。。。。。")

**Comment by wolfcon** [comment]
写个 demo 比这样描述清楚的多.
