### ISSUE TITLE
模型中有个数组属性，数组里面又要装着其他模型 

### ISSUE THREAD

**Issue by CoderiLife** [CoderMJLee/MJExtension#46]
在这种情况下，直接写
[StatusResult setupObjectClassInArray:^NSDictionary *{
        return @{
                 @"statuses" : @"Status",
                 @"ads" : @"Ad"
                 };
    }]; 是成功的；但是如果我在.m文件中写成
- (NSDictionary *)objectClassInArray{
    return @{
             @"statuses" : [Status class],
             @"ads" : [Ad class]
           }; 就失败了， 得到的status数据是字典形式的，而不是模型数据了。

**Comment by CoderMJLee** [comment]
不可能的哈，亲测可用。你可能写错方法类型了，是+开头的类方法哦，不是-开头的对象方法。
+ (NSDictionary *)objectClassInArray
