### ISSUE TITLE
转换成属性后值改变了

### ISSUE THREAD

**Issue by CoderYLZhang** [CoderMJLee/MJExtension#462]
原始值 json 的num 类型  725.19
转城模型属性后变成 725.19000000000001
用各种类型接收都试过了,string ,int,nsnumber 
都不行
求解

**Comment by tianglin** [comment]
同样遇到此问题，你是如何解决的

**Comment by tianglin** [comment]
@CoderYLZhang

**Comment by tianglin** [comment]
已经解决了。

方法① http://www.cocoachina.com/bbs/read.php?tid=196246

value是一个NSNumber对象

`double tmpDouble = [value doubleValue];
                    NSString *tmpStr = [NSString stringWithFormat:@"%lf", tmpDouble];
                    NSDecimalNumber *tmpNum = [NSDecimalNumber decimalNumberWithString:tmpStr];
                    value = [tmpNum stringValue];`

方法② http://blog.csdn.net/lizitao/article/details/49778227
`value = [NSString stringWithFormat:@"%g", [value doubleValue]];`

**Comment by CoderYLZhang** [comment]
我没解决, 后台直接传字符串过来了
