### ISSUE TITLE
Json数据中带有map结构的， 如：map<NSString *, NSArray<MyObject*> *>，有办法解析么？

### ISSUE THREAD

**Issue by ZengSir** [CoderMJLee/MJExtension#465]
下面这个是需要解析的json数据：
{"Value":true,"Detail":{"免费兑换":{"免费兑换":[{"ParentSortName":"免费兑换","SubSortName":"免费兑换"}]},"幸运抽奖":{"1元":[{"ParentSortName":"幸运抽奖","SubSortName":"1元"}],"免费":[{"ParentSortName":"幸运抽奖","SubSortName":"免费"}]}},"ErrorMessage":null,"OtherMessage":null}

格式化后如下：
<img width="422" alt="23b3f23c-83b1-41ce-990e-e13d43d2c69b" src="https://cloud.githubusercontent.com/assets/10495938/18335215/32740bb8-75b0-11e6-81d3-4a320e516f54.png">

求解析方法！！！

**Comment by PengChJ** [comment]
模型层层嵌套就行了

**Comment by ZengSir** [comment]
Detail里面的模型 的key 是中文， 而且是变化的。@PengChJ
