### ISSUE TITLE
如果模型1中有一个数组(数组里要求返回的是模型2数组) 但是模型1中的数组名与字典中的key不相同,怎么实现

### ISSUE THREAD

**Issue by Huan5** [CoderMJLee/MJExtension#469]
按照您给的方法,这样重写这两个方法不能实现(返回的数组里不是模型是字典)
- (NSDictionary *)mj_objectClassInArray{
  return @{@"dicArr": @"model2"};
  }

+(NSDictionary *)mj_replacedKeyFromPropertyName{
    return @{ @"modelArr" : @"dicArr"};
}

**Comment by mdjwanghong** [comment]
+ (NSDictionary *)mj_objectClassInArray
{
    return @{@"pics" : @"Pic"};
}
这样是可以的！

**Comment by Huan5** [comment]
想错了 我以为mj_objectClassInArray里面返回的key为Json里的数组名（而是自己定义的数组名）
