### ISSUE TITLE
请问MJ老师该类库是否支持MRC？

### ISSUE THREAD

**Issue by Lilacxyz** [CoderMJLee/MJExtension#47]
我在一个历史遗留的MRC的项目中使用MJExtension时，会在MJFoundation的+ (BOOL)isClassFromFoundation:(Class)c中crash掉，错误信息是：EXC_BAD_ACCESS(code=1, address=0x88180018)。请问是不支持MRC的项目么？或是在MRC的项目中需要注意什么问题呢？
谢谢MJ老师！

**Comment by CoderMJLee** [comment]
是的，不支持MRC。如果想在MRC中支持ARC，其中一种方法是：在Build Phases -> Compile Sources中给每一个MJExtension的.m文件增加一个Compiler Flags：-fobjc-arc。具体可以看看这篇文章：http://blog.csdn.net/q199109106q/article/details/8565403

**Comment by Lilacxyz** [comment]
好的，非常感谢！
