### ISSUE TITLE
3.0.13对象转字典会出现 superclass = NSObject;  debugDescription = "<MKProject: 0x12a2ea010>";等错误信息导致崩溃

### ISSUE THREAD

**Issue by programingHaozi** [CoderMJLee/MJExtension#470]
3.0.13对象转字典会出现 superclass = NSObject;  debugDescription = "<MKProject: 0x12a2ea010>";等错误信息导致崩溃

**Comment by programingHaozi** [comment]
{
   orderPartsListClassName = MKParts;

            partsTotalDiscountPrice = "65.00";

            partsTotalPrice = "65.00";

            projAmt = "93.00";

            superclass = NSObject;

            vId = 0;
}

出现这种转化

**Comment by wolfcon** [comment]
我也出现了这种情况

**Comment by kinarob** [comment]
@wolfcon 方便贴段代码出来看看吗？

**Comment by wolfcon** [comment]
@kinarob 已经提了PR

[https://github.com/CoderMJLee/MJExtension/pull/612](https://github.com/CoderMJLee/MJExtension/pull/612)
