### ISSUE TITLE
swift带有计算属性的类会转换出错

### ISSUE THREAD

**Issue by tkYan** [CoderMJLee/MJExtension#472]
我目前的工程中有个swift类拥有计算属性，使用这个库转成NSDictionary之后，再转回去会闪退。
调试发现，转成NSDictionary的时候会把计算属性也存入字典里，因此再转化类的时候，这个库会尝试给计算属性赋值，从而导致闪退。

**Comment by wolfcon** [comment]
ignore 掉相应的属性.
