### ISSUE TITLE
MJ老师，请问MJExtension可以把id这种int类型的直接转成NSString类型的吗？

### ISSUE THREAD

**Issue by Winzlee** [CoderMJLee/MJExtension#48]
MJ老师，请问MJExtension可以把id这种int类型的直接转成NSString类型的吗？能否针对id这种int类型的数据做一下特殊处理将其转成字符串类型的呢？

**Comment by CoderMJLee** [comment]
能贴一些具体代码么？我不太理解“id这种int类型”哈。sorry

**Comment by Winzlee** [comment]
MJ老师你好啊，您能在创业初期这么忙的时候回复我我真的是很高兴的，首先希望您的创业之路一帆风顺；第二关于您的这个框架我还不太会用，有个疑问就是比如我调服务器的一个接口，服务器传过来参数有userId字段，这个字段的类型是int的，那如果我用您的这个框架来转成model的话，那我在User类中定义userId的时候也必须定义成int类型的吗？如果定义成NSString可行否？

在 2015-05-13 10:12:12，"M了个J" <notifications@github.com> 写道：


能贴一些具体代码么？我不太理解“id这种int类型”哈。sorry

**Comment by CoderMJLee** [comment]
定义成int、NSNumber *、NSString *都可以

**Comment by Winzlee** [comment]
MJ老师，我在项目里把userId定义成了NSString类型的了，后台传过来的是int类型的，可是通过MJExtension转型之后转成了NSCFNumber的，您之前说id定义成NSString也行，可是为什么不能转成NSString的呢？

**Comment by CoderMJLee** [comment]
是可以的哈，我自己试过的。要不你写个有问题的Demo发来看看？

**Comment by Winzlee** [comment]
真是灰常的感谢您能为我传道授业解惑，对于这个问题，我下载了新的MJExtension框架，然后试了试转型完了就可以了，是打印看了一下是NSTaggedPointerString的了，可能我之前用的那个框架是很久以前的了，所以才会出现之前的那个问题，真是太感谢了O(∩_∩)O~~






在 2015-10-15 12:18:50，"M了个J" <notifications@github.com> 写道：


是可以的哈，我自己试过的。要不你写个有问题的Demo发来看看？

**Comment by CoderMJLee** [comment]
不客气
