### ISSUE TITLE
同一个类文件中同时声明了Parent 和 Son两个类，Parent类中有一个属性@property (nonatomic, strong) Son *son;通过  `[Parent mj_objectWithKeyValues:dict]` 解析失败，只能解析第一层

### ISSUE THREAD

**Issue by hanqingman** [CoderMJLee/MJExtension#489]
1. 解析如下：
   `
   NSDictionary *dict = @{
   @"son" : @{
       @"name" : @"Jack",
   },
   };
   [Parent mj_objectWithKeyValues:dict]
   `
   此时解析会失败，原因是在Parent.h文件中同时声明了Parent 和 Son两个类，通过  `[Parent mj_objectWithKeyValues:dict]` 只能解析第一层，默认son解析成了NSDictionary，只有把Son单独拉出来当成另外一个类文件，在Parent.h中`#import "Son.h"` 才可以成功解析。
2. 类文件如下：

```
@class Son;
@interface Parent : NSObject

@property (nonatomic, strong) Son *son;

@end

#pragma mark - son

@interface Son : NSObject

@property (nonatomic, copy) NSString *name;

@end
```

**Comment by hanqingman** [comment]
找到问题了，原因是个人代码的语法错误：
`Parent.m` 中缺少对Son类的实现
```
@implementation Parent
@end
```

`Parent.m`正确的写法：
```
@implementation Parent
@end

@implementation Son
@end
```
再次 [Parent mj_objectWithKeyValues:dict] 编译通过。

**Comment by skx926** [comment]
我也遇到这个问题了，😄感谢

**Comment by zhumi108** [comment]
给力啊,自己找了好久都没找到原因
