### ISSUE TITLE
JSON value is empty 

### ISSUE THREAD

**Issue by OllaAshour** [CoderMJLee/MJExtension#49]
Hi,

If a value in my JSON dictionary is an empty string, MJExtension fires an exception in  the class MJIVar in the method -  (void)setValue:(id)value forObject:(id)object. 

I thought if any value is an empty string, it will set the model property as empty string.

Thank you for your hard efforts.

**Comment by CoderMJLee** [comment]
Please try the lastest version.Thank you.

**Comment by OllaAshour** [comment]
Thanks alot.
