### ISSUE TITLE
property.srcClass未赋值就被使用了

### ISSUE THREAD

**Issue by maplelover** [CoderMJLee/MJExtension#491]
// 过滤掉Foundation框架类里面的属性
if ([MJFoundation isClassFromFoundation:property.srcClass]) continue;
property.srcClass = c;

只有这一处赋值，就是说isClassFromFoundation这条件无法成立

**Comment by wsxiaoluob** [comment]
mj_enumerateClasses遍历的时候已经去掉了Foundation框架里的类，
if ([MJFoundation isClassFromFoundation:c]) break;（NSObject+MSClass.m  65L）
所以
if ([MJFoundation isClassFromFoundation:property.srcClass]) continue;
这行代码应该是没有作用的。
如果有兼容性特殊用途或者应对一些偶现的bug这里也应该写上注释，没写注释应该就是单纯的无用代码了。
