### ISSUE TITLE
Collection <__NSArrayM: 0xb550c30> was mutated while being enumerated.-

### ISSUE THREAD

**Issue by yezhanxiang** [CoderMJLee/MJExtension#494]
您好，在上拉加载更多数据的时候，在还没加载完时快速点击其他数据，以下代码会出现标题的错误(NSObject+MJKeyValue.m):

    for (NSDictionary *keyValues in keyValuesArray) {
        if ([keyValues isKindOfClass:[NSArray class]]){
            [modelArray addObject:[self objectArrayWithKeyValuesArray:keyValues context:context error:error]];
        } else {
            id model = [self objectWithKeyValues:keyValues context:context error:error];
            if (model) [modelArray addObject:model];
        }
    }

我在网上找到的解决方法是改成block遍历，改完后发现不会出现这个crash了

**Comment by yezhanxiang** [comment]
这个问题困扰了我很久，经常有客户反馈APP浏览着商品列表就奔溃

**Comment by gongjl** [comment]
在keyValuesArray循环的过程中，在其他地方改变了，比如删除了内部对象
