### ISSUE TITLE
模型中有一个数组A，数组A里的元素又是一个数组a，数组a里才是模型，有办法解吗

### ISSUE THREAD

**Issue by ghost** [CoderMJLee/MJExtension#504]

**Comment by brucehelen** [comment]
可以的，在模型的+load方法中定义这个数组里面元素的类型，不管嵌套多少层都没问题。
`+ (void)load {
    [KMCourseDetailModel mj_setupObjectClassInArray:^NSDictionary *{
        return @{@"hole": @"NSString",
                 @"white": @"NSString"};
    }];
}`

KMCourseDetailModel是这个类的名称，hole和white是数组类型的字段，NSString可以是自定义模型

**Comment by Huang-Libo** [comment]
数组嵌套数组可以被自动被识别的，只要指定了自定义模型的 class 就行了。
