### ISSUE TITLE
线上APP崩溃问题!!

### ISSUE THREAD

**Issue by Toge66** [CoderMJLee/MJExtension#505]
@CoderMJLee 
# 线上的app在启动的时候崩溃，启动界面还没加载完就崩溃。此时会有网络数据的同步，网络数据返回会用到MJExtension模型转换。
![image](https://cloud.githubusercontent.com/assets/12079433/20560648/726a6258-b1b5-11e6-9938-a417cec4cb29.png)
![image](https://cloud.githubusercontent.com/assets/12079433/20560711/c6f973ea-b1b5-11e6-888c-d35c1ad36335.png)
![image](https://cloud.githubusercontent.com/assets/12079433/20560731/dd11c9b6-b1b5-11e6-896c-045fcbfeaa6e.png)
![image](https://cloud.githubusercontent.com/assets/12079433/20560748/e99e4600-b1b5-11e6-975a-79ae73bed38c.png)
![image](https://cloud.githubusercontent.com/assets/12079433/20560753/f4ea6b1a-b1b5-11e6-90b0-3b220d445b26.png)
![image](https://cloud.githubusercontent.com/assets/12079433/20560779/0afdc50a-b1b6-11e6-9a0e-1ca1636e5372.png)
![image](https://cloud.githubusercontent.com/assets/12079433/20560800/1c00a142-b1b6-11e6-903d-8c2ebfce62cf.png)
![image](https://cloud.githubusercontent.com/assets/12079433/20560805/25ab9c38-b1b6-11e6-8d0c-780eda415cac.png)

![image](https://cloud.githubusercontent.com/assets/12079433/20560829/48268408-b1b6-11e6-9466-4535cb729f15.png)
![image](https://cloud.githubusercontent.com/assets/12079433/20560845/5c5c3710-b1b6-11e6-87eb-d2ca72ed2676.png)
![image](https://cloud.githubusercontent.com/assets/12079433/20560915/ac8a5622-b1b6-11e6-846d-c7cb440c5aef.png)
![image](https://cloud.githubusercontent.com/assets/12079433/20560927/be64a97e-b1b6-11e6-913c-a4d4e99df9f3.png)
![image](https://cloud.githubusercontent.com/assets/12079433/20560941/cebedeb6-b1b6-11e6-96da-13284111bca6.png)
![image](https://cloud.githubusercontent.com/assets/12079433/20560946/d8275e24-b1b6-11e6-80ec-77ed3bd02c44.png)
![Uploading image.png…]()

**Comment by Toge66** [comment]
@CoderMJLee  怀疑是不是有线程安全问题

**Comment by tianzhihen521** [comment]
@Toge66  @CoderMJLee 
I met something similar to you.
And i resolved it like this:

`@synchronized (self) {
        self.propertyKeysDict[NSStringFromClass(c)] = propertyKeys;
    }`

**Comment by Cooooper** [comment]
新版本说解决多线程的问题，但是还是不够彻底，只是几率比以前低了很多。读取属性[NSObject(Property) properties]
[NSObject(Property) mj_setupReplacedKeyFromPropertyName:] 还是会出现 crash。

目前只能手动加 @synchronized (token){}
