### ISSUE TITLE
keyValues的类型为id和NSDictionary，混淆

### ISSUE THREAD

**Issue by wwwang89** [CoderMJLee/MJExtension#51]
方法：objectWithKeyValues:(NSDictionary *)keyValues error:(NSError *__autoreleasing *)error
方法二：objectWithKeyValues:(id)keyValues context:(NSManagedObjectContext *)context error:

MJ老师，对于keyValues的类型，，有的方法是写的NSDictionary，有的地方是id类型，二暴露在外边的是NSDictionary，，有时候传参是string等等，，虽然方法上面没有大问题，但是这样会不会造成用户的混淆，不统一？O(∩_∩)O谢谢

**Comment by CoderMJLee** [comment]
是我粗心了，统统改为id就好了，我已经改完了哈。
