### ISSUE TITLE
三级嵌套无法解析

### ISSUE THREAD

**Issue by lafayea** [CoderMJLee/MJExtension#510]
模型A嵌套模型B, 模型B又嵌套模型C, 无法解析这种情况:
@interface SDTrendLittleModel : NSObject
@property (nonatomic, copy) NSString *DrawNo;
@property (nonatomic, copy) NSString *SortedDrawed;
@property (nonatomic, copy) NSArray *Numbers;
@end

@interface SDTrendInsideModel : NSObject
@property (nonatomic, copy) NSArray <__kindof SDTrendLittleModel*>*NumberMissingList;
@property (nonatomic, copy) NSArray *MaxNumberAppear;
@property (nonatomic, copy) NSArray *MaxNumberMissing;
@property (nonatomic, copy) NSArray *MaxNumberContinueAppear;
@end

@interface SDTendElevenModel : NSObject
@property (nonatomic, copy) NSArray <__kindof SDTrendInsideModel*>*NumberMissingFirst;
@property (nonatomic, copy) NSArray <__kindof SDTrendInsideModel*>*NumberMissingSecond;
@property (nonatomic, copy) NSArray <__kindof SDTrendInsideModel*>*NumberMissingThird;
@end

**Comment by wxpasta** [comment]
+ (NSDictionary *)mj_objectClassInArray
{
    return @{@"retData" : [BJRetData class]};
}

**Comment by fengxuelei** [comment]
城市三级列表数据model 咋解析啊?
