### ISSUE TITLE
一个bug：当一个model要同时需要替换某些字段和转驼峰的时候，替换字段不成功

### ISSUE THREAD

**Issue by Steven-Yung** [CoderMJLee/MJExtension#513]
我有一个model，需要把API返回的id字段替换成ID，同时API的其他字段都是有下划线的，我需要把他们转成驼峰，可是我发现，一旦把`mj_replacedKeyFromPropertyName`和`mj_replacedKeyFromPropertyName121`用在一起，`mj_replacedKeyFromPropertyName`就失效了，结果是并没有id替换成ID。这里是具体代码：
API：

> {
> 	id = 16;
> 	autograph = "grap";
> 	area = 广东省 深圳市;
> 	reward_sum = 0;
> 	guard_numbers = 0;
> 	portrait = http://192.168.1.180/Flag/Uploads/Flag/User/5853a22e76522.jpg;
> 	username = 13800138000;
> 	nickname = n;
> 	target_nums = 0;
> 	gender = 0;
> }

Model.h:
```
#import <MJExtension.h>
@interface Model : NSObject

@property (copy, nonatomic) NSString *ID;
@property (copy, nonatomic) NSString *portrait;
@property (copy, nonatomic) NSString *nickname;
@property (copy, nonatomic) NSString *autograph;
@property (copy, nonatomic) NSString *guardNumbers;
@property (copy, nonatomic) NSString *targetNums;
@property (copy, nonatomic) NSString *rewardSum;
@property (copy, nonatomic) NSString *area;
@property (copy, nonatomic) NSString *gender;
@end
```
Model.m
```
#import "UserModel.h"
@implementation UserModel

+ (NSDictionary *)mj_replacedKeyFromPropertyName {
    return @{@"ID": @"id"};
}
+ (NSString *)mj_replacedKeyFromPropertyName121:(NSString *)propertyName {
    return [propertyName mj_underlineFromCamel];
}
@end
```
结果用`UserModel *user = [UserModel mj_objectWithKeyValues:data];`
输出结果是user.ID = nil

**Comment by Steven-Yung** [comment]
伤心，怎么没回答我的问题？？？？~~~~(>_<)~~~~

**Comment by PeiLongfei** [comment]
我也遇到类似的问题了, 既要转驼峰命名, 同时又要多级映射, 这种情况不知怎么办

**Comment by dongdong3344** [comment]
怎么解决的啊 ？我也遇到了这样的问题

**Comment by dongdong3344** [comment]
@PeiLongfei  
MJ： 1个key在执行mj_replacedKeyFromPropertyName121方法的时候已经经过mj_underlineFromCamel方法返回具体值，不会再执行mj_replacedKeyFromPropertyName方法。
可以将mj_replacedKeyFromPropertyName的内容写到mj_replacedKeyFromPropertyName121的，合二为一。

如下：
- (NSString *)mj_replacedKeyFromPropertyName121:(NSString *)propertyName
{
    if ([propertyName isEqualToString:@"ID"]) return @"id";
    return [propertyName mj_underlineFromCamel];
}

**Comment by YannChee** [comment]
我的项目也遇到这个bug,同时替换id 和 description字段 ,下划线转驼峰时,驼峰属性值始终 nil
