### ISSUE TITLE
+[NSObject encodeWithCoder:]: unrecognized selector sent to class 0x115156170

### ISSUE THREAD

**Issue by AshleyZCQ** [CoderMJLee/MJExtension#514]
+[NSObject encodeWithCoder:]: unrecognized selector sent to class 0x115156170 
1.问题一  当我使用sourcetree重新podinstall一份新的代码之后就会崩溃到上边的方法中 之前是没有问题的 当时的版本是3.0.10
2.问题二 当我将cocoapods里面的MJExtension更新到最新的3.0.13之后发现没有崩溃 可以正常使用，但是解决了这个问题的几个小时之后 没有动任何东西 再次运行 又会崩溃到此方法中

**Comment by loyalwind** [comment]
我今天也遇到这种情况了，主要是进行归档的模型遵守了自定义的一个协议(且这个协议遵守 NSObject 协议)，然后就会出现这个问题，希望 MJ老师可以帮忙解决。

**Comment by AshleyZCQ** [comment]
我的解决了 你用的是cocoapods吗

**Comment by loyalwind** [comment]
不是，是拖进去的

发自我的 iPhone 6s

**Comment by AshleyZCQ** [comment]
我清空了缓存 然后就可以了 你加我Q912031922没准可以帮你解决

**Comment by loyalwind** [comment]
应该是框架存在的bug，因为我为了验证我的猜想，我单独创建一个新的工程，如果我的模型遵守某个自己的协议（且该协议继承NSOject协议，如果该协议不继承NSOject协议，其实没问题），用框架进行归档模型时会你这个报错。另外如果协议有下面方法时在进行解档时就会出现另外一种错误、
@property (nonatomic, copy,readonly) NSString *todayEndTime;

发自我的 iPhone 6s

**Comment by kinarob** [comment]
Fix via #665 #666
