### ISSUE TITLE
启动的时候崩溃特别多cachedTypeWithCode第一次缓存数据类型的时候，偶现

### ISSUE THREAD

**Issue by MikeZhangpy** [CoderMJLee/MJExtension#518]
崩溃线程如下：
libobjc.A.dylib    0x1800b9bd0    _objc_msgSend + 16
CoreFoundation    0x180924c8c    -[__NSDictionaryM setObject:forKey:] + 360
MStore    0x100769454    +[MJPropertyType cachedTypeWithCode:] (MJPropertyType.m:30)
MStore    0x100768508    -[MJProperty setProperty:] (MJProperty.m:70)
MStore    0x1007683b4    +[MJProperty cachedPropertyWithProperty:] (MJProperty.m:45)
MStore    0x10076f318    ___32+[NSObject(Property) properties]_block_invoke (NSObject+MJProperty.m:163)
MStore    0x10076a180    +[NSObject(MJClass) mj_enumerateClasses:] (NSObject+MJClass.m:61)
MStore    0x10076f04c    +[NSObject(Property) properties] (NSObject+MJProperty.m:181)
MStore    0x10076ee50    +[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:138)
MStore    0x10076b088    -[NSObject(MJKeyValue) mj_setKeyValues:context:] (NSObject+MJKeyValue.m:199)
MStore    0x10076bef0    +[NSObject(MJKeyValue) mj_objectWithKeyValues:context:] (NSObject+MJKeyValue.m:223)
MStore    0x10019a888    -[MSConfigurationDataManager cacheConfigDataWithData:] (MSConfigurationDataManager.m:167)
MStore    0x10019a7ec    -[MSConfigurationDataManager parseData:userInfo:] (MSConfigurationDataManager.m:160)
MStore    0x10038ba64    -[MFDataParsers parsedResultWithRequestType:parsedInfo:userInfo:] (MFDataParsers.m:163)
MStore    0x10038af34    -[MFDataParsers parseResponseObject:requestType:userInfo:] (MFDataParsers.m:63)
MStore    0x100897dec    -[MFRequest requestFinished:] (MFRequest.m:364)
MStore    0x10088af78    -[ASIHTTPRequest reportFinished] (ASIHTTPRequest.m:2041)

**Comment by MikeZhangpy** [comment]
多线程引起的crash，更新到3.0.13问题修复

**Comment by JiangWenjia** [comment]
我更新到了3.0.13还是有遇到这个问题，偶发的，启动的时候多

**Comment by wolfcon** [comment]
**Update [`3.2.4`](https://github.com/CoderMJLee/MJExtension/releases/tag/3.2.4) ASAP.**
