### ISSUE TITLE
ReadME 想帮忙改进一下 不知可否？

### ISSUE THREAD

**Issue by LawrenceHan** [CoderMJLee/MJExtension#52]
顺便赞一下，第一次见到这么厉害的中国Repo :laughing:

**Comment by CoderMJLee** [comment]
可以的，3Q，谢谢认可。之前也有朋友帮忙改了README，欢迎欢迎哈

**Comment by CoderMJLee** [comment]
我为MJExtension增加了2个大功能哈，有空的话，希望能帮我修改下MD文件，把这2个新功能写上去，谢谢。我因为创业忙哈，没时间去添加。具体是哪2个新功能，可以看看Demo，谢谢啦
