### ISSUE TITLE
 @[@"debugDescription", @"description", @"hash", @"superclass"] 建议这个最好去掉，要不然有些转换会蹦

### ISSUE THREAD

**Issue by choiceyou** [CoderMJLee/MJExtension#525]
// iOS8以前dic会加上这几个不用的键值 @[@"debugDescription", @"description", @"hash", @"superclass"]

[keyValues removeObjectsForKeys:@[@"debugDescription", @"description", @"hash", @"superclass"]];

建议这个最好去掉，要不然有些转换会蹦

**Comment by jxzy999** [comment]
我也是遇到这个问题，自己在每一层模型里都加上mj_ignoredPropertyNames  ，才解决，希望能统一处理

**Comment by samzhiwei** [comment]
遇到同样的问题。关注改动

**Comment by wonderffee** [comment]
妈蛋，我也遇到这个问题了，报错：setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key hash.
好一顿问题定位
暂时在model里添加下面的代码解决了：
+ (NSArray *)mj_ignoredCodingPropertyNames{
    return @[@"debugDescription", @"description", @"hash", @"superclass"];
}

**Comment by wolfcon** [comment]
[https://github.com/CoderMJLee/MJExtension/pull/612](https://github.com/CoderMJLee/MJExtension/pull/612)这个 PR 已经修复了这个问题, 但是小马哥貌似很忙, 没时间管
