### ISSUE TITLE
id转ID问题

### ISSUE THREAD

**Issue by al1020119** [CoderMJLee/MJExtension#526]
在+ (void)load 中实现了这个，但是发展转模型的时候，拿到的ID是空的，返回的数据里面是有id这是字段的
    
#pragma mark 如果使用NSObject来调用这些方法，代表所有继承自NSObject的类都会生效
#pragma mark NSObject中的ID属性对应着字典中的id
    [NSObject mj_setupReplacedKeyFromPropertyName:^NSDictionary *{
        return @{
                 @"ID" : @"id"
                 };
    }];

**Comment by yischool611** [comment]
我也遇到这个问题了
在MJExtensionConfig中使用的mj_setupReplacedKeyFromPropertyName更改ID不起作用，mj_setupReplacedKeyFromPropertyName121起作用了

**Comment by dongdong3344** [comment]
@yischool611  你的问题是问题是如何解决的啊?
我在模型.m文件里使用mj_setupReplacedKeyFromPropertyName方法，将ID替代id,但是字典转模型时明月起作用。ID值为空。
