### ISSUE TITLE
关于属性名换为其他key去字典中取值问题

### ISSUE THREAD

**Issue by Jifeng2015** [CoderMJLee/MJExtension#529]
我一个这样的需求：
model底下有image_path属性，但是返回数据有时是image_path，有时是goods_cover，我又不想多加一个数据，然后我就这样处理：
+ (NSDictionary *)mj_replacedKeyFromPropertyName{
    return @{@"image_path":@"goods_cover"};
}
或
+ (NSDictionary *)mj_replacedKeyFromPropertyName{
    return @{@"image_path":@"goods_cover",@"image_path":@"image_path"};
}

问题：当返回的数据是goods_cover 时，用image_path可以取到值；但是，当返回的数据是image_path 时，用image_path却取不到值。
这个问题这么处理？

**Comment by anyuhao** [comment]
你应该变为数组
return @{@"image_path":@[@"goods_cover",@"image_path":@"image_path"]};

**Comment by Jifeng2015** [comment]
非常感谢，可以了！！！
