### ISSUE TITLE
objectArrayWithKeyValuesArray返回类型

### ISSUE THREAD

**Issue by wanyakun** [CoderMJLee/MJExtension#53]
+ (NSArray *)objectArrayWithKeyValuesArray:(NSArray *)keyValuesArray error:(NSError *__autoreleasing *)error

内部实现返回的是NSMutableArray，那么返回类型为什么不写成NSMutableArray？

**Comment by CoderMJLee** [comment]
写成NSMutableArray也可以，但是没有必要哈，外界只需要知道返回了个数组就OK

**Comment by wanyakun** [comment]
是什么类型就返回什么类型吧，指针其实还是个NSMutableArray，不然外界需要NSMutableArray类的时候，还需要进行显示转换，如果外界是NSArray也可以很方便使用。严谨一点没什么不好。

**Comment by CoderMJLee** [comment]
我的对外接口设计就是NSArray哈，内部用什么并不要紧，外界是不用关心的

**Comment by wanyakun** [comment]
外部使用可能是NSMutableArray也可能是NSArray，如果外部是NSMutableArray，对返回类型还需要显示转换。若方法返回NSMutableArray，外部使用NSMutableArray和NSArray都不用显示转换了。

**Comment by wanyakun** [comment]
如果不显示转换会有警告

**Comment by zhangao0086** [comment]
这个不是返回类型的问题，接口设计需要尽量抽象，外部也不应该对内部实现有所依赖，你如果需要 MutableArray，应该总是调用 mutableCopy

**Comment by CoderMJLee** [comment]
哈哈哈，我觉得这个争论下去没有意义哈。每个人都有自己的看法和设计思路。
