### ISSUE TITLE
如何将对象中的属性设置成另一个对象的属性

### ISSUE THREAD

**Issue by Huanhoo** [CoderMJLee/MJExtension#540]
小码哥，我想请教个问题；
我现在有一个对象是通过 mj 将本地 plist 文件转换成了模型，但是模型中有几个属性我想替换成另一个对象中的属性，例如：

{
key1 = 1,
key2 = YES
},
{
key1 = 2,
key2 = NO
}

现在我希望在key1 = 1时，将key2的value换成另一个对象的值，这个要怎么做？

原本我看- (id)mj_newValueFromOldValue:(id)oldValue property:(MJProperty *)property;函数可以做这个事，但是我如何能在进入这个回调之前，把另一个对象传到这个模型中呢？因为mj的模型转换都是类方法，所以无法将其他的实例对象传进来。

**Comment by wolfcon** [comment]
在解析完后, 自己做检查替换或者, 写另外一个 get 方法. 做判断.
