### ISSUE TITLE
关于解决32位BOOL类型转换json后成Int类型的问题

### ISSUE THREAD

**Issue by iOnRoad** [CoderMJLee/MJExtension#545]
在使用MJExtension时，发现BOOL属性在转换JSON后，在32位机器上出现转换成Int类型的问题。经查找，问题出现在MJProperty类的valueForObject方法，我尝试修改如下，即达到正确转换的目的。
还请能够更新一下源码。

- (id)valueForObject:(id)object
{
    if (self.type.KVCDisabled) return [NSNull null];
    id value = [object valueForKey:self.name];
    if(self.type.isBoolType){
        value = @([(NSNumber *)value boolValue]);
    }
    return value;
}

**Comment by yaoliangjun** [comment]
我也遇到同样的问题了，以上代码可以解决，多谢！

**Comment by tianliangyihou** [comment]
我也遇到同样的问题了，以上代码可以解决

**Comment by zhoumingwu** [comment]
以上代码完美解决

**Comment by luojianzhen** [comment]
完美！！！

**Comment by iOnRoad** [comment]
@CoderMJLee 以上解决办法是否可以采纳，目前是放到项目里。您更新之后，我们可以使用cocoapods来管理。

**Comment by wolfcon** [comment]
#687 你们测试一下, 我这里手边没有 32 位设备了.

**Comment by jiasongs** [comment]
@wolfcon 某些mac catalyst版本上，也会出现此问题，建议再加上TARGET_OS_MACCATALYST条件
