### ISSUE TITLE
字典转模型，字典中含有一个简单的字符串数组，

### ISSUE THREAD

**Issue by shafujiu** [CoderMJLee/MJExtension#555]
用简单的mj_setKeyValues是不行的，数组属性是拿不到值。
如果将数组当成包含的模型数组来处理  对应的class 就为NSString 这样也是不行的。
{
	VERIFYSTATE : -79228162514264337593543950335,
	PUBLISHTIME : 2017-08-06,
	REMARK : <null>,
	ID : 66,
	VERIFYDATE : <null>,
	BEGINTIME : 2017-08-06,
	ENDTIME : 2018-08-06,
	CONTACT : 沉约,
	VERIFYUSER : -2147483648,
	PHOTO : [http://192.168.155.111:80/ModileProtal/Images/CE972C73-C321-4EC9-B1F1-5E7D3758C6B22017-08-06-11-40-23-984-4.jpg],
	ADDRESS : 大方的撒,
	MASTER : 沉约,
	PHONE : 18312547858,
	USERID : -2147483648,
	AREA : 100
}
字典是这样的，其中PHOTO是数组，请指点  感激不尽

**Comment by aloow** [comment]
这个问题没有解决吗

**Comment by wolfcon** [comment]
这个都 17 年的 issue 了.  你有遇到这个问题吗?@aloow

**Comment by aloow** [comment]
> 这个都 17 年的 issue 了. 你有遇到这个问题吗?@aloow

在特定情况下，转不了字符串数组，一般是可以的，我已经解决了，谢谢

**Comment by wolfcon** [comment]
什么特定情况下? 可以添加一个 testcase
