### ISSUE TITLE
MJ老师您好，以前json属性如果出现null时，模型都能正常转换成@""，今天发现没转换

### ISSUE THREAD

**Issue by SuperDannyBoy** [CoderMJLee/MJExtension#556]
具体json如下：
`{
        "CommunityID": 6,
        "ActivityURL": null,
        "CommunityIntroduction": null,
        "ActivityContent": "<img alt=\"\" src=\"http://192.168.254.10:64414/PhonePicture/20170814/20170814152019/big/2017081415201963322.png\" style=\"height:800px; width:1000px\" /><br />\n瘦子多吃点<br />\n<img alt=\"\" src=\"http://192.168.254.10:64414/PhonePicture/20170814/20170814152204/big/2017081415220482671.jpg\" style=\"height:148px; width:200px\" />\n<h1><strong>胖子少吃点</strong></h1>\n"
}`

其中的ActivityURL、CommunityIntroduction两个字段转模型之后值变为nil

希望老师能够帮忙解答，谢谢！

**Comment by wolfcon** [comment]
理应如此吧? null 换成 @"" 才是不对应转换
