### ISSUE TITLE
杰哥，一个文件中定义了两个类，字典转模型有一个转不出来

### ISSUE THREAD

**Issue by kingloveyy** [CoderMJLee/MJExtension#56]
![qq20150511-1 2x](https://cloud.githubusercontent.com/assets/3993714/7557909/f7ab8780-f7cb-11e4-88f2-d0203e6baa41.png)

杰哥，一个文件中定义了两个类，字典转模型有一个转不出来，其中SKLocation这个类中还是字典

**Comment by CoderMJLee** [comment]
你试过NSLog(@"%@", [address.location class]);么？

**Comment by kingloveyy** [comment]
显示的是一个字典

**Comment by CoderMJLee** [comment]
能否发个代码到邮箱？感觉有点诡异，哈哈

**Comment by kingloveyy** [comment]
嗯，已发QQ

**Comment by CoderMJLee** [comment]
应该是没有写SKLocation类的实现哈
```objc
@implementation SKLocation 

@end
```
