### ISSUE TITLE
模型转字典 crash

### ISSUE THREAD

**Issue by xingze0308** [CoderMJLee/MJExtension#561]
![7de40ee6-ff40-4ddd-8f8c-f871368a1b75](https://user-images.githubusercontent.com/16461294/30022159-bc211f5a-919c-11e7-9c60-6ed356d9bd37.png)

**Comment by WXXXXH** [comment]
同样的问题 ，求解决啊
![b5898c6a2da471d90dc1e4f38e1b8fc0](https://user-images.githubusercontent.com/35984644/35604562-bcfda1ea-067d-11e8-96c5-a81c29d67594.jpg)

**Comment by wolfcon** [comment]
#660 已经修复
