### ISSUE TITLE
swift Bool怎么处理？

### ISSUE THREAD

**Issue by disenr** [CoderMJLee/MJExtension#565]
swift Bool?型，现在有没有好的解决方案呢

**Comment by disenr** [comment]
我现在暂时NSNumber去代替使用，不知道后面会不会有什么问题

**Comment by wolfcon** [comment]
你也只能通过 `NSNumber` 去代替. 因为 `Swift` `Bool` 类型是不能桥接到 `Objective-C` 这边的
