### ISSUE TITLE
SEGV_ACCERR mall +[NSObject(Property) properties] (NSObject+MJProperty.m:)

### ISSUE THREAD

**Issue by jashion** [CoderMJLee/MJExtension#566]
<img width="745" alt="2017-10-18 6 00 58" src="https://user-images.githubusercontent.com/9104433/31712676-5e1efc82-b3c1-11e7-9fc5-85ad1d0771cd.png">

传进入的数据是一个字典，不为nil。

**Comment by zhzDeveloper** [comment]
NSObject 的 property 分类中的 dictForKey:方法 被  NSObject+MJClass.h的覆盖了, 返回类型不一样, 导致crash

**Comment by kinarob** [comment]
@jashion 新版本已经修复线程安全的问题。
