### ISSUE TITLE
方法冲突

### ISSUE THREAD

**Issue by taifengliu** [CoderMJLee/MJExtension#568]
[LYList mj_setupReplacedKeyFromPropertyName:^NSDictionary *{
            return @{
                     @"idField" : @"id"
                     };
        }];

 [LYList mj_setupReplacedKeyFromPropertyName121:^NSString *(NSString *propertyName) {
            return [propertyName mj_underlineFromCamel];
        }];

同时使用这个两个方法，发现idField为nil!

**Comment by CoderMJLee** [comment]
```objc
[LYList mj_setupReplacedKeyFromPropertyName121:^NSString *(NSString *propertyName) {
if ([propertyName isEqualToString:@"idField"]) return @"id";
return [propertyName mj_underlineFromCamel];
}];
```

**Comment by CustomPBWaters** [comment]
-

**Comment by taifengliu** [comment]
非常感谢！！！
