### ISSUE TITLE
关于Json数据里面包含Json字符串

### ISSUE THREAD

**Issue by Margin915** [CoderMJLee/MJExtension#569]
{
    "attach" : "Attach",
    "method" : "POST",
    "data" : "{\"attach\":\"Attach\",\"method\":\"POST\",\"status\":\"200\",\"message\":\"message\"}",
    "status" : 200,
    "message" : "message"
}
如果是这种数据，想转换成字典，data对应的数据无法转换，现在我的做法是单独判断data数据，取出来强制再转换一次

**Comment by wolfcon** [comment]
你做的没问题
