### ISSUE TITLE
请问为何我model定义的是nsnumber,接受下来之后精度缺损失了，用decimal也不行。

### ISSUE THREAD

**Issue by hatjs880328** [CoderMJLee/MJExtension#572]
9.7 就变成了9.68888888

这个问题有处理吗、 按理说用decimal接受是没有问题的啊。

**Comment by hatjs880328** [comment]
后台API 传输的是 double类型，前台model是 String类型，这种转换更不应该出现精度损失吧？

**Comment by wolfcon** [comment]
[https://stackoverflow.com/questions/2816212/nsnumber-floatvalue-not-equal-to-nsnumber-value](https://stackoverflow.com/questions/2816212/nsnumber-floatvalue-not-equal-to-nsnumber-value)

#616
