### ISSUE TITLE
JSON -> CoreData ManagedObject 问题

### ISSUE THREAD

**Issue by BadReese** [CoderMJLee/MJExtension#579]
请问用
`mj_object(withKeyValues: keyValues, context: NSManagedObjectContext.mr_default())`
转换得到的object会因为调用
`NSManagedObjectContext.mr_default().mr_saveToPersistentStoreAndWait()`
而导致被存储到本地数据库么？
如果会，如何避免被存下来？

**Comment by BadReese** [comment]
我的问题很难么

**Comment by wolfcon** [comment]
你只要不 save 就可以了啊
