### ISSUE TITLE
MJProperty setPorpertyKeys: 方法会出错

### ISSUE THREAD

**Issue by jueying-xiangfeng** [CoderMJLee/MJExtension#580]
/** 对应着字典中的多级key */
- (void)setPorpertyKeys:(NSArray *)propertyKeys forClass:(Class)c
{
    if (propertyKeys.count == 0) return;
    self.propertyKeysDict[NSStringFromClass(c)] = propertyKeys;
}
方法的字典赋值self.propertyKeysDict[NSStringFromClass(c)] = propertyKeys会crash，请问是class为空导致的吗?

**Comment by CoderMJLee** [comment]
可以贴出你使用MJExtension的代码么

**Comment by jueying-xiangfeng** [comment]
您好  这是调用的用法 :
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
		int respCode = 0;
		bool exeResult = NO;

		NSDictionary * dict = [HttpUtil httpGet:url headers:nil parameter:nil responseCode:&respCode];

		HedoneAppAdResponse * responseData;
		if (VALIDATE_HTTPSTATUS_CODE(respCode)) {
			exeResult = YES;
			responseData = [HedoneAppAdResponse mj_objectWithKeyValues:dict];
		}

		dispatch_async(dispatch_get_main_queue(), ^{
			if(progress){
				[progress hide:YES];
			}
			completion(exeResult, responseData);
		});
	});

这是 HedoneAppAdResponse 的定义
#pragma mark - HedoneAppAdResponse
@interface HedoneAppAdResponse:NSObject
@property (nonatomic, strong) NSArray * ads;
@property (nonatomic, assign) int status;
@property (nonatomic, assign) long long when;
@end

@implementation HedoneAppAdResponse
@synthesize status;
@synthesize when;

+ (NSDictionary *)mj_objectClassInArray{
	return @{@"ads":[HedoneAdRoute class]};
}

@end

#pragma mark - HedoneAdRoute
@interface HedoneAdRoute:NSObject
@property (nonatomic, copy) NSString * picture;
@property (nonatomic, copy) NSString * route;
@property (nonatomic, assign) int tipType;
@property (nonatomic, copy) NSString * displayText;
@property (nonatomic, strong) HedoneFormatText * formatText;
@end

@implementation HedoneAdRoute
@synthesize picture;
@synthesize route;
@synthesize tipType;
@synthesize displayText;
@synthesize formatText;
@end

#pragma mark - HedoneFormatText
@interface HedoneFormatText:NSObject
@property (nonatomic, copy) NSString * content;
@property (nonatomic, strong) NSArray * args;
@end

@implementation HedoneFormatText
@synthesize content;

+ (NSDictionary *)mj_objectClassInArray{
	return @{@"args":[HedoneFormatArg class]};
}

@end

#pragma mark - HedoneFormatArg
@interface HedoneFormatArg:NSObject
@property (nonatomic, copy) NSString * str;
@property (nonatomic, copy) NSString * color;
@end

@implementation HedoneFormatArg
@synthesize str;
@synthesize color;
@end

**Comment by jueying-xiangfeng** [comment]
@CoderMJLee 
您好  这是调用的用法 :
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
		int respCode = 0;
		bool exeResult = NO;

		NSDictionary * dict = [HttpUtil httpGet:url headers:nil parameter:nil responseCode:&respCode];

		HedoneAppAdResponse * responseData;
		if (VALIDATE_HTTPSTATUS_CODE(respCode)) {
			exeResult = YES;
			responseData = [HedoneAppAdResponse mj_objectWithKeyValues:dict];
		}

		dispatch_async(dispatch_get_main_queue(), ^{
			if(progress){
				[progress hide:YES];
			}
			completion(exeResult, responseData);
		});
	});

这是 HedoneAppAdResponse 的定义
#pragma mark - HedoneAppAdResponse
@interface HedoneAppAdResponse:NSObject
@property (nonatomic, strong) NSArray * ads;
@property (nonatomic, assign) int status;
@property (nonatomic, assign) long long when;
@end

@implementation HedoneAppAdResponse
@synthesize status;
@synthesize when;

+ (NSDictionary *)mj_objectClassInArray{
	return @{@"ads":[HedoneAdRoute class]};
}

@end

#pragma mark - HedoneAdRoute
@interface HedoneAdRoute:NSObject
@property (nonatomic, copy) NSString * picture;
@property (nonatomic, copy) NSString * route;
@property (nonatomic, assign) int tipType;
@property (nonatomic, copy) NSString * displayText;
@property (nonatomic, strong) HedoneFormatText * formatText;
@end

@implementation HedoneAdRoute
@synthesize picture;
@synthesize route;
@synthesize tipType;
@synthesize displayText;
@synthesize formatText;
@end

#pragma mark - HedoneFormatText
@interface HedoneFormatText:NSObject
@property (nonatomic, copy) NSString * content;
@property (nonatomic, strong) NSArray * args;
@end

@implementation HedoneFormatText
@synthesize content;

+ (NSDictionary *)mj_objectClassInArray{
	return @{@"args":[HedoneFormatArg class]};
}

@end

#pragma mark - HedoneFormatArg
@interface HedoneFormatArg:NSObject
@property (nonatomic, copy) NSString * str;
@property (nonatomic, copy) NSString * color;
@end

@implementation HedoneFormatArg
@synthesize str;
@synthesize color;
@end

**Comment by WXXXXH** [comment]
有同样问题，主要是在app启动的时候
![b5898c6a2da471d90dc1e4f38e1b8fc0](https://user-images.githubusercontent.com/35984644/35604499-71655c28-067d-11e8-93f8-408f51742e90.jpg)

**Comment by zhenzhenxu** [comment]
我也是  主要是app启动的时候  接口蹦的概率特别大

**Comment by zhenzhenxu** [comment]
我的转模型 也是放在了异步线程执行的

**Comment by kinarob** [comment]
3.0.16 已经修复了线程安全的问题！
