### ISSUE TITLE
重写model的description方法时使用mj_keyValues，全局异常断点崩溃了

### ISSUE THREAD

**Issue by ymsying** [CoderMJLee/MJExtension#581]
在model设置属性对应字典中的多级key，通过model的属性获取值时，能够成功获取属性的值，但是在description中通过mj_keyValues获取model全部属性时报错 `-[__NSFrozenDictionaryM setObject:forKeyedSubscript:]: unrecognized selector sent to instance `,在有全局断点时crash，无断点时打印 `-[__NSFrozenDictionaryM setObject:forKeyedSubscript:]: unrecognized selector sent to instance `。
断点获取到NSObject+MJKeyValue.m中374行，在设置后一个key时报错__NSFrozenDictionaryM类无set方法。

使用如下方法打印
```
- (IBAction)printChart:(id)sender {
    SYPChartModel *model = [SYPChartModel mj_objectWithKeyValues:self.sourceData];
    
    NSLog(@"chart model: %@", model);
}
```

[测试用例.zip](https://github.com/CoderMJLee/MJExtension/files/1520324/default.zip)

**Comment by CoderMJLee** [comment]
NSDictionary *config用strong试试

**Comment by ymsying** [comment]
谢谢MJ哥，这个方法可行！
但是请问这地方只能用strong吗，用 copy 有什么影响呢，并且用copy会比strong更安全一些。在使用你的框架什么情况下应该有strong呢？
