### ISSUE TITLE
swift4 字典转模型失败

### ISSUE THREAD

**Issue by Yankk** [CoderMJLee/MJExtension#582]
mj_object(withKeyValues: data)转模型失败，请问什么时候会更新知识swift4的版本呢

**Comment by 350541732** [comment]
我也遇到了   MJ老师更新一下吧

**Comment by sunxiaoyi** [comment]
我也遇到了..

**Comment by Yankk** [comment]
@350541732 @sunxiaoyi 模型的属性增加@objc就可以用了

**Comment by MichaelTiramisu** [comment]
有两种办法可以解决:
1. 在每个属性的定义前增加@objc
2. 在项目设置中，将Swift 3 @objc Inference设置为On
---------------------------------------------------------
There are two ways to solve it:
1. Manually add @objc to the class definition for each property.
2. Go to Project settings, and set 'Swift 3 @objc Inference' to 'On'.

**Comment by okayYusi** [comment]
swift下一堆问题，还是用别的吧

**Comment by wolfcon** [comment]
@JasonSparrow `CubeCategoryLabelModel` 加 `@objc` 了吗
