### ISSUE TITLE
字典数组转模型数组耗时1秒

### ISSUE THREAD

**Issue by kongxiaofeng** [CoderMJLee/MJExtension#584]
2017-12-12 10:42:57.781581+0800 MobileArk[2547:552663] Tue Dec 12 10:42:57 2017
2017-12-12 10:42:58.679081+0800 MobileArk[2547:552663] Tue Dec 12 10:42:58 2017

**Comment by kongxiaofeng** [comment]
IOS版本为11以上

**Comment by kongxiaofeng** [comment]
数据量越来越多  能否提高下效率呢

**Comment by CoderMJLee** [comment]
可以贴出你的具体数据和测试速度的代码么

**Comment by kongxiaofeng** [comment]
[文件.zip](https://github.com/CoderMJLee/MJExtension/files/1554285/default.zip)

**Comment by kongxiaofeng** [comment]
NSString* filePath = [NSString stringWithFormat:@"%@/Library/circleSave/circleList",str1];
        
        NSArray* baseArray;
        if(![fileManager fileExistsAtPath:filePath]){//如果不存在,则说明是第一次运行这个程序，那么建立这个文件夹
            baseArray = [NSMutableArray array];
        }else{
            NSArray* array = [NSArray arrayWithContentsOfFile:filePath];
            baseArray = [MACircleModel mj_objectArrayWithKeyValuesArray:array];
        }

**Comment by kongxiaofeng** [comment]
文件数据  稍后 贴上

**Comment by kongxiaofeng** [comment]
[文件.zip](https://github.com/CoderMJLee/MJExtension/files/1554293/default.zip)

**Comment by kongxiaofeng** [comment]
文件已上传  希望能帮看下  现在这段阻塞主线程的代码 已放入子线程当中

**Comment by kongxiaofeng** [comment]
耗时时间 上面已贴上

**Comment by kongxiaofeng** [comment]
[附加文件.zip](https://github.com/CoderMJLee/MJExtension/files/1554434/default.zip)

**Comment by kongxiaofeng** [comment]
字典转模型所需类文件都在文件和附加文件 里面

**Comment by kongxiaofeng** [comment]
杰哥，大概是什么原因导致的呢
