### ISSUE TITLE
32位，系统10以上的机器数值溢出

### ISSUE THREAD

**Issue by Rui9420** [CoderMJLee/MJExtension#585]
在5或者5s的系统10以上的机器上，数值位数为1512622610000转换是错的，找到问题是32位机器上数值溢出

**Comment by kongxiaofeng** [comment]
这个要你自己转换吧

**Comment by kongxiaofeng** [comment]
MJExtention只是字典转模型 时间自己格式化的

**Comment by Rui9420** [comment]
我描述的有问题， 我说的是数值类似于1512622610000，最后解析出来不是这个1512622610000值而是794121808这种数值

**Comment by kongxiaofeng** [comment]
那应该超出精度了 溢出了
