### ISSUE TITLE
+[NSObject(Property) properties] (NSObject+MJProperty.m:179)

### ISSUE THREAD

**Issue by daaiwusheng** [CoderMJLee/MJExtension#586]
#1 Thread
SIGSEGV
SEGV_ACCERR

CoreFoundation | -[__NSDictionaryM setObject:forKey:] + 320
-- | --
1 CoreFoundation | -[__NSDictionaryM setObject:forKey:] + 296
2 XX | +[NSObject(Property) properties] (NSObject+MJProperty.m:179)
3 XX | +[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:0)
4 XX | -[NSObject(MJKeyValue) mj_setKeyValues:context:] (NSObject+MJKeyValue.m:197)
5 XX | +[NSObject(MJKeyValue) mj_objectWithKeyValues:context:] (NSObject+MJKeyValue.m:218)

子线程使用,崩溃次数还是挺高的,系统各个版本都有,+ (NSMutableArray *)properties
{
    @synchronized (self) {
     }
}
函数体加锁还是不行

**Comment by ZLWorm** [comment]
同样问题，有解决办法吗

**Comment by zhzDeveloper** [comment]
同样的问题, 求解

**Comment by zhzDeveloper** [comment]
这个是不是性能消耗太大了, 每次都要创建mArray, 遍历属性 @daaiwusheng

**Comment by zhzDeveloper** [comment]
大概定位到问题了

**Comment by zhzDeveloper** [comment]
NSObject 的 property 分类中的 dictForKey:方法 被 NSObject+MJClass.h的覆盖了, 返回类型不一样, 导致crash

**Comment by daaiwusheng** [comment]
也是太着急下的办法了,

**Comment by daaiwusheng** [comment]
@zhzDeveloper  能否加个qq,跟您请教一下 245033896

**Comment by chengyifly** [comment]
@zhzDeveloper 请问怎么解决的？自己clone一份，把 dictForKey 方法重命名吗？

**Comment by zhzDeveloper** [comment]
@daaiwusheng @chengyifly 我们已经解决了, clone 一份, 
` + (instancetype)mj_objectWithKeyValues:(id)keyValues context:(NSManagedObjectContext *)context
 {
     if ([keyValues isKindOfClass:[NSNull class]] || keyValues == nil) {
-        return [[self alloc] init];
+        return nil;
     }
.....
}}
`

**Comment by daaiwusheng** [comment]
@zhzDeveloper  看你这个更改,是不是和多线程没什么关系?

**Comment by daaiwusheng** [comment]
@zhzDeveloper  和方法重名也没有关系?

**Comment by CoderMJLee** [comment]
用新版本看看？

**Comment by kinarob** [comment]
新版本已经修复线程安全的问题！
