### ISSUE TITLE
在SDK开发中的crash

### ISSUE THREAD

**Issue by sn5diphone6** [CoderMJLee/MJExtension#591]
[PheiMapRequestModel mj_keyValues]: unrecognized selector sent to instance 0x1c4441b00

PheiMapRequestModel是我创建的模型 在model.mj_keyValues的时候报以上错。
在app项目中能正常使用，但在开发SDK时，代码里使用了这个方法，把SDK放到项目中测试时就出现了这个问题。

**Comment by liuxuleidota** [comment]
怎么解决的，我也是开发sdk遇到的

**Comment by kinarob** [comment]
@sn5diphone6 @liuxuleidota 开发SDK可能需要添加MJExtension的依赖

**Comment by liuxuleidota** [comment]
@kinarob,你是指要将mjextension也添加到工程中？
我现在已经改用jsonModel了
