### ISSUE TITLE
后台返回的数据组中，一个九个，一个八个，怎么解析？

### ISSUE THREAD

**Issue by WenzheFan** [CoderMJLee/MJExtension#593]
老师好啊 ，后台返回的数据中，需要用同一个model（事先申明八个属性）去解析，可是有的数据中只有6个属性，有的数据中只有4个数据，这样该怎么解析

**Comment by kinarob** [comment]
@WenzheFan 你把服务器返回所有可能的字段都申明属性，到时解析根据服务器有几个字段解析几个字段，如果没有就为nil。

**Comment by WenzheFan** [comment]
最后我们处理的比较简单，不管是什么类型的数据，都是JOSN格式，并且只有字符串，不会出现，float，int ，bool,Date等类型
