### ISSUE TITLE
模型转字典的问题

### ISSUE THREAD

**Issue by yinxing29** [CoderMJLee/MJExtension#594]
当模型中有一个属性为数组，数组里面是UIImage或者PHAsset的时候，模型转字典会崩溃。这个是有约定，还是需要特殊处理呢？

**Comment by yinxing29** [comment]
模型中如果这个属性是一个NSDictionary对象，然后字典中一个字段对应UIImage数组是没有问题的，但是如果将这个属性设为NSArray对象，直接存放UIImage数组就崩溃。

**Comment by kinarob** [comment]
@yinxing29 如果模型中有数组，默认的做法是将这些数组里面的元素按照     模型数组 -> 字典数组   的方式进行转换了。
![Uploading WechatIMG3331.jpeg…]()

显然UIImage不是自定义模型导致转换失败，这可能算是`MJExtension`的bug。

**Comment by kinarob** [comment]
@yinxing29 这种情况下，即使使用[YYModel](https://github.com/ibireme/YYModel)、[JsonModel](https://github.com/jsonmodel/jsonmodel)进行模型转字典都是转不成功的，此时是不是需要考虑一下，是否还需要这样转换。

**Comment by wolfcon** [comment]
转换 Image 没有必要吧? 在设置属性的时候过滤掉
