### ISSUE TITLE
用 MJExtension 产生的模型什么时候会销毁? 页面消失了,但是变量的内存好像还没有释放吧?

### ISSUE THREAD

**Issue by nelsonnan** [CoderMJLee/MJExtension#596]
用 MJExtension 产生的模型什么时候会销毁? 页面消失了,但是变量的内存好像还没有释放吧?

**Comment by CoderMJLee** [comment]
模型什么时候销毁，与MJExtension无关，因为MJExtension只是把字典转成模型了，模型是返回给开发者了，究竟把模型放到数组了？还是字典了？什么时候释放模型，这是开发者决定的

**Comment by nelsonnan** [comment]
但是你生成模型中好多 for 环境的产生的变量没放在自动释放中!造成很多变量生成后一直都没释放....

**Comment by nelsonnan** [comment]
主要就是生成模型 尤其是 json 数组 转 模型数组时

**Comment by nelsonnan** [comment]
建议把一些必要的 for 循环添加 自动释放

**Comment by wolfcon** [comment]
这个有可能不是立即释放, 由系统在之后的 Runloop 中, 会自行释放. 可能会有延迟.
