### ISSUE TITLE
MJProperty中- (void)setPorpertyKeys:(NSArray *)propertyKeys forClass:(Class)c频繁Carsh

### ISSUE THREAD

**Issue by WXXXXH** [CoderMJLee/MJExtension#597]
非主线程使用，网络请求里面使用，非必现，但是出现了，大概率会连续出现几次，然后恢复正常
![b5898c6a2da471d90dc1e4f38e1b8fc0](https://user-images.githubusercontent.com/35984644/35604688-4edf8524-067e-11e8-93f7-c9d59a2658ec.jpg)

**Comment by WXXXXH** [comment]
具体是使用mj_keyValues 方法 非主线程

**Comment by zhenzhenxu** [comment]
我这边也遇到了  偶尔会蹦

**Comment by WXXXXH** [comment]
算了，看历史就知道我不是第一个反应这个问题的，看明杰已经忙着挣钱了，估计这个代码也不会维护了，已经切换了YYModel，问题解决，不在使用MJExtension

**Comment by loveuqian** [comment]
@WXXXXH 
其实 YY 也很久没更新。。。

**Comment by BruceWee01** [comment]
也遇到了

**Comment by kinarob** [comment]
@WXXXXH @zhenzhenxu 3.0.16修复了线程安全的问题。
