### ISSUE TITLE
模型转换问题

### ISSUE THREAD

**Issue by q858333** [CoderMJLee/MJExtension#599]
比如我有个weibo模型，里面还有个用户模型，用户模型里有name属性，现在有个这样的数据，
        {
                        @"text" : @"今天天气真不错！",                   
                        @"name" : @"Rose",                       
                        @"icon" : @"nami.png"                    
          }
想把里面的name取出来给我赋值给weibo模型里用户模型的name属性，这样有办法实现吗？

**Comment by kinarob** [comment]
@q858333 很好实现啊，在微博模型的里面映射一下就ok了！
`+ (NSDictionary *)mj_replacedKeyFromPropertyName
{
    return @{
             @"name" : @"user.name"
             };
}`
user是你的jsonString里面的对应用户的key。
