### ISSUE TITLE
多层嵌套的数据（数组包字典，字典包数组，数组中再包字典）如何处理，杰哥？

### ISSUE THREAD

**Issue by yudigege** [CoderMJLee/MJExtension#60]
[
    {
        "DUdate": "2015-03-10",
        "info": [
            {
                "DUid":"1",
                "DUinterval": "上午",
                "DRname": "郭清华",
                "DRmetitle": "主任医师",
                "DRprice": 100,
                "DRphoto": "",
                "HDid1_name": "儿科",
                "HDid2_name": "",
                "HCname": "门诊1",
                "DUstatus":"0"
            },
            {
                "DUid":"2",
                "DUinterval": "下午",
                "DRname": "王刚",
                "DRmetitle": "主任医师",
                "DRprice": 80,
                "DRphoto": "",
                "HDid1_name": "骨科",
                "HDid2_name": "",
                "HCname": "门诊1",
                "DUstatus":"2"
            },
            {
                "DUid":"3",
                "DUinterval": "下午",
                "DRname": "杨明",
                "DRmetitle": "主任医师",
                "DRprice": 90,
                "DRphoto": "",
                "HDid1_name": "内科",
                "HDid2_name": "",
                "HCname": "门诊2",
                "DUstatus":"0"
            }
        ]
    },
    {
        "DUdate": "2015-03-11",
        "info": [
            {
                "DUid":"4",
                "DUinterval": "上午",
                "DRname": "郭清华",
                "DRmetitle": "主任医师",
                "DRprice": 100,
                "DRphoto": "",
                "HDid1_name": "儿科",
                "HDid2_name": "",
                "HCname": "门诊1",
                "DUstatus":"0"
            },
            {
                "DUid":"5",
                "DUinterval": "下午",
                "DRname": "王刚",
                "DRmetitle": "主任医师",
                "DRprice": 80,
                "DRphoto": "",
                "HDid1_name": "骨科",
                "HDid2_name": "",
                "HCname": "门诊1",
                "DUstatus":"0"
            },
            {
                "DUid":"6",
                "DUinterval": "下午",
                "DRname": "杨明",
                "DRmetitle": "主任医师",
                "DRprice": 90,
                "DRphoto": "",
                "HDid1_name": "内科",
                "HDid2_name": "",
                "HCname": "门诊2",
                "DUstatus":"0"
            }
        ]
    },
    {
        "DUdate": "2015-03-12",
        "info": [
            {
                "DUid":"7",
                "DUinterval": "上午",
                "DRname": "郭清华",
                "DRmetitle": "主任医师",
                "DRprice": 100,
                "DRphoto": "",
                "HDid1_name": "儿科",
                "HDid2_name": "",
                "HCname": "门诊1",
                "DUstatus":"0"
            },
            {
                "DUid":"8",
                "DUinterval": "下午",
                "DRname": "王刚",
                "DRmetitle": "主任医师",
                "DRprice": 80,
                "DRphoto": "",
                "HDid1_name": "骨科",
                "HDid2_name": "",
                "HCname": "门诊1",
                "DUstatus":"0"
            },
            {
                "DUid":"9",
                "DUinterval": "下午",
                "DRname": "杨明",
                "DRmetitle": "主任医师",
                "DRprice": 90,
                "DRphoto": "",
                "HDid1_name": "内科",
                "HDid2_name": "",
                "HCname": "门诊2",
                "DUstatus":"0"
            }
        ]
    },
    {
        "DUdate": "2015-03-14",
        "info": [
            {
                "DUid":"11",
                "DUinterval": "上午",
                "DRname": "郭清华",
                "DRmetitle": "主任医师",
                "DRprice": 100,
                "DRphoto": "",
                "HDid1_name": "儿科",
                "HDid2_name": "",
                "HCname": "门诊1",
                "DUstatus":"0"
            },
            {
                "DUid":"12",
                "DUinterval": "下午",
                "DRname": "王刚",
                "DRmetitle": "主任医师",
                "DRprice": 80,
                "DRphoto": "",
                "HDid1_name": "骨科",
                "HDid2_name": "",
                "HCname": "门诊1",
                "DUstatus":"0"
            },
            {
                "DUid":"13",
                "DUinterval": "下午",
                "DRname": "杨明",
                "DRmetitle": "主任医师",
                "DRprice": 90,
                "DRphoto": "",
                "HDid1_name": "内科",
                "HDid2_name": "",
                "HCname": "门诊2",
                "DUstatus":"0"
        }
        ]
    }
]

**Comment by CoderMJLee** [comment]
```objc
@interface MyModel : NSObject
@property (nonatomic, copy) NSString *DUdate;
@property (nonatomic, strong) NSArray *info;
@end

@implementation MyModel
+ (NSDictionary *)objectClassInArray
{
     return @{@"info" : @"MyInfo"};
}
@end

@interface MyInfo : NSObject
@property (nonatomic, copy) NSString *DUinterval;
@property (nonatomic, copy) NSString *DRmetitle;
/** ... ... */
@end

NSArray *models = [MyModel objectArrayWithKeyValuesArray:json];
```

**Comment by yudigege** [comment]
终于搞明白了，Thank you 杰哥！
