### ISSUE TITLE
关于数据模型转换

### ISSUE THREAD

**Issue by zhangfurun** [CoderMJLee/MJExtension#600]
问题出现:在数据模型转换或者解档的时候,打全局断点,会断在下面代码1的部分,看的self.name为只读属性
/**
 *  设置成员变量的值
 */
- (void)setValue:(id)value forObject:(id)object
{
    if (self.type.KVCDisabled || value == nil) return;
    [object setValue:value forKey:self.name];
}

猜想sdk对只读属性没有做统一的处理吧

**Comment by wolfcon** [comment]
不会出现这个问题哦, 请更新库版本再试试

**Comment by zhangfurun** [comment]
> 不会出现这个问题哦，请更新库版本再试试

我这边在对接完数据并且转换成所需要的model时,runtime获取model中的属性列表信息,如果该属性判定为只读属性,设置到白名单列表,就可以了

**Comment by wolfcon** [comment]
不存在这个问题啊. 我这边的都模型都是只读属性, 不会有任何问题
