### ISSUE TITLE
crash when transform to json string

### ISSUE THREAD

**Issue by qmkCamel** [CoderMJLee/MJExtension#602]
Invalid number value (infinite) in JSON write
Invalid number value (NaN) in JSON write

Is there any workaround to avoid this?

**Comment by shannonchou** [comment]
我也遇到这个问题，版本3.0.10

**Comment by kinarob** [comment]
@qmkCamel @shannonchou  It's better to provide a demo or code  that can reproduce this issue, Thus ,someone can quickly find the problem and solve it,Thank you!

**Comment by wolfcon** [comment]
@qmkCamel Check your code to avoid produce `infinite number` & `NaN number`. That is developer's job to do.
