### ISSUE TITLE
数组直接嵌套数组

### ISSUE THREAD

**Issue by tangbin583085** [CoderMJLee/MJExtension#603]
{"class_list": [
      [
        {
          "name": 1,
          "age": 11,
        },
        {
          "name": 2,
          "age": 22,
        }
      ],
      [
        {
          "name": 3,
          "age": 33,
        }
      ]
    ]
}

请问可以解析以上json数据吗？
贴出代码，谢谢啦

**Comment by kinarob** [comment]
在2个类里面分别实现这个方法
+ (NSDictionary *)mj_objectClassInArray
不就可以了啊

**Comment by kinarob** [comment]
@tangbin583085
