### ISSUE TITLE
关于服务端数据为空时（<null>）的问题

### ISSUE THREAD

**Issue by Michaelyb520** [CoderMJLee/MJExtension#605]
### 能否按原始数据转换输出呢？希望得到的依然是`<null>`

![image](https://user-images.githubusercontent.com/9857312/37586883-a4f2d22e-2b98-11e8-928b-662f852029b2.png)

**Comment by CoderMJLee** [comment]
服务器返回的是null么

**Comment by kinarobin** [comment]
@CoderMJLee 看json 应该指的是kCFNull，

**Comment by Michaelyb520** [comment]
是的呢？返回的是<null>，指定属性是NSString，转换结果就变成了字符串的(null)了

**Comment by CoderMJLee** [comment]
NSString和NSNull本来就不同类型哦，你把NSNull赋值给NSString，将来使用也会出问题的

**Comment by Michaelyb520** [comment]
了解~
