### ISSUE TITLE
当一个模型类遵守了一个自定义的协议，归档的时候encoderObject: forKey: 的key会出现superclass导致崩溃

### ISSUE THREAD

**Issue by FastGitHub** [CoderMJLee/MJExtension#607]
由于使用CocoaPods集成的，没办法改动，就特定的调用ignorePropertys把@[@"superclass"]放进去了

**Comment by CoderMJLee** [comment]
除了superclass，还有哪些属性？

**Comment by FastGitHub** [comment]
记不得了，应该只有一个

**Comment by wolfcon** [comment]
@CoderMJLee 这个PR解决了这个问题. 的确有时候挺烦人的.

[https://github.com/CoderMJLee/MJExtension/pull/612](https://github.com/CoderMJLee/MJExtension/pull/612)

**Comment by kinarob** [comment]
Fix via #665  #666
