### ISSUE TITLE
两个NSObejct的分类方法同名

### ISSUE THREAD

**Issue by petyou** [CoderMJLee/MJExtension#608]
+ (NSMutableDictionary *)dictForKey:(const void *)key;
该方法在NSObject (MJClass)和NSObject (Property)中都存在,导致只有一个分类中的缓存有效

**Comment by chengyifly** [comment]
朋友，我看楼下有好多反馈这个问题的，https://github.com/CoderMJLee/MJExtension/issues/597，是不是和你说的这个有关系啊？

**Comment by petyou** [comment]
这两个方法只是根据key返回缓存字典而已,重名会导致一个方法不被调用.不会导致崩溃问题

**Comment by CoderMJLee** [comment]
@petyou 谢谢提醒
