### ISSUE TITLE
swift 4.1使用bug

### ISSUE THREAD

**Issue by SLE-song** [CoderMJLee/MJExtension#611]
objectArrayWithKeyValuesArray 此方法已经不能正确使用

**Comment by LuDamon** [comment]
在swift4.1下，+ (instancetype)mj_objectWithKeyValues:(id)keyValues; 此方法转换失败

**Comment by LuDamon** [comment]
解决办法： 在自己的model文件中，变量之前添加 @objc标记

**Comment by okayYusi** [comment]
swift下一堆bug

**Comment by wolfcon** [comment]
不加@objc的话, 你的类根本都不会暴漏给 OC 代码使用. 你怎么能用 OC 的库呢? 加 objc 不是基本操作么?
