### ISSUE TITLE
数组里面又要装着其他模型,只转了最外层的数组？

### ISSUE THREAD

**Issue by niyongsheng** [CoderMJLee/MJExtension#613]
[QMHStatusResult mj_setupObjectClassInArray:^NSDictionary *{
                return @{
                         @"returnValue" : [QMHStatus class],
                         @"postsPraiseList" : [QMHPraise class],
                         @"postsReplyList" : [QMHReply class]
                         };
            }];
QMHStatusResult *result = [QMHStatusResult mj_objectWithKeyValues:responseObject];
NLog(@"statusArray:%@  praiseArray:%@  replyArray:%@", result.returnValue, result.postsPraiseList, result.postsReplyList);
![image](https://user-images.githubusercontent.com/28373699/41334242-725cf3c2-6f17-11e8-90f7-8e4eed0be018.png)

#import <Foundation/Foundation.h>

@interface QMHStatusResult : NSObject
/** 状态模型数组 */
@property(strong, nonatomic) NSMutableArray *returnValue;
/** 点赞模型数组 */
@property(strong, nonatomic) NSArray *postsPraiseList;
/** 评论模型数组 */
@property(strong, nonatomic) NSArray *postsReplyList;

@property (strong, nonatomic) NSString *error;
@property (strong, nonatomic) NSNumber *success;
@end
![image](https://user-images.githubusercontent.com/28373699/41334320-c749b406-6f17-11e8-8eaa-b929421d9e62.png)
log输出：
statusArray:(
    "<QMHStatus: 0x10c5bdd10>",
    "<QMHStatus: 0x10c5c0420>",
    "<QMHStatus: 0x10c5c1c50>",
    "<QMHStatus: 0x10f520db0>",
    "<QMHStatus: 0x10f521680>",
    "<QMHStatus: 0x10f521f80>",
    "<QMHStatus: 0x10f522570>",
    "<QMHStatus: 0x10c5c21d0>",
    "<QMHStatus: 0x10c5c2810>"
)  praiseArray:(null)  replyArray:(null)

服务器返回转JSON:{
    error = "<null>";
    list = "<null>";
    msg = "<null>";
    param =     {
    };
    returnValue =     (
                {
            account = 15615691823;
            comName = "\U7027\U749f\U793e\U533a";
            comNo = 1;
            content = "\U53bb\U5c0f\U533a\U901b\U901b\Uff0c\U5c0f\U533a\U548c\U5468\U8fb9\U7684\U53d8\U5316\U771f\U4e0d\U5c0f\Uff01\U5c0f\U533a\U5317\U95e8\U597d\U591a\U706f\U7b3c\Uff0c\U633a\U6709\U8fc7\U8282\U6c14\U6c1b\U3002";
            gmtCreate = 1529042377000;
            gmtModify = "<null>";
            imgAddress = "http://p8ppgb8ha.bkt.clouddn.com/intelCommunity/uploadImg/image/1527746333177.jpg";
            isTop = 1;
            pId = 2;
            posterImgAddress = "http://p8ppgb8ha.bkt.clouddn.com/morentouxiang@3x.png";
            posterNickName = "\U80d6\U72d7";
            postsPraiseList =             (
                                {
                    gmtCreate = "2018-05-31 16:58:28";
                    gmtModify = "<null>";
                    pAccount = 15615691823;
                    pAccountName = "\U80d6\U72d7";
                    pId = 2;
                    ppId = 5;
                    status = 0;
                },
                                {
                    gmtCreate = "2018-05-31 16:58:55";
                    gmtModify = "<null>";
                    pAccount = 18853936112;
                    pAccountName = "\U680b\U680b\U62d0";
                    pId = 2;
                    ppId = 7;
                    status = 0;
                },
                                {
                    gmtCreate = "2018-05-31 16:58:39";
                    gmtModify = "<null>";
                    pAccount = 18669300603;
                    pAccountName = zero;
                    pId = 2;
                    ppId = 6;
                    status = 0;
                }
            );
            postsReplyList =             (
            );
            praiseCount = 3;
            replayCount = 0;
            sorts = 3;
            status = 0;
            viewCount = 0;
        },
        {
           ......
        },

);
    success = 1;
    type = "<null>";
    unread = "<null>";
}

**Comment by kinarob** [comment]
@niyongsheng 看返回的json 你用错了啊， 数组postsPraiseList应该是在returnValue模型中的啊 `  [QMHStatus mj_setupObjectClassInArray:^NSDictionary *{
        return @{
                 @"postsPraiseList" : [QMNPraise class],
                 };
    }];`

**Comment by kinarob** [comment]
@niyongsheng 不是框架的问题

**Comment by niyongsheng** [comment]
@kinarob Thanks♪(･ω･)ﾉ

**Comment by CoderMJLee** [comment]
@kinarob 3Q
