### ISSUE TITLE
MJ json 与model转换线程安全问题

### ISSUE THREAD

**Issue by hxming2919** [CoderMJLee/MJExtension#614]
MJ json 与model的代码存在不少地方有线程安全问题。
比如：
/** 对应着字典中的多级key */
- (void)setPorpertyKeys:(NSArray *)propertyKeys forClass:(Class)c
{
    if (propertyKeys.count == 0) return;
    self.propertyKeysDict[NSStringFromClass(c)] = propertyKeys;
}

+ (NSMutableArray *)properties {

....
 [self dictForKey:&MJCachedPropertiesKey][NSStringFromClass(self)] = cachedProperties;
}

是否可以把MJ中的可变数组、可变字典都使用线程安全数组，安全字典解决？【安全数组，安全字典可以参考weex 封装的】

**Comment by kinarob** [comment]
@hxming2919 最新的3.0.16已经修复了这个问题。
