### ISSUE TITLE
一个数组中有多个不同类型的模型,怎么解析?

### ISSUE THREAD

**Issue by hychen1024** [CoderMJLee/MJExtension#615]
如题

**Comment by QQ920924960** [comment]
多个不同类型的模型本身就不应该放在数组中，而是放在字典中，所以不应该存在这样的问题

**Comment by CaiChenghan** [comment]
@QQ920924960 怎么可能没有这样的数组？例如常见的聊天消息，这就可以构成多类型元素的数组。我在想，此类数组，对于混合元素，是否需要合并成一个大的元素，来进行处理。

**Comment by QQ920924960** [comment]
你就不能封装一个通用聊天模型放到数组里吗？这个模型包含聊天所需要的各类属性

**Comment by CoderMJLee** [comment]
- 这个属于个性化的需求，框架不太好处理，框架只负责通用的需求
- 个性化的需求需要开发者自行解决
- 数组是有顺序的，究竟哪个位置是什么模型，这个是不确定的。需要自己去遍历服务器返回的JSON数组，根据JSON的情况转为对应的模型
