### ISSUE TITLE
NSNumber数据精度丢失问题

### ISSUE THREAD

**Issue by ccmysoul** [CoderMJLee/MJExtension#616]
<img width="882" alt="2018-07-09 7 21 40" src="https://user-images.githubusercontent.com/10458208/42447753-7ea5d504-83ad-11e8-9eef-07bac5129eb4.png">
当服务器返回某些特定的数值时，数据转换后会发生精度丢失问题,请MJ大神看一下

**Comment by kinarob** [comment]
@ccmysoul 事实上MJExtension在KVC赋值的时候确实将double591.18 赋值给了height属性，可以在控制台的左边看到height属性值确实是591.18，即使使用` NSNumber *number = [NSNumber numberWithDouble:591.18];`打印number 结果仍为591.1799999999999。所以这不是框架本身的原因！
至于打印精度丢失可以参考[https://stackoverflow.com/questions/2816212/nsnumber-floatvalue-not-equal-to-nsnumber-value](https://stackoverflow.com/questions/2816212/nsnumber-floatvalue-not-equal-to-nsnumber-value) 希望可以帮到您！
