### ISSUE TITLE
关于模型转json的问题

### ISSUE THREAD

**Issue by yanqiuLove** [CoderMJLee/MJExtension#619]
目前使用的时候出现了模型无法转成jsonString的问题，我创建了一个模型，继承NSObject，定义了四个属性，我接着创建了两个模型对象，并将这两个模型对象放入数组中，不管我是使用模型对象调用mj_JSONString还是模型数组调用mj_JSONString，都会出现闪退，具体如下：
![image](https://user-images.githubusercontent.com/19206208/42938781-0ba86c7a-8b86-11e8-966c-119e4eefcb6a.png)
![image](https://user-images.githubusercontent.com/19206208/42938813-22ff113a-8b86-11e8-877d-5af83ebf9e78.png)

**Comment by kinarob** [comment]
@yanqiuLove 使用模型对象`[modelOne mj_JSONString]`调用不会崩溃吧，您用数组调用会产生异常`MJExtensionAssertError(![MJFoundation isClassFromFoundation:[self class]], (NSMutableDictionary *)self, [self class], @"不是自定义的模型类")` ，导致 `[NSJSONSerialization dataWithJSONObject:@[modelOne,modelTwo] options:kNilOptions error:nil]` 解析失败。
会不会是`PRProjectListModel`模型的实现文件做什么操作了呀？正常应该是不会崩溃的。

**Comment by kinarob** [comment]
@yanqiuLove 或者方便提供一份报错的demo吗？

**Comment by yanqiuLove** [comment]
昨天的项目工程中模型[modelOne mj_JSONString]确实出现了没有找到方法的情况，今天我的测试demo中模型对象转json是没有问题的，我的demo已经上传，我也根据您的建议再排查一下。

[TestModelArrayJson.zip](https://github.com/CoderMJLee/MJExtension/files/2212188/TestModelArrayJson.zip)

**Comment by kinarob** [comment]
@yanqiuLove `MJExtension`默认是不支持模型数组转为mj_JSONString的哦😯😯

**Comment by yanqiuLove** [comment]
哎呀呀，尴尬，怪不好意思的，因为我记错了耽误您的时间，实在抱歉~

**Comment by yanqiuLove** [comment]
从开始使用就觉得挺方便的，用顺手了然后反而犯了不该犯的错误~感谢您的耐心解答~

**Comment by wolfcon** [comment]
@yanqiuLove @kinarob 

`MJExtension` 是支持模型数组转 JSONString 的哟

```objective-c
[PRProjectListModel mj_keyValuesArrayWithObjectArray:self.modelArray] mj_JSONString];
```
