### ISSUE TITLE
现在只能显式指定ignoredPropertyNames（“黑名单”），不能直接指定哪些属性是可以被转换（“白名单”）的吗？

### ISSUE THREAD

**Issue by chenqiu1024** [CoderMJLee/MJExtension#62]
像Mantle可以通过JSONKeyPathsByPropertyKe y直接指示哪几个属性是应该被考虑到与JSON字典的相互转化的，而其它属性全被忽略；但是MJExtension却只能在ignoredPropertyNames里指明哪些是不能被放进JSON字典的。这样如果类有很多个与JSON序列化无关的其它属性岂不是全都要列出？有点麻烦

**Comment by CoderMJLee** [comment]
已经增加白名单功能.参考allowedPropertyNames哈

**Comment by chenqiu1024** [comment]
是哪个版本里增加的？我用的2.0.2，好像没找到这个方法

**Comment by CoderMJLee** [comment]
2.0.3，昨晚刚上传的

**Comment by chenqiu1024** [comment]
还没有更新到CocoaPods源吧？

**Comment by CoderMJLee** [comment]
更新了，你需要pod repo update更新远程库先

**Comment by chenqiu1024** [comment]
好的，多谢MJ大牛！

**Comment by CoderMJLee** [comment]
不客气，过奖了
