### ISSUE TITLE
MJExtension / 会转为\/,怎么解决？

### ISSUE THREAD

**Issue by youhujia-jingkai** [CoderMJLee/MJExtension#620]

**Comment by youhujia-jingkai** [comment]
后端接到请求之后会报protobuf不支持

**Comment by kinarob** [comment]
@youhujia-jingkai 可否详细的描述一下您遇到的问题？或者可否提供一下自定义的模型和需要转换的json数据？

**Comment by youhujia-jingkai** [comment]
后台接口使用Google的Protobuf ，使用MJExtension 将模型转化为字典【xxxModel mj_keyValues】, 如果此模型某一个key对应的value是一个字符串，而这个字符串里有输入“/”，那么使用【xxxModel mj_keyValues】转换完毕之后value会变为“\/”,而“\/”,使用Protobuf解析不了，会报错，所以我想能不能在iOS端解决这个问题

**Comment by kinarob** [comment]
@youhujia-jingkai 我觉得这种情况您在`[xxxModel mj_keyValues];`调用之前处理一下" / "比较好。如果在mj_keyValues方法中处理是不是有点不合适，假如value是url，那到底是处理" / "还是不处理" / "呢，还得维护一个是否需要处理的属性。

**Comment by youhujia-jingkai** [comment]
@kinarob 考虑到这个问题了，所以我现在的做法是在[xxxModel mj_keyValues]调用之前处理的，我是是直接将“/”换成了“或”，但是总感觉这种方法不是很优雅，所以请教一下，可以证明处理？

**Comment by kinarob** [comment]
@youhujia-jingkai 这种需求`JsonModel`可以帮你做到，自定义`JSONValueTransformer`，走自定义的转换方法，可以帮你处理" / "。目前`MJExtension`好像还不支持这种处理方案哦！

**Comment by youhujia-jingkai** [comment]
好的，中的来说谢谢你，也谢谢你提供的思路。
