### ISSUE TITLE
数组里面还是数组，然后最内层的数组里面是一个Model，怎么破？

### ISSUE THREAD

**Issue by qinqi777** [CoderMJLee/MJExtension#621]
如下的字典怎么转？
<img width="687" alt="wx20180727-112224 2x" src="https://user-images.githubusercontent.com/14885158/43299999-69b62fc8-918f-11e8-92c7-8da5146d5fa1.png">

@property (nonatomic, copy) NSString *method;
@property (nonatomic, strong) NSArray<NSArray<Bet *> *> *sections;

很难受啊~但是没办法，只能这样设计，求指点

**Comment by kinarob** [comment]
@qinqi777 你可以把想要获取的数据在`mj_replacedKeyFromPropertyName`方法中做一层映射，比如demo中`MJStudent`类 `@"nameChangedTime" : @"name.info[1].nameChangedTime"`，希望有所帮助。

**Comment by wolfcon** [comment]
class XXX
var method: String?
var sections: [Section]?

class Section
var subSection: [SubSection]?

class SubSection
var bid: [Bid]?

class Bid
var title: String?
var bets: [Bet]?

class Bet
var number: Int = 0
var radius: Double = 0

**Comment by wolfcon** [comment]
建议你先 `String` 转 `Dictionary`, 然后拿 `Sections` 自己构造你的 `Bet` , 然后使用 MJExtension 进行解析
