### ISSUE TITLE
iOS12.0的问题

### ISSUE THREAD

**Issue by jiaocx** [CoderMJLee/MJExtension#623]
1个对象A包含一个数组B，B数组对象又包含一个数组C，数组C对象D继承一个对象E。结构是这样的，在iOS12.0之前11.0都没有问题，但是最后数组C对象的属性都不对。请帮忙看一下问题，谢谢

**Comment by kinarob** [comment]
@jiaocx 方便来份demo？

**Comment by kinarob** [comment]
@jiaocx 方便来一份demo吗？

**Comment by wolfcon** [comment]
@jiaocx 请给出你出问题的 Demo
