### ISSUE TITLE
【模型中有个数组属性，数组里面又要装着本身自己的模型】

### ISSUE THREAD

**Issue by manguoge** [CoderMJLee/MJExtension#624]
模型中有个数组属性，数组里面又要装着本身自己的模型，及多层嵌套自己的模型，这个如何转换和解析。
现在我解析出来的话，嵌套里面的模型是字典而不是模型

**Comment by kinarob** [comment]
@manguoge `+mj_objectClassInArray`中value存放当前的模型不能解决你的问题吗？如果是多层嵌套可以使用`+mj_replacedKeyFromPropertyName`做一层映射，然后再配合`+mj_objectClassInArray`就可以解析了。
