### ISSUE TITLE
Model里还有NSDecimalNum类型的属性时，转化之后为nil

### ISSUE THREAD

**Issue by zhangguangqian** [CoderMJLee/MJExtension#625]
Model里还有NSDecimalNum类型的属性时，转化之后为nil。
我看issues在2015年的时候，解决了。但是我用的是3.0.15.1（最新版）依然存在该问题。李大神，看一下。

**Comment by kinarob** [comment]
@zhangguangqian 

![wechatimg335](https://user-images.githubusercontent.com/29303030/43585207-226658c0-9697-11e8-9848-90d1b4fa8502.jpeg)
问题的原因在于判断value类型的时候，没有考虑是double类型，所以没有走NSDecimalNumber的解析方法，从而也导致将value置为nil了。

**Comment by kinarob** [comment]
@zhangguangqian  [#628](https://github.com/CoderMJLee/MJExtension/pull/628) 已经解决json数据是double类型，无法转model的NSDecimalNumber类型的情况，下载最新的代码试试！
