### ISSUE TITLE
调用崩溃，这个是arc的还是mrc的？

### ISSUE THREAD

**Issue by MonicaZhou** [CoderMJLee/MJExtension#627]
是不是要添加mrc的标示-fobjc-arc。
需要在文件前面添加相关警告啊

**Comment by kinarob** [comment]
@MonicaZhou 可否提供一下使用的版本和相关崩溃的信息呢，以便于帮助到您！`MJExtension`是ARC的
  >    s.source       = { :git => "https://github.com/CoderMJLee/MJExtension.git", :tag => s.version }
  s.source_files  = "MJExtension"
  s.requires_arc = true

**Comment by MonicaZhou** [comment]
嗯，知道了，代码是mrc的，没加arc的标示-fobjc-arc， 建议在文件中加上提示，谢谢～
