### ISSUE TITLE
objectArrayWithKeyValuesArray转换时，数据为空导致其他数据转换失败

### ISSUE THREAD

**Issue by weiched** [CoderMJLee/MJExtension#63]
我在使用objectArrayWithKeyValuesArray的时候，出现了这样一个问题。

比如我有这样一个类
@interface Student : NSObject
@property (nonatomic,copy) NSString *name;
@property (nonatomic,copy) NSString *name1;
@property (nonatomic,copy) NSString *name2;
@property (nonatomic,copy) NSString *name3;
@end 

然后我从服务器接收的字典，就是有Student类的数组组成的。
json格式为:
{
    "students": [
        {
            "name": "name",
            "name1": "name1",
            "name2": "name2",
            "name3": "name3"
        },
        {
            "name": "name",
            "name1": "name1",
            "name2": "name2",
            "name3": "name3"
        }
    ]
}

然后我使用objectArrayWithKeyValuesArray把它转成模型数组时，问题就出现了。
问题就是如果json中有一个数据为空，比如：
 {         "name": "name",
            "name1": "",
            "name2": "name2",
            "name3": "name3"
}，
这样会导致转换后的模型中，name1，name2，name3都为空。就是定义的属性中，按顺序name1之后的属性都是空。其他模型没有问题。

不知是不是我的使用问题，还望告知。

**Comment by CoderMJLee** [comment]
麻烦贴出模型的.h文件代码、服务器返回的字典、objectArrayWithKeyValuesArray的调用代码。要真实的哈。你的举例不一定和真实情况一样哦

**Comment by natewang** [comment]
我也会出现同样问题，是这样的，.h如下
@interface WURecommendDrugEntity : NSObject
@property (nonatomic, assign) NSInteger id;
@property (nonatomic, assign) NSInteger did;
@property (nonatomic, strong) NSString *dname;
@property (nonatomic, assign) double price;
@property (nonatomic, strong) NSString *img;
@property (nonatomic, assign) long indate;
@property (nonatomic, assign) long update_time;
@property (nonatomic, strong) NSString *factory;
@end
服务器json如下

{
drugRecommend: {
id: 13,
did: 1157,
dname: "维生素B1丸",
price: 11,
img: "resource/upload/2014_12_05/1417767971642_0.jpg",
indate: 1431408844319,
update_time: 1431408844319,
type: 1,
funattending: null,
factory: null
}
},
可以看到服务器中得factory字段是null，这在使用线面转化方法后
            WURecommendDrugEntity *recommendDrug = [WURecommendDrugEntity objectWithKeyValues:recommendDic[@"drugRecommend"]];

得到的recommendDrug中是没有factory的，当调用recommendDrug.factory时候就会奔溃，unrecognized selector sent to instance 。
希望在这种情况下可以加入自动初始化的值，我现在是自定义init方法中写的，不知道有没有更好的方法。
