### ISSUE TITLE
使用MJExtension 上架审核被拒2.5.1，请问是什么原因呢？

### ISSUE THREAD

**Issue by luhai7758** [CoderMJLee/MJExtension#632]
### 1. 具体信息如下：

Guideline 2.5.1 - Performance - Software Requirements

Your app uses or references the following non-public APIs:

[NSManagedObject allocWithEntity:] and [NSManagedObject allocBatch:withEntity:count:]

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change. 

Continuing to use or conceal non-public APIs in future submissions of this app may result in the termination of your Apple Developer account, as well as removal of all associated apps from the App Store.

Next Steps

If you are using third-party libraries, please update to the most recent version of those libraries. If you do not have access to the libraries' source, you may be able to search the compiled binary using the "strings" or "otool" command line tools. The "strings" tool can output a list of the methods that the library calls and "otool -ov" will output the Objective-C class structures and their defined methods. These tools can help you narrow down where the problematic code resides. You could also use the "nm" tool to verify if any third-party libraries are calling these APIs.

Resources

If there are no alternatives for providing the functionality your app requires, you can file an enhancement request. 

2. 使用终端命令扫描私有API 显示在MJExtension里边

 **终端扫描的具体信息如下：**

IMacdeiMac:yjq-ios imac$ grep -lr "NSManagedObject" * | grep -v .svn | grep -v .md
Pods/MJExtension/MJExtension/MJFoundation.m
Pods/MJExtension/MJExtension/NSObject+MJKeyValue.h
Pods/MJExtension/MJExtension/NSObject+MJKeyValue.m

请问该怎么解决呢？现在一点方向也没有，项目所有的数据都经过了MJExtension。

**Comment by kinarob** [comment]
@luhai7758 你的项目中用到了`MJExtension` 的哪些接口？

**Comment by luhai7758** [comment]
用了基本的字典、数组转模型，其它的基本没用到 @kinarob

**Comment by kinarob** [comment]
@luhai7758  有没有可能是你的项目的其他地方用到了私有的API，很多APP使用`MJExtension`，却没有出现这种审核的问题！

**Comment by CoderMJLee** [comment]
MJExtension里面确实有NSManagedObject，但并没用到NSManagedObject的allocWithEntity方法哦。其他人也并没有被拒的现象哈。NSManagedObject属于CoreData，你是否还用了其他基于CoreData的模块？

**Comment by kinarob** [comment]
@luhai7758 你检查一下看看，你的项目中是否还有其他地方用到了`NSManagedObject `。

**Comment by CoderMJLee** [comment]
你可以看看这3个文件：
Pods/MJExtension/MJExtension/MJFoundation.m
Pods/MJExtension/MJExtension/NSObject+MJKeyValue.h
Pods/MJExtension/MJExtension/NSObject+MJKeyValue.m
里面没有用到你说的API

你是否还用了一些静态库？也可能一些静态库中用到了私有API

**Comment by luhai7758** [comment]
嗯 里边只有NSManagedObject初始化、NSManagedObject的allocWithEntity和allocBatch没有。其它的静态库用了些、比如融360的。只是我试了几种扫描方法grep 、strings 和otool、扫NSManagedObject就进到了MJExtension、 扫allocWithEntity和allocBatch扫不出来也无法准确定位。好头大 @CoderMJLee

**Comment by CoderMJLee** [comment]
如果你没有用到CoreData，那你直接把NSManagedObject初始化相关代码都注释掉试试

**Comment by luhai7758** [comment]
😔试过了还是不行，把MJExtension暂时移除了还是有两个私有方法

**Comment by CoderMJLee** [comment]
那说明那2个不是来自MJExtension吧？哈哈

**Comment by luhai7758** [comment]
嗯，是的。不知道从哪里冒出来的，找又找不到。有没有可能是编译时系统自己加的？
