### ISSUE TITLE
Model 重数组的数组数据如果，Model转jsonstring ?jsonstring转Model?

### ISSUE THREAD

**Issue by sujiewen** [CoderMJLee/MJExtension#634]
我就是下面model转string,string 转model,不行，是不是我用错了？谢谢 我使用版本是pod 'MJExtension', '~> 3.0.15.1'，
<img width="789" alt="2018-08-26 9 09 04" src="https://user-images.githubusercontent.com/1973318/44628553-51e40a80-a974-11e8-9677-a5040f305e61.png">

.h 代码如下：
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//  LXLocationPointInfo.h
//
//  Created by Sjw on 2018/8/23.
//

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, LXLocationPointState) {
    LXLocationPointStateInit=0,
    LXLocationPointStateValidOn,
    LXLocationPointStateValidOff,
    LXLocationPointStateNotAddress,
    LXLocationPointStateHasAddress,
    LXLocationPointStateFail

};

typedef NS_ENUM(NSInteger, LXLocationUploadPointFlag) {
    //
    LXLocationUploadPointFlagInit=0,
    //上传点
    LXLocationUploadPointFlagUpload
};

typedef NS_ENUM(NSInteger, LXLocationPointUploadState) {
    //0:初始
    LXLocationPointUploadStateInit=0,
    //上传中
    LXLocationPointUploadStateUploading,
    //上传完成
    LXLocationPointUploadStateFinish,
    //上传失败
    LXLocationPointUploadStateFail
};

@interface LXLocationPointInfo : NSObject 
@property (nonatomic) NSInteger pointId;
@property (nonatomic, strong) NSString *scheduleId;
@property (nonatomic, strong) NSString *pointLocaleName;
@property (nonatomic, strong) NSString *pointLat;
@property (nonatomic, strong) NSString *pointLon;
@property (nonatomic, strong) NSString *createTime;
@property (nonatomic, strong) NSString *wifiName;
@property (nonatomic, strong) NSString *macAddress;
@property (nonatomic, strong) NSString *type;
@property (nonatomic, strong) NSString *code;
@property (nonatomic, strong) NSString *message;
@property (nonatomic) LXLocationPointState status;
@property (nonatomic) LXLocationPointUploadState uploadStatus;
@property (nonatomic) LXLocationUploadPointFlag uploadPointFlag;

@end

@interface LXLocationPointInfoArray : NSObject

@property (nonatomic, strong) NSMutableArray *keyArray;
@property (nonatomic, strong) NSMutableArray *itemArray;

@end

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
.m 代码如下：

//
//  LXLocationPointInfo.m
//  OfficeManagement
//
//  Created by Sjw on 2018/8/23.
//

#import "LXLocationPointInfo.h"
#import "MJExtension.h"

@implementation LXLocationPointInfo

- (id)mj_newValueFromOldValue:(id)oldValue property:(MJProperty *)property
{
//    if ([property.name isEqualToString:@"publisher"]) {
//        if (oldValue == nil) return @"";
//    } else if (property.type.typeClass == [NSDate class]) {
//        NSDateFormatter *fmt = [[NSDateFormatter alloc] init];
//        fmt.dateFormat = @"yyyy-MM-dd";
//        return [fmt dateFromString:oldValue];
//    }
//
    return oldValue;
}

//////转json，忽略属性
//+ (NSArray *)mj_ignoredPropertyNames {
//    return @[@"pointId",@"status",@"uploadStatus",@"uploadPointFlag"];
//}

- (instancetype)init
{
    self = [super init];
    if (self) {
#warning test 哪些是必须字段
    }
    return self;
}

@end

@implementation LXLocationPointInfoArray

+(void)load {
    [LXLocationPointInfoArray test];
}

+ (NSDictionary *)mj_objectClassInArray {
    return @{@"keyArray" : @"NSString",@"itemArray" : @"NSMutableArray<LXLocationPointInfo *>"};
}

- (instancetype)init
{
    self = [super init];
    if (self) {
        _keyArray = [NSMutableArray new];
        _itemArray = [NSMutableArray new];
    }
    return self;
}

+(void)test {
    LXLocationPointInfoArray *pDict = [LXLocationPointInfoArray new];
    [pDict.keyArray addObject:@"1"];
    LXLocationPointInfo *t = [LXLocationPointInfo new];
    NSMutableArray *tt = [NSMutableArray new];
    [tt addObject:t];
    [pDict.itemArray addObject:tt];
    
    NSMutableArray *dict = [pDict mj_keyValues];  //正常,但是数组数组的数据，还是类不是字典
    
    
//    id sss = [pDict mj_JSONData];   //无法转化，crash
    
//    NSString *strJson = [pDict mj_JSONString];  //无法转化，crash
    
//    我改怎么把model转成jsonstring?
}

@end

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by kinarob** [comment]
@sujiewen 为什么要在 `+(void)load`里面调用test 方法呢？

**Comment by sujiewen** [comment]
@kinarob 测试

**Comment by kinarob** [comment]
@sujiewen 最好不要在`+(void)load`方法中进行测试哦，你在其他方法中测试一下试试。
