### ISSUE TITLE
大小写的问题

### ISSUE THREAD

**Issue by goodcyg** [CoderMJLee/MJExtension#636]
在json转模型的时候，最好大小不分。我这里经常遇到和服务器那边，因为大小写的问题，转换失败？最新版测试了，也失败的？在讨论区没有找相关的解决办法？

**Comment by goodcyg** [comment]
我这边设计到底层端，服务器端。。。移动端，一端改了，我的都的改一遍。否则就是失败。增加一个增加一个大小写的开关，默认区分大小，否则就不区分大小写，这样会好很多。让他们服务器随便改吧？

**Comment by goodcyg** [comment]
@kinarob 是不是有bug？

**Comment by kinarob** [comment]
@goodcyg 老哥，你的意思是服务器端的字段是`Name`，然后你的属性里面定义的`name`，你想设置一个转换的开关，能解析你的`json`。

**Comment by goodcyg** [comment]
@kinarob 
是这个意思。

**Comment by kinarob** [comment]
@goodcyg 老哥，你可以尝试
```javascript
+ (NSDictionary *)mj_replacedKeyFromPropertyName
{
    return @{
              @"name" : @"Name",
             };
}
```
直接替换一下，不能解决问题吗？
设置一个开关的话，在源码上改动的比较大。

**Comment by goodcyg** [comment]
@kinarob 设置个开关改动不大的。你说这种是办法，但是还是解决不了我的问题。
服务端没有改一次，我这边不是的改动做一次映射？

**Comment by kinarob** [comment]
@goodcyg 你的意思，是服务端这个某个字段会经常大小写的切换？

**Comment by goodcyg** [comment]
@kinarob 是啊，设计到的人多。每改一次，都的大家讨论一番，沟通成本高啊。有没有啥技术含量。

**Comment by goodcyg** [comment]
@kinarob 还不是某个字段，例如：服务器端这次全是小写，服务器端下次全是大写，在下次是驼峰写。这不搞死了。

**Comment by kinarob** [comment]
@goodcyg 好的，好的。

**Comment by goodcyg** [comment]
@kinarob 
你帮MJ收集意见吗？

**Comment by kinarob** [comment]
😊😊


@kinarob<https://github.com/kinarob>
你帮MJ收集意见吗？

**Comment by CoderMJLee** [comment]
大小写区分肯定是要的，万一有同时name、Name两个属性呢？每个公司的业务不一样，个性化的东西，建议开发者自行解决哈，框架是只做一些通用的操作。你可以这么写
```objc
+ (NSDictionary *)mj_replacedKeyFromPropertyName
{
    return @{
              @"name" : @[@"name", @"Name"];
             };
}
```

**Comment by goodcyg** [comment]
@CoderMJLee 
虽然这种解决的办法，但是不是最佳的方案。例如：name，其中一个字母大写，2个字母大写，3个字母大写，4个字母大写，这是一个排列组合的问题。你要在如下中写多少中可能？
+(NSDictionary *)mj_replacedKeyFromPropertyName
{
    return @{
             @"name":@[@"name",@"nAme",@"naMe",@"namE",
                       @"Name",@"NAme",@"NaMe",@"NamE",@"NAME"，。。。。。。。。]
             };
}
光这个4个字母的组合就把你写晕了，如果key在长些，组合更多，哪不会把人写疯了？

**Comment by goodcyg** [comment]
@CoderMJLee
而你在属性赋值的核心方法里，统一转换成小写来赋值，可以彻底解决这个问题？

**Comment by PredatorDrillmaster** [comment]
老兄，你们后台设计字段都这么乱的吗，驼峰命名规则难道不是开发行业默认的命名规则？或者使用下划线来分割单词？要是我们后台能第一次给我命名出nAme，第二次是naMe，第三次namE……这样的东西，我第一件事就是在工作群骂一句傻逼，然后跟后台开发干一架，第二件事就是找老大或者老总谈话，要不他们改，要不他们走，或者我直接提辞职报告干不了。我不信哪个开发能忍受nAme/naMe/namE这样的东西，这明显属于设计不规范，这样的锅为什么要移动端的开发来背？我就想知道是哪位大神能这么命名字段的，以后有机会接触这群大神，我要好好请教一番

**Comment by PredatorDrillmaster** [comment]
哦对，还有一个办法，你下次发请求的时候，你也这么干，后台让你传nAMe，你就传给他NamE，再下次传NaMe，你让他们自己去解析，看他们怎么玩，他们不是喜欢瞎JB命名吗，你也瞎JB发请求，他们不管你解不解析的了，你也别管他们能不能解析的了

**Comment by goodcyg** [comment]
@PredatorDrillmaster 小公司，说出来都是泪，都是你的领导，没有编码规范，都是各自为政。鬼知道下次搞个啥？有时候甚至给字典key都是iOS的关键字，这些你说能处理吧？能，完全能，但是看起来蛋疼啊。在命名是就能避免的问题，为什么最后需要移动端用代码来解决呢？而我想法就是能不能在字典转模型的时候，就杜绝这个没有技术含量的问题？

**Comment by goodcyg** [comment]
我自己修改也没有啥问题，或许有些兄弟，也遇到我这样困窘。如果框架也能完全杜绝解决这个问题。岂不美哉？

**Comment by Henry519** [comment]
> 我自己修改也没有啥问题，或许有些兄弟，也遇到我这样困窘。如果框架也能完全杜绝解决这个问题。岂不美哉？

这纯粹是命名规范问题，只能要求你们服务端改正，别提这些没营养的issue
