### ISSUE TITLE
对于子类中用@dynamic的属性，解释不了；

### ISSUE THREAD

**Issue by weiming8202** [CoderMJLee/MJExtension#638]
# BaseListResponseResultItem
@interface BaseListResponseResultItem : XLIQJsonBaseItem
@property (nonatomic,strong)NSNumber *totalCount;
@property (nonatomic,strong)NSMutableArray *items;
- (NSArray<PropertyOptionItem *> *)getOptionItems;
@end

# BaseListResponse
@interface BaseListResponse : BaseResponse
@property (nonatomic,strong)BaseListResponseResultItem *result;
@end

# ContactGetAllPagedResponse
@interface ContactGetAllPagedResponse : BaseListResponse

@property (nonatomic,strong)Contacts *result;

@end

# Contacts
@interface Contacts : BaseListResponseResultItem

@property (nonatomic,strong)NSMutableArray *items;

@end

@implementation Contacts

@dynamic items;

- (id)init{
    self = [super init];
    if(self){
        if([self respondsToSelector:@selector(configRegular)]){
            [self configRegular];
        }
    }
    return self;
}

- (void)configRegular{
    
    Class klass = [self class];
    NSString* className = NSStringFromClass(klass);
    
    [klass mj_setupObjectClassInArray:^NSDictionary *{
        return @{
                 @"items" : @"Contact"
                 };
    }];
}

Contact没有被正确解释，最终解释出来的数组里包含的还是dictionary;

**Comment by wolfcon** [comment]
dynamic 需要你自己实现 `get` 和 `set` 方法. 如果实现了, 有保存在私有实例变量中. 解析是没有问题的.

是不是你的 get 和 set 方法的问题? 能给出完整的小 Demo 吗? 

我这边测试时没有问题的.
