### ISSUE TITLE
mj_jsonObject方法存在的问题

### ISSUE THREAD

**Issue by hengyizhangcn** [CoderMJLee/MJExtension#649]
当一个普通的对象，需要转换成json时，调用mj_jsonObject是没问题的，如

```
@interface Person : NSObject
/*
 姓名
 */
@property (nonatomic, copy) NSString *name;

@end
```

转换json后的值打印为：

>{
>
>​    name = Michael;
>
>}

当一个遵守某个协议的对象，再调用mj_jsonObject方法，返回的值不是一个有效的json对象，如：

```
@interface Person : NSObject <SCOrderConfirmProductListProtocol>

/*
 姓名
 */
@property (nonatomic, copy) NSString *name;

@end
```

转换json后的的值打印为

>{
>
>​    debugDescription = "<Person: 0x600003e78390>";
>
>​    description = "<Person: 0x600003e78390>";
>
>​    hash = 105553181770640;
>
>​    name = Michael;
>
>​    superclass = NSObject;
>
>}

调用[NSJSONSerialization isValidJSONObject:personInfo]发现，它不是一个有效的json对象

**Comment by zhzDeveloper** [comment]
SCOrderConfirmProductListProtocol 不要继承 NSObject 协议

**Comment by CoderYQ** [comment]
MJE的确存在这样的问题，SCOrderConfirmProductListProtocol 由于继承 NSObject 协议，所以MJE在转换的时候将  NSObject 协议中的 hash、superclass、description、debugDescription 属性也一并转换了（很明显这是不应该的），楼上提到了一种解决办法："SCOrderConfirmProductListProtocol 不要继承 NSObject 协议"，可以解决这种问题，但是这对自定义协议的遵守有一些要求，解决方式不够优雅。我尝试用YYModel 进行同样的测试，发现YYModel 并不会这样，楼上两位有兴趣可以去了解两者的源码一探究竟。

**Comment by wolfcon** [comment]
这个问题已经修复

**Comment by hengyizhangcn** [comment]
wonderful!
