### ISSUE TITLE
mj_objectClassInArray 不支持解析NSNumber成NSString

### ISSUE THREAD

**Issue by louis-ly** [CoderMJLee/MJExtension#651]
/**
 *  数组中需要转换的模型类
 *
 *  @return 字典中的key是数组属性名，value是数组中存放模型的Class（Class类型或者NSString类型）
 */
+ (NSDictionary *)mj_objectClassInArray;
方法说明是说支持Class类型或者NSString，后台返回的数组里是NSNumber，然后我 return @{@"colaIds" : NSString.class};  解析出来的数组里还是NSNumber

**Comment by JRJian** [comment]
你的模型对象实现这个方法
`- (id)mj_newValueFromOldValue:(id)oldValue property:(MJProperty *)property {
    if ([property.name isEqualToString:@"xxx"]) {// 属性名匹配
        if ([oldValue isKindOfClass:[NSNumber class]]) {
            return [NSString stringWithFormat:@"%@", oldValue];
        }
    }
    return oldValue;
}`
