### ISSUE TITLE
打印对象数组失败

### ISSUE THREAD

**Issue by KearLiao** [CoderMJLee/MJExtension#652]
李老师你好
使用mj_objectArrayWithKeyValuesArray得到数组  打印出来是
![image](https://user-images.githubusercontent.com/10768739/50126893-c509e780-02a9-11e9-9237-6e4105211be7.png)
有.m添加MJExtensionLogAllProperties
打印数组中的单个对象没问题 po整个对象数组也没问题

**Comment by JackZhoujian** [comment]
你应该注意单个遍历


On Dec 18, 2018, at 9:47 AM, KearLiao <notifications@github.com<mailto:notifications@github.com>> wrote:


李老师你好
使用mj_objectArrayWithKeyValuesArray得到数组 打印出来是
[image]<https://user-images.githubusercontent.com/10768739/50126893-c509e780-02a9-11e9-9237-6e4105211be7.png>
有.m添加MJExtensionLogAllProperties
打印数组中的单个对象没问题 po整个对象数组也没问题
