### ISSUE TITLE
json -> model -> json, NSDate的转换问题

### ISSUE THREAD

**Issue by huangqingchao** [CoderMJLee/MJExtension#654]
我从服务器获取到的日期格式是 "yyyy-MM-dd"，通过
`- (id)mj_newValueFromOldValue:(id)oldValue property:(MJProperty *)property;`
可以将NSString类型的"2018-12-12"转换为 NSDate类型的 2018-12-11 16:00:00 +0000。
但是将Model反转回Json时，会转成NSString类型的"2018-12-11 16:00:00 +0000"，有没有方法可以Model反转Json时也转成"2018-12-12"？类似于`mj_newValueFromOldValue`的方法。

谢谢大佬们解答！

**Comment by kinarob** [comment]
@huangqingchao 目前`MJExtension`还不支持这种操作哟！

**Comment by ElfSundae** [comment]
@huangqingchao 
https://github.com/CoderMJLee/MJExtension#-nsdate---nsstring%E6%A8%A1%E5%9E%8B%E8%BD%AC%E5%AD%97%E5%85%B8%E6%97%B6-%E4%BF%AE%E6%94%B9-date-%E7%B1%BB%E5%9E%8B%E8%87%B3-string
```objc
- (void)mj_objectDidConvertToKeyValues:(NSMutableDictionary *)keyValues {
    // NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
    // formatter.dateFormat = @"yyy-MM-dd";
    // should use sharedFormatter for better performance  
    keyValues[@"publishedTime"] = [sharedFormatter stringFromDate:self.publishedTime];
}
```
