### ISSUE TITLE
打开全局错误断点，总是是会莫名地停在 - (void)setValue:(id)value forObject:(id)object

### ISSUE THREAD

**Issue by KaoUserName** [CoderMJLee/MJExtension#657]
![image](https://user-images.githubusercontent.com/42034681/53223529-998de980-36ac-11e9-940f-821c073a096d.png)

**Comment by kinarob** [comment]
@KaoUserName 你用的版本是多少？

**Comment by kinarob** [comment]
`Clean Build Folder` 清除Xcode 缓存试试呢。

**Comment by KaoUserName** [comment]
3.0.15.1。
Clean Build Folder 之后，还是老样子

**Comment by kinarob** [comment]
@KaoUserName 方便上传一份Demo吗？

**Comment by K-Dragon** [comment]
我也碰到了，上来瞅瞅发现不止我一人 。。。

**Comment by K-Dragon** [comment]
我用的是3.0.15，3.0.16 Carthage安装不了

**Comment by wolfcon** [comment]
@K-Dragon 再试试. 另外, 能传一份 Demo 吗/

**Comment by KaoUserName** [comment]
是因为需要解析的模型遵守了某个协议导致莫名地停在 - (void)setValue:(id)value forObject:(id)object 。
3.0.16已解决
