### ISSUE TITLE
键值对的值对应的是数组，数组里面都是子数组，子数组里存了两个元素：经度和纬度，但不是字典格式，怎么办

### ISSUE THREAD

**Issue by Dast1990** [CoderMJLee/MJExtension#658]
您好，键值对的值对应的是数组，数组里面都是子数组，子数组里存了两个元素：经度和纬度，但不是字典格式，请问该如何处理？
eg:
{"arr" : [
[110.11, 23.22],
[111.11, 23.33]
]}

**Comment by kinarob** [comment]
数组里面再嵌套一层数组，不能结局你的问题吗?
Array -> Array -> 对象

**Comment by Dast1990** [comment]
@kinarob 不是很明白你的意思，初步解决方案是把[110.11, 23.22]这种格式装换为字典格式{"lati" : "110.11", "longti" : "23.22"}，然后进行字典转模型

**Comment by wolfcon** [comment]
@Dast1990 
1. 嵌套为 Array1<Array2>, Array2的为你的经纬度信息
2. 联系服务端封装

**Comment by Dast1990** [comment]
> @ Dast1990
> 
> 1. 嵌套为Array1，Array2的为你的经纬度信息
> 2. 联系服务端封装

谢谢，最近才想到了第一种方法
