### ISSUE TITLE
模型转字典时能否动态指定所需要的字段名?

### ISSUE THREAD

**Issue by larrytin** [CoderMJLee/MJExtension#66]
keyValues方法能否加个参数(数组类型, 指定所需要转换的字段名), 因为每次调用keyValues时希望得到的字段都可能不一样

**Comment by larrytin** [comment]
最好能有这么一个方法
keyValues:(NSArray *)filterKeys exclude:(NSArray *)excludeKeys

**Comment by CoderMJLee** [comment]
已经增加

**Comment by larrytin** [comment]
好快, 谢了
