### ISSUE TITLE
多线程环境下崩溃

### ISSUE THREAD

**Issue by pengshengsongcode** [CoderMJLee/MJExtension#660]
pod 'MJExtension', '3.0.15.1'

![image](https://user-images.githubusercontent.com/18256030/53405222-56a47c80-39f2-11e9-9174-ea9434c50431.png)

**Comment by kinarob** [comment]
在 #656 已经修复了这个问题！

**Comment by yuwind** [comment]
> 在 #656 已经修复了这个问题！

还存在这个问题，还是会崩溃，我这也是

**Comment by kinarob** [comment]
@yuwind 还没有发布最新的版本，如果没有使用cocoapods，可以直接克隆新的代码到项目中！

**Comment by yuwind** [comment]
@kinarob 我就是按照你修复的哪种方法改的，发现还是存在崩溃，频率蛮高的。
![image](https://user-images.githubusercontent.com/16901415/53734716-beaa0580-3ebf-11e9-9956-3b0723364041.png)

**Comment by kinarob** [comment]
![1551705940598](https://user-images.githubusercontent.com/29303030/53736232-1cd8e780-3ec4-11e9-8155-d6d664079e14.jpg)

**Comment by kinarob** [comment]
上面的崩溃显示是在`properties`方法出现的问题，你的崩溃也是这样的吗？

**Comment by yuwind** [comment]
@kinarob  对，就是这个问题

**Comment by yuwind** [comment]
@kinarob 
![image](https://user-images.githubusercontent.com/16901415/53775652-56463d00-3f2e-11e9-8427-93f9d51797c7.png)

**Comment by kinarob** [comment]
@yuwind 你的崩溃在这个类`MJProperty`这段代码上：
```objc
- (NSArray *)propertyKeysForClass:(Class)c
{
    NSString *key = NSStringFromClass(c);
    if (!key) return nil;
    return self.propertyKeysDict[key];
}
```

**Comment by yuwind** [comment]
@kinarob 这句话不应该导致崩溃吧，字典取值，取不到也不过是个nil哦。

**Comment by kinarob** [comment]
跟上面的崩溃不在一个地方

**Comment by kinarob** [comment]
你将这两个方法加一下锁试试，看日志是这两个方法也存在问题：
```Objc
- (NSArray *)propertyKeysForClass:(Class)c {
    NSString *key = NSStringFromClass(c);
    if (!key) return nil;
    
    MJExtensionSemaphoreCreate
    MJExtensionSemaphoreWait
    NSArray *propertyKeys = self.propertyKeysDict[key];
    MJExtensionSemaphoreSignal
    return propertyKeys;
}

- (Class)objectClassInArrayForClass:(Class)c {
    NSString *key = NSStringFromClass(c);
    if (!key) return nil;
    
    MJExtensionSemaphoreCreate
    MJExtensionSemaphoreWait
    Class objectClass = self.objectClassInArrayDict[key];
    MJExtensionSemaphoreSignal
    return objectClass;
}

```

**Comment by yuwind** [comment]
@kinarob  ok，谢谢 ,我试下，感觉取值不应该出现多线程问题哦。

**Comment by kinarob** [comment]
对于`NSMutable`容器 在多线程的环境下，`setter`和`getter`方法都需要加锁。

**Comment by kinarob** [comment]
@yuwind 怎么样，还有crash吗？

**Comment by yuwind** [comment]
@kinarob 这个暂时还测不出来，需要等到线上用户量大了才能体现。

**Comment by kinarob** [comment]
@yuwind 好的，目前代码还没有发版，你发包的时候确定一下，锁的代码是否已经加上了，如果还有crash的情况，你再通知一声！

**Comment by yuwind** [comment]
@kinarob 好的，谢谢！

**Comment by yuwind** [comment]
@kinarob 那个崩溃解决了，但是上述的加锁是有问题的，多线程下字典取值并不会崩溃，只有边取值边赋值才会导致野指针，感谢你提供了思路，正确的解法是创建全局锁，赋值和取值必须为同一把锁，部分代码如下：
```objc
- (void)setPorpertyKeys:(NSArray *)propertyKeys forClass:(Class)c
{
    if (propertyKeys.count == 0) return;
    NSString *key = NSStringFromClass(c);
    if (!key) return;
    
    dispatch_semaphore_wait(_propertySemaphore, DISPATCH_TIME_FOREVER);
    self.propertyKeysDict[key] = propertyKeys;
    dispatch_semaphore_signal(_propertySemaphore);
}

- (NSArray *)propertyKeysForClass:(Class)c
{
    NSString *key = NSStringFromClass(c);
    if (!key) return nil;
    dispatch_semaphore_wait(_propertySemaphore, DISPATCH_TIME_FOREVER);
    NSArray *propertyArray = self.propertyKeysDict[key];
    dispatch_semaphore_signal(_propertySemaphore);
    return propertyArray;
}

```

**Comment by kinarob** [comment]
>@kinarob  那个崩溃解决了，但是上述的加锁是有问题的，多线程下字典取值并不会崩溃，只有边取值边赋值才会导致野指针

多线程可变字典取值都要加锁吧！ https://github.com/SDWebImage/SDWebImage/blob/44b39715bb76034b9c12b4621ed1bbb8a378e81f/SDWebImage/SDWebImageDownloader.m#L186

**Comment by kinarob** [comment]
当前的加锁确实都是同一把锁，只是有点影响效率。正确的做法，是对每一个可变容器，声明一把锁。

**Comment by yuwind** [comment]
@kinarob 是的，每个容器一个锁。

**Comment by kinarob** [comment]
@yuwind 老哥，可以看看 #667 的代码吗，能不能解决你的问题？

**Comment by yuwind** [comment]
@kinarob 你好，这样是可以解决这个问题的，我修改的源码也是这样改的。

**Comment by kinarob** [comment]
@yuwind 好的，稍后我将发布3.0.16版本。

**Comment by pengshengsongcode** [comment]
没有更新pod么？

**Comment by kinarob** [comment]
还没？

**Comment by pengshengsongcode** [comment]
Search 不到




| |
彭盛凇
邮箱：psscode@163.com
|

签名由 网易邮箱大师 定制

在2019年03月25日 19:12，Kinarobin 写道：

还没？

**Comment by kinarob** [comment]
还有一个 #667 没有合进去，合并了马上发布新的版本！

**Comment by kinarob** [comment]
@pengshengsongcode @yuwind 发布了 3.0.16的版本。

**Comment by pengshengsongcode** [comment]
感恩




| |
彭盛凇
邮箱：psscode@163.com
|

签名由 网易邮箱大师 定制

在2019年03月27日 19:27，Kinarobin 写道：

Closed #660.

**Comment by a330416020** [comment]
hello,我这边使用MJExtension 最新版本的3.2.1 的，线上版本还是会出现启动闪退问题。这个不是必现的。请问下这是什么原因。
![1585109141688](https://user-images.githubusercontent.com/4032392/77500888-4c70de00-6e91-11ea-8c1c-3dc7e24bdc9f.jpg)

**Comment by fypyxz** [comment]
我这边使用MJExtension 最新版本的3.2.4 的，线上版本还是会出现启动闪退问题。也是偶发的。
![7A2E6948-CF6E-4A44-B7CE-06231979020C](https://user-images.githubusercontent.com/4725045/110412248-d2982b80-80c6-11eb-9ebc-e7f16080152e.png)
看到问题记录，我先尝试异步串行队列处理该数据解析，看看还有没有反馈

**Comment by wolfcon** [comment]
你是不是使用了 `mj_setupObjectClassInArray`

**Comment by fypyxz** [comment]
谢谢，我是使用了mj_setupObjectClassInArray

**Comment by fypyxz** [comment]
好的谢谢，你的3.2.5版本，我会替换方法解决这个问题

**Comment by fypyxz** [comment]
3.2.5版本预计什么时候更新

**Comment by wolfcon** [comment]
你可以先试这个分支

`pod 'MJExtension', :git => 'https://github.com/MJExtension/MJExtension.git', :branch => 'fix/fixing-racing-condition'`
