### ISSUE TITLE
-[__NSCFConstantString substringFromIndex:]: Index 1 out of bounds; string length 0

### ISSUE THREAD

**Issue by Daemonson** [CoderMJLee/MJExtension#663]
0 CoreFoundation | ___exceptionPreprocess + 228
-- | --
1 libobjc.A.dylib | objc_exception_throw + 56
2 CoreFoundation | -[NSCache init]
3 Foundation | -[NSString substringFromIndex:] + 132
4 App | -[MJProperty setProperty:] (MJProperty.m:0)
5 App | +[MJProperty cachedPropertyWithProperty:] (MJProperty.m:40)
6 App | __32+[NSObject(Property) properties]_block_invoke_2 (NSObject+MJProperty.m:167)
7 App | +[NSObject(MJClass) mj_enumerateClasses:] (NSObject+MJClass.m:61)
8 App | +[NSObject(Property) properties] (NSObject+MJProperty.m:180)
9 App | +[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:0)
10 App | -[NSObject(MJKeyValue) mj_setKeyValues:context:] (NSObject+MJKeyValue.m:197)
11 App | +[NSObject(MJKeyValue) mj_objectWithKeyValues:context:] (NSObject+MJKeyValue.m:218)
12 App | +[NSObject(MJKeyValue) mj_objectArrayWithKeyValuesArray:context:] (NSObject+MJKeyValue.m:0)

线上突然出现这个崩溃，应该是接口返回的数据有异常，但是setProperty这个方法中的字符串截取操作是否有必要做下容错？
![image](https://user-images.githubusercontent.com/7628550/54081132-6ef19100-433a-11e9-8a68-9e2f626b50bd.png)

**Comment by kinarob** [comment]
具体是什么类型的属性产生的crash，可以提供一下吗？

**Comment by Daemonson** [comment]
@kinarob 我们看了有问题的用户接收到的接口数据，没有什么异常，我们也复现不了这个问题，这个不好确定是哪个类型引起的。

**Comment by kinarob** [comment]
这个问题引起的崩溃率高吗？

**Comment by Daemonson** [comment]
@kinarob 昨天有一个用户崩溃了6次😀，接口返回数据有不确定的特殊异常，这种公共库可以不做兼容的。不过这种涉及index的操作做下容错应该更安全些
