### ISSUE TITLE
使用 MJCodingImplementation 崩溃

### ISSUE THREAD

**Issue by KaoUserName** [CoderMJLee/MJExtension#664]
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/42034681/54617739-d4612280-4a9c-11e9-96fa-0cfb87a307a3.png">

<img width="615" alt="image" src="https://user-images.githubusercontent.com/42034681/54618115-6e28cf80-4a9d-11e9-9051-34ec99feca87.png">
协议对象是没有办法归档的吗

**Comment by kinarob** [comment]
@KaoUserName 你Model 定义的内容方便贴出来吗？

**Comment by KaoUserName** [comment]
2019-03-20 14:44:21.709106+0800 QZBorrow[8221:2336458] +[NSObject encodeWithCoder:]: unrecognized selector sent to class 0x1b89ddea0
2019-03-20 14:44:21.712245+0800 QZBorrow[8221:2336458] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSObject encodeWithCoder:]: unrecognized selector sent to class 0x1b89ddea0'
*** First throw call stack:
(0x19270afe0 0x19116c538 0x192711e34 0x19270ef54 0x19260ad4c 0x19315efd4 0x1001de67c 0x1001e66b0 0x1001de3bc 0x1000f9aa8 0x19315efd4 0x193165e9c 0x10014b5a8 0x10013a600 0x10010dbd0 0x100123ca8 0x100153f64 0x10017601c 0x1008b5a50 0x1008b5a10 0x1008ba8b0 0x1926b90c8 0x1926b6ce4 0x1925e6da4 0x194051074 0x1988a1c9c 0x1001352ac 0x1915f559c)
libc++abi.dylib: terminating with uncaught exception of type NSException

![image](https://user-images.githubusercontent.com/42034681/54664338-e8e5ff00-4b1e-11e9-8d0d-5afdabc4f881.png)
![image](https://user-images.githubusercontent.com/42034681/54664339-eaafc280-4b1e-11e9-820d-34a33f90c460.png)

**Comment by kinarob** [comment]
Fix via [#665](https://github.com/CoderMJLee/MJExtension/pull/665)
