### ISSUE TITLE
做简单测试时，转换（方法调用）失败

### ISSUE THREAD

**Issue by Golduko** [CoderMJLee/MJExtension#67]
![代码与报错截图](https://cloud.githubusercontent.com/assets/11625453/7605509/f3157506-f982-11e4-9443-4542bd66af3f.png)

不知道原因，在Demo中测试没有问题。

**Comment by CoderMJLee** [comment]
可以把Demo发到邮箱么？

**Comment by Golduko** [comment]
可以的，但是您的邮箱是？前面的README没有。

**Comment by CoderMJLee** [comment]
richermj123go@vip.qq.com

**Comment by CoderMJLee** [comment]
我看了下你的代码哈，是因为MJExtension框架没有参与编译。你将MJExtension文件夹拽进项目时记得勾选：Add to targets

**Comment by Golduko** [comment]
......自己检查了一下，果真是的，这么低级的错误。
谢谢您抽出时间解决了我的问题。

**Comment by CoderMJLee** [comment]
不客气
