### ISSUE TITLE
Carthage build failed

### ISSUE THREAD

**Issue by darkThanBlack** [CoderMJLee/MJExtension#670]
**WHAT I DO:**
in Cartfile：
```
github "CoderMJLee/MJExtension"
```
then，run command in shell：``$carthage update --platform "iOS"``

**WHAT I MEET：**
```
Skipped building MJExtension due to the error:
Dependency "MJExtension" has no shared framework schemes for any of the platforms: iOS
```

**Other：**
I sure it works in old version.

---

**我做了什么：**
创建一个Cartfile文件，内容为：
```
github "CoderMJLee/MJExtension"
```
在命令行运行：``$carthage update --platform "iOS"``

**出现了什么问题：**
```
Skipped building MJExtension due to the error:
Dependency "MJExtension" has no shared framework schemes for any of the platforms: iOS
```

**补充：**

对旧版本的MJExtension而言carthage可以生效。

---

**Thanks!**

**Comment by wolfcon** [comment]
已经修复
