### ISSUE TITLE
您好！请问一下 同一字段 不同类解析如果实现

### ISSUE THREAD

**Issue by hsm209** [CoderMJLee/MJExtension#676]
我的需求是这样的，比如服务端返回json结构为{"code":"0","message":"成功","data":{"obj":{}}}
而这个code,message,data这3个固定的，针对不同的接口，data下面的obj不一样。
此需求在java那边通过范型很方便解决，不知道iOS方面有没有好办法，谢谢！

**Comment by wolfcon** [comment]
Parent Class:
```swift
var code: String?
var message: String?
```

Subclass: 
```swift
var data: XXXClass?
```

**Comment by hsm209** [comment]
这样子不方便，我是想这样定义

**Comment by wolfcon** [comment]
泛型对于 Objective-C 而言只是在编译期之前的一个 🍬, 并不能作用于 Runtime 时期

其实继承还是不太好, 更好的方式应该是这样

Common protocol:
```swift
@objc var code: String?
@objc var message: String?
```

Class: Common protocol
```swift
@objc var data: XXXClass?
```
