### ISSUE TITLE
Json转Model   精度丢失问题

### ISSUE THREAD

**Issue by airy99** [CoderMJLee/MJExtension#677]
**Json数据中某个Value是Double类型**
**Model中定义Double、NSDecimalNumber、NSNumber类型接收，都会出现精度丢失问题**

**示例**
![image](https://user-images.githubusercontent.com/12271307/56020837-ab018280-5d3a-11e9-89fd-aca9edb1917a.png)

**尝试修改**
NSObject+MJKeyValue.m
![image](https://user-images.githubusercontent.com/12271307/56110744-2c018980-5f88-11e9-8504-6b7965b615ff.png)

**Comment by wolfcon** [comment]
兄弟你试了吗? 我这边测试 `NSDecimalNumber` 是正常的哟?

**Comment by wolfcon** [comment]
请更新版本
