### ISSUE TITLE
protocol_copyPropertyList 使用有内存泄漏

### ISSUE THREAD

**Issue by cnxbox360** [CoderMJLee/MJExtension#679]
protocol_copyPropertyList 官方文档解释，最后必须free获得的数组

**Comment by wolfcon** [comment]
> A C array of pointers of type objc_property_t describing the properties declared by proto. Any properties declared by other protocols adopted by this protocol are not included. The array contains *outCount pointers followed by a NULL terminator. You must free the array with free().

If the protocol declares no properties, NULL is returned and *outCount is 0.

You're right. thx
