### ISSUE TITLE
字典转JsonString 使用mj_JSONString崩溃

### ISSUE THREAD

**Issue by JCInTheShadow** [CoderMJLee/MJExtension#684]
字典转JsonString时,报错NSInvalidArgumentException , reason: 'Invalid type in JSON write (NSError)'
![1558064284899](https://user-images.githubusercontent.com/21034742/57901619-7d0ee100-7898-11e9-8f3b-c4c244c28526.jpg)
![1558064447706](https://user-images.githubusercontent.com/21034742/57901762-ee4e9400-7898-11e9-85ab-992f9978a21f.jpg)

**Comment by kinarob** [comment]
@JCInTheShadow 方便把errorDict里面的内容打出来吗？我调试一下？

**Comment by JCInTheShadow** [comment]
@kinarob 我已经找到问题了,因为errorDict里面有一个NSError的对象
