### ISSUE TITLE
两级json数据中存在相同属性名问题

### ISSUE THREAD

**Issue by cailiangdev** [CoderMJLee/MJExtension#686]
{
        list: [
                      name: "1",
                      list: [
                                 {
                                          name: "222"
                                  }
                              ]
              ] 

}

**Comment by cailiangdev** [comment]
解析出来第二层list == nil

**Comment by wolfcon** [comment]
是没有问题的, 你的代码写的有问题吧. 方便 Demo 放上来吗?
