### ISSUE TITLE
description

### ISSUE THREAD

**Issue by Bob-WPF** [CoderMJLee/MJExtension#688]

**Comment by Bob-WPF** [comment]
Model的propertyClass类型是NSString，json的值类型是NSNumber，
NSObject+MJKeyValue.m中148行的[value description]会出现精度丢失问题，是否可以通过NSDecimalNumber进行转换？

**Comment by wolfcon** [comment]
Duplicate of #572

**Comment by Bob-WPF** [comment]
确实可以通过服务端传string，计算时用DecimalNumber转解决问题，但是这里NSNumber -> NSString的问题还是存在的啊。
`                if (propertyClass == [NSString class]) {
                    if ([value isKindOfClass:[NSNumber class]]) {
                        // NSNumber -> NSString
                        value = [value description];
                    } else if ([value isKindOfClass:[NSURL class]]) {
                        // NSURL -> NSString
                        value = [value absoluteString];
                    }
                }`

**Comment by wolfcon** [comment]
建议仔细看看 #572 , 计算机在使用 Number 表示 Double/Float 类型时的机制是什么.

你需要特别告诉计算机, 处理这个 Double 要用 DecimalNumber 来去处理, 否则他会按照 Double 和 Float 来去处理. 精度就不能保证的.建议好好学习一下基本的知识😁
