### ISSUE TITLE
调用`mj_setupReplacedKeyFromPropertyName`方法闪退

### ISSUE THREAD

**Issue by MakeHui** [CoderMJLee/MJExtension#689]
> 设备：iPad 3 wifi 9.3.5

使用 iPad 模拟器 9.3 也可以复现
新版本系统则没有这个问题

**Comment by MakeHui** [comment]
经测试：3.0.15.1 使用正常

**Comment by wolfcon** [comment]
崩溃信息方便发出来吗?

**Comment by MakeHui** [comment]
项目中 example 可以复现出来

**Comment by wolfcon** [comment]
你重新试一下吧, Example 之前是有点小问题的, 在 iOS 10 以下

**Comment by MakeHui** [comment]
#545 和这个应该是同一个问题
我尝试把这个问题修复的代码去掉，就出现了我当前遇到的问题
希望尽快 release ，目前最新版本并没有包含 #545 修复的代码块

**Comment by wolfcon** [comment]
你上传一个 demo 吧. 你的问题跟这个毫无关系. 只是随手修复了一个 Example 的 bug. 引入项目并不影响的啊

**Comment by MakeHui** [comment]
https://github.com/MakeHui/MJExtensionDemo-Crash

我使用的模拟器： ipad retina (ios 9.3)

---

我线上应用崩溃的堆栈信息

![17BE89B1-10A8-4A1A-9446-8F90F3DC6239](https://user-images.githubusercontent.com/8622405/58941473-70eab500-87ae-11e9-992f-9e0e0a6cd72f.png)

**Comment by 13104495959** [comment]
@MakeHui  你的项目换成cocoapods集成试一下, 我使用carthage在低版本的iPad上面也会出现无法链接的情况, 使用cocoapods这一正常运行

**Comment by MakeHui** [comment]
@13104495959 确实有可能是你说的原因，在类还没有加载的时候进行反射操作容易出现这种问题，但是我在上面的疑问并不能用这个结论解释（能控制的变量我都尝试控制了，问题依旧）

BTW: 我暂时退到低版本保平安了
