### ISSUE TITLE
关于model的copy和mutablecopy

### ISSUE THREAD

**Issue by MrStock007** [CoderMJLee/MJExtension#690]
平时可能有一个需求就是把一个model传到下个控制器，直接A_VC.model = B_VC.model; A和B就会是同一地址，同时改变。实现copy或mutablecopy协议的话又比较麻烦，而且需要把每一个属性都写一遍，遇到新加属性，就会容易遗漏，比较不安全。
最近试了NSMutableDictionary *dict = [self.model mj_keyValues];
               Model *newModel = [Model mj_objectWithKeyValues:dict];
   能满足copy或mutablecopy的需求，但还是希望MJ能给来个更牛的实现，直接加上mj_copy和mj_mutablecopy。

**Comment by wolfcon** [comment]
copy 有深浅, 实现不能够满足所有的类型. 这个还是开发者自己实现.
