### ISSUE TITLE
最新版本 v3.0.17是否支持iOS7

### ISSUE THREAD

**Issue by mqlsq** [CoderMJLee/MJExtension#695]
在最新版本的podspec中,移除了iOS7的支持,变成最低支持iOS8,但是我使用iOS7去编译运行,发现并没有什么问题.MJExtension内部是否有使用iOS8之后的api?

**Comment by wolfcon** [comment]
兄弟. 你得自行测试了. 因为新版本的 Xcode 没有 iOS 7 模拟器. 而且设备也非常稀少了, 不在维护了
