### ISSUE TITLE
测试人员的手机iphone6splus 系统12.3.1 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (NSURL)'

### ISSUE THREAD

**Issue by wangzhao0630** [CoderMJLee/MJExtension#696]

**Comment by wangzhao0630** [comment]
'NSInvalidArgumentException', reason: 'Invalid type in JSON write (NSURL)'
#pragma mark - 转换为JSON
- (NSData *)mj_JSONData
{
    if ([self isKindOfClass:[NSString class]]) {
        return [((NSString *)self) dataUsingEncoding:NSUTF8StringEncoding];
    } else if ([self isKindOfClass:[NSData class]]) {
        return (NSData *)self;
    }
    
    return [NSJSONSerialization dataWithJSONObject:[self mj_JSONObject] options:kNilOptions error:nil];
}
走到     return [NSJSONSerialization dataWithJSONObject:[self mj_JSONObject] options:kNilOptions error:nil];报错的

**Comment by wangzhao0630** [comment]
只有他的手机有这个问题,好奇怪

**Comment by wolfcon** [comment]
你调用的是哪个方法?

方便的话贴出错误堆栈

**Comment by wangzhao0630** [comment]
好的.多谢,去复查

**Comment by wolfcon** [comment]
> 好的.多谢,去复查

注意一下, 应该是有手动构造 `Dictionary` 如果是模型转的, 不会有问题.

**Comment by wangzhao0630** [comment]
嗯嗯,我同事收集业务日志的时候 将字典里写了个NSURL类型的数据.我是把日志翻了个遍😃,修复了.感谢老师解惑
