### ISSUE TITLE
调用 mj_JSONString .断点显示转义字符

### ISSUE THREAD

**Issue by Xiahaiquan** [CoderMJLee/MJExtension#699]
**你的新功能建议是否牵扯到某个常见的问题？**
在开发中[myDic mj_JSONString] 打断点，显示有转义字符。但是NSLog没有。

断点显示：
__NSCFString *    "{\"KeyOne\":\"ValueOne\",\"KeyTwo\":\"ValueTwo\"}"
NSLog显示：
{"KeyOne":"ValueOne","KeyTwo":"ValueTwo"}

**你希望达到的效果**
我希望有提供去除转义字符的方法。 断点显示的如NSLog一样。

**你能考虑到的可选实现方案**
我不知道如何把 \ 从调用方法后去掉。

**Comment by wolfcon** [comment]
### 请好好学习编程的基础知识.
这是 `Xcode` 给你的`调试`信息. 在里面他要以 `String` 的形式展现给你看, 这时候遇到 `双引号` 怎么办? 当然是要加转义符号了

试想一下你写如下代码
```swift
var string = "{"a":"b", "c":"d"}"
```
秒报错好吗? 

正确的方式是
```swift
var string = "{\"a\":\"b\", \"c\":\"d\"}"
```

**Comment by Xiahaiquan** [comment]
谢谢提醒

我现在的具体问题是：
生成一个字典
`NSDictionary * myDict = @{@"keyOne": @"ValueOne",
                                        @"keyTwo": @"ValueTwo"};`
字典转JSONString
`NSString *jsonStr = [testDict mj_JSONString];`
加入到字典前打印出：
`{"keyOne":"ValueOne","keyTwo":"ValueTwo"}`
把jsonStr加入到一个新字典中
`NSDictionary *dic = @{
                          @"body": jsonStr,
                          };`
打印字典
`{
    body = "{\"keyOne\":\"ValueOne\",\"keyTwo\":\"ValueTwo\"}";
}`

我现在想得到字典中的Value没有转义字符
我该如何做呢

谢谢

**Comment by wolfcon** [comment]
### 兄弟, 你确实应该补一下基础知识...

你自己构造一个 `Dictionary`
试想一下你写如下代码
```swift
var dict = ["body": "{"a":"b", "c":"d"}"]
```
秒报错好吗?

正确的方式是
```swift
var dict = ["a": "{\"a\":\"b\", \"c\":\"d\"}"]
```

**Comment by Xiahaiquan** [comment]
**嗯 谢谢提醒 我基础知识是很薄弱**
