### ISSUE TITLE
建议删除过时方法

### ISSUE THREAD

**Issue by ElfSundae** [CoderMJLee/MJExtension#702]
我刚开始用 MJExtension ，看到代码里有很多不带 `mj_` 前缀的过时方法，好像是从 `2.5.16` 版本被过时的。现在主版本是 `3` ，我觉得可以删除这些过时方法了。
加前缀是为了防止和别的类的方法重名冲突，现在只是对这些方法调用加了警告，如果有重名方法，冲突还是存在的。
再者， 这些过时方法是加到基类 NSObject 上的，不带前缀很不合适。
所以我建议删除这些过时方法。
如果有人觉得现在删除尚早的话，那建议增加预处理宏来隔离删除这些方法，例如：
```objc
#ifdef MJEXTENSION_DEPRECATED_METHODS_ENABLED

@interface NSObject (MJKeyValueDeprecated_v_2_5_16)
- (instancetype)setKeyValues:(id)keyValue MJExtensionDeprecated("请在方法名前面加上mj_前缀，使用mj_***");
@end

#endif
```

**Comment by wolfcon** [comment]
的确
