### ISSUE TITLE
ios13系统不兼容

### ISSUE THREAD

**Issue by puhahalx** [CoderMJLee/MJExtension#705]
**描述bug**
ios 13系统一调用mj_keyValuesWithKeys就崩溃
**怎么样重现这个bug**
调用mj_keyValuesWithKeys方法,崩溃在NSObject+MJKeyValue.m文件的312行,可能是ios13不支持将nsmutabledictionary直接赋给id了,麻烦请尽快适配13
**你期望的结果是什么？**

**截图**
![image](https://user-images.githubusercontent.com/28496967/61280854-36cbf480-a7eb-11e9-86f6-c436e63dd36b.png)

**运行环境**
 - iPhone8
 - iOS13.0
 - Xcode10.2

**额外的**
最好能提供出现bug的Demo

**Comment by puhahalx** [comment]
再次测试发现 是因为源数据是NSNULL造成的 但是在ios12不会崩溃 在ios13却抛异常崩溃了 稍后我给出一个demo

**Comment by puhahalx** [comment]
你们可以在ios13上测试一下,随便定义一个模型,然后定义一个源数据为<null>,然后调用mj_objectArrayWithKeyValuesArray方法就会崩溃

**Comment by wolfcon** [comment]
iOS 13 is still in beta progress.

**Comment by BobbChen** [comment]
iOS13下如果数据类型是NSNull,MJExtension进行数据转模型会崩溃

**Comment by ElfSundae** [comment]
经测试没发现 crash

```objc
@interface User : NSObject
@property (nonatomic, copy) NSString *name;
@end
```

```objc
NSDictionary *dict = @{
    @"name": [NSNull null],
};
User *user = [User mj_objectWithKeyValues:dict];
NSLog(@"%@", user.name);

NSLog(@"%@", [user mj_keyValues]);

NSArray<User *> *array = [User mj_objectArrayWithKeyValuesArray:@[dict]];
NSLog(@"%@", array.firstObject.name);
```

**Comment by BobbChen** [comment]
> 经测试没发现 crash
> 
> ```objc
> @interface User : NSObject
> @property (nonatomic, copy) NSString *name;
> @end
> ```
> 
> ```objc
> NSDictionary *dict = @{
>     @"name": [NSNull null],
> };
> User *user = [User mj_objectWithKeyValues:dict];
> NSLog(@"%@", user.name);
> 
> NSLog(@"%@", [user mj_keyValues]);
> 
> NSArray<User *> *array = [User mj_objectArrayWithKeyValuesArray:@[dict]];
> NSLog(@"%@", array.firstObject.name);
> ```

更新MJExtension到3.1.2，这个问题已经修正了
