### ISSUE TITLE
使用归档的宏时, 属性的类型被改变了

### ISSUE THREAD

**Issue by SabinLee** [CoderMJLee/MJExtension#708]
@implementation User

MJCodingImplementation

使用后, User.sharedUser的ID比如是字符串@"13",, 被归档再解档后,类型变成了number, 调用string的相关方法就崩了, 看了源码发现只是简单的做了kvc处理导致, 是不是这个暂时就无解了?
目前计划归解档字典, 再用mj转模型

**Comment by wolfcon** [comment]
提供 Demo?

**Comment by SabinLee** [comment]
> 提供 Demo?

ok， 晚点给你

**Comment by SabinLee** [comment]
暂时无法重现, 等有空再仔细研究一下原因, 先关闭了
