### ISSUE TITLE
3.1.0解析报错

### ISSUE THREAD

**Issue by JanWirt** [CoderMJLee/MJExtension#711]
**描述bug**
json是字典数组嵌套字典数据，3.0.17没问题，3.1.0解析完内部嵌套的还是字典，没有解析成model。

[ {   
@"xx":@"1"；
@"xx":@"2";
@"xx":[ {
            @"xx":@"123";
            @"xx":@"456";},
           { @"xx":@"123";
            @"xx":@"456";},
           ...
         ]
}，
{   
@"xx":@"1"；
@"xx":@"2";
@"xx":[ {
            @"xx":@"123";
            @"xx":@"456";},
           { @"xx":@"123";
            @"xx":@"456";},
           ...
         ]
}
...
]

**Comment by UknowHui** [comment]
这bug整个项目都炸了，没人修复下么。。。

**Comment by JanWirt** [comment]
> objectClassInArray -> mj_objectClassInArray

多谢
