### ISSUE TITLE
iOS 13  null转换还是闪退啊,3.1.0版本

### ISSUE THREAD

**Issue by dodolook** [CoderMJLee/MJExtension#712]

**Comment by dodolook** [comment]
更新了跟没更新一样

**Comment by wolfcon** [comment]
demo?

**Comment by Xhsuio** [comment]
iOS13下类似于这种
NSMutableArray * boxList = [ActivityBoxModel mj_objectArrayWithKeyValuesArray:result[@"KData"]]
result[@"KData"]为null，就会崩溃

**Comment by dodolook** [comment]
[第340行] 通用成功回调 responseDic:{
    data =     {
        currentPage = 1;
        dataList = "<null>";
        pageSize = 20;
        start = 0;
        totalCount = 0;
        totlePage = 0;
        totleResult = 0;
    };
    errCode = 0000;
    errMsg = "\U64cd\U4f5c\U6210\U529f";
    success = 1;
    sysTime = 1564989472764;
    versionData = "<null>";
}
 NSArray<WDRepayMoneyRecord_M *> *tempArray = [WDRepayMoneyRecord_M mj_objectArrayWithKeyValuesArray:result[@"dataList"]];

**Comment by dodolook** [comment]
通用成功回调 responseDic:{
    data =     {
        currentPage = 1;
        dataList = "<null>";
        pageSize = 20;
        start = 0;
        totalCount = 0;
        totlePage = 0;
        totleResult = 0;
    };
    errCode = 0000;
    errMsg = "\U64cd\U4f5c\U6210\U529f";
    success = 1;
    sysTime = 1564989806553;
    versionData = "<null>";
}

**Comment by dodolook** [comment]
通用成功回调 responseDic:{
    data =     {
        currentPage = 1;
        dataList = "<null>";
        pageSize = 20;
        start = 0;
        totalCount = 0;
        totlePage = 0;
        totleResult = 0;
    };
    errCode = 0000;
    errMsg = "\U64cd\U4f5c\U6210\U529f";
    success = 1;
    sysTime = 1564989806553;
    versionData = "<null>"; 
NSArray<WDLoanrecord_M *> *tempArray = [WDLoanrecord_M mj_objectArrayWithKeyValuesArray:result[@"dataList"]];

**Comment by dodolook** [comment]
通用成功回调 responseDic:{
    data =     {
        currentPage = 1;
        dataList = ''<null>";
        pageSize = 20;
        start = 0;
        totalCount = 0;
        totlePage = 0;
        totleResult = 0;
    };
    errCode = 0000;
    errMsg = "\U64cd\U4f5c\U6210\U529f";
    success = 1;
    sysTime = 1564989806553;
    versionData = "<null>";
}
NSArray<WDLoanrecord_M *> *tempArray = [WDLoanrecord_M mj_objectArrayWithKeyValuesArray:result[@"dataList"]];

**Comment by dodolook** [comment]
NSArray<WDLoanrecord_M *> *tempArray = [WDLoanrecord_M mj_objectArrayWithKeyValuesArray:result[@"dataList"]];
dataList = **"<null>";**

**Comment by dodolook** [comment]
NSArray<WDLoanrecord_M *> *tempArray = [WDLoanrecord_M mj_objectArrayWithKeyValuesArray:result[@"dataList"]];
dataList = "<null>";
这个怎么提交不了<null>；

**Comment by dodolook** [comment]
NSArray<WDLoanrecord_M *> *tempArray = [WDLoanrecord_M mj_objectArrayWithKeyValuesArray:result[@"dataList"]];
dataList = "<null>";
dataList 值为 左右一个尖括号然后中间为null

**Comment by wolfcon** [comment]
麻烦提供个 Demo 好吗?
