### ISSUE TITLE
iOS13，beta5崩溃

### ISSUE THREAD

**Issue by vitasapple** [CoderMJLee/MJExtension#713]
NSObject+MJProperty.m的153行
#pragma mark - 公共方法

(NSMutableArray *)properties
{
NSMutableArray *cachedProperties = [self dictForKey:&MJCachedPropertiesKey] [NSStringFromClass(self)];
崩溃在这行

**Comment by kinarobin** [comment]
@vitasapple 方便给一份复现的Demo？我本地调试 Xcode 11 beta5 + iOS13 真机，没有复现这个问题

**Comment by stoneUoU** [comment]
我也在这里崩溃了

**Comment by vitasapple** [comment]
@wolfcon 后台返回空进去就崩了

**Comment by wolfcon** [comment]
把 Demo 打成 zip 包 拖动到打字框里
