### ISSUE TITLE
期望有清空模型属性的功能

### ISSUE THREAD

**Issue by SabinLee** [CoderMJLee/MJExtension#715]
**你的新功能建议是否牵扯到某个常见的问题？**
比如，用户退出后, 我希望清空单例用户的所有属性, 就像对象刚创建时的状态

**你希望达到的效果**
比如，我希望框架能够帮助我清空属性, [kSharedUser mj_clearProperties]; 就能帮我清空所有属性

**你能考虑到的可选实现方案**
for循环遍历mjproperty, 应该很简单吧

**Comment by SabinLee** [comment]
补充下, 为什么我不新建个对象让单例对象指向它? 因为有时候外界会对该单例用户进行kvo属性监听, 我贸然改变指针的话无法及时通知相关对象

**Comment by wolfcon** [comment]
这个清空功能你应该自己做. 少年.
`xxx = nil`
