### ISSUE TITLE
iOS13，beta5 死循环了

### ISSUE THREAD

**Issue by VijayMay** [CoderMJLee/MJExtension#716]
**描述bug**
调用 [model mj_keyValues] ，出现死循环，model 有这三个属性。

/** 联系人姓名*/
@property (nonatomic, copy) NSString *name;
/** 联系人电话数组,因为一个联系人可能存储多个号码*/
@property (nonatomic, strong) NSMutableArray *mobileArray;
/** 联系人头像*/
@property (nonatomic, strong) UIImage *headerImage;

**怎么样重现这个bug**
在这个类 NSObject+MJKeyValue  的 334行

会一直进入这个 if 
if (!type.isFromFoundation && propertyClass) {
     value = [value mj_keyValues];
}
propertyClass 是UIImage，UIImageConfiguration，UIImageAsset，UITraitCollection 

**你期望的结果是什么？**
正常运行，不出现死循环。

**截图**
<img width="586" alt="image" src="https://user-images.githubusercontent.com/8068487/62748869-cda76c00-ba8c-11e9-83a2-74fbcd79daac.png">
<img width="551" alt="image" src="https://user-images.githubusercontent.com/8068487/62749277-65f22080-ba8e-11e9-88d9-da65edc8c2aa.png">
<img width="671" alt="image" src="https://user-images.githubusercontent.com/8068487/62749292-70acb580-ba8e-11e9-9139-14180ada083a.png">
<img width="631" alt="image" src="https://user-images.githubusercontent.com/8068487/62749302-77d3c380-ba8e-11e9-92cf-cb23c836090f.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/8068487/62749306-7bffe100-ba8e-11e9-8b72-101ea2def230.png">
<img width="739" alt="image" src="https://user-images.githubusercontent.com/8068487/62749311-80c49500-ba8e-11e9-82b6-6c2802d9761e.png">
<img width="708" alt="image" src="https://user-images.githubusercontent.com/8068487/62749318-8621df80-ba8e-11e9-8d2f-c5a27421723b.png">

**运行环境**
 - iPhone7
 - iOS13.0 beta5
 - Xcode 10.3

**Comment by CoderMJLee** [comment]
实现下面方法，忽略掉UIImage属性。另外，在模型里面带有UIKit的东西，其实不太好，建议弄成类似NSString *imageName会比较合适
```objc
+ (NSArray *)mj_ignoredPropertyNames {
    return @[@"headerImage"];
}
```
