### ISSUE TITLE
SDK升级问题

### ISSUE THREAD

**Issue by pengshengsongcode** [CoderMJLee/MJExtension#717]
除了 replacedKeyFromPropertyName和objectClassInArray这两个api需要加前缀还有什么需要改？？？ #

**Comment by pengshengsongcode** [comment]
mj_replacedKeyFromPropertyName 这个API从哪个版本的SDK开始只取这个的 我们之前写的replacedKeyFromPropertyName这个没有问题啊

**Comment by wolfcon** [comment]
3.0

**Comment by pengshengsongcode** [comment]
3.0.17 replacedKeyFromPropertyName和mj_replacedKeyFromPropertyName都会取，3.1.0只会取mj_replacedKeyFromPropertyName，从而导致我们线上APP数据解析不出来 我们使用的是replacedKeyFromPropertyName

**Comment by pengshengsongcode** [comment]
改这个东西最好在release note里面体现一下

**Comment by wolfcon** [comment]
很早以前那些方法都被标注为过期方法了. 15年就开始标注了.
ReleaseNotes 里说了呀
[https://github.com/CoderMJLee/MJExtension/releases](https://github.com/CoderMJLee/MJExtension/releases)

- 话说你们项目里的警告都不去除直接忽略的吗?
- 话说升级第三方库后, 不做适配的吗?
- 话说你们上线都不测试的吗?

🤣

**Comment by pengshengsongcode** [comment]
哎~前人埋坑，后人进坑




| |
彭盛凇
邮箱：psscode@163.com
|

签名由 网易邮箱大师 定制

在2019年08月14日 18:34，Frank 写道：

很早以前那些方法都被标注为过期方法了. 15年就开始标注了.
ReleaseNotes 里说了呀
https://github.com/CoderMJLee/MJExtension/releases

话说你们项目里的警告都不去除直接忽略的吗?
话说升级第三方库后, 不做适配的吗?
话说你们上线都不测试的吗?

🤣
