### ISSUE TITLE
字典转模型时，字符串出现nil，可以设置为空串吗

### ISSUE THREAD

**Issue by WuKongCoo1** [CoderMJLee/MJExtension#72]

**Comment by CoderMJLee** [comment]
这种特殊需求需要自行处理哈，你可以重写属性的set方法，在里面置为@""

**Comment by CoderMJLee** [comment]
现在提供了+ (void)setupNewValueFormOldValue:(MJNewValueFormOldValue)newValueFormOldValue方法或者在.m中实现- (id)newValueFromOldValue:property:来处理字符串为nil的问题哈。具体可以看看Demo，谢谢。
