### ISSUE TITLE
在字典数组转模型的时候，相同的字段。有的转成NSCFString，有的转成NSTaggedPointerString类型。这是一个bug吗

### ISSUE THREAD

**Issue by CQxiaogang** [CoderMJLee/MJExtension#722]
**描述bug**
清晰简单地描述这个bug是啥

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone6
 - iOS8.1
 - Xcode10

**额外的**
最好能提供出现bug的Demo

**Comment by jzfjay** [comment]
NSString 会根据 返回字符串的长度 决定存储的位置，NSCFString，NSTaggedPointerString

**Comment by wolfcon** [comment]
`NSString` 是封装类, 其中真实的类型有很多种, 是由 Foundation 决定的

**Comment by xuekey** [comment]
NSTaggedPointerString 转成model后变成了nil了，iOS14系统
