### ISSUE TITLE
发现最新版BOOL值字段转模型有问题，3.0.17之前的都没问题

### ISSUE THREAD

**Issue by QuintGao** [CoderMJLee/MJExtension#723]
**描述bug**
清晰简单地描述这个bug是啥

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone6
 - iOS8.1
 - Xcode10

**额外的**
最好能提供出现bug的Demo

**Comment by QuintGao** [comment]
如果后台返回的字典是是"is_new": ""，默认转模型的时候会把is_new转成YES，这是不是有问题？

**Comment by wolfcon** [comment]
空字符串难道不属于非 0 的范畴么@@

**Comment by QuintGao** [comment]
空字符串转为BOOL值是YES??

**Comment by QuintGao** [comment]
3.0.17之前后台返回的@""，转成BOOL值都是NO，之后的版本都转成了YES

**Comment by wolfcon** [comment]
由于这次的改动造成的 #721 
@kinarobin 

原有的
```objc
value = [numberFormatter_ decimalNumber:oldValue];
```
转换 "" 结果为 nil, 被识别为 NO

更换后
```objc
value = @([NSDecimalNumber decimalNumberWithString:oldValue].doubleValue);
```
转换 "" 结果为 nan, 被识别为 YES

### 分析

`""` 被识别为 `Number` 和 `BOOL` 两种类型.
<img width="314" alt="image" src="https://user-images.githubusercontent.com/1538729/64523933-02c70880-d330-11e9-9b19-4f7950870e90.png">
在 `Number` 判断中做了赋值
在 `BOOL` 跳过了判断条件

**Comment by kinarobin** [comment]
@QuintGao 当时为了跟KakaJson 统一转换方式，我先调试一下这个问题。

**Comment by QuintGao** [comment]
我这试了下，应该没问题了，pod什么时候更新呢？

**Comment by kinarobin** [comment]
我马上更新一下

**Comment by wolfcon** [comment]
pod 已经更新.
