### ISSUE TITLE
杰哥,字典转模型,数据错误!!!

### ISSUE THREAD

**Issue by IcefieldWolf** [CoderMJLee/MJExtension#725]
返回字典中有字符串数字, 模型中用long long来接, 会出现数剧变了,比如"148423162444258920",没越界,翘首以盼!!!

**Comment by wolfcon** [comment]
<img width="229" alt="image" src="https://user-images.githubusercontent.com/1538729/64521880-64d13f00-d32b-11e9-8599-f2424034fc15.png">
上传个 Demo?

**Comment by IcefieldWolf** [comment]
[Uploading QuestionDemo.zip…]()

老版本没问题,新版本有这个问题.

**Comment by IcefieldWolf** [comment]
老版本没问题,新版本有这个问题.
[QuestionDemo.zip](https://github.com/CoderMJLee/MJExtension/files/3619576/QuestionDemo.zip)

**Comment by wolfcon** [comment]
## 这个是由于超出精度造成的. 
### 曾经的实现
是依靠 `NSNumberFormat` 来实现转数字.
### 而现在是
简单粗暴的 `doubleValue`, 所以出现了精度问题, `Double` 精度不够 `longlong`

@kinarobin #726 #721 
@CoderMJLee

**Comment by kinarobin** [comment]
@IcefieldWolf 收到，会尽快处理这个问题！

**Comment by ElfSundae** [comment]
我对 MJExtension 不熟，貌似你们说的是字符串转数字的问题？我看最近两次更新都是在修复这个。

@kinarobin 有空可以试试我[之前](https://github.com/CoderMJLee/MJExtension/pull/721#issuecomment-526177978)说的方法，给 NSNumberFormatter 设置 NSNumberFormatterDecimalStyle 。

另外，字符串转数字可能还要考虑处理分隔符，比如 "123, 456" 。为了兼容更广泛，可能还要处理某些特殊字符串，比如 "true", "t", "false", "f" 等要转为 numberWithBool 。我使用的方法是这个： https://github.com/ElfSundae/ESFramework/blob/master/ESFramework/Core/NSNumber%2BESExtension.m

**Comment by wolfcon** [comment]
@IcefieldWolf 建议你先退回使用老版本或者直接使用 `String` 接收数字. 再自行转换.

稍后会有完善方案.

**Comment by kafeidou1991** [comment]
我也碰到这个问题了。。有回退到老版本了

**Comment by wolfcon** [comment]
建议用 String 来接 @kafeidou1991

**Comment by itdongbaojun** [comment]
是否可以记录一下从哪个版本引入这个问题的，谢谢

**Comment by kinarobin** [comment]
@itdongbaojun 从3.1.0版本因为多语言的问题，去掉`NSNumberFormatter`，改用#721 的方式。

**Comment by wolfcon** [comment]
已经修复. 敬请期待发布版本

**Comment by dadahua** [comment]
![image](https://user-images.githubusercontent.com/14857647/92897259-a40b0200-f44f-11ea-9924-4e1aa8c034c9.png)


加行if ([oldValue intValue] > INT_MAX && [oldValue containsString:@"."]) {
                            value = @([oldValue longLongValue]);
                        }  就可以了

**Comment by dadahua** [comment]
![image](https://user-images.githubusercontent.com/14857647/92897716-0237e500-f450-11ea-9382-ed1fe156286a.png)
加个方法就是了
if ([oldValue longLongValue] > INT_MAX &&
                            ![oldValue containsString:@"."]) {
                            value = @([oldValue longLongValue]);
                        }

**Comment by wolfcon** [comment]
> ![image](https://user-images.githubusercontent.com/14857647/92897716-0237e500-f450-11ea-9382-ed1fe156286a.png)
> 加个方法就是了
> if ([oldValue longLongValue] > INT_MAX &&
> ![oldValue containsString:@"."]) {
> value = @([oldValue longLongValue]);
> }

你这个做无用功啊, 你看到 `standardValueWithTypeCode` 了吗? 这里已经处理过了
