### ISSUE TITLE
使用mj_objectWithKeyValues崩溃问题

### ISSUE THREAD

**Issue by wangxiusen** [CoderMJLee/MJExtension#729]
iOS13之后出现的bug，后台是java，数据返回来的可能是<null>，如果不加判断直接使用 mj_objectWithKeyValues 就会崩溃了，13之前的版本是没问题的

**Comment by huolong1237** [comment]
兄弟，你的也有问题？

**Comment by wangxiusen** [comment]
数据返回来的是（null）

**Comment by huolong1237** [comment]
我的是<null>

**Comment by huolong1237** [comment]
<null>

**Comment by huolong1237** [comment]
我返回的和你的一样

**Comment by wangxiusen** [comment]
> 兄弟，你的也有问题？

是的啊 所以加了判断先用着只是加个判断比较麻烦，可能很多地方需要这样

**Comment by huolong1237** [comment]
调用这个方法的时候直接闪退

**Comment by huolong1237** [comment]
卧槽，我们后台这边有很多地方都是这样返回的，我总不能一个一个的去写啊

**Comment by huolong1237** [comment]
返回的字段本身对应的是字典，但是他们在没有数据的时候直接返回了（null），就导致了崩溃

**Comment by wangxiusen** [comment]
是啊 我也只能是遇到哪里崩溃就改哪里，等着杰哥看看怎么解决吧

**Comment by huolong1237** [comment]
我们今天上线呢🤦‍♂️

**Comment by dong09000** [comment]
着急的话，
方案1：可以拖一个  nullSafe.m 到工程里，可以解决你们的 null对象闪退问题
方案2：AFN有Null对象过滤的API接口，开一下

**Comment by huolong1237** [comment]
好的

**Comment by wolfcon** [comment]
通篇没一个例子? demo? 这个问题已经修复了吧
