### ISSUE TITLE
MJ老师能不能做一下容错处理，比如模型写的是NSArray，但服务器将数据错误返回成了NSDictionary

### ISSUE THREAD

**Issue by wudijiang** [CoderMJLee/MJExtension#73]

**Comment by CoderMJLee** [comment]
如果类型不匹配，框架没有直接崩溃的，就仅仅是打印个错误警告信息哈。你是想怎么处理呢？

**Comment by wudijiang** [comment]
我的想法是如果模型属性与服务器返回类型不一致时（比如模型属性是NSArray，但返回的是一个字符串），直接将其置空同时打印出警告信息，从而防止crash
