### ISSUE TITLE
杰哥，iOS13时调用闪退了，

### ISSUE THREAD

**Issue by huolong1237** [CoderMJLee/MJExtension#730]
情况是这样的：后台返回的字典没有数据的时候是<null>,当我拿这个<null>去调用mj_objectWithKeyValues方法的时候就闪退了，闪退的位置在NSMutableArray *cachedProperties = [self mj_propertyDictForKey:&MJCachedPropertiesKey][NSStringFromClass(self)];这行代码，报野指针

**Comment by huolong1237** [comment]
iOS13一下在同样的情况下是没有问题的

**Comment by dong09000** [comment]
1.如果网络请求用的框架是 AFN的话，AFN有行代码我记得好像是removesKeysWithNullValues 开一下
2.若用的其它方式， 拖一个 nullSafe.m 进去

**Comment by huolong1237** [comment]
添加nullSafe.m也不行，还是闪退

**Comment by wolfcon** [comment]
@huolong1237 你看不到人家说, 用最新版本, 问题解决了吗? #731 

连开无数个 Issue, 你就不能自己试一下? 
试完了不行, 把你的 Demo 传上来, 不行? 等着别人喂进嘴里吗?
