### ISSUE TITLE
升级iOS13后，后端返回“<null>”数据，使用mj_objectArrayWithKeyValuesArray解析会闪退，但是升级最新版本，问题解决了

### ISSUE THREAD

**Issue by yzpIOS** [CoderMJLee/MJExtension#731]
升级iOS13后，后端返回“<null>”数据，使用mj_objectArrayWithKeyValuesArray解析会闪退，但是升级最新版本，问题解决了

**Comment by huolong1237** [comment]
已经解决了是吗？怎么没有看到更新记录呢？

**Comment by wolfcon** [comment]
@huolong1237  **你看不到人家说, 用最新版本, 问题解决了吗?** 连开无数个 Issue, 你就不能自己试一下? 试玩了不行, 把你的 Demo 传上来? 不行? 等着别人喂进嘴里吗?
