### ISSUE TITLE
iOS13,null赋值还是闪退

### ISSUE THREAD

**Issue by huolong1237** [CoderMJLee/MJExtension#732]
NSMutableArray *array = [self mj_classDictForKey:key][NSStringFromClass(self)];崩在这个地方

**Comment by echo2046** [comment]
是最新的库吗？3.1.2的?

**Comment by zhangli4659507** [comment]
处理完了么

**Comment by zhangli4659507** [comment]
iOS 13 [NSObject mj_objectWithKeyValues:[NSNull null]] 。 iOS 13以前的版本没问题，iOS 13会出现闪退

**Comment by wolfcon** [comment]
你更新库了吗? 不更新. 吵着闪退, 闪退了不修复的吗?
