### ISSUE TITLE
MJExtension (3.0.16)崩溃的问题

### ISSUE THREAD

**Issue by liubo1368** [CoderMJLee/MJExtension#735]
@interface TestP2 : NSObject
@property (nonatomic, strong) NSString *name;
@end

@interface TestP : NSObject

@property (nonatomic, strong) NSArray<TestP2*>* t_Name;

@end

@implementation TestP
+ (NSDictionary *)mj_objectClassInArray{
    return @{@"t_Name":@"TestP2"};
}
@end

@implementation TestP2
@end

void main(){
TestP* p = [TestP mj_setKeyValues:@{
            @"t_Name":NSNull.null
        }];
        
        
        NSLog(@"%@",p);
}

简单说明下 因为接手的项目里大量用到这个框架, 在服务器返回数据后, 很可能出现[XXClass mj_objectArrayWithKeyValuesArray:idObj] 的时候idObj可能是空对象(NSNull.null,这个值全局只有一个地址),导致后续的函数调用栈, 会出现取出value,然后死循环的情况, 这个在最新的iOS13的时候会出现, 我当前的做法是在mj_objectArrayWithKeyValuesArray的入口拦截了空对象的情况, 我没用AOP切入, 太花时间

**Comment by wolfcon** [comment]
为什么使用 3.0.16 版本呢? 最新版本早就修复了这个问题.

**Comment by liubo1368** [comment]
> 为什么使用 3.0.16 版本呢? 最新版本早就修复了这个问题.

接手的项目, ios13之前的时候没有出现, 这两天系统更新后出现了这种问题, 刚调试就来github上提了下, 我现在更新试一试
