### ISSUE TITLE
字典中包含数组模型转不成功，数组中还是字典

### ISSUE THREAD

**Issue by Q773000230** [CoderMJLee/MJExtension#739]
数据格式最外层是字典，字典中有三个数组，数组中的模型转换不成功
'MJExtension', '~> 3.1.2'，通过最外层字典mj_objectWithKeyValues
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryI clientName]: unrecognized selector sent to instance 0x600002ba63e0'
![image](https://user-images.githubusercontent.com/13879884/65679889-9155bc80-e088-11e9-9622-12c46b7e8c8c.png)
![image](https://user-images.githubusercontent.com/13879884/65679986-b64a2f80-e088-11e9-8d69-a893b8832378.png)
但是MJExtension 3.0.17版本正常，MJExtension 3.1.2转换失败

**Comment by Q773000230** [comment]
MJExtension 3.0.17版本正常

**Comment by xieytt** [comment]
我也出现了该问题，更新到最新的3.2版本还是存在该问题，另外replacedKeyFromPropertyName 也出去不起作用了。

**Comment by wolfcon** [comment]
麻烦上传个出问题的 Demo

**Comment by Q773000230** [comment]
> @Q773000230 麻烦上传个出问题的 Demo
> 我这边测试是没问题的
> 
> ===========
> 
> @xieytt `replacedKeyFromPropertyName `是无数年前就废弃的方法. 你从来不处理代码中的警告⚠️
> 吗?
> 另外你更新库之前都不看看库的 ReleaseNotes 吗?

错误demo
[testMJExtension.zip](https://github.com/CoderMJLee/MJExtension/files/3660770/testMJExtension.zip)

**Comment by Q773000230** [comment]
@CoderMJLee @wolfcon 错误demo
https://github.com/CoderMJLee/MJExtension/files/3660770/testMJExtension.zip

**Comment by wolfcon** [comment]
@Q773000230 老哥代码不是你这么写的好么, 仔细看看 Demo 不好吗? 看看说明不好吗?
非 mj 开头的方法都废弃一万年了.

### 你的代码❌
```objc
+ (NSDictionary *)objectClassInArray{
}
```

### ✅正确的代码
```objc
+ (NSDictionary *)mj_objectClassInArray{
}
```

**Comment by Q773000230** [comment]
感谢！！！

**Comment by feixue299** [comment]
> @Q773000230 老哥代码不是你这么写的好么, 建议仔细看看Demo, 升级前看看 [ReleaseNotes](https://github.com/CoderMJLee/MJExtension/releases/tag/3.1.0), [这是改动代码](https://github.com/CoderMJLee/MJExtension/commit/79e4089deae920c4d0210d130c052a69163b6530).
> 非 mj 开头的方法都废弃一万年了.
> 
> ### 你的代码❌
> ```objc
> + (NSDictionary *)objectClassInArray{
> }
> ```
> 
> ### ✅正确的代码
> ```objc
> + (NSDictionary *)mj_objectClassInArray{
> }
> ```
> 
> ### 一点小小的建议, 希望你加上这个 <MJKeyValue>
> ```objc
> @interface LKCustomerTypeListModel : NSObject <MJKeyValue>
> ```

在库里面已经给NSObject扩展实现了MJKeyValue，自定义的类只要继承NSObject不需要在加MJKeyValue了吧。
