### ISSUE TITLE
MJ老师，请问MJExtension能不能归档C语言的数据类型啊，如ABRecordRef等？

### ISSUE THREAD

**Issue by gwpp** [CoderMJLee/MJExtension#74]
我的项目中用到RHAddressBook框架，然后我想要存储RHPerson对象，他原本是不遵守NSCoding协议的，也就是说不能进行归档。我在他的那些模型里都加上了 MJCodingImplementation ,他们可以归档了，但是发现很多C语言的类型的数据都不能执行归档，都会报错，比如 RHMultiStringValue、ABRecordRef 等数据类型。请问有没有办法用 MJExtension 归档他们呢？期待您的回复，谢谢

**Comment by CoderMJLee** [comment]
没有试过哦，你试过了么？

**Comment by GanWenPeng** [comment]
前段时间试了一下，好像只能归档OC对象和int、float等基本数据类型，像CoreFoundation里面的那些C语言的数据类型都不能归档哦

**Comment by wolfcon** [comment]
暂时不支持
