### ISSUE TITLE
I am migrating my code from swift 3.3 to swift 4.1

### ISSUE THREAD

**Issue by Manpreetkaurrao** [CoderMJLee/MJExtension#743]
I have migrated my code from Swift 3.3 to Swift 4.1. Everything is working fine. Its just that mj_object(withKeyValues:) returns nil object.

Please help me. As i am new to this library. Got the maintenance project.

**Comment by wolfcon** [comment]
You should ADD `@objc` attributes to your class and property since `Swift 4.0`. 🤝
