### ISSUE TITLE
嵌套对象字典报错闪退

### ISSUE THREAD

**Issue by Raydem0n** [CoderMJLee/MJExtension#744]
**描述bug**
`Class User{
var role:[String: Role] = ["1":Role("Admin")]
}`

**怎么样重现这个bug**
user.mj_JSONString()闪退

**你期望的结果是什么？**
序列化成功

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone11
 - iOS13
 - Xcode11.1

**额外的**
最好能提供出现bug的Demo

**Comment by wolfcon** [comment]
crash log?

**Comment by Raydem0n** [comment]
as debugged in breakpoints, it showed the "role" property of user was translated to string value as shown below
`{"1": "Role object" }`

Exprected:
`{"1": "{"Role":{"type":"admin"}}"}`

**Comment by wolfcon** [comment]
麻烦上传个 demo

**Comment by Raydem0n** [comment]
[mj.zip](https://github.com/CoderMJLee/MJExtension/files/3778895/mj.zip)
FYI

精简了代码，没有闪退；但是序列化成字符串失败、只返回了空字典{}

**Comment by wolfcon** [comment]
你在模型里用字典, 为什么不都用字典来操作.
既然用模型, 就统一用模型. 你的 `roles` 明显是一个数组, 你是怎么把它弄成字典的...

另外你如果真的很想用这种奇怪的设计, 你可以试试 [KakaJSON - MJExtension 的 Swift 版本](https://github.com/kakaopensource/KakaJSON)

另外, 其实还有一个问题
你用框架都不看 README 的么?

> 关于在Swift中使用MJExtension ‼️

> ‼️ @objc attributes should be added to class and property for declaration of Objc accessibility > [在 Swift4 之后, 请在属性前加 @objc 修饰. 以保证 Swift 的属性能够暴露给 Objc 使用. ]‼️

> ‼️ Use NSNumber instead of Bool, which is not bridged to BOOL. [请勿使用 Bool 类型, 因为在 > Swift 中并没有桥接该类型, 不能显式的对应 BOOL, 请使用 NSNumber 替代] ‼️

**Comment by Raydem0n** [comment]
demo是精简版本，实际上在完整版里Roles是一个数组（Sequence）。用字典的原因在于字典不需要排序、存储效率高。用数组的原因在于可以实现值类型的下标引用。
demo是我漏了加@objcMembers所以只返回了{}没有闪退，后面我加上@objcMembers就闪退了

**Comment by Raydem0n** [comment]
感觉上mj是没有实现复杂字典类型的模型识别转换的，只是一个建议，看能否像mj_objectClassInArray一样处理复杂类型字典。lkdb在这方面相对处理的好一些。没有的话也无所谓了，我已经不考虑使用这种复杂字典索引类型直接存到obj-db里面了。

**Comment by wolfcon** [comment]
#745
