### ISSUE TITLE
ios 13模型转字典崩溃；ios 13 以下系统不会崩溃：崩在NSObject+MJClass 这个类的152行：   NSMutableArray *array = [self mj_classDictForKey:key][NSStringFromClass(self)];

### ISSUE THREAD

**Issue by 123LCQ** [CoderMJLee/MJExtension#747]
**描述bug**
清晰简单地描述这个bug是啥

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**运行环境**
 - iPhone6
 - iOS8.1
 - Xcode10

**额外的**
最好能提供出现bug的Demo

**Comment by 007lihegong** [comment]
{"code":"0","msg":"msg","data":[null,null,null]}  昨天服务器异常 返回这样一组数据，转model的时候报
错

@implementation AUserModel

+(NSDictionary *)mj_objectClassInArray{
    return @{@"data":[UserModel class]};
}
@end

@interface AUserModel : NSObject
///头像
@property (nonatomic,copy) NSArray * data;

@end


@interface UserModel : NSObject
///头像
@property (nonatomic,copy) NSString * head;
///昵称
@property (nonatomic,copy) NSString * nickname;
@end



XCode  11.1  iOS 13

**Comment by 007lihegong** [comment]
崩溃也在在NSObject+MJClass 这个类的152行： NSMutableArray *array = [self mj_classDictForKey:key][NSStringFromClass(self)];

**Comment by kinarobin** [comment]
@123LCQ 使用最新的3.2.1版本试试。
