### ISSUE TITLE
模型中如果有同名的属性，例如（name,Name）,赋值的时候不论数据源是name还是Name，都只会给第一个属性赋值

### ISSUE THREAD

**Issue by whichpage** [CoderMJLee/MJExtension#749]
**描述bug**
模型中如果有同名的属性，例如（name,Name）,赋值的时候不论数据源是name还是Name，都只会给第一个属性赋值

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**

**截图**
<img width="796" alt="1" src="https://user-images.githubusercontent.com/20877763/69023374-7ef95e80-09f9-11ea-99eb-fa7d78dee912.png">
<img width="437" alt="2" src="https://user-images.githubusercontent.com/20877763/69023375-7ef95e80-09f9-11ea-9744-5c7008b5ab64.png">
<img width="927" alt="3" src="https://user-images.githubusercontent.com/20877763/69023376-7ef95e80-09f9-11ea-87a7-4cb9995cf8ef.png">

**运行环境**
 - iPhone11
 - iOS13.1
 - Xcode11.1

**额外的**
最好能提供出现bug的Demo

**Comment by wolfcon** [comment]
请放弃这种不标准的写法
`Id` 或者 `ID` 是没有办法. 因为 `id` 是保留关键字. 属性请正确使用首字母小写/ 另外就算大写, 不要写这种类似的属性名.

如果稍微了解点 Objective-C 的 `get` `set` 机制的话, 就不会问出这种问题了
