### ISSUE TITLE
模型嵌套模型数组的bug

### ISSUE THREAD

**Issue by tipshot** [CoderMJLee/MJExtension#751]
**描述bug**
在多层模型嵌套时，模型里嵌套一个模型数组，数组里面有小模型，如果小模型里面有自定义属性，那么这个属性事不会被初始化的，在外面的模型没事。

**怎么样重现这个bug**
1. 写一个模型，模型里面嵌套一个模型数组
2. 在这个模型数组里面的模型中自定义一个属性（所谓自定义，就是服务器没有返回这个字段属性）
3. 然后进行模型转换
4. 发现小模型的正常属性正常初始化，但是自定义的属性没初始化

**你期望的结果是什么？**
期望小模型里面的自定义属性被初始化

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - ipad 9.7
 - iOS12.1
 - Xcode11.1

**额外的**
最好能提供出现bug的Demo

**Comment by tipshot** [comment]
![image](https://user-images.githubusercontent.com/18547353/69791074-b4bef400-11fe-11ea-8e6e-61aac3e3d7f9.png)

**Comment by wolfcon** [comment]
Demo

**Comment by tipshot** [comment]
> Demo

已经找到原因了，是我的问题。
