### ISSUE TITLE
mj_ignoredPropertyNames 包含父类的数组吗？

### ISSUE THREAD

**Issue by ElfSundae** [CoderMJLee/MJExtension#752]
如果子类和父类都实现了 `+mj_ignoredPropertyNames` 返回各自的数组，子类的 ignored 数组不包含父类的 ignored 数组。不知道这是 bug 还是设计如此？

**Comment by ElfSundae** [comment]
例如：父类忽略 foo 属性，子类忽略 bar 属性，在调用子类 mj_keyValues 等方法时 foo 属性没被忽略，必须在子类的 mj_ignoredPropertyNames 方法中手动包含父类的 ignored 数组：
```objc
+ (NSArray *)mj_ignoredPropertyNames
{
    return [[super mj_ignoredPropertyNames] arrayByAddingObjectsFromArray:@[
        NSStringFromSelector(@selector(bar)),
        // ...
    ]];
}
```

**Comment by ElfSundae** [comment]
刚看了下库代码，该问题同样存在于 `allowedPropertyNames`, `ignoredPropertyNames`, `allowedCodingPropertyNames`, `ignoredCodingPropertyNames` 这四个数组缓存。

`+mj_totalObjectsWithSelector:key:` 中确实只调用了 self 的相应方法，totalArray 中 _不包含_ 父类的该方法返回的数组，但是会包含父类的 setup 方法返回的数组。

因为我印象中 setup*** 方法是全局的配置，比如全局配置 key 的替换 face -> avatar, uid -> userId 等这类需求，而我一般会尽可能把作用域（影响范围）降到最小，所以从没使用过 setup 相关方法。
对于这个 issue ，我期望的 `+mj_ignoredPropertyNames` 等方法的行为其实正是 `setup` 等方法的行为，即一个类的 total allowed/ignored 数组缓存应该包含其所有父类的数组。我觉得如果父类因为某原因忽略或允许了某属性，子类应该也忽略/允许它。Just my 2 cents.

如果设计如此，即：子类的数组不包含其父类的数组，那就会有个问题：假设父类实现了该方法而子类没实现（重载），那么调用子类的该方法其实会调用父类的方法返回父类的数组，这跟我们的设计相悖。

**Comment by ElfSundae** [comment]
Demo: [MJExtension-Issue752.zip](https://github.com/CoderMJLee/MJExtension/files/3941313/MJExtension-Issue752.zip)

```objc
#import <MJExtension/MJExtension.h>

@interface Message : NSObject
@end

@implementation Message

+ (NSArray *)mj_ignoredPropertyNames
{
    return @[ @"super" ];
}

@end

@interface ChatMessage : Message
@end

@implementation ChatMessage
@end

@interface SocketMessage : Message
@end

@implementation SocketMessage

+ (NSArray *)mj_ignoredPropertyNames
{
    return @[ @"child" ];
}

@end

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        NSLog(@"%@", [Message mj_totalIgnoredPropertyNames]);
        NSLog(@"%@", [ChatMessage mj_totalIgnoredPropertyNames]);
        NSLog(@"%@", [SocketMessage mj_totalIgnoredPropertyNames]);
    }
    return 0;
}

```

```
2019-12-10 03:05:19.205690+0800 MJExtension-Issue752[54223:4329024] (
    super
)
2019-12-10 03:05:19.206603+0800 MJExtension-Issue752[54223:4329024] (
    super
)
2019-12-10 03:05:19.206700+0800 MJExtension-Issue752[54223:4329024] (
    child
)
```

**Comment by wolfcon** [comment]
你 override 方法, 都不调用 Super 的吗?

**Comment by ElfSundae** [comment]
@wolfcon 这些方法是 protocol 里的 optional 方法，没要求每个类都实现吧？如果父类没实现，子类调 super 不就 crash 了？

**Comment by ElfSundae** [comment]
@wolfcon 如果每个子类都要求调 super 来保证一致性，那这四个方法和 setup***Names 方法有啥区别？

**Comment by wolfcon** [comment]
你写子类的时候, 完全都不看父类实现了什么么...而且还是如此重要的 Model. 

一个是使用数据库(Sort of), 一个是使用方法(而方法则是涉及到是否覆盖或者完全重写的问题)

**Comment by wolfcon** [comment]
继承为何物. 方法 override 为何物. 好好学习下基础, 老兄

**Comment by ElfSundae** [comment]
谢谢，我就是因为看不到父类代码才遇到了这个问题... 我有个闭源的 SDK ，里面有几十个 model 类使用了 MJExtension ，SDK 里有些 model 类没实现这个方法，而我的子类一调 super 就 crash ，所以我之后就没再调 super 了。昨天发现有个类把父类的忽略数组暴露了。好吧，是他 SDK 的问题...

**Comment by wolfcon** [comment]
你先 respondsToSelector 检测一下啊. 如果是说的那种情况.

**Comment by ElfSundae** [comment]
@wolfcon 感谢回复。我基础确实很差，初中文凭，从家电维修转学的编程，编程只是我的业余爱好。对 MJExtension 内部也不熟，使用 MJExtension 也是因为有个闭源 SDK 使用了。

如果因为我的能力问题而提出了弱智问题，我深表抱歉。如果大佬您觉得继续讨论此问题是浪费时间，请忽略我后面的回复，打扰了。

---

我是在请教这四个方法的设计意图（工作模式）。从你的回复里我得到的答案是：这四个方法是属于继承范畴，那么我想问下为什么不直接给 NSObject category 里加方法，而要定义在 Optional Protocol 里？事实上，NSObject 已经遵循了这个协议 `@interface NSObject (MJKeyValue) <MJKeyValue>` ，但是为什么没有默认实现？

我不知道你是如何使用这几个方法的，按你说的，是不是应该这样用：

```objc
@interface Message : NSObject
@end

@implementation Message

+ (NSArray *)mj_ignoredPropertyNames
{
    return [[super mj_ignoredPropertyNames]
            arrayByAddingObjectsFromArray:@[ @"foo", @"bar" ]];
}

@end
```

因为 NSObject 没有实现这个方法，这样写会 crash ，所以要改成：

```objc
@implementation Message

+ (NSArray *)mj_ignoredPropertyNames
{
    if ([NSObject respondsToSelector:@selector(mj_ignoredPropertyNames)]) {
        return [[super mj_ignoredPropertyNames]
                arrayByAddingObjectsFromArray:@[ @"foo", @"bar" ]];
    } else {
        return @[ @"foo", @"bar" ];
    }
}

@end

@interface ChatMessage : Message
@end

@implementation ChatMessage

+ (NSArray *)mj_ignoredPropertyNames
{
    if ([Message respondsToSelector:@selector(mj_ignoredPropertyNames)]) {
        return [[super mj_ignoredPropertyNames]
                arrayByAddingObject:@"abc"];
    } else {
        return @[ @"abc" ];
    }
}

@end
```

是这样 override 吗？

**Comment by ElfSundae** [comment]
以我所学，override 应该是这样：

```objc
@interface NSObject (MJKeyValue)

+ (NSArray *)mj_allowedPropertyNames;

@end

@implementation NSObject (MJKeyValue)

+ (NSArray *)mj_allowedPropertyNames
{
    return @[];
}

@end

@interface AnyModel : AnyBaseModel
@end

@implementation AnyModel

+ (NSArray *)mj_allowedPropertyNames
{
    return [[super mj_allowedPropertyNames] arrayByAddingObjects...]
}

@end
```

子类 override 父类方法的几种情况：

- 不实现：继承父类特性
- 实现，且调用 super ：继承父类特性，并添加自有特性
- 实现，不调 super ：重写该方法

**Comment by wolfcon** [comment]
只对子类写就可以了. NSObject 是系统基类. 无需判断 `Message`

只需要对于你用的自定义子类判断即可 `ChatMessage`, 写 super 即可

```objc

@interface ChatMessage : Message <MJKeyValue>
@end

@implementation ChatMessage

+ (NSArray *)mj_ignoredPropertyNames {
    NSMutableArray *ignoredNames = [NSMutableArray arrayWithObject:@"abc"];
    if ([super respondsToSelector:@selector(mj_ignoredPropertyNames)]) {
        NSArray *ancestorIgnoredNames = [super mj_ignoredPropertyNames];
        [ignoredNames addObjectsFromArray:ancestorIgnoredNames];
    }
    return ignoredNames;
}

@end
```

**Comment by ElfSundae** [comment]
非常感谢🙏 其实不能这么写： `[super respondsToSelector:]` 。

我大量使用过 Protocol 模式，我也知道 `<MJKeyValue>` `<MJCoding>` 是为了公开接口的。我的意思是 MJExtension 中关于这几个方法的设计是不是有迷惑性？或者说不确定性？

我觉得如果设计的就是需要继承，那么所有类都应该继承（respondsToSelector 检查然后调 super 然后再 add 本类的数组）才能保证类的独立性、一致性、强壮、安全。
子类怎么实现还要看父类是不是 NSObject ，还要看父类的父类是不是 NSObject，还有参考父类是怎么实现的，我不觉得这是「随需求而定」。
难道这几个接口存在的价值就是为了写随性的代码？

**Comment by ElfSundae** [comment]
如果是 optional data source protocol methods ，就应该表示各类只需要实现自己的方法。
 total 缓存应该遍历所有父类。

```objc
@protocol MJKeyValueConfig <NSObject>
@optional

+ (NSArray *)mj_ignoredPropertyNames;

@end

@interface AnyModel : AnyBaseModel <MJKeyValueConfig>
@end

@implementation AnyModel

+ (NSArray *)mj_ignoredPropertyNames
{
    return @[ @"foo" ];
}

@end

NSArray *totalIgnoredPropertyNames(Class cls)
{
    NSMutableArray *array = objc_getAssociatedObject(cls, key);

    if (!array) {
        array = [NSMutableArray array];

        [cls enumerateAllClasses:^(Class c) {
            if ([c respondsToSelector:@selector(mj_ignoredPropertyNames)]) {
                [array addObjectsFromArray:[c mj_ignoredPropertyNames]];
            }
        }];

        objc_setAssociatedObject(cls, key, array, 1);
    }

    return array;
}
```

**Comment by ElfSundae** [comment]
我就是比较困惑 MJExtension 中这几个接口的设计模式，貌似是 override 和 optional protocol 的「混合模式」，导致了不确定性。
我现在已经放弃使用这几个方法了，改用相应的 setup 方法。依我愚见，这几个方法应该予以删除。当然，本人才疏学浅，可能还没有领悟到这种设计的特性。我好像也没写过 `if ([super respondsToSelector])` 这种代码。

**Comment by wolfcon** [comment]
一般情况下, 继承到如此深的 Model. 这得是多奇怪的 Model......

这个方案只是解决你继承不到父类忽略的内容.
正常情况下, 你的子类 Model 一定会忽略父类的? 一定不会忽略父类的? 子类的 Model 解析依托特殊性. 按理说你自己写一个完整列表才是对的. 

按你的说法, 继承很多次后. 你在不熟悉父类忽略了什么的情况下, 你敢随意用?

**Comment by ElfSundae** [comment]
了解了，谢谢。
