### ISSUE TITLE
model对象存在id类型model 使用mj_jsonString会报错

### ISSUE THREAD

**Issue by Faithlight** [CoderMJLee/MJExtension#753]
如果对象obj存在一个不可预知id类型对象,使用mj_jsonString会崩溃,id类型对象没有正确解析成json

**Comment by wolfcon** [comment]
来 Demo?

**Comment by Faithlight** [comment]
@interface Member : NSObject
@property(nonatomic,assign)NSString *name;
@property(nonatomic,assign)NSString *level;
@property(nonatomic,assign)NSString *age;
@end
@interface Example : NSObject
@property(nonatomic,assign)NSString *type;
@property(nonatomic,strong)Member *member;
@property(nonatomic,strong)id content;
@end


    Member *member = [Member new];
    member.name = @"name";
    member.level = @"level";
    member.age = @"age";
    Example *example = [Example new];
    example.type = @"type";
    example.member = member;
    example.content = member;
    NSLog(@"%@",example.mj_JSONString);

**Comment by wolfcon** [comment]
不要使用 id 类型.
