### ISSUE TITLE
Suggested support for Carthage

### ISSUE THREAD

**Issue by WGFcode** [CoderMJLee/MJExtension#755]
**你的新功能建议是否牵扯到某个常见的问题？**
比如，在开发中，经常遇到XXX问题，目前框架的功能不足以解决这个问题

**你希望达到的效果**
比如，我希望框架能够帮助我解决XXX问题，实现XXXX那样的效果

**你能考虑到的可选实现方案**
描述一下你认为要实现这个功能，有哪些可行的一些实现方案？

**Comment by wolfcon** [comment]
github "CoderMJLee/MJExtension"
