### ISSUE TITLE
UIColor类型的属性如何进行转换

### ISSUE THREAD

**Issue by ZihenMo** [CoderMJLee/MJExtension#758]
数据模型中定了一个`UIColor`类型的属性，对该模型转字典时会出现以下错误。

```
[<UIDeviceRGBColor 0x600003c5f380> valueForUndefinedKey:]: this class is not key value coding-compliant for the key dynamic.
```
我查看了`UIColor`本身是支持`NSCoding`协议，在使用`NSKeyedArchiver`也是可以正常归档与解归档。我应该怎么做让该属性能够转成字典，又能再次解析成模型？请求大佬指点。

补充一下：在使用`runtime`获取属性转字典时是正确的类型，使用`mj_keyValues`获得的字典时，`UIColor`被转换了类型。对比如下：

```
dict: 	{
	begin : NSPoint: {100, 100},
	end : NSPoint: {200, 200},
	color : 	{
		MP_lightness : 0.5,
		writableTypeIdentifiersForItemProvider : 	[
			"com.apple.uikit.color",
		],
	},
}
dict: 	{
	begin : NSPoint: {100, 100},
	end : NSPoint: {200, 200},
	color : UIExtendedSRGBColorSpace 1 0 0 1,
}
```

**Comment by wolfcon** [comment]
MJExtension 对 UIKit 内容不支持解析啊.

**Comment by wolfcon** [comment]
趁着重构的时候, 回答下这个问题, 对于 UIColor 来说.
1. 归档, 解档是没有任何问题的.
2. 含有 UIColor 属性的 Model 转化成 JSON 也是可以的, 但是没有意义, 你应当转换其含义后, 存储至另一个值中
3. 与 2 类似, 你不能使用 JSON 字符串去重新构建一个 UIColor.

好了, 我们现在来分析一下为什么会这样.
### UIColor 的本质
它并不是一个普通的类, 如果你经常看 Apple 的 WWDC, 或者其他人对于类型的科普, 你应该听说过一个词 `Class Clusters`. 没错, 我们的 `UIColor` 就是一个这样的类簇. 他并不是实际的 UIColor, 而是以下这些类中的一个:
- UICachedDeviceWhiteColor
- UIDeviceRGBColor
- UIDisplayP3Color
- ...

而这些类中, 有些是初始化后, 信息是存储在 ivar 中, 没有暴露任何 property, 你也无法正常通过 ivar 去创建他们(黑科技除外).

### 扩展一下, UIColor 可以被特殊化解决, 那么其他的呢?
所以说这类内容最好不要简单的去在模型里面存储, 取而代之的使用一些预设名字或者预设格式字符串去解析反而是更加稳妥的方式.

> 最后说一下, 崩溃的问题, 重构后的 4.0.0 将会修复崩溃的问题.
