### ISSUE TITLE
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:134) crash

### ISSUE THREAD

**Issue by lengqingfeng** [CoderMJLee/MJExtension#761]
**描述bug**

-[MJPropertyKey valueInObject:] (MJPropertyKey.m:16)
--
3 GJHearlthStore | __48-[NSObject(MJKeyValue) mj_setKeyValues:context:]_block_invoke (NSObject+MJKeyValue.m:0)
4 GJHearlthStore | +[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:134)
5 GJHearlthStore | -[NSObject(MJKeyValue) mj_setKeyValues:context:] (NSObject+MJKeyValue.m:228)

**怎么样重现这个bug**
bugly 收集的bug mjextension 版本为  pod 'MJExtension','~>3.2.1'

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone 6
 - 11.4
 - Xcode 11

**Comment by kinarobin** [comment]
@lengqingfeng 直接把整个crash日志上传上来看看。

**Comment by lengqingfeng** [comment]
libobjc.A.dylib | objc_msgSend + 16
-- | --
1 CoreFoundation | -[__NSDictionaryI objectForKeyedSubscript:] + 148
2 GJHearlthStore | -[MJPropertyKey valueInObject:] (MJPropertyKey.m:16)
3 GJHearlthStore | __48-[NSObject(MJKeyValue) mj_setKeyValues:context:]_block_invoke (NSObject+MJKeyValue.m:0)
4 GJHearlthStore | +[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:134)
5 GJHearlthStore | -[NSObject(MJKeyValue) mj_setKeyValues:context:] (NSObject+MJKeyValue.m:228)
6 GJHearlthStore | +[NSObject(MJKeyValue) mj_objectWithKeyValues:context:] (NSObject+MJKeyValue.m:258)
7 GJHearlthStore | +[NSObject(MJKeyValue) mj_objectArrayWithKeyValuesArray:context:] (NSObject+MJKeyValue.m:301)
8 GJHearlthStore | __32-[GJHomeController getChainList]_block_invoke (GJHomeController.m:0)
9 GJHearlthStore | __48-[YTKNetworkAgent requestDidSucceedWithRequest:]_block_invoke (YTKNetworkAgent.m:404)
10 libdispatch.dylib | __dispatch_call_block_and_release + 24
11 libdispatch.dylib | __dispatch_client_callout + 16
12 libdispatch.dylib | __dispatch_main_queue_callback_4CF$VARIANT$mp + 1012
13 CoreFoundation | ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
14 CoreFoundation | ___CFRunLoopRun + 2272
15 CoreFoundation | CFRunLoopRunSpecific + 552
16 GraphicsServices | GSEventRunModal + 100
17 UIKit | UIApplicationMain + 236
18 GJHearlthStore | main (main.m:16)
19 libdyld.dylib | _start + 4

**Comment by a330416020** [comment]
@lengqingfeng 我遇到的问题和你这一样，你那解决了么。

**Comment by wolfcon** [comment]
@lengqingfeng 你是不是使用了下面 其中一个 或 全部 的方法

mj_setupObjectClassInArray:
mj_setupReplacedKeyFromPropertyName:
mj_setupReplacedKeyFromPropertyName121:

**Comment by wolfcon** [comment]
**Update `3.2.4` ASAP.**
