### ISSUE TITLE
我想问一下，如果一个模型属性，没有被成功解析，变成了字典可能是什么原因

### ISSUE THREAD

**Issue by 900116** [CoderMJLee/MJExtension#762]
RT
模型属性的架构如下

@interface XXX : NSObject<NSCoding>

@property (nonatomic, copy, nullable) NSString *xxx;
@property (nonatomic, copy) NSString *xxx;
@property (nonatomic, assign) NSUInteger xxx;
@property (nonatomic, copy) NSNumber *xxxx;
@property (nonatomic, copy) NSArray<NSDictionary *> *xxx;
@property (nonatomic, copy) NSString *xxx; 
@property (nonatomic, assign) XXXStatus status;  //一个枚举

@end

@CoderMJLee 期待您的回复

**Comment by kinarobin** [comment]
应该是你没有使用正确吧？

**Comment by 900116** [comment]
> 应该是你没有使用正确吧？

你这等同于没说啊

**Comment by 900116** [comment]
绝大多数，都是能够解析成功的，只有极少部分变成字典，因为最近代码有较大改动，不太确定是哪儿引起的，我理解MJ就算解析失败了，顶多是对象变成nil，不会变成字典啊，所以这块不太清楚在什么情况下变字典

**Comment by wwwangS** [comment]
> 绝大多数，都是能够解析成功的，只有极少部分变成字典，因为最近代码有较大改动，不太确定是哪儿引起的，我理解MJ就算解析失败了，顶多是对象变成nil，不会变成字典啊，所以这块不太清楚在什么情况下变字典

我也碰到了，我是因为把两个class写在一个文件中了，后来一个文件一个class就正常了

**Comment by 900116** [comment]
> > 绝大多数，都是能够解析成功的，只有极少部分变成字典，因为最近代码有较大改动，不太确定是哪儿引起的，我理解MJ就算解析失败了，顶多是对象变成nil，不会变成字典啊，所以这块不太清楚在什么情况下变字典
> 
> 我也碰到了，我是因为把两个class写在一个文件中了，后来一个文件一个class就正常了

很诡异啊

**Comment by wolfcon** [comment]
@900116 解析失败的确是字典, 你传个 Demo 上来
另外@wwwangS `class`写在一个文件中也没事, 你如果有 Demo 传上来, 我可以给你看看

**Comment by SpacetimeMaster** [comment]
我也遇到这问题了....但是我把遍历数组一个个的转换又没问题

**Comment by xuanhr** [comment]
提供出现的一种情况：只在头文件`.h` 使用 `@interface` 定义了 `class` ，而没有在`.m`中对应实现`@implementation`则会出现转换对象却变成了字典。
