### ISSUE TITLE
app启动时闪退

### ISSUE THREAD

**Issue by a330416020** [CoderMJLee/MJExtension#763]
IOS 13设备，MJExtension 版本为最新3.2.1 的。非必现的崩溃，bugly 上统计线上用户使用的版本的bug,开发联调复现不了，目前无法提供一个测试demo出来
![1585109141688](https://user-images.githubusercontent.com/4032392/77501390-e1c0a200-6e92-11ea-8eed-e4ac898b50e5.jpg)

**Comment by kinarobin** [comment]
@a330416020 
上传一个崩溃日志看看。

**Comment by a330416020** [comment]
@kinarobin 
[bug.txt](https://github.com/CoderMJLee/MJExtension/files/4379314/bug.txt)

**Comment by kinarobin** [comment]
是 子线程进行字典转模型还是主线程转的？

**Comment by a330416020** [comment]
@kinarobin 网络请求回调里，主线程，不过貌似这个问题出现的概率比之前小了很多，只出现过两次，我这几天再看看bugly统计情况，谢谢你的回答。

**Comment by kinarobin** [comment]
嗯嗯，如果崩溃比较多，可以描述一些你具体是如何使用的？

**Comment by a330416020** [comment]
@kinarobin 👌，主要是线上用户出现的，我们开发和测试这边没有出现过，所以比较难定位问题。

**Comment by wolfcon** [comment]
@a330416020 你是不是使用了下面的方法
- mj_setupObjectClassInArray:
- mj_setupReplacedKeyFromPropertyName:
- mj_setupReplacedKeyFromPropertyName121:

**Comment by wolfcon** [comment]
Duplicate of #761

**Comment by wolfcon** [comment]
**Update [`3.2.4`](https://github.com/CoderMJLee/MJExtension/releases/tag/3.2.4) ASAP.**
