### ISSUE TITLE
怎么获取类属性前面的泛型的声明

### ISSUE THREAD

**Issue by blooming2017** [CoderMJLee/MJExtension#764]
类的属性@property (nonatomic, copy) NSArray<List *> *list;        
怎么获取类属性前面的泛型的声明，例如这个尖括号里的“List”

property_getAttributes 内容是 T@"NSArray",&,N,V_list，只知道是NSArray，怎么获取尖括号里的“List”，谢谢

**Comment by ElfSundae** [comment]
OC里泛型只是「声明」，对编译后的二进制没有实际效果，只是用于编译前检查代码、提示。
