### ISSUE TITLE
老版本好使,新版本崩溃

### ISSUE THREAD

**Issue by xiaofu666** [CoderMJLee/MJExtension#766]
[MJExtensionDemo.zip](https://github.com/CoderMJLee/MJExtension/files/4419694/MJExtensionDemo.zip)
## 为了排除你自己的问题, 请写一个 Demo
最好能提供出现bug的Demo

**描述bug**
已经提供demo

**你期望的结果是什么？**
希望解决或者提供解决办法
**运行环境**
 - iPhone7 Plus
 - iOS 13
 - Xcode 11

**Comment by wolfcon** [comment]
`objectClassInArray`

老哥这个方法早就弃用了
请使用
`mj_objectClassInArray`
