### ISSUE TITLE
在model.h的@property (copy, nonatomic) NSString 中添加<Optional>这个符号后, 转模型没有转为NSString类型,后台json对应的是long类型 , 转为错误的模型属性类型NSCFNumber *

### ISSUE THREAD

**Issue by Rakkkking** [CoderMJLee/MJExtension#767]
**描述bug**
在model.h的@property (copy, nonatomic) NSString 中添加< Optional >这个符号后, 转模型没有转为NSString类型,后台json对应的是long类型 , 转为错误的模型属性类型NSCFNumber * , 正确的期望结果是NSString类型

**怎么样重现这个bug**
错误结果,< Optional >添加
@property (copy, nonatomic) NSString< Optional > *lid;   结果为类型是NSCFNumber
![图片](https://user-images.githubusercontent.com/22495081/79841343-dc02a180-83e9-11ea-94b4-47a57c1a81d4.png)

**你期望的结果是什么？**

正确结果因为NSString
,
没有添加< Optional >的话是正常的
![_log id (NSTaggedPointerString) @103976](https://user-images.githubusercontent.com/22495081/79841866-9b575800-83ea-11ea-85e3-52a8a4c2b7f9.png)

**截图**
![@property (copy, nonatomic) NSString 0ptionallog_id;](https://user-images.githubusercontent.com/22495081/79841829-90042c80-83ea-11ea-97d9-9946cda739df.png)

![log id = (NSCFNumber ) (long)103976](https://user-images.githubusercontent.com/22495081/79841809-8975b500-83ea-11ea-8ed6-73a958925e48.png)

**运行环境**
 - iPhone11
 - iOS 13
 - Xcode 11
'MJExtension','3.2.1'版本

**Comment by wolfcon** [comment]
<Optional> 这是什么符号@@

**Comment by Rakkkking** [comment]
这个符号确实可以编译, 指导使用这个符号是JSONMode这个库.

**Comment by Rakkkking** [comment]
[modeltest.zip](https://github.com/CoderMJLee/MJExtension/files/4521017/modeltest.zip)
demo

**Comment by Rakkkking** [comment]
这个Optional 是jsonModel 的协议

**Comment by wolfcon** [comment]
不要在基础类型上加协议. 会导致以下代码无法生成正确的 `typeClass`, 最终无法正确获取类型导致此值为空, 转换后的 value 未经过 String 的转化.
```objc
_typeClass = NSClassFromString(_code);
```

JSONModel 使用 `<Optional> <Index> <Ignore>` 来标记属性, 在解析时把 `<>` 内容去掉来解析的.
MJExtension 采用类方法来过滤属性, 没有对 `<>` 做处理.

**Comment by Rakkkking** [comment]
好的, 祝工作顺利
