### ISSUE TITLE
T泛型的支持

### ISSUE THREAD

**Issue by wzi90921** [CoderMJLee/MJExtension#768]
@interface BaseResponseVo<T> : NSObject

@property (nonatomic , retain)T data;

@end

很想知道用MJExtension同学们，这类对象有什么好的解决方案

**Comment by wolfcon** [comment]
Duplicate of #385

**Comment by CaiChenghan** [comment]
是否可增加一个方法，来间接实现这种需求呢？
```/**
 *  字典中需要转换的模型类
 *
 *  @return 字典中的key是数组属性名，value是数组中存放模型的Class（Class类型或者NSString类型）
 */
+ (NSDictionary *)mj_objectClassInDictionary;
```
取不到类型，就查看这个方法，要是能对的上，就用这个方法内的类，去做转换，

**Comment by wolfcon** [comment]
看看 [Refactor/4.0.0](https://github.com/CoderMJLee/MJExtension/tree/Refactor/4.0.0) 中的 `mj_modifiedClassForDictionary`?
