### ISSUE TITLE
Bug 版本3.1.2 系统iOS13 转模型后取值闪退

### ISSUE THREAD

**Issue by chengzj456** [CoderMJLee/MJExtension#769]
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/13412802/81156661-c203ba00-8fb8-11ea-88bb-961d904e0302.png">
已经转为模型model 
log输出了-[__NSDictionaryI class_name]: unrecognized selector sent to instance 0x283197580
<img width="431" alt="image" src="https://user-images.githubusercontent.com/13412802/81156756-d9db3e00-8fb8-11ea-897c-e2eaf09809b0.png">
去moel取值的时候报错
po model.class_name
error: warning: couldn't get cmd pointer (substituting NULL): no variable named '_cmd' found in this frame
error: Execution was interrupted, reason: Attempted to dereference an invalid ObjC Object or send it an unrecognized selector.
The process has been returned to the state before expression evaluation.

**Comment by chengzj456** [comment]
使用的是mj_objectWithKeyValues这个方法

**Comment by wolfcon** [comment]
仔细看你的 model 类型是什么?
