### ISSUE TITLE
请教如何在字典转模型的过程中，过滤掉错误数据

### ISSUE THREAD

**Issue by loveuqian** [CoderMJLee/MJExtension#770]
假设可以设定一个数组，里面装着字典必须包含的 key，如果要转换的字典没有其中某一个 key，直接返回 nil

如果是在字典数组转模型数组时，某一个字典，缺少了某一个指定 key，自动跳过这个字典不转换，进入下一个字典的转换

**Comment by ElfSundae** [comment]
先自行检查要被转换为模型的字典，如果字典不符合要求（比如缺少 key）就不调用 `mj_objectWithKeyValues` 方法。
如果是数组，先自行检查数组里的字典，不符合要求就从数组先移除。

**Comment by ElfSundae** [comment]
校验一般都是说校验转换后的模型对象，你这是校验原始输入值，所以从源头先校验再执行转换。
如果这是个通用需求，有很多模型都需要这么处理的话，可以考虑在 MJExtension 外封装一层，或者 Swizzle MJExtension 相关方法添加校验处理。

**Comment by loveuqian** [comment]
明白了，自己处理一下，尝试弄成通用的做法
