### ISSUE TITLE
How to parse ？ thanks！

### ISSUE THREAD

**Issue by zhoubo2015** [CoderMJLee/MJExtension#771]
NSDictionary *dict = @{
    @"users" : @{
        @"user" : @[
                 @{
                     @"name" : @"Bill",
                     @"passoword" : @"1234"
                 },
                 @{
                     @"name" : @"Lee",
                     @"password" : @"1234"
                 }
             ]
    }
};

Now，I only parsing in two steps;
Can I parsing one times ?

**Comment by zhoubo2015** [comment]
NSDictionary *dict = @{

@"users" : @{

          

        @"user" : @[

                                @{
                                       @"name" : @"Bill",
                                       @"passoword" : @"1234"
                                   },
                                @{
                                       @"name" : @"Lee",
                                       @"password" : @"1234"
                                   }
                              ]
         }
};

**Comment by wolfcon** [comment]
### .h
```objc
@interface User : NSObject
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *password;
@end

@interface UserPackage : NSObject
@property (nonatomic, strong) NSArray<User *> *user;
@end

@interface Users : NSObject
@property (nonatomic, strong) UserPackage *userPackage;
```

### .m
```objc
@interface UserPackage () <MJKeyValue>
@end
@implementation UserPackage
+ (NSDictionary *)mj_objectClassInArray {
    return @{"user": User.class};
}
@end
```

> 你这个数据真是很奇怪啊. 为啥多套了一层...users 应该是数组啊. 咋就包一个 user. 然后 user 才包一个数组...

**Comment by zhoubo2015** [comment]
> ### .h
> ```objc
> @interface User : NSObject
> @property (nonatomic, copy) NSString *name;
> @property (nonatomic, copy) NSString *password;
> @end
> 
> @interface UserPackage : NSObject
> @property (nonatomic, strong) NSArray<User *> *user;
> @end
> 
> @interface Users : NSObject
> @property (nonatomic, strong) UserPackage *userPackage;
> ```
> 
> ### .m
> ```objc
> @interface UserPackage () <MJKeyValue>
> @end
> @implementation UserPackage
> + (NSDictionary *)mj_objectClassInArray {
>     return @{"user": User.class};
> }
> @end
> ```
> 
> > 你这个数据真是很奇怪啊. 为啥多套了一层...users 应该是数组啊. 咋就包一个 user. 然后 user 才包一个数组...

是的，服务器返回的，坑死做客户端的

**Comment by zhoubo2015** [comment]
谢谢了！！
