### ISSUE TITLE
一些小的点

### ISSUE THREAD

**Issue by CodeForYang** [CoderMJLee/MJExtension#772]
代码小笔误
1.> - (void)setPorpertyKeys:(NSArray *)propertyKeys forClass:(Class)c 名字拼写错误(setProperty...)

2.> + (NSMutableArray *)mj_properties
{
    NSMutableArray *cachedProperties = [self mj_propertyDictForKey:&MJCachedPropertiesKey][NSStringFromClass(self)];
    if (cachedProperties == nil) {//判断
    
        if (cachedProperties == nil) {//判断 - 这里做了两次判断...

}

3.> 如果有这种属性呢
@interface MJPerson : NSObject
@property (nonatomic)char *nickName;
@end

**Comment by kinarobin** [comment]
@CodeForYang 感谢指正！👍

对于`@property (nonatomic)char *nickName;` 还是不支持的哈，解析出来是 NULL，建议使用`NSString`。
