### ISSUE TITLE
解析NSArray中NSString的bug

### ISSUE THREAD

**Issue by JayJJ** [CoderMJLee/MJExtension#774]
```objc
@interface Cat : NSObject
@property (nonatomic, strong, nullable) NSString *item;
@property (nonatomic, strong, nullable) NSArray<NSString *> *subjects;
@end

@implementation Cat
+ (NSDictionary *)mj_objectClassInArray {
    return @{
        @"subjects" : @"NSString"
    };
}
@end

- (void)testNull {    

    NSArray *subjects = @[@"", [[NSNull alloc] init]];
    
    NSDictionary *dic = @{
        @"item":[[NSNull alloc] init],
        @"subjects":subjects};
        
    Cat *cat = [Cat mj_objectWithKeyValues:dic];
    
    NSLog(@"%@", cat);
}
```
解析出来的cat对象中subjects的元素为NSNull

**Comment by wolfcon** [comment]
你可以这样想想看

如果 subjects 是这样的呢?
```objc
@"subjects": @[
    @"1",
    [NSNull null],
    @"2"
]
```

很明显数组元素个数为 3 个, 中间一个是占位, 而且不能等于 nil.(你能往 NSArray 中写 nil 吗?) 转换的结果你觉的应该是什么? `@""`?

**Comment by JayJJ** [comment]
> 你可以这样想想看
> 
> 如果 subjects 是这样的呢?
> 
> ```objc
> @"subjects": @[
>     @"1",
>     [NSNull null],
>     @"2"
> ]
> ```
> 
> 很明显数组元素个数为 3 个, 中间一个是占位, 而且不能等于 nil.(你能往 NSArray 中写 nil 吗?) 转换的结果你觉的应该是什么? `@""`?

因为数据来自服务端，解析出来的数据有可能为任何对象，如果在解析完后数据类型错误，会导致使用的时候崩溃，还需要手动再检查一遍。像cat里面的item数据类型错误就默认为nil了。
建议在这里可以做一个兼容，给个参数选择，数据类型不正确默认为@""或自定义或不做处理

**Comment by wolfcon** [comment]
都要设定参数了, 就自己处理一下, 对于数组, 因为无法给你置空, 又要保留占位, 所以你在使用时自己处理.
