### ISSUE TITLE
关于NSDecimalNumber类型转换

### ISSUE THREAD

**Issue by fanlilinSaber** [CoderMJLee/MJExtension#775]
你好，
我这边使用AFN 网络请求得到的JSON数据；有些是关于数字方面的；比如价格
"total_price" = "70.01000000000001";
这个数据在后台是本来就是 70.01
但是因为苹果的JSON解析出来之后精度丢失
我这边想用JSON转Model时候就修复这个问题，但是直接使用 NSDecimalNumber 属性 得到值还是精度有问题的，于是我这边手动修改了代码
<img width="712" alt="修复数字精度问题" src="https://user-images.githubusercontent.com/26476506/84275418-9fd6fc00-ab63-11ea-94b1-a894c914bf1f.png">
这样才满足的的需求，我不知道这样修改之后会不会有其他影响

**Comment by wolfcon** [comment]
建议你们后台传输就传输成字符串, 然后对于敏感数字, 自行处理转换.
这样才能避免转换丢失精度

**Comment by ElfSundae** [comment]
@fanlilinSaber 我项目中有几处 double, decimal 类型，目前没遇到类似问题。服务端是 PHP。

> "total_price" = "70.01000000000001";

这行有两种可能，你没说清：
- 可能一：这个是 NSLog 的输出。 AFNetworking 将响应的 JSON 字符串（比如 `{"json": 70.01}`）转换成 NSDictionary 类型，其中的 "70.01000000000001" 是 NSNumber 类型，最后一位「不正确」是存储相关的问题，跟转换没关系。
- 可能二：你服务端返回数据时把 decimal 或 double 类型格式化成了「错误的」字符串类型，导致「精度丢失」问题。如果是这样，联系服务端同学修正。

如果你的 model 类的相关属性是 double 或 NSDecimalNumber 类型的话，应该没什么问题的。界面上的「精度问题」可以在 UI 层解决，例如
```objc
NSLog(@"$%.2f", 70.01);

NSDecimalNumber *priceNumber = [NSDecimalNumber decimalNumberWithString:@"70.01"];
NSLog(@"$%@", priceNumber.stringValue);

priceNumber = [[NSDecimalNumber alloc] initWithDouble:70.01];
NSLog(@"$%@", priceNumber.stringValue);

priceNumber = [[NSDecimalNumber alloc] initWithDouble:@(70.01).doubleValue];
NSLog(@"$%@", priceNumber.stringValue);
```
以上都会输出 `$70.01`.
存储用 float, double, NSNumber, NSDecimalNumber, NSString 都可以。

PS. 如果为了避免在多平台多语言之间出现类似问题，可以统一使用字符串传输、存储、显示。或者用整型，比如传输、存储时用 7001 ，显示、计算时再除以 100。
