### ISSUE TITLE
MJExtension 解析 NSNull 对象解析出错误的 properties 导致出现崩溃

### ISSUE THREAD

**Issue by LockeSwift** [CoderMJLee/MJExtension#779]
MJExtension 解析 NSNull 对象解析出错误的 properties 导致出现崩溃
![image](https://user-images.githubusercontent.com/26478789/85355051-6aa4b380-b53e-11ea-99b9-40e79728f83a.png)

运行环境
 - iPhone 6s
 - iOS 13.4.1
 - Xcode 11.4

**Comment by wolfcon** [comment]
Demo?
