### ISSUE TITLE
encoding and decoding

### ISSUE THREAD

**Issue by caofei10119** [CoderMJLee/MJExtension#78]
I am trying to store custom object into NSUserDefault

User user = [User userWithDictionary:dic];
NSData *encodedObject = [NSKeyedArchiver archivedDataWithRootObject:user];
[[NSUserDefaults standardUserDefaults] setObject:encodedObject forKey:@"user"];
[[NSUserDefaults standardUserDefaults] synchronize];

crash:
[User encodedWithCoder:] unrecognized selector sent to instance 0x7fa5e42d3070

**Comment by CoderMJLee** [comment]
Please add "MJCodingImplementation" to @implementation of User.m

**Comment by caofei10119** [comment]
works like a charm, thanks for your help
This is out of topic, actually I thought for a while which one to choose between Mantle and MJExtension.
are you sure this is really better than Mantle?

**Comment by CoderMJLee** [comment]
Thank you for your appreciation.I'm sure MJExtension is really faster and easier than Mantle.You can create a project to test it.

**Comment by caofei10119** [comment]
thanks for your point out. hope you try harder to enhance this library in performance and usage perspectives both.
