### ISSUE TITLE
iOS14崩溃,调用mj_keyValues模型转字典的时候UIColor解析错误

### ISSUE THREAD

**Issue by yunjinghui123** [CoderMJLee/MJExtension#780]
<img width="986" alt="image" src="https://user-images.githubusercontent.com/9649401/87228722-a0b6b400-c3d5-11ea-8ee6-895e60ee06ad.png">
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/9649401/87228739-b88e3800-c3d5-11ea-8945-231f59841054.png">
https://report.tingyun.com/mobile/mobileApp/crashShare?id=c2hhcmVzaGFyZTE2NDY4ODFfMTU5NDQ4NDU0NTg3Ni5odG1s

**Comment by wolfcon** [comment]
UIColor 本来就不能够被解析的啊. 你要加过滤的.
