### ISSUE TITLE
ios14 模型中含有数组，数组中含有其他模型，解析失败

### ISSUE THREAD

**Issue by JRJian** [CoderMJLee/MJExtension#784]
一层模型
含有数组-二层模型
                       -三层模型（解析失败）

IOS14之前正常解析，14解析成字典

**Comment by GoKnow** [comment]
遇到同样的问题，解决了吗？

**Comment by wolfcon** [comment]
方便写个 Demo 吗?

**Comment by gank0326** [comment]
我也遇到这样的问题引起iOS14以上全面崩溃了

**Comment by wolfcon** [comment]
@gank0326  Demo?
