### ISSUE TITLE
 json 中包含 json string，如何转换 为 model 呢

### ISSUE THREAD

**Issue by LuDamon** [CoderMJLee/MJExtension#788]
下面是一个例子：
{
  "code" : "123",
  "extras" : "{\"isSystem\":\"0\",\"name\":\"重新卸货\",\"pushTime\":\"2020-10-19 14:21:17\",\"type\":\"1006\",\"params\":\"code=73be78cc182143e58eb4f3a40c96d638\",\"key\":\"1004\"}",
  "havaRead" : "1",
  "type" : 2
}

**Comment by wolfcon** [comment]
提供一个思路:
使用 `- (id)mj_newValueFromOldValue:(id)oldValue property:(MJProperty *)property;` 将 extras 处理掉

**Comment by LuDamon** [comment]
> 提供一个思路:
> 使用 `- (id)mj_newValueFromOldValue:(id)oldValue property:(MJProperty *)property;` 将 extras 处理掉

谢谢，解决了
