### ISSUE TITLE
墙裂添加的新功能

### ISSUE THREAD

**Issue by internetWei** [CoderMJLee/MJExtension#793]
我想抛弃YYModel，转而在工程中使用MJExtension，但是以下几个功能的缺少使我感到犹豫不决。
1.modelHash的缺少。
2.modelCopy的缺少。
3.modelIsEqual的缺少。
详情可参考YYModel中的yy_modelHash、yy_modelCopy、yy_modelIsEqual。
如果您添加了这些功能，我想您的支持者将会更多。

**Comment by ElfSundae** [comment]
你写个 NSObject 分类，把 YYModel 的这几个方法挪过来就行了么

**Comment by wolfcon** [comment]
这里解释一下, 
1. Hash 的生成, 这个根据个人需要, 可能不同, YYModel 使用了各变量 `hash` 之后`与`的方式. 根据具体实现可以采用其他.
2. modelCopy, 这个问题参照#690
3. modelEqual 问题同第二个问题, 另外根据不同的设计实现重载 isEqual, 实现自己的即可. 譬如 model 的 id 相同即认为相同, id 和 hash 相同即认为相同.(这里又涉及到 1 的问题).

这 3 个方法 YYModel 中给出的是其中的一种实现, 至于在使用时, 大家各自有各自的实现机制, 况且大多数人用不到或者通用根本不能满足.
基于以上的原因, 没有实现上述方法.
