### ISSUE TITLE
发布的版本是3.2.3 但是pod的版本是3.2.2

### ISSUE THREAD

**Issue by jobs769** [CoderMJLee/MJExtension#794]
## 为了排除你自己的问题, 请写一个 Demo
最好能提供出现bug的Demo

**描述bug**
清晰简单地描述这个bug是啥

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhoneX
 - iOS 12
 - Xcode 11

**Comment by 295060456** [comment]
[!] CocoaPods could not find compatible versions for pod "MJExtension":
  In snapshot (Podfile.lock):
    MJExtension (= 3.2.3)

  In Podfile:
    MJExtension

None of your spec sources contain a spec satisfying the dependencies: `MJExtension, MJExtension (= 3.2.3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by ElfSundae** [comment]
3.2.3 发布了，又删了 https://github.com/CocoaPods/Specs/commits/master/Specs/8/a/b/MJExtension

**Comment by wolfcon** [comment]
use 3.2.2 instead.

**Comment by 295060456** [comment]
你为什么不改一下？

**Comment by ElfSundae** [comment]
我有几个项目都更新到 3.2.3 了，过了两天 pod install 又报错了。不知道为啥删，也不知道啥时再发布新版本。 3.2.3 有个修复 https://github.com/CoderMJLee/MJExtension/pull/789 对我还挺有用的..

**Comment by wolfcon** [comment]
@ElfSundae @295060456 打开项目中的 `Podfile.lock`, 找到 `MJExtension`, 将序号修改为 3.2.2, 然后 install

**Comment by ElfSundae** [comment]
@wolfcon 谢谢，我重新update了下，已经还原到3.2.2了
