### ISSUE TITLE
是否能增加像YYModel 那样的keypath映射

### ISSUE THREAD

**Issue by juxiaohui** [CoderMJLee/MJExtension#795]
经常遇到在一个字典中只有1-2个属性，或者只能用到1-2个属性，如果这样也搞个模型就太恶心，希望增加像YYModel那样的keypath映射

**Comment by wolfcon** [comment]
[好好看README, 答应我!!!┭┮﹏┭┮](https://github.com/CoderMJLee/MJExtension#-model-name---json-key-mapping%E6%A8%A1%E5%9E%8B%E4%B8%AD%E7%9A%84%E5%B1%9E%E6%80%A7%E5%90%8D%E5%92%8C%E5%AD%97%E5%85%B8%E4%B8%AD%E7%9A%84key%E4%B8%8D%E7%9B%B8%E5%90%8C%E6%88%96%E8%80%85%E9%9C%80%E8%A6%81%E5%A4%9A%E7%BA%A7%E6%98%A0%E5%B0%84)
