### ISSUE TITLE
能否增强一下兼容性

### ISSUE THREAD

**Issue by yuchern** [CoderMJLee/MJExtension#799]
1.mj_JSONString这个方法只能转基本的模型，如果模型里面的属性有字典或者数组的模型，就会崩溃。例如Persion类下有个Dogs：NSArray <Dog *> *dogs的属性，将Persion转jsonstring就会崩溃，坑爹了。请参考一下YY_Model的yy_modelToJsontring。
2.还有啊，json转模型方法，云端有时候返回的json数据是转了好几次的，里面会出现多个转义符 \，你这个库只能解一层， 我吐了啊。请学习一下YY_Model的库可以吗？
3.json转模型方法能不能做成一个通用的，非要用户去判断外层是不是数据再去调对应接口，太恶心了。
项目从MJ换yy，各种坑。

**Comment by wolfcon** [comment]
1. Demo?
2. Demo?
3. Demo? 判断外层是数据? 

麻烦请用实际用例来举例.

**Comment by wolfcon** [comment]
No response for a long time. 🧐 Reopen if needed later.
