### ISSUE TITLE
请问MJ老师，复杂的字典 -> 模型时，如果字典中包含多个模型数组时要怎么处理？

### ISSUE THREAD

**Issue by Lilacxyz** [CoderMJLee/MJExtension#8]
具体来说，对应您给出的example，就是当StatusResult中除了statuses这个array之外，如果还有装着另一个model的array，- (NSDictionary *)objectClassInArray要怎么写？

**Comment by CoderMJLee** [comment]
return @{@"statuses", [Status class], @"other" : [Other class]};  增加键值对即可

**Comment by Lilacxyz** [comment]
多谢MJ老师！回复这么快~~(*^__^*) ~~刚才一直报错，原来是我自己猜测着写的不对，给写成if else判断了。
