### ISSUE TITLE
当返回json的字符串中是个 对象字符串"{}" 这个对象用mjextension 进行转换的时候，遇到问题

### ISSUE THREAD

**Issue by fbi080703** [CoderMJLee/MJExtension#80]
例如：   type = img,
	      transBlog = { },
	      publisher_is_attention = ,  这里的transBlog 是一个对象 再用mjextension进行转换的时候，transBlog 相对应的对象不为空，属性全部为nil 。这个对象不能转换为 nil 吗？

**Comment by CoderMJLee** [comment]
因为字典是{ }，是个非空对象，所以转成了模型，也是非空对象
