### ISSUE TITLE
对于内外部API的描述不够清楚,希望完善文档和隐藏不对外的API

### ISSUE THREAD

**Issue by ATMLGG** [CoderMJLee/MJExtension#803]
看了下这个项目下的issue,很多都是因为使用了所谓的私有API,可所有的方法都暴露在外,文档也没有明确说明所有的外部方法,希望能完善一下
#800

**Comment by ATMLGG** [comment]
搞不懂这种人怎么能管代码,是真没人了.
另外告诉你issue还可以删除,也有人会看close的issue,删除在右下角哦

**Comment by wolfcon** [comment]
生活不顺可以找地方发泄, 别这样兄弟.

**Comment by ATMLGG** [comment]
同样的话给你呢,兄弟

**Comment by wolfcon** [comment]
有空你就 PR , 没空你就等等. API 在首页 README 里, 至于私有 API 的问题, 这个问题已知的, 现阶段没空管罢了. 不影响使用

**Comment by ATMLGG** [comment]
我说不等了?800这个issue我描述的问题按你的说法不存在,我重新提了一个没毛病吧
你关了有任何说明?不要气急败坏,有问题解决问题,解决了我帮你关
