### ISSUE TITLE
咨询一个小问题

### ISSUE THREAD

**Issue by 295060456** [CoderMJLee/MJExtension#807]
这个是我的请求数据：
function:-[MKEarnVC signListGET]_block_invoke line:108 content:AAAdata = {
    code = 200;
    data =     {
        data =         (
                        {
                days = 1;
                goldNum = 90;
                isSign = 0;
            },
                        {
                days = 2;
                goldNum = 49;
                isSign = 0;
            },
                        {
                days = 3;
                goldNum = 58;
                isSign = 0;
            },
                        {
                days = 4;
                goldNum = 188;
                isSign = 0;
            },
                        {
                days = 5;
                goldNum = 20;
                isSign = 0;
            },
                        {
                days = 6;
                goldNum = 10;
                isSign = 0;
            },
                        {
                days = 7;
                goldNum = 288;
                isSign = 0;
            }
        );
        isSign = 0;
        nowGoldNum = 90;
    };
    msg = "";
}

![image](https://user-images.githubusercontent.com/13795605/105631482-3f41c880-5e81-11eb-9077-69c6f71f6bab.png)

![image](https://user-images.githubusercontent.com/13795605/105631492-479a0380-5e81-11eb-9e56-9011ebf6f652.png)

我想请教一下，目前的框架内部是不是做了处理？
我注释mj_objectClassInArray，依然可以正确解析。

**Comment by wolfcon** [comment]
Demo?

**Comment by 295060456** [comment]
我是clean了的。
我clean的过程比较深入，用的是这个软件+tencent lemon
![image](https://user-images.githubusercontent.com/13795605/105660510-bddc4b80-5efd-11eb-982a-e1c4532ff801.png)
还chong'qi重启过电脑
![image](https://user-images.githubusercontent.com/13795605/105660468-adc46c00-5efd-11eb-9ca1-d8e294eb372c.png)
你要demo，我就给你做，数据本地化json文件，给你

**Comment by 295060456** [comment]
这个是我完全清除缓存以后自建的demo运行图
![image](https://user-images.githubusercontent.com/13795605/105663723-8d001480-5f05-11eb-8d24-dd85300498e0.png)
以下是demo，你需要pod install
[MjExtensionBugDemo.zip](https://github.com/CoderMJLee/MJExtension/files/5864297/MjExtensionBugDemo.zip)

**Comment by wolfcon** [comment]
## 没注释掉 - 解析出 `MKSignModel`
![image](https://user-images.githubusercontent.com/1538729/105666064-62b55380-5f13-11eb-81f0-1edadcb1893d.png)
## 注释掉 - 没有解析出 `MKSignModel`, 而是 `NSDictionary`
![image](https://user-images.githubusercontent.com/1538729/105666091-7365c980-5f13-11eb-8cae-153784c93e6f.png)

我这边是对的呀?
