### ISSUE TITLE
支不支持 判转数组模型的某个值 根据条件插入到模型数组中

### ISSUE THREAD

**Issue by yimao009** [CoderMJLee/MJExtension#813]
**你的新功能建议是否牵扯到某个常见的问题？**
在转模型数组的 时候， 发现不能根据某个模型的属性没有值， 就不加入数组模型中
- (id)mj_newValueFromOldValue:(id)oldValue property:(MJProperty *)property 
在这个方法中， 只对空值做了处理
**你希望达到的效果**

**你能考虑到的可选实现方案**

- (id)mj_newValueFromOldValue:(id)oldValue property:(MJProperty *)property 
应该在这个方法可以对当前对象的状态去判断

**Comment by wolfcon** [comment]
用实际的 JSON 跟模型举个详细的例子?
