### ISSUE TITLE
希望在podspec中增加watch的支持

### ISSUE THREAD

**Issue by brainiron** [CoderMJLee/MJExtension#815]
**你的新功能建议是否牵扯到某个常见的问题？**
我想在watch app中使用这个库，但是这个podspec不支持watchOS

**你希望达到的效果**

**你能考虑到的可选实现方案**
在podspec中增加这行，亲测可用：
 s.watchos.deployment_target = '5.0'

**Comment by wolfcon** [comment]
check [3.3.0](https://github.com/CoderMJLee/MJExtension/releases/tag/3.3.0)
