### ISSUE TITLE
我没发现多维数组解析方法啊

### ISSUE THREAD

**Issue by HanYaZhou1990** [CoderMJLee/MJExtension#816]
(
(
@"1",@"2",@"3",@"4",@"5",@"6"
),
(
@"4",@"2",@"2",@"8",@"5",@"6"
),
(
@"4",@"5",@"6",@"7",@"9",@"11"
)
)

**Comment by wolfcon** [comment]
这个是多维数组? 

另外多维数组的话, 你先给个模型来举例子啊, 扔了一个这...
