### ISSUE TITLE
mj_objectWithKeyValues突然失效 xcode12 

### ISSUE THREAD

**Issue by Easyzhan** [CoderMJLee/MJExtension#819]
![image](https://user-images.githubusercontent.com/8928783/131221274-a831f576-5a55-4a71-be8c-8e91ef8a17aa.png)

**Comment by wolfcon** [comment]
Demo or specific detail?

**Comment by Easyzhan** [comment]
试过很多的请求，都是第一层可以，越往里面越不能解析了

**Comment by wolfcon** [comment]
if updated, reopen it.
