### ISSUE TITLE
iOS 15字典中包含UIimage对象，崩溃

### ISSUE THREAD

**Issue by lpb006** [CoderMJLee/MJExtension#824]
## 为了排除你自己的问题, 请写一个 Demo
最好能提供出现bug的Demo

**描述bug**

***model****
@interface Model : NSObject
@property (nonatomic,strong) NSString *name;
@property (nonatomic,strong) UIImage *image;
@end

***解析*****
NSDictionary *dic = @{@"name":@"111",@"image":[UIImage new]};
    
Model *model = [Model mj_objectWithKeyValues:dic];

**期望结果**
xcode12以前编译运行成功
xcode13编译运行崩溃

**运行环境**
 - iPhone10
 - iOS 15
 - Xcode 13

**Comment by wolfcon** [comment]
Duplicate of #578
