### ISSUE TITLE
浮点型精度丢失

### ISSUE THREAD

**Issue by LiwxCoder** [CoderMJLee/MJExtension#825]
## 为了排除你自己的问题, 请写一个 Demo
    // mj_JSONString 出现精度丢失demo
    NSDictionary *dict = @{
        @"heigit": @10.3,
        @"weight": @43.4,
    };
    // result: {"heigit":10.300000000000001,"weight":43.399999999999999}
    NSLog(@"result: %@", [dict mj_JSONString]);

**描述bug**
浮点型转JSON字符串出现精度丢失,麻烦杰哥排查下这个问题.

**运行环境**
 - iPhoneX
 - iOS 12
 - Xcode 11

**Comment by wolfcon** [comment]
你首先要理解浮点型 `Double/Float` 本身就无法有高精度, 这是浮点型的设计原理.
你如果想使用高精度, 请使用字符串或者 Decimal.
