### ISSUE TITLE
崩溃：mj_objectArrayWithKeyValuesArray ，已更新至3.4.0版本

### ISSUE THREAD

**Issue by victordengx** [CoderMJLee/MJExtension#828]
**描述bug**
APP冷启动时偶发闪退，每次启动APP会有大量嵌套数据需要转换，偶发转换崩溃，统计数据显示崩溃发生在多机型，系统大多在iOS14以上

**截图**
![Snip20211122_17](https://user-images.githubusercontent.com/15939455/142793377-440755ea-f706-4067-bb6e-2361773ce859.png)

**运行环境**
 - iPhone 11
 - iOS 15.0.2
 - Xcode 12.5.1

**Comment by wolfcon** [comment]
冷启动时间一般是多久?
另外冷启动时, 能不能本地复现出 bug? 

`StorageManager` 加载数据是并行加载的吗?

**Comment by victordengx** [comment]
李老师：
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;您好，冷启动时间在iOS15.0.2系统上普遍是1到3秒，崩溃复现的概率不高，没有规律，StorageManager加载数据有加锁处理，以下是部分代码，非常感谢您这么及时的回复


部分代码截图：









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CoderMJLee/MJExtension"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CoderMJLee/MJExtension] 崩溃：mj_objectArrayWithKeyValuesArray ，已更新至3.4.0版本 (Issue #828)





 
冷启动时间一般是多久?
 另外冷启动时, 能不能本地复现出 bug?
 
StorageManager 加载数据是并行加载的吗?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by victordengx** [comment]
李老师：
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;您好，由于这个问题比较着急，您那边有没有什么方法可以先让它不崩溃呢，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CoderMJLee/MJExtension"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CoderMJLee/MJExtension] 崩溃：mj_objectArrayWithKeyValuesArray ，已更新至3.4.0版本 (Issue #828)





 
冷启动时间一般是多久?
 另外冷启动时, 能不能本地复现出 bug?
 
StorageManager 加载数据是并行加载的吗?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wolfcon** [comment]
emmm 我不是 CoderLee.

部分代码的话, 这边记录没看到. 不方便的话, 可以加我 Q 私发.
