### ISSUE TITLE
时间戳无法解析~

### ISSUE THREAD

**Issue by seanLee** [CoderMJLee/MJExtension#83]
从服务器传来的时间戳转换为NSDate为空,是因为Java获取的时间戳与OC中获取的时间戳单位不一样?还是本身就不支持时间戳转换为NSDate格式?我也点进去看了,有点不懂代码,所以希望能指点一下.

**Comment by seanLee** [comment]
额~我自己点进去看了,貌似本身就是不支持NSDate转换的.可能是我自己也不太懂,不过我自己加了一点代码,解决了～

**Comment by CoderMJLee** [comment]
可以声明为NSDate类型的属性，然后重写set方法，在里面解析服务器返回的时间

**Comment by CoderMJLee** [comment]
现在提供了+ (void)setupNewValueFormOldValue:(MJNewValueFormOldValue)newValueFormOldValue方法或者在.m中实现- (id)newValueFromOldValue:property:来统一处理时间类型哈。具体可以看看Demo，谢谢。

**Comment by seanLee** [comment]
@CoderMJLee 好的 谢谢了～
