### ISSUE TITLE
简单的字典 -> 模型（key替换，比如ID和id。多级映射，比如 oldName 和 name.oldName） 有关替换key的问题请教

### ISSUE THREAD

**Issue by zq4950411** [CoderMJLee/MJExtension#84]
/**
 * 简单的字典 -> 模型（key替换，比如ID和id。多级映射，比如 oldName 和 name.oldName）
 */
void keyValues2object4()
{
    // 1.定义一个字典
    NSDictionary *dict = @{
                           @"id" : @"20",
                           @"desciption" : @"好孩子",
                           @"name" : @{
                                @"newName" : @"lufy",
                                @"oldName" : @"kitty",
                                @"info" : @{
                                    @"nameChangedTime" : @"2013-08-07"
                                }
                           },
                           @"other" : @{
                                @"bag" : @{
                                    @"name" : @"小书包",
                                    @"price" : @100.7
                                }
                           }
                        };

    /*
     @property (copy, nonatomic) NSString *ID;
     @property (copy, nonatomic) NSString *nowName;
     @property (copy, nonatomic) NSString *oldName;
     @property (copy, nonatomic) NSString *nameChangedTime;
     @property (copy, nonatomic) NSString *desc;
     @property (strong, nonatomic) Bag *bag;
     */
    // 2.将字典转为Student模型
    Student *stu = [Student objectWithKeyValues:dict];

    // 3.打印Student模型的属性
    NSLog(@"ID=%@, desc=%@, oldName=%@, nowName=%@, nameChangedTime=%@",
          stu.ID, stu.desc, stu.oldName, stu.nowName, stu.nameChangedTime);
    NSLog(@"bagName=%@, bagPrice=%f",
          stu.bag.name, stu.bag.price);
}

在上面的代码中ID和id是怎么映射的？

**Comment by CoderMJLee** [comment]
readme.md里面有说明的，demo里面也有，认真看看哈，3Q

**Comment by zq4950411** [comment]
看到了，都是在MJExtensionConfig文件里面实现的，谢谢大神，么么哒

**Comment by zq4950411** [comment]
看到了，都是在MJExtensionConfig文件里面实现的，谢谢大神，么么哒
