### ISSUE TITLE
字典 转 JSONString Crash

### ISSUE THREAD

**Issue by leezhihua** [CoderMJLee/MJExtension#841]
**描述bug**
定义一个字典dic，key是字符串，value是自定义model。
调用 [dic mj_JSONString] crash

demo：

`
@interface ParticipantExtension : NSObject
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *imageUrl;
@end

@implementation ParticipantExtension

@end

@interface BlockParticipant : NSObject
@property (nonatomic, copy) NSString *participantId;
@property (nonatomic, assign) NSInteger type;
@property (nonatomic, assign) long endTime;
@property (nonatomic, strong) ParticipantExtension *extension;
@end

@implementation BlockParticipant
+ (NSDictionary *)mj_objectClassInArray {
    return @{@"extension":ParticipantExtension.class};
}
@end
`

`
ParticipantExtension *exten = ParticipantExtension.new;
exten.name = @"zzz";
exten.imageUrl = @"https://xxxx";

BlockParticipant *bp = [[BlockParticipant alloc] init];
bp.participantId = @"xxx11111";
bp.type = 1;
bp.endTime = 1434978789421;
bp.extension = exten; 

NSDictionary *dict = @{@"user": bp};
NSString *json = [dict mj_JSONString];
`

**你期望的结果是什么？**
调用mj_JSONString 得到正常结果
 or
请教大佬调用现有api是否可以解决问题

**截图**
断点发现以下问题：

![1649668090025_0 34502535407473312](https://user-images.githubusercontent.com/19367689/162707143-567942b6-b650-469f-9e03-c93a563be99e.png)

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/19367689/162702428-37200093-7968-42b1-8c73-c9a6cfc1301b.png">

**Comment by leezhihua** [comment]
自己定义的字典，字典里面包含模型，然后字典转jsonstring，我通过外部封装已经解决了。

现在发现如果是模型里面包含字典，字典里面包含模型，这时候模型转jsonstring还是会crash的，这种情况怎么解决呢？

建议：丰富mj_JSONString 的实现，可以参考YYModel

**Comment by leezhihua** [comment]
上面是自己定义字典，如果是模型里面有类似上面的字典，转jsonstring应该怎么做呢？请指教

**Comment by leezhihua** [comment]
> 请尝试 [`Refactor/4.0.0`](https://github.com/CoderMJLee/MJExtension/tree/Refactor/4.0.0) 这个分支.

请问 [Refactor/4.0.0](https://github.com/CoderMJLee/MJExtension/tree/Refactor/4.0.0) 分支.新增的功劳是什么，这个分支支持pod吗

**Comment by wolfcon** [comment]
请查看 [这个列表](https://github.com/CoderMJLee/MJExtension/milestone/3)

**Comment by Murphy-zhu** [comment]
> 

@wolfcon 你好，用了这个分支还是会有这个情况发生

**Comment by wolfcon** [comment]
我测试后, 没问题啊. 用你的代码. 要不你传个整个工程上来看下? 压缩包直接拖到文本框即可
