### ISSUE TITLE
在Bugly上发现个问题SEGV_ACCERR pemv260 +[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:)

### ISSUE THREAD

**Issue by MyNameZhangXinMiao** [CoderMJLee/MJExtension#845]
提示是这个分类 NSObject+MJProperty.m:144 
没有找到具体的什么原因！

详细信息在下方⬇️
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
1
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
2
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
3
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
4
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
5
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
6
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
7
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
8
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
9
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
10
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
11
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
12
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
13
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
14
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
15
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
16
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
17
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
18
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
19
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
20
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
21
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
22
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
23
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
24
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
25
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
26
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
27
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
28
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
29
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
30
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
31
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
32
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
33
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
34
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
35
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
36
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
37
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
38
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
39
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
40
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
41
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
42
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
43
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
44
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
45
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
46
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
47
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
48
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
49
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
50
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
51
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
52
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
53
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
54
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
55
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
56
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
57
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
58
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
59
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
60
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
61
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
62
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)
63
pemv260
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:144)
64
pemv260
-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:] (NSObject+MJKeyValue.m:390)
65
pemv260
__57-[NSObject(MJKeyValue) mj_keyValuesWithKeys:ignoredKeys:]_block_invoke (NSObject+MJKeyValue.m:326)

**Comment by wolfcon** [comment]
版本...
能复现吗?

**Comment by LiuQingying** [comment]
这个bug解决了吗，我也遇到这个问题了。看情况是出现了死循环 iOS16.3 iPhone13手机出现这问题。

**Comment by MyNameZhangXinMiao** [comment]
目前还没有去更新新版本，还未尝试！

**Comment by MyNameZhangXinMiao** [comment]
楼主把改问题归纳至4.0.0版本，你可以去升级尝试一下

**Comment by LiuQingying** [comment]
> 楼主把改问题归纳至4.0.0版本，你可以去升级尝试一下
谢谢，我看历史bug说4.0有些其他的问题没敢修改，我改用4.0.0看看
