### ISSUE TITLE
-[MJProperty setValue:forObject:] + [MJProperty.m : 98] 

### ISSUE THREAD

**Issue by AlbertCamusSZB** [CoderMJLee/MJExtension#847]
出错堆栈如下：
0	libobjc.A.dylib
_objc_release_x0 + 8
1	Foundation
-[NSObject(NSKeyValueCoding) setValue:forKey:] + 324
2	DuCheng
-[MJProperty setValue:forObject:] (MJProperty.m:98)
3	DuCheng
__48-[NSObject(MJKeyValue) mj_setKeyValues:context:]_block_invoke (NSObject+MJKeyValue.m:221)
4	DuCheng
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:134)
5	JinJiangDuCheng
-[NSObject(MJKeyValue) mj_setKeyValues:context:] (NSObject+MJKeyValue.m:231)
6	DuCheng
+[NSObject(MJKeyValue) mj_objectWithKeyValues:context:] (NSObject+MJKeyValue.m:0)
7	DuCheng
+[NSObject(MJKeyValue) mj_objectArrayWithKeyValuesArray:context:] (NSObject+MJKeyValue.m:0)
8	DuCheng
__48-[NSObject(MJKeyValue) mj_setKeyValues:context:]_block_invoke (NSObject+MJKeyValue.m:0)
9	DuCheng
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:134)
10	DuCheng
-[NSObject(MJKeyValue) mj_setKeyValues:context:] (NSObject+MJKeyValue.m:231)
11	JinJiangDuCheng
+[NSObject(MJKeyValue) mj_objectWithKeyValues:context:] (NSObject+MJKeyValue.m:0)
12	DuCheng
__48-[NSObject(MJKeyValue) mj_setKeyValues:context:]_block_invoke (NSObject+MJKeyValue.m:0)
13	DuCheng
+[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:134)
14	DuCheng
-[NSObject(MJKeyValue) mj_setKeyValues:context:] (NSObject+MJKeyValue.m:231)
15	DuCheng
+[NSObject(MJKeyValue) mj_objectWithKeyValues:context:] (NSObject+MJKeyValue.m:0)

这个错误经常发生在iOS 16.1系统上。请问如何解决？

**Comment by wolfcon** [comment]
版本?

**Comment by AlbertCamusSZB** [comment]
> 

 版本是 pod 'MJExtension','3.3.0'
