### ISSUE TITLE
4.0.0 版本模型数组转数组时，模型数组有值，使用- (id)mj_JSONObjectWithKeys:(NSArray *)keys 后转化的值为nil

### ISSUE THREAD

**Issue by AlbertCamusSZB** [CoderMJLee/MJExtension#850]
4.0.0 版本模型数组转数组时，模型数组有值，使用- (id)mj_JSONObjectWithKeys:(NSArray *)keys 后转化的值为nil

**Comment by wolfcon** [comment]
`testModelArray2JSONArray` 这个测试方法就是测试模型数组->数组的案例, 是没有问题的.

你这边能传一个 demo 上来么? 打包 zip 拖动到编辑框即可

**Comment by AlbertCamusSZB** [comment]
> `testModelArray2JSONArray` 这个测试方法就是测试模型数组->数组的案例, 是没有问题的.
> 
> 你这边能传一个 demo 上来么? 打包 zip 拖动到编辑框即可

你好，抱歉，我理解错了。mj_JSONObjectWithKeys 没有问题。

**Comment by AlbertCamusSZB** [comment]
> `testModelArray2JSONArray` 这个测试方法就是测试模型数组->数组的案例, 是没有问题的.
> 
> 你这边能传一个 demo 上来么? 打包 zip 拖动到编辑框即可

谢谢支付，加油。
