### ISSUE TITLE
关于ios.deployment_target最低版本

### ISSUE THREAD

**Issue by homeYsy** [CoderMJLee/MJExtension#860]
目前项目支持的最低版本还是9.0，但是我看MJExtension的最新Realease版本的ios.deployment_targe是12.0，最低版本能改下吗？

**Comment by wv-y** [comment]
+1，是在升级3.4.2是修改的，可以调整会9.0吗？

**Comment by wolfcon** [comment]
不要升级最新版本, stick with `3.4.2`
