### ISSUE TITLE
sometimes setupReplacedKeyFromPropertyName method doesn't allocate the properties properly

### ISSUE THREAD

**Issue by caofei10119** [CoderMJLee/MJExtension#87]
+ (IPUser *)userWithDictionary:(NSDictionary *)dic {
    [IPUser setupReplacedKeyFromPropertyName:^NSDictionary *{
        return @{@"userId" : @"id",
                 @"login" : @"login",
                 @"location" : @"location",
                 @"createdAtTimestamp" : @"created_at",
                 @"userDescription" : @"description",
                 @"firstname" : @"firstname",
                 @"lastname" : @"lastname",
                 @"yearOfBirth" : @"year_of_birth",
                 @"genderString" : @"gender",
                 @"prayersCount" : @"prayers_count",
                 @"followersCount" : @"followers_count",
                 @"followingCount" : @"following_count",
                 @"groupsCount" : @"groups_count",
                 @"church" : @"church",
                 @"photoUrlString" : @"photo_url",
                 @"photoBigUrlString" : @"photo_big_url",
                 @"photoBackgroundUrlString" : @"photo_background_url"};
    }];
    
    IPUser *user = [IPUser objectWithKeyValues:dic];
    
    return user;
}

dictionary value
{
    "blames_count" = 0;
    church = "";
    "created_at" = 1366634834564;
    description = "Revolve my life around God.\nathlete #college follow me on twitter Live4God12 allisjah means God is good \n\n";
    firstname = Vez;
    "followers_count" = 1872;
    "following_count" = 375;
    gender = "";
    "groups_count" = 5;
    id = 517531523025de1400000143;
    lastname = "";
    login = Allisjah;
    "photo_background_url" = "http://i.instapray.com/36a0a70f-ad5a-428f-817f-3b7fdf665533";
    "photo_big_url" = "http://i.instapray.com/86d495f2-f8a8-4a88-99b9-3b28717bbb39";
    "photo_url" = "http://i.instapray.com/70abda33-3dd9-414b-a433-0e5f6a2a6436";
    "prayers_count" = 4183;
    "year_of_birth" = 0;
}

some properties are nil.

I defined these methods to store to NSUserDefaults.

-(id)initWithCoder:(NSCoder *)decoder {
    if (self = [super init]) {
        [self decode:decoder];
    }
    return self;
}

- (void)encodeWithCoder:(NSCoder *)encoder {
    [self encode:encoder];
}

Please let me know what causes an issue.
Thanks in advance.

**Comment by CoderMJLee** [comment]
You can try to implements +(NSDictionary *)replacedKeyFromPropertyName method in .m file instead.
If the property name is same as the dictionary key, you don't need to add it to the dictionary, such as @"login" : @"login"

**Comment by caofei10119** [comment]
thanks
