### ISSUE TITLE
Update ReadMe.MD for 2 new features (更新ReadMe.MD)

### ISSUE THREAD

**Issue by LawrenceHan** [CoderMJLee/MJExtension#88]
#### M了个J说:
`我为MJExtension增加了2个大功能哈，有空的话，希望能帮我修改下MD文件，把这2个新功能写上去，谢谢。我因为创业忙哈，没时间去添加。具体是哪2个新功能，可以看看Demo，谢谢啦`

**Comment by LawrenceHan** [comment]
@CoderMJLee @100mango @daviskoh @YAANNZ @SarielTang 
Hi, 我最近也有点忙，可能不能及时更新，各位大大看看谁有空呢。。。

**Comment by CoderMJLee** [comment]
哈哈哈，这才是团队开发的感觉！！！赞！！！

**Comment by LawrenceHan** [comment]
哈哈，我也是创业公司，用github托管项目，工作习惯了。。。如有冒犯 还请见谅啊 :smile: 
(现在还在苦逼的敲代码中... :sob: )

**Comment by SarielTang** [comment]
是typedef id (^MJNewValueFormOldValue)(id object, id oldValue, MJProperty *property);这个于过滤字典中的值的block属性，+ (NSString *)replacedKeyFromPropertyName121:(NSString *)propertyName;将属性名换为其他key去字典中取值- (id)newValueFromOldValue:(id)oldValue property:(MJProperty *)property;旧值换新值，用于过滤字典中的值这两个方法么？
