### ISSUE TITLE
能否解析有动态key的JSON

### ISSUE THREAD

**Issue by starFelix** [CoderMJLee/MJExtension#90]
{
  "1":[
         {"name":"peter","label":"men"},
         {"name":"peter","label":"men"}
        ],
  "2":[
         {"name":"peter","label":"men"},
         {"name":"peter","label":"men"}
        ],
}

像这样的结构，"1"/"2"都不是固定的，如何做解析？

**Comment by CoderMJLee** [comment]
这个无法解析哦，因为是动态，所以肯定是需要自己写代码去判断哈。能直接解析的就是那种固定的。除非你给模型同时增加1、2这两个属性
