### ISSUE TITLE
objectWithKeyValues 有点问题

### ISSUE THREAD

**Issue by neng18** [CoderMJLee/MJExtension#92]
@interface AUGoodImage : NSObject
@property (copy,nonatomic) NSString * name;
@property (copy,nonatomic) NSString * icon;
@end

NSDictionary *tmp = @{@"name":@"123",@"icon":@"234"};
AUGoodImage *ff = [AUGoodImage objectWithKeyValues:tmp];

ff转换不到

**Comment by CoderMJLee** [comment]
有这种事？可以发Demo到我邮箱么：richermj123go@vip.qq.com，谢谢哈

**Comment by neng18** [comment]
有点诡异，同样的代码，刚刚不行，现有又可以。
