### ISSUE TITLE
用这个框架做微博项目时，若要加载的微博转发了没有“来自于（即source为@""）”的微博，会奔溃。

### ISSUE THREAD

**Issue by GavinFlying** [CoderMJLee/MJExtension#94]
![screen shot 2015-06-13 at 4 18 32 pm](https://cloud.githubusercontent.com/assets/10380321/8143590/dec144f4-11e7-11e5-8d6c-eb79c42c7385.png)
这张是彭于晏的微博，转发之后运行程序会奔溃

![screen shot 2015-06-13 at 4 17 28 pm](https://cloud.githubusercontent.com/assets/10380321/8143593/f44cf3a4-11e7-11e5-9eba-72f5fcb15851.png)
这张是周鸿祎的微博，同样，转发之后运行程序会奔溃，因为周转发的那条微博没有 “来自于XXX”

以彭于晏的微博为例，我转发他的微博之后运行程序, 在这之后在往下走两步，这个方法就崩掉了，而在他这条微博前的其他微博都能正常显示。
![screen shot 2015-06-13 at 4 24 19 pm](https://cloud.githubusercontent.com/assets/10380321/8143610/ecd48ed8-11e8-11e5-9482-369576473287.png)

```
Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFConstantString substringWithRange:]: Range {2147483648, 4294967295} out of bounds; string length 0'

```
以上是bug的表现，但是具体原因……能力有限没找出来，在框架中加入相关判断反而更容易崩了…………
还请杰哥看看这个~

**Comment by CoderMJLee** [comment]
跟MJExtension一点关系都没有哈。-[__NSCFConstantString substringWithRange:]是字符串截取错误，你找到你截串的代码，判断一下范围就好了。我猜测你肯定是在模型的setSource:或者source方法里面写错了哈，if (range.location != NSNotFound) ....执行截串代码

**Comment by GavinFlying** [comment]
确实是！！！谢谢杰哥！！！新手看哪儿报错就盯着那儿了……看不到本质……谢谢！

**Comment by CoderMJLee** [comment]
不客气哈，解决了就好！
