### ISSUE TITLE
swift：模型里有模型，调用子模型的属性会死 EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by alwaystrong** [CoderMJLee/MJExtension#95]
我模型里有个模型，如people模型里面有dog；使用字典转模型后，people.dog正常，但调用people.dog.eyes会死掉（ EXC_BAD_ACCESS），请问老师，这个要怎么办？多谢了！

**Comment by CoderMJLee** [comment]
可否发个Demo到邮箱看看？

**Comment by alwaystrong** [comment]
发你richermj123go@vip.qq.com邮箱了。
非常感谢哈！
有空到深圳请你吃饭！

**Comment by CoderMJLee** [comment]
找到原因了哈，是Swift对NSClassFromString的支持跟OC不一致导致的。。。看来要写个Swift版本的MJExtension了

**Comment by alwaystrong** [comment]
@CoderMJLee swift目前还没那么流行。估计明年这个时候用的人会多点。swift2应该也会完善很多。

**Comment by wealon** [comment]
支持  swift 版 MJExtension 横空出世
