### ISSUE TITLE
return [_foundationClasses containsObject:c];提示坏的地址

### ISSUE THREAD

**Issue by chihaodong** [CoderMJLee/MJExtension#96]
MJ老师，一直用你这个，很方便，但是之前偶尔遇到这个错误，后来更新了你的最新版，依然是这个错误，不解前来请教！！！
+ (BOOL)isClassFromFoundation:(Class)c
{
    return [_foundationClasses containsObject:c];
}

c传过来的是 GoodsModel  的模型类型， 但是就报错了  提示EXC_BAD_ACCESS这个错误，难道是我的用法错误了嘛 ？_goodsModels = [GoodsModel objectArrayWithKeyValuesArray:json];  这个是调用的地方，感谢帮忙解答

**Comment by CoderMJLee** [comment]
你的ARC还是MRC？

**Comment by chihaodong** [comment]
不好意思，来晚了，是MRC模式的

**Comment by CoderMJLee** [comment]
这个框架是ARC的哦，在MRC环境，肯定会报错的哈。你需要给.m文件添加-fobjc-arc编译标记哈

**Comment by chihaodong** [comment]
哦  哦  原来 哈  谢谢 MJ啊 哈哈  我在去试试  啥时候 回北京 请你吃饭 哈

**Comment by CoderMJLee** [comment]
不客气哈

**Comment by chihaodong** [comment]
膜拜了~~！！！  完美解决了  又学到知识了  支持啦~~!哈
