### ISSUE TITLE
ios7下MJCodingImplementation归档成功，解档出来为空

### ISSUE THREAD

**Issue by newbbydong** [CoderMJLee/MJExtension#97]
ios7下MJCodingImplementation归档成功，解档出来为空，ios8没有这个问题

**Comment by CoderMJLee** [comment]
可以发个Demo看看么？谢谢哈

**Comment by newbbydong** [comment]
大神，我debug了一下午，发现是因为我先解档，再归档，但是第一次没有文件，解档出来的数组为nil，往里添加数据之后还是为nil，但是归档是成功的。不好意思，虚报军情了哈

**Comment by CoderMJLee** [comment]
没事哈，解决了就好
