### ISSUE TITLE
Model contains model-array 的情况，在转换前调用setupObjectClassInArray无效，但在模型类.m中实现objectClassInArray有效

### ISSUE THREAD

**Issue by JC-Hu** [CoderMJLee/MJExtension#99]
如题

ViewController.m中
        NSDictionary *dict = responseData[@"data"];
        [Order setupObjectClassInArray:^NSDictionary *{
            return @{@"tickets": NSStringFromClass([Ticket class])};
        }];
        self.orderToShow = [Order objectWithKeyValues:dict];
无效，转换后tickets字段仍为字典数组

Order.m中
@implementation Order
+ (NSDictionary *)objectClassInArray
{   
    return @{@"tickets": NSStringFromClass([Ticket class])};
}
@end
有效，成功转换

**Comment by JC-Hu** [comment]
很奇怪，在MJExtension的Demo里，我尝试这两种方式都能转换成功，

但在我的工程里，在转换前使用setupObjectClassInArray就无效。
追踪到NSObject+MJKeyValue.m的“核心代码”方法中，
            Class objectClass = [property objectClassInArrayFromClass:[self class]];
objectClass在tickets字段时仍为0x0

**Comment by CoderMJLee** [comment]
可以发个代码给我看看么？
另外，提醒一下哈，你返回的字典还可以这么写哈：
```objc
return @{@"tickets" : [Ticket class]};
```

**Comment by CoderMJLee** [comment]
我预计你是在[Order objectWithKeyValues:dict];之前的某些地方已经使用过Order相关类进行字典转模型。setupObjectClass...方法只需要初始化一次的哈，最好放在程序启动完后做一次就可以了。或者可以参考MJExtensionDemo里面的MJExtensionConfig.m，统一放在initialize方法中哈

**Comment by JC-Hu** [comment]
对，Order类在之前就进行过转换。那我还是在模型类里实现objectClassInArray方法吧，这样比较符合逻辑。谢谢MJ。
